force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_County__c.field-meta.xml
<CustomField>
    <fullName>Tax_County__c</fullName>
    <label>Tax County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RET_DocumentsListController.cls
public without sharing class RET_DocumentsListController {

    @AuraEnabled
    public static String getHostName() {
        System.debug(' **** System.Url.getSalesforceBaseUrl(): ' + System.Url.getSalesforceBaseUrl());
        return System.Url.getSalesforceBaseUrl().getHost().replace('https://', '');
    }

    @AuraEnabled
    public static List<AttachmentListWrapper> deleteSelectedDocument(String docToDelete, String caseId) {
        try {
            Attachment attachToDelete = new Attachment(Id = docToDelete);
            delete attachToDelete;
            RET_Document_Data__c rec = [select id,Document_Type__c from RET_Document_Data__c where Attachment_ID__c = :docToDelete limit 1];
            String docType = rec.Document_Type__c;
            delete rec;  
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return getCaseDocuments(caseId);
    }

    @AuraEnabled
    public static List<AttachmentListWrapper> getUpdatedCaseDocuments(String caseId) {
        return getCaseDocuments(caseId);
    }
    
    @AuraEnabled
    public static List<AttachmentListWrapper> getCaseDocuments(String caseId) {
        
        List<AttachmentListWrapper> wrapperList = new List<AttachmentListWrapper>();
        Map<String, List<Attachment>> wrapperMap = new Map<String, List<Attachment>>();             

        Map<Id, Attachment> attachmentMap = new Map<Id, Attachment>();
        for(Attachment attach : [select Id, Name from Attachment where parentId = :caseId]) {
            attachmentMap.put(attach.Id, attach);
        }  
        if(!attachmentMap.isEmpty()) {
            for(RET_Document_Data__c docData : [select Id, Name, Attachment_ID__c, Tax_Year__c, Document_Type__c, 
                                           Tax_County__c from RET_Document_Data__c where Attachment_ID__c in :attachmentMap.keySet() order by Name asc]) {
                if(wrapperMap.containsKey(docData.Document_Type__c)) {
                    wrapperMap.get(docData.Document_Type__c).add(attachmentMap.get(docData.Attachment_ID__c));
                } else {
                    wrapperMap.put(docData.Document_Type__c, new List<Attachment>{attachmentMap.get(docData.Attachment_ID__c)});
                }
            }
            if(!wrapperMap.isEmpty()) {
                // Add our documents to the list in the same order as the document type picklist.
                List<String> docTypes = new List<String>();
                Schema.DescribeFieldResult fieldResult = RET_Document_Data__c.Document_Type__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();                
                for( Schema.PicklistEntry pickListVal : ple) {
                    String docType = pickListVal.getLabel();
                    if(wrapperMap.containsKey(docType)) {
                        List<Attachment> listToSort = wrapperMap.get(docType);
                        listToSort.sort();
                        wrapperList.add(new AttachmentListWrapper(listToSort, docType));
                    }
                }               
            }
        }
        return wrapperList;
    }

    public class AttachmentListWrapper {
        @AuraEnabled public String documentType {get;set;}
        @AuraEnabled public List<Attachment> attachList {get;set;}

        public AttachmentListWrapper(List<Attachment> attList, String docType) {
            documentType = docType;
            attachList = attList;
        }
    }

    @AuraEnabled
    Public static Map<String,String> getUrls(String caseId ){
        Map<String,String> urls = new Map<String,String>();
        string tempurl;
        String hostlink = Url.getSalesforceBaseUrl().toExternalForm()+'/realestatetaxes/servlet/servlet.FileDownload?file=';
        
        for(Attachment att :  [SELECT Id, Name, Body, ContentType FROM Attachment WHERE ParentId =: caseId] ){
                tempurl = hostlink+att.id;
                urls.put(att.Name,tempurl);
                tempurl = '';
            }
        if(urls.size()>0){
            return urls;
        }else{
            throw new AuraHandledException('No attachments found for this tax submission.');
        }
    }

}