force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/PBS_gBUILD_ProjectFunding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Funding information.</description>
    <label>gBUILD Project Funding</label>
    <nameField>
        <displayFormat>gbPf_{00000}</displayFormat>
        <label>PBSgBUILDPF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Fundings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount ($)</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/Asid__c.field-meta.xml
<CustomField>
    <fullName>Asid__c</fullName>
    <label>ASID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32767</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/FundingFY__c.field-meta.xml
<CustomField>
    <fullName>FundingFY__c</fullName>
    <label>Funding Fiscal Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/FundingSource__c.field-meta.xml
<CustomField>
    <fullName>FundingSource__c</fullName>
    <label>Funding Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AgencyOperating</fullName>
            </value>
            <value>
                <fullName>Building</fullName>
            </value>
            <value>
                <fullName>CFCLineItem</fullName>
            </value>
            <value>
                <fullName>ECOE</fullName>
            </value>
            <value>
                <fullName>ESPC</fullName>
            </value>
            <value>
                <fullName>BA03 - ARRA Fund</fullName>
            </value>
            <value>
                <fullName>BA04 - ARRA Fund</fullName>
            </value>
            <value>
                <fullName>BA61 - Energy Division</fullName>
            </value>
            <value>
                <fullName>BA54 - Regionally Funded Repair and Alteration</fullName>
            </value>
            <value>
                <fullName>BA55 - ENE0000 - Original Energy Prospectus</fullName>
            </value>
            <value>
                <fullName>BA55 - ENWTR000 - Energy &amp; Water Retrofit Prospectus</fullName>
            </value>
            <value>
                <fullName>BA61 - Regional Budget</fullName>
            </value>
            <value>
                <fullName>BA63 - Rebate Fund</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/FundingType__c.field-meta.xml
<CustomField>
    <fullName>FundingType__c</fullName>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>OriginalAmountFunded</fullName>
            </value>
            <value>
                <fullName>SubstitutionFunding</fullName>
            </value>
            <value>
                <fullName>SupplimentalFunding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_Project</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_Project</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_gBUILD_Project__c</referenceTo>
    <relationshipLabel>gBUILD Project Funding</relationshipLabel>
    <relationshipName>gBUILD_Project_to_Funding</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_PFundingItemController.cls
public with sharing class PBS_gBUILD_PFundingItemController extends PBS_gBUILD_ProjectIdBaseController 
{
    public PBS_gBUILD_ProjectFunding__c item { get;private set;}
    
    public PBS_gBUILD_PFundingItemController()
    {
        super(
            'Details', 
            false,
            new List<string>{
                'Funding Sources', 'PBS_gBUILD_PFundingSources'                     
            });
        try
        {            
            bind();
        }
        catch (Exception ex)
        {
            handleConstructorError(ex);
        }            
    }
    
    protected override void bind()
    {
        super.bind();    
        string id = ApexPages.currentPage().getParameters().get(PBS_gBUILD_Utility.queryStringPFundingId);
        if (id!=null)
        {
            item = [
                select 
                    id,
                    FundingFY__c,
                    FundingType__c,
                    ProjectId__c,
                    Amount__c,
                    Asid__c,
                    Description__c,
                    FundingSource__c
                from
                    PBS_gBUILD_ProjectFunding__c
                where 
                    id=:id                          
            ];
        }
        if (item==null)
        {
            item = new PBS_gBUILD_ProjectFunding__c();
            item.ProjectId__c = projectId;
            viewMode = false;
        }   
    }
    
    public PageReference edit()
    {
        PBS_gBUILD_Utility.showDebugMessage('EDIT');
        viewMode = false;
        bind();
        return null;
    }
    
    public PageReference save()
    {
        try
        {
            PBS_gBUILD_Utility.showDebugMessage('SAVE');    
            upsert item;
        }
        catch (Exception ex)
        {
            PBS_gBUILD_Utility.showDebugMessage(ex); 
            return null;   
        }                    
        PBS_gBUILD_Utility.RecordProjectModifiedReason(projectId, 'Project funding item was added/updated');                
        viewMode = true;
        bind();
        return null;
    }

    public PageReference saveAndNew()
    {
        PBS_gBUILD_Utility.showDebugMessage('SAVEandNEW');
        upsert item;
        return createPageLink(ProjectPageRefs.PFundingSourcesItem, true);
    }

    public PageReference cancel()
    {
        return createPageLink(ProjectPageRefs.PFundingSources);
    }   
}