force-app/main/default/objects/gBUILD_ApplicationConfig__c/gBUILD_ApplicationConfig__c.object-meta.xml
<CustomObject>
    <description>gBUILD Application level configuration</description>
    <label>gBUILD Application Config</label>
    <nameField>
        <label>The Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>gBUILD Application Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/recordTypes/WfState.recordType-meta.xml
<RecordType>
    <fullName>WfState</fullName>
    <active>true</active>
    <description>A workflow state machine state.</description>
    <label>Workflow State</label>
</RecordType>

force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>Small Projects: Minor improvements of systems/conditions
Lim. Scope: Improvement of single/limited component(s)
Partial Mod: Replace/restore some major systems
Full Mod: Replace/restore all major components
New Con: New structures/building extensions</description>
    <inlineHelpText>Small Projects: Minor improvements of systems/conditions
Lim. Scope: Improvement of single/limited component(s)
Partial Mod: Replace/restore some major systems
Full Mod: Replace/restore all major components
New Con: New structures/building extensions</inlineHelpText>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NewConstruction</fullName>
            </value>
            <value>
                <fullName>FullModernization</fullName>
            </value>
            <value>
                <fullName>PartialModernizations</fullName>
            </value>
            <value>
                <fullName>LimitedScope</fullName>
            </value>
            <value>
                <fullName>SmallProject</fullName>
            </value>
            <value>
                <fullName>EnergyDivision</fullName>
            </value>
            <value>
                <fullName>EnergyDiv - ENE0000</fullName>
            </value>
            <value>
                <fullName>EnergyDiv - ENWTR000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/WorkflowPhaseId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current workflow phase for this project</description>
    <inlineHelpText>Current workflow phase for this project</inlineHelpText>
    <label>Workflow Phase ID</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>PBS_gBUILD_Project -&amp;amp;amp;amp;gt; gBUILD_ApplicationConfig</relationshipLabel>
    <relationshipName>L_PBS_gBUILD_Project_2_gBUILD_Applicatio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtCreatedIn__c.field-meta.xml
<CustomField>
    <fullName>txtCreatedIn__c</fullName>
    <label>Created In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gBUILD</fullName>
            </value>
            <value>
                <fullName>GPGIS</fullName>
            </value>
            <value>
                <fullName>ePM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCurrentState__c.field-meta.xml
<CustomField>
    <fullName>txtCurrentState__c</fullName>
    <label>Current State [from ePM]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Formative</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtLongName__c.field-meta.xml
<CustomField>
    <fullName>txtLongName__c</fullName>
    <label>Project Long Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtRegion__c.field-meta.xml
<CustomField>
    <fullName>txtRegion__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPBS_gBUILD_PContactsRoleDetail.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_PContactsRoleDetail
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        //PBS_gBUILD_Project__c p = td.createGbProjectOnPbsProjectEpm1();
        Profile pro = [SELECT Id FROM Profile WHERE Name='GSA System User'];
        User u = new User(Alias = 'GBTest2', Email='gbuildtesuser123_2@testorg.com', 
              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
              LocaleSidKey='en_US', ProfileId = pro.Id, 
              TimeZoneSidKey='America/Los_Angeles', UserName='gbuildTestclassuser123_2@gsa.gov');
        insert u;
         
            PBS_Project__c pbsproj = new PBS_Project__c(
                txtLongName__c='gBUILD:TEST:EPM:XXX',
                txtRegion__c='00',
                txtCreatedIn__c=PBS_gBUILD_Utility.commonProjCreatorEpm,
                txtCurrentState__c='Active'
            );
            insert pbsproj ;
             String sobjectName ='gBUILD_ApplicationConfig__c';
             String devName ='WfState';
             String rtId = [select id from RecordType where sobjecttype=:sobjectName and developername=:devName].id; 
             gBUILD_ApplicationConfig__c acWfStateLarge = new gBUILD_ApplicationConfig__c(RecordTypeId=rtId, Name='WFS1_LargeProject_Initiated');
             insert acWfStateLarge; 
            PBS_gBUILD_Project__c p = new PBS_gBUILD_Project__c(
                Projectid__c=pbsproj.id,
                WorkflowPhaseId__c = acWfStateLarge.id,
                ProjectType__c=PBS_gBUILD_Utility.projectTypeNewConstruction
            );
            insert p;
        TestPBS_gBUILD_Utility.setCurrentPageReference(p.id);

        PBS_gBUILD_PContactsRoleDetailController ctrl = new PBS_gBUILD_PContactsRoleDetailController();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assert(ctrl.container!=null);        
        ctrl.Container = p;
        ctrl.Container.OwnerId = u.id;//UserInfo.getUserId();
        ctrl.Role = PBS_gBUILD_Utility.SharingReasonWfRoleDataEntry;
        ctrl.Save();
        ctrl.Role = PBS_gBUILD_Utility.SharingReasonWfRoleDesignReviewer;
        ctrl.Save();
        ctrl.Role = PBS_gBUILD_Utility.SharingReasonWfRoleProjectAdmin;
        ctrl.Save();
        ctrl.Role = 'superman';
        ctrl.saveAndNew();
        system.assert(ctrl.cancel()!=null);
        
    }
}