force-app/main/default/objects/gBUILD_ApplicationConfig__c/gBUILD_ApplicationConfig__c.object-meta.xml
<CustomObject>
    <description>gBUILD Application level configuration</description>
    <label>gBUILD Application Config</label>
    <nameField>
        <label>The Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>gBUILD Application Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The human readible label</description>
    <inlineHelpText>The human readible label</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/AwardDate__c.field-meta.xml
<CustomField>
    <fullName>AwardDate__c</fullName>
    <description>Enter the date when the Project was awarded</description>
    <inlineHelpText>Enter the date when the project was awarded</inlineHelpText>
    <label>Actual Constr. Award Date (EnergyDiv)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/BudgetActivityCode__c.field-meta.xml
<CustomField>
    <fullName>BudgetActivityCode__c</fullName>
    <description>The major code used to fund this project.</description>
    <inlineHelpText>Please indicate primary budget activity code used to fund this project.</inlineHelpText>
    <label>Budget Activity Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ba01</fullName>
            </value>
            <value>
                <fullName>Ba02</fullName>
            </value>
            <value>
                <fullName>Ba03</fullName>
            </value>
            <value>
                <fullName>Ba04</fullName>
            </value>
            <value>
                <fullName>Ba05</fullName>
            </value>
            <value>
                <fullName>Ba06</fullName>
            </value>
            <value>
                <fullName>Ba31</fullName>
            </value>
            <value>
                <fullName>Ba51</fullName>
            </value>
            <value>
                <fullName>Ba52</fullName>
            </value>
            <value>
                <fullName>Ba53</fullName>
            </value>
            <value>
                <fullName>Ba54</fullName>
            </value>
            <value>
                <fullName>Ba55</fullName>
            </value>
            <value>
                <fullName>Ba61</fullName>
            </value>
            <value>
                <fullName>Ba62</fullName>
            </value>
            <value>
                <fullName>Ba63</fullName>
            </value>
            <value>
                <fullName>Ba64</fullName>
            </value>
            <value>
                <fullName>Ba71</fullName>
            </value>
            <value>
                <fullName>Ba80</fullName>
            </value>
            <value>
                <fullName>Ba81</fullName>
            </value>
            <value>
                <fullName>Ba90</fullName>
            </value>
            <value>
                <fullName>Ba99</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>Project Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cm</fullName>
            </value>
            <value>
                <fullName>CMc</fullName>
            </value>
            <value>
                <fullName>CmAtRisk</fullName>
            </value>
            <value>
                <fullName>DesignBidBuild</fullName>
            </value>
            <value>
                <fullName>DesignBuild</fullName>
            </value>
            <value>
                <fullName>DesignBuildBridging</fullName>
            </value>
            <value>
                <fullName>EnergySavingsPerformanceContract(ESPC)</fullName>
                <label>EnergySavingsPerformanceContract (ESPC)</label>
            </value>
            <value>
                <fullName>FirmFixedPrice</fullName>
            </value>
            <value>
                <fullName>GuaranteedMaximumPrice</fullName>
            </value>
            <value>
                <fullName>Other,PleaseSpecify:</fullName>
                <label>Other -- PleaseSpecify:</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ContractTypeOther__c.field-meta.xml
<CustomField>
    <fullName>ContractTypeOther__c</fullName>
    <inlineHelpText>If other, please specify</inlineHelpText>
    <label>Other Project Delivery Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If an escalation to another project has occurred.</description>
    <inlineHelpText>Please check box if an escalation project.</inlineHelpText>
    <label>Escalation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>Small Projects: Minor improvements of systems/conditions
Lim. Scope: Improvement of single/limited component(s)
Partial Mod: Replace/restore some major systems
Full Mod: Replace/restore all major components
New Con: New structures/building extensions</description>
    <inlineHelpText>Small Projects: Minor improvements of systems/conditions
Lim. Scope: Improvement of single/limited component(s)
Partial Mod: Replace/restore some major systems
Full Mod: Replace/restore all major components
New Con: New structures/building extensions</inlineHelpText>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NewConstruction</fullName>
            </value>
            <value>
                <fullName>FullModernization</fullName>
            </value>
            <value>
                <fullName>PartialModernizations</fullName>
            </value>
            <value>
                <fullName>LimitedScope</fullName>
            </value>
            <value>
                <fullName>SmallProject</fullName>
            </value>
            <value>
                <fullName>EnergyDivision</fullName>
            </value>
            <value>
                <fullName>EnergyDiv - ENE0000</fullName>
            </value>
            <value>
                <fullName>EnergyDiv - ENWTR000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/SubstantiallyCompleteDate__c.field-meta.xml
<CustomField>
    <fullName>SubstantiallyCompleteDate__c</fullName>
    <label>Substantially Complete Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/UNID__c.field-meta.xml
<CustomField>
    <fullName>UNID__c</fullName>
    <description>The ID from the legacy RAHD 1.x Lotus Notes application</description>
    <externalId>true</externalId>
    <inlineHelpText>Please provide the ID from the legacy RAHD 1.x Lotus Notes application.</inlineHelpText>
    <label>UNID</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/WorkflowPhaseId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current workflow phase for this project</description>
    <inlineHelpText>Current workflow phase for this project</inlineHelpText>
    <label>Workflow Phase ID</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>PBS_gBUILD_Project -&amp;amp;amp;amp;gt; gBUILD_ApplicationConfig</relationshipLabel>
    <relationshipName>L_PBS_gBUILD_Project_2_gBUILD_Applicatio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtCreatedIn__c.field-meta.xml
<CustomField>
    <fullName>txtCreatedIn__c</fullName>
    <label>Created In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gBUILD</fullName>
            </value>
            <value>
                <fullName>GPGIS</fullName>
            </value>
            <value>
                <fullName>ePM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCurrentState__c.field-meta.xml
<CustomField>
    <fullName>txtCurrentState__c</fullName>
    <label>Current State [from ePM]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Formative</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProjectManager__c.field-meta.xml
<CustomField>
    <fullName>txtProjectManager__c</fullName>
    <label>Project Manager</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_ProjectBasicsController.cls
public with sharing class PBS_gBUILD_ProjectBasicsController extends PBS_gBUILD_ProjectIdBaseController
{
    public PBS_gBUILD_Utility.LinkedObjectFieldInfo projectNameLink { get; private set; }
    
    public Boolean viewModeCommon
    {
        get
        {
            return viewMode || pro==null || pbsPro.txtCreatedIn__c!=PBS_gBUILD_Utility.commonProjCreatorGbuild;
        }
    }
    public Boolean editModeCommon
    {
        get
        {
            return !viewModeCommon;
        }
    }
    public PBS_gBUILD_Project__c pro { get; private set; }
    public PBS_Project__c pbsPro { get; private set; }
    
    public PBS_gBUILD_ProjectBasicsController()
    {
        super('Project Basics');
        try{
            bind();
        }
        catch (Exception ex){ handleConstructorError(ex);}        
    }
    
    public PageReference edit() 
    {
        viewMode = false;
        bind();
        return null;
    }  
         
    public PageReference cancel() 
    {
        viewMode = true;
        bind();
        return null;
    }  
    
    public PageReference save() 
    {
        update pro;
        update pbsPro;
        viewMode = true;
        RecordPageSaved();
        bind();
        return null;
    }      
    
    protected override void bind()
    {
        super.bind();
        
        pro = 
        [
            select
                name,
                id, 
                ProjectID__c, 
                UNID__c, 
                BudgetActivityCode__c,
                WorkflowPhaseId__r.Label__c,
                ProjectType__c,
                Escalation__c,
                ContractType__c,
                ContractTypeOther__c,                
                SubstantiallyCompleteDate__c,
                LastModifiedById,
                LastModifiedDate,
                AwardDate__c
            from PBS_gBUILD_Project__c
            where id=:ProjectId
        ];
        
        pbsPro = [
            select
                id, 
                txtCreatedIn__c,
                txtCurrentState__c,
                txtProjectManager__c,
                txtProgram__c,
                txtProgramArea_FullCode__c, 
                txtLongName__c,
                txtProjectDescription__c,
                txtRegion__c,
                txtProlianceAccountName__c,
                numConstructionPlanYear__c,
                numDesignPlanYear__c,
                numProjectNumber__c                
            from PBS_Project__c
            where id=:pro.ProjectID__c
            ];
            
        projectNameLink = new PBS_gBUILD_Utility.LinkedObjectFieldInfo(Schema.sObjectType.PBS_Project__c.fields.txtLongName__c, pbsProjectId, pbsPro.txtLongName__c);            
        
        confirmKeyProjectItems();
    }
    
    private void confirmKeyProjectItems()
    {            
        set<string> buildingIds = new set<string>();
        for (PBS_BuildingProjectAssociation__c bpa : 
        [
            select rluBuilding__c
            from PBS_BuildingProjectAssociation__c
            where 
                rluProject__c =:pbsProjectId and
                rluBuilding__c<>null
        ])
        {
            buildingIds.add(bpa.rluBuilding__c);
        }
        boolean missingPba = false;                
        for (PBS_gBUILD_ProjectBuilding__c pb :
        [
            select id, BldgId__c
            from PBS_gBUILD_ProjectBuilding__c
            where Rahd_ProjectParentId__c =:ProjectId
        ])
        {
            if (buildingIds.contains(pb.BldgId__c)) continue;
            PBS_gBUILD_Utility.ShowErrorMessage(string.format('A project building ({0}) exists without an underlying buildingProjectAssociation record.  Please contact {1}.', new string[]{pb.id, AppConfig.HelpDeskEmail__c}));
        }
                
        if (!missingPba && buildingIds.size()==0){
            PBS_gBUILD_Utility.ShowWarningMessage('No buildings have been assigned to this project');
        }
    }
}