force-app/main/default/objects/gBUILD_ApplicationConfig__c/gBUILD_ApplicationConfig__c.object-meta.xml
<CustomObject>
    <description>gBUILD Application level configuration</description>
    <label>gBUILD Application Config</label>
    <nameField>
        <label>The Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>gBUILD Application Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/ForCustomerPortalUsers__c.field-meta.xml
<CustomField>
    <fullName>ForCustomerPortalUsers__c</fullName>
    <defaultValue>true</defaultValue>
    <label>For Customer Portal Users</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/ForInternalUsers__c.field-meta.xml
<CustomField>
    <fullName>ForInternalUsers__c</fullName>
    <defaultValue>true</defaultValue>
    <label>For Internal Users</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The human readible label</description>
    <inlineHelpText>The human readible label</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/LinkReference__c.field-meta.xml
<CustomField>
    <fullName>LinkReference__c</fullName>
    <label>Link Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The order in the group.  Lowest number first.</description>
    <label>Order</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>gBUILD Application Configs</relationshipLabel>
    <relationshipName>gBUILD_Application_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/recordTypes/Link.recordType-meta.xml
<RecordType>
    <fullName>Link</fullName>
    <active>true</active>
    <description>A link that is part of a collection.</description>
    <label>Link</label>
</RecordType>

force-app/main/default/classes/PBS_gBUILD_LinkListCController.cls
public with sharing class PBS_gBUILD_LinkListCController
{
    public string Name { get; set; }
    public string Target { get; set; }
    public string Title { get { bind(); return Title_p; } }
    private string Title_p;
    public List<Link> Links { get { bind(); return Links_p; } }
    private List<Link> Links_p;
    
    public class Link
    {
        public string Text { get; set; }
        public string Reference { get; set; }
    }
    
    public PBS_gBUILD_LinkListCController()
    {
        Links_p = null;
        Title_p = '';
    }
    
    private void bind()
    {
        if (Links_p!=null) return;
        boolean isCustomerPortalUser = UserInfo.getUserType()=='CspLitePortal' || UserInfo.getUiTheme()=='PortalDefault';
        gBUILD_ApplicationConfig__c[] acs;
        if (isCustomerPortalUser)
        {
            acs = 
            [
                select parent__r.label__c, name, label__c, LinkReference__c 
                from gBUILD_ApplicationConfig__c 
                where 
                    RecordTypeId=:PBS_gBUILD_Utility.appConfigRecordTypeIdLink and 
                    Parent__r.name=:Name and ForCustomerPortalUsers__c=true
                order by order__c, name
            ];
         }
         else
         {
            acs = 
            [
                select parent__r.label__c, name, label__c, LinkReference__c 
                from gBUILD_ApplicationConfig__c 
                where 
                    RecordTypeId=:PBS_gBUILD_Utility.appConfigRecordTypeIdLink and 
                    Parent__r.name=:Name and ForInternalUsers__c=true
                order by order__c, name
            ];         
         }
        
//        Title_p = string.format('My Title(name="{0}", cnt={1}, rt={2})', new string[]{Name, acs.size().format(), PBS_gBUILD_Utility.appConfigRecordTypeIdLink});
        Links_p = new List<Link>();
        for (gBUILD_ApplicationConfig__c ac : acs)
        {
            Link l = new Link();
            l.Text=ac.label__c;
            l.Reference=ac.LinkReference__c;
            Links_p.add(l);
            Title_p = ac.parent__r.label__c;
        }
    }
}