force-app/main/default/objects/gBUILD_ApplicationConfig__c/gBUILD_ApplicationConfig__c.object-meta.xml
<CustomObject>
    <description>gBUILD Application level configuration</description>
    <label>gBUILD Application Config</label>
    <nameField>
        <label>The Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>gBUILD Application Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The human readible label</description>
    <inlineHelpText>The human readible label</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gBUILD_ApplicationConfig__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>gBUILD Application Configs</relationshipLabel>
    <relationshipName>gBUILD_Application_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/PBS_Building__c.object-meta.xml
<CustomObject>
    <description>PBS Common Building Object</description>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Building__c/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <label>Building Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Location_Code_Plus__c.field-meta.xml
<CustomField>
    <fullName>Location_Code_Plus__c</fullName>
    <externalId>true</externalId>
    <label>Location Code Plus</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/PBS_BuildingProjectAssociation__c.object-meta.xml
<CustomObject>
    <description>PBS Project-Building Junction Object</description>
    <label>PBS Building Project Association</label>
    <nameField>
        <displayFormat>PBSPRJ-BLDG-{0000000000}</displayFormat>
        <label>PBS Building Project Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Building Project Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/fields/rluBuilding__c.field-meta.xml
<CustomField>
    <fullName>rluBuilding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Record ID</label>
    <referenceTo>PBS_Building__c</referenceTo>
    <relationshipLabel>PBS Building Project Associations</relationshipLabel>
    <relationshipName>PBS_Building_Project_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/fields/rluProject__c.field-meta.xml
<CustomField>
    <fullName>rluProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Record ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>PBS Building Project Associations</relationshipLabel>
    <relationshipName>PBS_Building_Project_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/WorkflowPhaseId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current workflow phase for this project</description>
    <inlineHelpText>Current workflow phase for this project</inlineHelpText>
    <label>Workflow Phase ID</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>PBS_gBUILD_Project -&amp;amp;amp;amp;gt; gBUILD_ApplicationConfig</relationshipLabel>
    <relationshipName>L_PBS_gBUILD_Project_2_gBUILD_Applicatio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtCreatedIn__c.field-meta.xml
<CustomField>
    <fullName>txtCreatedIn__c</fullName>
    <label>Created In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gBUILD</fullName>
            </value>
            <value>
                <fullName>GPGIS</fullName>
            </value>
            <value>
                <fullName>ePM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCurrentState__c.field-meta.xml
<CustomField>
    <fullName>txtCurrentState__c</fullName>
    <label>Current State [from ePM]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Formative</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtLongName__c.field-meta.xml
<CustomField>
    <fullName>txtLongName__c</fullName>
    <label>Project Long Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProjectManager__c.field-meta.xml
<CustomField>
    <fullName>txtProjectManager__c</fullName>
    <label>Project Manager</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProlianceAccountName__c.field-meta.xml
<CustomField>
    <fullName>txtProlianceAccountName__c</fullName>
    <label>Proliance Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtRegion__c.field-meta.xml
<CustomField>
    <fullName>txtRegion__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_CookieHelper.cls
public with sharing class PBS_gBUILD_CookieHelper {

    private List<Cookie> cookies { get; set; }
    public String pbsProjectId { get; private set; }
    public String pbsProjectCreatedIn { get; private set; }
    public String numProjectRegion { get; private set; }
    public string wfPhaseId  { get; private set; }
    public string wfPhaseName  { get; private set; }
    public String prolianceAccountName { get; private set; }
    public String pmName { get; private set; }
    public Boolean isProjectFormative { get; private set; }
    public string projectOwnerId { get; private set; }
    
    public PBS_gBUILD_CookieHelper()
    {
        cookies = new List<Cookie>();
    }
        
    public void setPageName(String pageName)
    {
        cookies.add(new Cookie('PBS_gBUILD_PageName', pageName, null, -1, false));
//      ApexPages.currentPage().setCookies(cookies);            
    }
    
    public void setExtraBreadcrumbs(List<string> extraBreadcrumbs)
    {
        string s = '';
        if (extraBreadcrumbs!=null)
        {
            for (string z : extraBreadcrumbs)
            {
                if (s.length()>0)
                {
                    s+=',';
                }
                s+=z;
            }
        }       
        cookies.add(new Cookie('PBS_gBUILD_ExtraBreadcrumbs', s, null, -1, false));
    }
    
    public void setCookies()
    {
        ApexPages.currentPage().setCookies(cookies);                
    }
    
    public void resetProjectCookies()
    {
        setProjectCookies(null);
    }
    
    public String getProjectId()
    {
        return ApexPages.currentPage().getCookies().get('PBS_gBUILD_ProjectId').getValue();
    }
    
    public String getBuildingId()
    {
        return ApexPages.currentPage().getCookies().get('PBS_gBUILD_BuildingId').getValue();
    }   
    
    public void setProjectCookies(String projectId)
    {
        setProjectCookies(projectId, null);
    }
    
    public void setDebugVal(String val)
    {
        cookies.add(new Cookie('PBS_gBUILD_DBG', val, null, -1, false));    
    }
    
    public void setProjectCookies(String projectId, String pbuildingId)
    {       
        if (projectId==null || projectId=='')
        {
            cookies.add(new Cookie('PBS_gBUILD_ProjectId', '', null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_ProjectName', '', null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_ProjectNameField', '', null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_BuildingId', '', null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_BuildingIds', '', null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_BuildingNames', '', null, -1, false));               
        }
        else        
        {
            String projectIdEscapeSingleQuotes = String.isNotBlank(projectId)?string.escapeSingleQuotes(projectId):projectId;
            String strQuery = 'select ';
            strQuery += 'id,Name,OwnerId,ProjectId__c,ProjectId__r.txtLongName__c,';
            strQuery += 'ProjectId__r.txtRegion__c,ProjectId__r.txtCreatedIn__c,';
            strQuery += 'ProjectId__r.txtProlianceAccountName__c,ProjectId__r.txtCurrentState__c,';
            strQuery += 'ProjectId__r.txtProjectManager__c,WorkflowPhaseId__c,';
            strQuery += 'WorkflowPhaseId__r.Label__c,WorkflowPhaseId__r.Parent__r.Name';
            strQuery += ' from PBS_gBUILD_Project__c';
            strQuery += ' where id =: projectIdEscapeSingleQuotes';
            PBS_gBUILD_Project__c gbProj = Database.query(strQuery);
            
            /*
            PBS_gBUILD_Project__c gbProj = [
                select id, 
                    Name,
                    OwnerId,
                    ProjectId__c,
                    ProjectId__r.txtLongName__c, 
                    ProjectId__r.txtRegion__c, 
                    ProjectId__r.txtCreatedIn__c,
                    ProjectId__r.txtProlianceAccountName__c,
                    ProjectId__r.txtCurrentState__c,
                    ProjectId__r.txtProjectManager__c,
                    WorkflowPhaseId__c,
                    WorkflowPhaseId__r.Label__c,                    
                    WorkflowPhaseId__r.Parent__r.Name
                from PBS_gBUILD_Project__c
                where id=:projectId
            ];
            */
            
            pbsProjectId = gbProj.ProjectId__c;         
            pbsProjectCreatedIn = gbProj.ProjectId__r.txtCreatedIn__c;
            numProjectRegion = gbProj.ProjectId__r.txtRegion__c;
            wfPhaseId = gbProj.WorkflowPhaseId__c;
            wfPhaseName = gbProj.WorkflowPhaseId__r.Label__c;
            prolianceAccountName = gbProj.ProjectId__r.txtProlianceAccountName__c;
            pmName = gbProj.ProjectId__r.txtProjectManager__c;
            isProjectFormative = gbProj.ProjectId__r.txtCurrentState__c==PBS_gBUILD_Utility.projectStateFormative;
            projectOwnerId = gbProj.OwnerId;
            
            Set<string> uniqueBuildings = new Set<string>();
            String bids=null;   
            String bnames=null;
            List<PBS_BuildingProjectAssociation__c> pbas = [
                select 
                    id,
                    rluBuilding__r.Location_Code_Plus__c, 
                    rluBuilding__r.Building_Name__c 
                from PBS_BuildingProjectAssociation__c
                where rluProject__c=:pbsProjectId
            ];                  
            for (PBS_BuildingProjectAssociation__c pba : pbas)
            {
                if (uniqueBuildings.contains(pba.rluBuilding__r.Location_Code_Plus__c)) continue;
                uniqueBuildings.add(pba.rluBuilding__r.Location_Code_Plus__c);
                if (bids==null)
                {
                    bids = '';
                    bnames = '';
                }
                else
                {
                    bids += '`';
                    bnames += '`';              
                }
                bids += pba.rluBuilding__r.Location_Code_Plus__c;
                bnames += pba.rluBuilding__r.Building_Name__c;
            }
            cookies.add(new Cookie('PBS_gBUILD_ProjectId', projectId, null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_ProjectName', gbProj.ProjectId__r.txtLongName__c, null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_ProjectNameField', gbProj.Name, null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_BuildingId', pbuildingId, null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_BuildingIds', bids, null, -1, false));
            cookies.add(new Cookie('PBS_gBUILD_BuildingNames', bnames, null, -1, false));                   
            cookies.add(new Cookie('PBS_gBUILD_WfMachine', gbProj.WorkflowPhaseId__r.Parent__r.Name, null, -1, false));       
        }
    }
}