force-app/main/default/objects/Batch_Process_Log__c/Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <description>This object serves as the error logging object for any batch process. If batches run successfully or if they run unsuccessfully, records are logged here to ensure error log captures during an apex job run.</description>
    <label>Batch Process Log</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>Batch Process Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Process_Log__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>This field stores the name of the apex batch class that created this record.</description>
    <inlineHelpText>This field stores the name of the apex batch class that created this record.</inlineHelpText>
    <label>Batch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Process_Log__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>It references when the batch process started.</description>
    <inlineHelpText>It stores the beginning date time of the batch process run.</inlineHelpText>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Process_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field stores the transaction status per batch process run.</description>
    <inlineHelpText>This field stores the transaction status per batch process run.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_License__c.field-meta.xml
<CustomField>
    <fullName>User_License__c</fullName>
    <formula>Profile.UserLicense.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LMT_PermSetInitialSync_Batch.cls
/*
*********************************************************
Apex Class Name    : LMT_PermSetInitialSync_Batch
Created Date       : February 12, 2025
@description       : This batch class calls the LMT_PermSetInitialSyncHandler to 
					 update the modified LMT User License records based on related User record. 
                     It updates the CRM permission set assignment checkbox on the related LMT User License object. 
@author            : Disha Bailoor
Modification Log:
Ver   Date         Author                               Modification
1.0   04-15-2025   Disha Bailoor                        Create.
*********************************************************
*/

global  with sharing class LMT_PermSetInitialSync_Batch implements Database.batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    global  String query;
    Datetime daysAgo; 
    public Batch_Process_Log__c log; 
    String BATCH_NAME = 'LMT_PermSetInitialSync_Batch'; 
     
    //Constructor which will be invoked by the scheduler
    global LMT_PermSetInitialSync_Batch(){  
		List<Batch_Process_Log__c> batchLogs = [
            SELECT Id, Batch_Name__c, Start_Date_Time__c, CreatedDate 
            FROM Batch_Process_Log__c 
            WHERE Batch_Name__c = :BATCH_NAME 
            	AND Status__c = 'Completed' 
            WITH USER_MODE
            ORDER BY CreatedDate DESC NULLS LAST 
            LIMIT 1];
        System.debug(batchLogs); 
        query = 'SELECT Id, FederationIdentifier, User_License__c, IsActive, Email, LastLoginDate, CreatedDate FROM User WHERE isActive = TRUE AND User_License__c != NULL ORDER BY CreatedDate ASC';  
       	if(Test.isRunningTest()){
            query += ' Limit 10';
        } 
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){ 
        log = BatchProcessLogHandler.logBatchCreate(BATCH_NAME);
        log = BatchProcessLogHandler.logBatchStart(log); 
        return Database.getQueryLocator(query);
    }
    
    global  void execute(Database.BatchableContext BC, List<User> users){
        try{
            LMT_PermSetInitialSyncSenderService permSetHandler = new LMT_PermSetInitialSyncSenderService(); 
        	permSetHandler.processCRMAssignments(users);    
        }catch(Exception e){BatchProcessLogHandler.logBatchFailure(log, e.getMessage()); throw e;}   
    }
    
    global  void finish(Database.BatchableContext BC){
         if(log != null){
            BatchProcessLogHandler.logBatchSuccess(log); 
        }
    }
    
}