force-app/main/default/objects/Case/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <formula>PBS_Lease__r.Building_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/GSA_Inbox__c.field-meta.xml
<CustomField>
    <fullName>GSA_Inbox__c</fullName>
    <defaultValue>&quot;g-rex.file@gsa.gov&quot;</defaultValue>
    <description>GSA generic email for all Case Submissions</description>
    <label>GSA Inbox</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lessor__c.field-meta.xml
<CustomField>
    <fullName>Lessor__c</fullName>
    <formula>PBS_Lease__r.Lessor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lessor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Building_City__c.field-meta.xml
<CustomField>
    <fullName>Building_City__c</fullName>
    <formula>PBS_Building__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <formula>PBS_Building__r.Building_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Building_State_Code__c</fullName>
    <formula>PBS_Building__r.State_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Street_Address__c</fullName>
    <formula>PBS_Building__r.Street_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Street Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Building_Zip_Code__c</fullName>
    <formula>PBS_Building__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lessor__c.field-meta.xml
<CustomField>
    <fullName>Lessor__c</fullName>
    <label>Lessor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Short_Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Lease_Number__c</fullName>
    <formula>if(NOT(ISBLANK(Lease_Number__c)),if( LEN(Lease_Number__c)&gt;5, RIGHT(Lease_Number__c, 5),Lease_Number__c ),&apos;&apos;)</formula>
    <label>Short Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor_Comments__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Comments__c</fullName>
    <label>Requestor Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_RegionalEmail__mdt/RET_RegionalEmail__mdt.object-meta.xml
<CustomObject>
    <description>The metadata holds mapping between Region and the email box associated to this.</description>
    <label>RET Regional Email</label>
    <pluralLabel>RET_RegionalEmails</pluralLabel>
</CustomObject>

force-app/main/default/objects/RET_RegionalEmail__mdt/fields/RegionalEmail__c.field-meta.xml
<CustomField>
    <fullName>RegionalEmail__c</fullName>
    <label>RegionalEmail</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_RegionalEmail__mdt/fields/RegionCode__c.field-meta.xml
<CustomField>
    <fullName>RegionCode__c</fullName>
    <label>RegionCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RET_LeaseSearchController.cls
public without sharing class RET_LeaseSearchController {
    public static final List<String> selectFields = new List<String>{'Lease_Number__c ','Building_City__c', 'Building_Name__c', 'Building_State_Code__c', 'Building_Street_Address__c', 'Building_Zip_Code__c', 'Lease_Effective_Date__c', 'Lease_Expiration_Date__c', 'Short_Lease_Number__c','Lessor__c'};
    public static final List<String> searchableFields = new List<String>{'Lease_Effective_Date__c', 'Lease_Expiration_Date__c', 'Short_Lease_Number__c', 'Lessor__c'};

    /* Commented out for 2024-2025 RET Surge to no longer facilitate Lease Access Request and Approval functionality
       on the Search and Home pages.
    @AuraEnabled
    public static boolean createLeaseAccess(String leaseId, String ReqComments) {
        PBS_Lease_Access__c leaseAccess;
        boolean result;
        try {
            //Seatch for existing lease access record if there is one.
            PBS_Lease_Access__c[] lsacList = [select Id, PBS_Lease__c, Requestor__c, Requestor_Comments__c, Status__c from PBS_Lease_Access__c
                           where Requestor__c = :UserInfo.getUserId()
                           and PBS_Lease__c = :leaseId];
            if(lsacList != null && lsacList.size() > 0){
                PBS_Lease_Access__c updateLsac = lsacList[0];
                updateLsac.Status__c = RET_LeaseShareUtility.RET_Access_Status_Requested;
                updateLsac.Requestor_Comments__c = ReqComments;
                update updateLsac;
                result = true;
            } else {
                leaseAccess = new PBS_Lease_Access__c(
                    PBS_Lease__c = leaseId,
                    Requestor__c = UserInfo.getUserId(),
                    Requestor_Comments__c = ReqComments,
                    Status__c = RET_LeaseShareUtility.RET_Access_Status_Requested);
                insert leaseAccess;  
                result = true;
            }
        } catch(Exception e) {
            result = false; throw new AuraHandledException(e.getMessage());
        }   
        return result;
    } */
    
    @AuraEnabled
    public static Case createNewCase(String leaseId) {
        createApprovedLeaseAccess(leaseId);
        if(avoidDuplicateCaseCreation(leaseId) !=null){ return avoidDuplicateCaseCreation(leaseId); }
        system.debug('leaseId ' +leaseId);
        PBS_Lease__c lease;
        Case c;
        try {
            lease = [select Id,Region_Code__c from PBS_Lease__c where Id = :leaseId limit 1];
        } catch(Exception e) {
            throw new AuraHandledException(System.Label.RET_Lease_Not_Found);
        }
        //Check if the lease has an existing Draft case with same requesting lease owner
        List<Case> existingCase = [select Id,PBS_Lease__c from Case where PBS_Lease__c = :leaseId AND Status ='Draft' AND  OwnerId =:UserInfo.getUserId() limit 1];
        if(existingCase.size() >0){
            return existingCase[0];
        }
        system.debug('No Existing Cases');
        //Fetch the custom setting for region and email
        Map<String,String> regionEmailmap = new Map<String,String>();
        for(RET_RegionalEmail__mdt  regCst : [select RegionalEmail__c,RegionCode__c  from RET_RegionalEmail__mdt]){
            regionEmailmap.put(regCst.RegionCode__c,regCst.RegionalEmail__c);
        }
        try {
            c = new Case(
                Origin = 'Web',
                OwnerId = UserInfo.getUserId(),
                PBS_Lease__c = lease.Id,
                Status = 'Draft',
                Subject = 'Real Estate Tax Submission',
                Region_Code__c  = lease.Region_Code__c);
                
            if(String.isNotBlank(lease.Region_Code__c) && !regionEmailmap.isEmpty() && regionEmailmap.containsKey(lease.Region_Code__c))  c.GSA_Inbox__c  = regionEmailmap.get(lease.Region_Code__c);
                        
            insert c;
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        //createApprovedLeaseAccess(lease.Id);
        return c;
    }
    
    //Check if the lease has an existing Draft case with same requesting lease owner
    public static case avoidDuplicateCaseCreation(String leaseId) {
        case cse = null;
        List<Case> existingCase = [select Id,PBS_Lease__c from Case where PBS_Lease__c = :leaseId AND Status ='Draft' AND  OwnerId =:UserInfo.getUserId() limit 1];
        if(existingCase.size() >0)  cse = existingCase[0];
        return cse;
    }
    
    public static void createApprovedLeaseAccess(String leaseId) {
        PBS_Lease_Access__c leaseAccess;
        //Seatch for existing lease access record so we don't create unneeded records.
        PBS_Lease_Access__c[] lsacList = [select Id, PBS_Lease__c, Requestor__c, Requestor_Comments__c, Status__c from PBS_Lease_Access__c
                       where Requestor__c = :UserInfo.getUserId()
                       and PBS_Lease__c = :leaseId
                       and Status__c in ('POC', 'Approved')];
        if(lsacList != null && lsacList.size() > 0){
            //Do nothing since user already has a "POC" or "Approved" Lease Access record
        } else {
            leaseAccess = new PBS_Lease_Access__c(
                PBS_Lease__c = leaseId,
                Requestor__c = UserInfo.getUserId(),
                Requestor_Comments__c = '',
                Status__c = RET_LeaseShareUtility.RET_Access_Status_Approved);
            insert leaseAccess;  
        }
    }

    @AuraEnabled
    public Static SearchResultsWrapper getLeaseResults(PBS_Lease__c template, 
                                                        Integer selectedPage, 
                                                        Integer pageSize, 
                                                        String buildingName, 
                                                        String buildingAddress, 
                                                        String buildingCity, 
                                                        String buildingState,
                                                        String buildingZipCode) {
        selectedPage = Integer.valueOf(selectedPage);
        pageSize = Integer.valueOf(pageSize);

        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('PBS_Lease__c').getDescribe().fields.getMap();
        List<PBS_Lease__c> leaseList = new List<PBS_Lease__c>();
        Map<Id, PBS_Lease_Access__c> leaseLeaseAccessMap = new Map<Id, PBS_Lease_Access__c>();
        List<LeaseAccessWrapper> leaseAccessWrapperList = new List<LeaseAccessWrapper>();
        String soql = 'select Id,' + String.join(selectFields, ', ') + ' FROM PBS_Lease__c where ';
        List<String> whereStrings = new List<String>();
        if(template != null) {
            for(String field : searchableFields) {
                System.debug('Checking on adding searchable field ' + field + ' to whereStrings...');
                Schema.DisplayType fielddataType = fieldMap.get(field).getDescribe().getType();
                if(fielddataType == Schema.DisplayType.Date) {
                    if(template.get(field) != null) {
                        Date tmpDate = Date.valueof(template.get(field));
                        String dateVal = DateTime.newInstance(tmpDate.year(), tmpDate.month(), tmpDate.day()).format('yyyy-MM-dd');
                        whereStrings.add(field + ' = ' + dateVal);
                    }
                } else if(fielddataType == Schema.DisplayType.String) {
                    if(String.isNotBlank(String.valueOf(template.get(field)))) {
                        String strEsc = String.escapeSingleQuotes(String.valueof(template.get(field))); 
                        String tempInput = '\'%'+strEsc+'%\''; 
                        whereStrings.add(field + ' like ' + tempInput);
                    }
                }
                System.debug('whereStrings after date or string check: ' + whereStrings);
            }
            // Building fields
            if(String.isNotBlank(buildingName)) {
                whereStrings.add(createWhereClause('Building_Name__c', buildingName));
            }
            if(String.isNotBlank(buildingAddress)) {
                whereStrings.add(createWhereClause('Building_Street_Address__c', buildingAddress));
            }
            if(String.isNotBlank(buildingState)) {
                whereStrings.add(createWhereClause('Building_State_Code__c', buildingState));
            }
            if(String.isNotBlank(buildingCity)) {
                whereStrings.add(createWhereClause('Building_City__c', buildingCity));
            }
            if(String.isNotBlank(buildingZipCode)) {
                whereStrings.add(createWhereClause('Building_Zip_Code__c', buildingZipCode));
            }
            /* Commented out for 2024-2025 RET Surge to allow all Leases to be searched
            // Filter out search results if the owner is 'Cast Ironprd'(Integration User)
            if(System.Label.RET_Integration_User_Name != null) {
                whereStrings.add('Owner.Name != \''+ String.escapeSingleQuotes(System.Label.RET_Integration_User_Name) + '\'');
            } */
            //Added error handling if state is missing when lease number is entered - Ramesh
            if(String.isNotBlank(String.valueOf(template.get('Short_Lease_Number__c'))) && String.isBlank(buildingState)){
               throw new AuraHandledException(System.Label.RET_Missing_State_in_Search_Criteria);
            }

            //Replaced for 2024-2025 RET Surge to only require 1 or more where clause predicates 
            //since we commented out line 127 above which excluded leases owned by Cast Ironprd user.
            //if(whereStrings.size() > 1) {
            if(whereStrings.size() > 0) {
                try{
                    soql += String.join(whereStrings, ' AND ');
                    String countSoql = 'select count(Id) result from PBS_Lease__c where ' + String.join(whereStrings, ' AND ');
                    List<AggregateResult> countResult = Database.query(countSoql);
                    Integer rowCount = (Integer)countResult[0].get('result');
                    soql += ' order by Short_Lease_Number__c asc';
                    soql += ' limit ' + String.valueOf(pageSize);
                    soql += ' offset ' + String.valueOf(pageSize * (selectedPage - 1));
                    system.debug('getLeaseResults soql **** '+soql);
                    leaseList = Database.query(soql);
                    
                    // Get Lease Access records
                    for(PBS_Lease_Access__c lsac : [Select Id, PBS_Lease__c, Requestor__c, Status__c from PBS_Lease_Access__c 
                                                    where PBS_Lease__c in :leaseList
                                                    and Requestor__c = :UserInfo.getUserId() order by lastModifiedDate desc]) {
                        if(leaseLeaseAccessMap.containsKey((lsac.PBS_Lease__c))) {
                            continue;
                        } else {
                            leaseLeaseAccessMap.put(lsac.PBS_Lease__c, lsac);
                        }
                    }
                    for(PBS_Lease__c lease : leaseList) {
                        leaseAccessWrapperList.add(new LeaseAccessWrapper(lease, leaseLeaseAccessMap.get(lease.Id)));
                    }
                    system.debug('leaseAccessWrapperList ***' +leaseAccessWrapperList);
                    SearchResultsWrapper srw = new SearchResultsWrapper(leaseAccessWrapperList, rowCount, pageSize, selectedPage);
                    system.debug('Returning SearchResultWrapper: ' + srw);
                    return srw;
                }catch(Exception e) {
                    throw new AuraHandledException(e.getMessage());
                }
            } else {
                throw new AuraHandledException(System.Label.RET_Missing_Search_Criteria);
            } 
        }
        return null;
    }

    private static String createWhereClause(String apiName, String value) {
        String strEsc = String.escapeSingleQuotes(value);
        String tempInput = '\'%'+strEsc+'%\''; 
        return apiName + ' like ' + tempInput;
    }
    
    public class LeaseAccessWrapper {
        @AuraEnabled Public PBS_Lease__c lease {get;set;}
        @AuraEnabled Public PBS_Lease_Access__c leaseAccess {get;set;}
        LeaseAccessWrapper(PBS_Lease__c ls, PBS_Lease_Access__c lsac) {
            lease = ls;
            leaseAccess = lsac;
        }
    }

    public class SearchResultsWrapper {
        @AuraEnabled @testvisible Public List<LeaseAccessWrapper> leaseWrapperList {get;set;}
        @AuraEnabled @Testvisible Public Integer totalPages {get;set;}
        @AuraEnabled @Testvisible Public Integer totalResults {get;set;}
        @AuraEnabled @Testvisible Public Boolean hasPrevious {get;set;}
        @AuraEnabled @Testvisible Public Boolean hasNext {get;set;}

        public SearchResultsWrapper(List<LeaseAccessWrapper> wrappers, Integer rowCount, Integer pageSize, Integer selectedPage) {
            leaseWrapperList = wrappers;
            totalResults = rowCount;
            totalPages = (Integer)((Decimal)rowCount / (Decimal)pageSize).round(System.RoundingMode.UP);
            hasPrevious = selectedPage > 1;
            hasNext = selectedPage < totalPages;
        }
    }
    
}