force-app/main/default/objects/Case/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <formula>PBS_Lease__r.Building_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lessor__c.field-meta.xml
<CustomField>
    <fullName>Lessor__c</fullName>
    <formula>PBS_Lease__r.Lessor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lessor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Base_Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>RET_Base_Tax_Year__c</fullName>
    <description>Real Estate Tax submission base tax year.</description>
    <inlineHelpText>Real Estate Tax submission base tax year.</inlineHelpText>
    <label>RET Base Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Initial_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Initial_Submission_Date__c</fullName>
    <description>Indicates the first time a Real Estate Tax submission has been sent to GSA.</description>
    <inlineHelpText>Indicates the first time a Real Estate Tax submission has been sent to GSA.</inlineHelpText>
    <label>RET Initial Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Building_City__c.field-meta.xml
<CustomField>
    <fullName>Building_City__c</fullName>
    <formula>PBS_Building__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <formula>PBS_Building__r.Building_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Building_State_Code__c</fullName>
    <formula>PBS_Building__r.State_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Street_Address__c</fullName>
    <formula>PBS_Building__r.Street_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Street Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Building_Zip_Code__c</fullName>
    <formula>PBS_Building__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lessor__c.field-meta.xml
<CustomField>
    <fullName>Lessor__c</fullName>
    <label>Lessor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Short_Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Lease_Number__c</fullName>
    <formula>if(NOT(ISBLANK(Lease_Number__c)),if( LEN(Lease_Number__c)&gt;5, RIGHT(Lease_Number__c, 5),Lease_Number__c ),&apos;&apos;)</formula>
    <label>Short Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RET_LeaseListController.cls
public with sharing class RET_LeaseListController {

    @AuraEnabled
    public static LeaseListWrapper getWrapperList(List<String> statusFilters, Integer selectedPage, Integer pageSize) {
        selectedPage = Integer.valueOf(selectedPage);
        pageSize = Integer.valueOf(pageSize);

        List<LeaseWrapper> wrapperList = new List<LeaseWrapper>();
        Map<Id, List<Case>> leaseCaseMap = new Map<Id, List<Case>>();
        Map<Id, PBS_Lease_Access__c> leaseLeaseAccessMap = new Map<Id, PBS_Lease_Access__c>();
        Integer queryOffset = pageSize * (selectedPage - 1);

        // Count case results.
       // List<AggregateResult> countResult = [Select count(Id) result from Case where OwnerId = :UserInfo.getUserId() and Status in :statusFilters];
        List<AggregateResult> countResult = [Select count(Id) result from Case where PBS_Lease__c IN (Select Id from PBS_Lease__c) and Status in :statusFilters];
        Integer caseCount = (Integer)countResult[0].get('result');
        
        countResult = [Select count(Id) result from PBS_Lease__c];
        Integer rowCount = (Integer)countResult[0].get('result');       

        List<PBS_Lease__c> currentLeaseList = [select Id, Lease_Number__c, Building_Street_Address__c,
                            Building_State_Code__c, Building_Zip_Code__c,Short_Lease_Number__c, 
                            Building_Name__c, Lease_Effective_Date__c, Lease_Expiration_Date__c,
                            Lessor__c, Building_City__c from PBS_Lease__c
                            order by Lease_Number__c asc
                            limit :pageSize offset :queryOffset];

        // Get actual page results.
        for(Case taxCase : [Select Id, CaseNumber, PBS_Lease__c, RET_Base_Tax_Year__c, RET_Initial_Submission_Date__c, Status from Case 
                         where Status in :statusFilters
                         and PBS_Lease__c in :currentLeaseList order by CaseNumber asc]) {
            if(leaseCaseMap.containsKey(taxCase.PBS_Lease__c)) {
                leaseCaseMap.get(taxCase.PBS_Lease__c).add(taxCase);
            } else {
                leaseCaseMap.put(taxCase.PBS_Lease__c, new List<Case>{taxCase});
            }
        }
        system.debug('currentLeaseList *** '+currentLeaseList);
        system.debug('UserInfo.getUserId() *** '+ UserInfo.getUserId());
        
        // Get Lease Access records
        leaseLeaseAccessMap = RET_LeaseShareUtility.getLeaseAccessMap(currentLeaseList);
        
        /*for(PBS_Lease_Access__c lsac : [Select Id, PBS_Lease__c, Requestor__c, Status__c from PBS_Lease_Access__c 
                                       where PBS_Lease__c in :currentLeaseList
                                        and Requestor__c = :UserInfo.getUserId() order by lastModifiedDate desc]) {
             system.debug('Inside lease access for loop ***'+lsac);
            if(leaseLeaseAccessMap.containsKey((lsac.PBS_Lease__c))) {
                continue;
            } else {
                leaseLeaseAccessMap.put(lsac.PBS_Lease__c, lsac);
            }
        }*/
        

        for(PBS_Lease__c lease : currentLeaseList) {
            wrapperList.add(new LeaseWrapper(lease, leaseCaseMap.get(lease.Id), leaseLeaseAccessMap.get(lease.Id)));
        }
        system.debug('wrapperList ***' +wrapperList);
        return new LeaseListWrapper(wrapperList, rowCount, pageSize, selectedPage, caseCount);
    }

    public class LeaseWrapper {
        @AuraEnabled public List<Case> caseList {get;set;}
        @AuraEnabled public PBS_Lease__c lease {get;set;}
        @AuraEnabled public PBS_Lease_Access__c leaseAccess {get;set;}
        public LeaseWrapper(PBS_Lease__c ls, List<Case> csl, PBS_Lease_Access__c lsac) {
            lease = ls;
            caseList = csl;
            leaseAccess = lsac;
        }
    }

    public class LeaseListWrapper {
        @AuraEnabled @testvisible public List<LeaseWrapper> wrapperList {get;set;}
        @AuraEnabled @testvisible public Integer totalPages {get;set;}
        @AuraEnabled @testvisible public Integer totalCases {get;set;}
        @AuraEnabled @testvisible public Integer totalLeases {get;set;}
        @AuraEnabled @testvisible public Boolean hasPrevious {get;set;}
        @AuraEnabled @testvisible public Boolean hasNext {get;set;}

        public LeaseListWrapper(List<LeaseWrapper> wrappers, Integer rowCount, Integer pageSize, Integer selectedPage, Integer caseCount) {
            wrapperList = wrappers;
            totalLeases = rowCount;
            totalCases = caseCount;
            totalPages = (Integer)((Decimal)rowCount / (Decimal)pageSize).round(System.RoundingMode.UP);
            hasPrevious = selectedPage > 1;
            hasNext = selectedPage < totalPages;
        }
    }
}