force-app/main/default/objects/Case/fields/GSA_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>GSA_Contact_Email__c</fullName>
    <label>GSA Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Initial_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Initial_Submission_Date__c</fullName>
    <description>Indicates the first time a Real Estate Tax submission has been sent to GSA.</description>
    <inlineHelpText>Indicates the first time a Real Estate Tax submission has been sent to GSA.</inlineHelpText>
    <label>RET Initial Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Last_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Last_Submission_Date__c</fullName>
    <description>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</description>
    <inlineHelpText>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</inlineHelpText>
    <label>RET Last Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Submission_Comments__c.field-meta.xml
<CustomField>
    <fullName>RET_Submission_Comments__c</fullName>
    <label>RET Submission Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Taxes</fullName>
            </value>
            <value>
                <fullName>Change of Ownership / Novation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Full_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_File_Name__c</fullName>
    <label>Full File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RET Document Data</relationshipLabel>
    <relationshipName>RET_Document_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/RET_GREX_Integration_Email_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains email settings for notifications used by Real Estate Tax GREX integration.</description>
    <label>RET GREX Integration Email Settings</label>
</CustomObject>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>The email body. Additional information (integration error messages, etc.) may be appended.</description>
    <inlineHelpText>The email body. Additional information (integration error messages, etc.) may be appended.</inlineHelpText>
    <label>Email Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>The email subject line.</description>
    <inlineHelpText>The email subject line.</inlineHelpText>
    <label>Email Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Sender_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Display_Name__c</fullName>
    <description>The name displayed in the email &quot;From&quot; Field.</description>
    <inlineHelpText>The name displayed in the email &quot;From&quot; Field.</inlineHelpText>
    <label>Sender Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <description>The email address or distribution list that the email will be sent to.</description>
    <inlineHelpText>The email address or distribution list that the email will be sent to.</inlineHelpText>
    <label>To Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RET_SubmitAttachmentsController.cls
public without sharing class RET_SubmitAttachmentsController {
    
    public class MyException extends Exception {}
    
    Static String RET_GREX_API_INTEGRATION_NOTIFICATION='RET_Notification';
    Static String RET_GREX_API_INTEGRATION_NOTIFICATION_NONPROD ='RET_Notification_NonProd';
    Static String RET_GREX_API_INTEGRATION ='RET_GREX_API_Integration';
    
    @AuraEnabled
    public static ReviewAttachmentsResponse reviewAttachments(String leaseNumber) {
        System.debug('Inside reviewAttachments(), leaseNumber = ' + leaseNumber);
        // Initialize the response wrapper class
        ReviewAttachmentsResponse response = new ReviewAttachmentsResponse();
        try {
            // Fetch the most recent Draft Case for the Lease Number and see if any Documents are attached
            Case caseRec = getCase(leaseNumber);
            response.myCase = caseRec !=null? caseRec : null;
            if(caseRec !=null){
                List<RET_Document_Data__c> docs = [SELECT Attachment_Id__c FROM RET_Document_Data__c WHERE Parent_Case__c =: caseRec.Id];
                response.success = docs.size() > 0 ? true : false; 
            }else{
                response.success = false;
            }
        }Catch (Exception e){
            System.debug('caught error: ' + e.getMessage());
            response.addErrorMessage(e.getMessage());
        }
        // Return the response 
        return response;
    }
    
    public class ReviewAttachmentsResponse {
        @AuraEnabled public Boolean success { get; set; }
        @AuraEnabled public List<String> errorMessages { get; set; }
        @AuraEnabled public case myCase { get; set; }
        // Constructor to initialize the response object
        public ReviewAttachmentsResponse() {
            this.success = false;
            this.errorMessages = new List<String>();
            this.myCase = new Case();
        }
        // Method to add an error message to the response
        public void addErrorMessage(String message) {
            this.errorMessages.add(message);
        }
    }
    
    public static case getCase(String leaseNumber){
        Case cse = null;
        System.debug('Starting getCaseId() with leaseNumber ' + leaseNumber);
        String leaseId = [SELECT Id FROM PBS_Lease__c WHERE Lease_Number__c =: leaseNumber LIMIT 1].Id;
        String myUserId = UserInfo.getUserId();
        List<Case> caseRec = [SELECT Id,GSA_Contact_Email__c, Status,PBS_Lease__c, RET_Submission_Comments__c  FROM Case WHERE Status = 'Draft' AND PBS_Lease__c =: leaseId AND OwnerId =: myUserId ORDER BY CreatedDate DESC Limit 1];
        if(caseRec.size()>0){
            cse = caseRec[0];
        }
        //Only the RET_UploadAttachmentController Apex class should create a new Draft Case if one is not found for the User and Lease
        //if (caseId == null) {
        //    Case newCase = new Case();
        //    newCase.Status = 'Draft';
        //    newCase.PBS_Lease__c = leaseId;
        //    insert newCase;
        //    return newCase.Id;
        //} else {
        return cse;
        //}
    }
    
    @AuraEnabled
    public static void submitDocumentsToGREX(String caseId) {
        try{
           
                Datetime currentDateTime = Datetime.now();
                List<RET_Document_Data__c> attachmentRecs = [SELECT Parent_Case__c, Parent_Case__r.Status, Parent_Case__r.Lease_Number__c,Id, Attachment_ID__c, Full_File_Name__c, Document_Category__c, Document_Type__c 
                                                             FROM RET_Document_Data__c
                                                             WHERE Parent_Case__c = :caseId];
             if(attachmentRecs[0].Parent_Case__r.Status == 'Draft'){
                CaseWrapper caseData = new CaseWrapper();
                caseData.caseId = caseId;
                caseData.initialSubmissionDate = currentDateTime;
                caseData.documents = new List<Document>();
                if (attachmentRecs.size() > 0) {
                    caseData.leaseNumber = attachmentRecs[0].Parent_Case__r.Lease_Number__c;
                    for(RET_Document_Data__c docu : attachmentRecs) {
                        Document doc1 = new Document();
                        doc1.attachmentId = docu.Attachment_ID__c !=null ? docu.Attachment_ID__c : null;
                        doc1.fileName = docu.Full_File_Name__c != null? docu.Full_File_Name__c : null ;
                        doc1.documentCategory = docu.Document_Category__c != null ? docu.Document_Category__c : null;
                        doc1.documentType = docu.Document_Type__c !=null ?docu.Document_Type__c : null;
                        caseData.documents.add(doc1); 
                    }
                    system.debug(JSON.serializePretty(caseData) ); 
                    String reqStr =JSON.serializePretty(caseData);
                    //Call GREX Service 
                    String SERVICETYPE =[Select Id, Name, IsSandbox from Organization].IsSandbox == true ? RET_GREX_API_INTEGRATION_NOTIFICATION_NONPROD : RET_GREX_API_INTEGRATION_NOTIFICATION;
                    if(RET_APICallManager.resourceToHandler.containsKey(RET_GREX_API_INTEGRATION) ){
                        RET_APIntegration_Interface GREX_Handler = (RET_APIntegration_Interface) RET_APICallManager.resourceToHandler.get(RET_GREX_API_INTEGRATION).newinstance();
                        GREX_Handler.doHandleRequest(reqStr, SERVICETYPE); 
                        //Update Case after successfull callout
                        Case cs = new case (Id= caseId , Status ='Submitted' ,  RET_Initial_Submission_Date__c = currentDateTime, RET_Last_Submission_Date__c = currentDateTime) ;
                        update cs;
                    }
                }
            }
            else{
                throw new MyException('System Could not find a recent draft case ');
            }
        }Catch (Exception e){
            //sendIntegrationErrorEmail(e.getMessage());
            throw new MyException('Unable to process the request at this time. Please provide following details to admin. '+'/n' + e);
        }
    }  
    
    @TestVisible private static void sendIntegrationErrorEmail(String error) {
        RET_GREX_Integration_Email_Settings__c emailSettings1 = RET_GREX_Integration_Email_Settings__c.getInstance(
            'O&M Integration Failure'
        );
        RET_GREX_Integration_Email_Settings__c emailSettings2 = RET_GREX_Integration_Email_Settings__c.getInstance(
            'GREX Team Integration Failure'
        );
        if (emailSettings1 != null || emailSettings2 != null) {
            try {
                //Messaging.reserveSingleEmailCapacity(2);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setSenderDisplayName(emailSettings1.Sender_Display_Name__c);
                mail.setToAddresses(new List<String>{ emailSettings1.To_Address__c, emailSettings2.To_Address__c });
                mail.setSubject(emailSettings1.Email_Subject__c);
                mail.setHtmlBody(emailSettings1.Email_Body__c + error);
                Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
                system.debug('**' + mail);
            } catch (Exception e) {
                System.debug(' *** email error: ' + e.getMessage());
                throw new AuraHandledException(e.getMessage());
            }
        }
    }
    
    public class Document { 
        public String attachmentId; 
        public String fileName; 
        public String documentCategory; 
        public String documentType; 
    }
    
    public class CaseWrapper {
        public String caseId;
        public String leaseNumber;
        public Datetime initialSubmissionDate;
        public List<Document> documents;
    }
    
    
}