force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lessor__c.field-meta.xml
<CustomField>
    <fullName>Lessor__c</fullName>
    <formula>PBS_Lease__r.Lessor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lessor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Building__c.field-meta.xml
<CustomField>
    <fullName>PBS_Building__c</fullName>
    <formula>PBS_Lease__r.PBS_Building__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PBS Building</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Base_Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>RET_Base_Tax_Year__c</fullName>
    <description>Real Estate Tax submission base tax year.</description>
    <inlineHelpText>Real Estate Tax submission base tax year.</inlineHelpText>
    <label>RET Base Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Editable_by_Submitter__c.field-meta.xml
<CustomField>
    <fullName>RET_Editable_by_Submitter__c</fullName>
    <description>Indicates if this case should display with fields editable by the submitter.</description>
    <formula>OR(
NOT(ISPICKVAL(Status, &apos;Determination Made&apos;))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if this case should display with fields editable by the submitter.</inlineHelpText>
    <label>RET Editable by Submitter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Initial_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Initial_Submission_Date__c</fullName>
    <description>Indicates the first time a Real Estate Tax submission has been sent to GSA.</description>
    <inlineHelpText>Indicates the first time a Real Estate Tax submission has been sent to GSA.</inlineHelpText>
    <label>RET Initial Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Last_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Last_Submission_Date__c</fullName>
    <description>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</description>
    <inlineHelpText>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</inlineHelpText>
    <label>RET Last Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Submission_Comments__c.field-meta.xml
<CustomField>
    <fullName>RET_Submission_Comments__c</fullName>
    <label>RET Submission Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Tax_County__c.field-meta.xml
<CustomField>
    <fullName>RET_Tax_County__c</fullName>
    <label>RET Tax County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Building_City__c.field-meta.xml
<CustomField>
    <fullName>Building_City__c</fullName>
    <formula>PBS_Building__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Building_State_Code__c</fullName>
    <formula>PBS_Building__r.State_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Street_Address__c</fullName>
    <formula>PBS_Building__r.Street_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Street Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Building_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Building_Zip_Code__c</fullName>
    <formula>PBS_Building__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lessor__c.field-meta.xml
<CustomField>
    <fullName>Lessor__c</fullName>
    <label>Lessor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/PBS_Building__c.field-meta.xml
<CustomField>
    <fullName>PBS_Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Building</label>
    <referenceTo>PBS_Building__c</referenceTo>
    <relationshipLabel>PBS Leases</relationshipLabel>
    <relationshipName>PBS_Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Short_Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Lease_Number__c</fullName>
    <formula>if(NOT(ISBLANK(Lease_Number__c)),if( LEN(Lease_Number__c)&gt;5, RIGHT(Lease_Number__c, 5),Lease_Number__c ),&apos;&apos;)</formula>
    <label>Short Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_County__c.field-meta.xml
<CustomField>
    <fullName>Tax_County__c</fullName>
    <label>Tax County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Required_Documents__c/RET_Required_Documents__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies the type of documents and the quantity that must attached to a case before being submitted to GSA.</description>
    <label>RET Required Documents</label>
</CustomObject>

force-app/main/default/objects/RET_Required_Documents__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RET_TaxSubmissionSummaryController.cls
public without sharing class RET_TaxSubmissionSummaryController {
	@AuraEnabled
	public static Map<String, String> getPageData() {
		Map<String, String> pageData = new Map<String, String>();
		pageData.put('userName', userinfo.getName());
		return pageData;
	}

	@AuraEnabled
	public static List<String> getDocumentTypes() {
		List<String> docTypes = new List<String>();
		Schema.DescribeFieldResult fieldResult = RET_Document_Data__c.Document_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for (Schema.PicklistEntry pickListVal : ple) {
			docTypes.add(pickListVal.getLabel());
		}
		return docTypes;
	}

	@AuraEnabled
	public static Case getCase(String caseId) {
		if (String.isBlank(caseId)) {
			throw new AuraHandledException(System.Label.RET_Case_Not_Found);
		} else {
			// Check that the User has been approved to view the Lease with the Case:
			try {
				final Case[] caseList = [
					SELECT
						(
							SELECT
								Id,
								Account.Name,
								PBS_Lease__r.Lessor__c,
								PBS_Lease__r.PBS_Building__c,
								PBS_Lease__r.Lease_Number__c,
								PBS_Lease__r.Building_Street_Address__c,
								PBS_Lease__r.Building_City__c,
								PBS_Lease__r.Short_Lease_Number__c,
								PBS_Lease__r.Building_State_Code__c,
								PBS_Lease__r.Building_Zip_Code__c,
								Status,
								Owner.Name,
								RET_Base_Tax_Year__c,
								RET_Tax_County__c,
								RET_Editable_by_Submitter__c,
								RET_Last_Submission_Date__c,
								RET_Initial_Submission_Date__c,
								RET_Submission_Comments__c
							FROM Cases__r
							WHERE Id = :caseId
							LIMIT 1
						)
					FROM PBS_Lease__c
					WHERE
						Id IN (
							SELECT PBS_Lease__c
							FROM PBS_Lease_Access__c
							WHERE Requestor__c = :UserInfo.getUserId() AND Status__c IN ('Approved', 'POC')
						)
						AND Id IN (SELECT PBS_Lease__c FROM Case WHERE Id = :caseId)
					LIMIT 1
				]
				.Cases__r;
				return caseList[0];
			} catch (QueryException qe) {
				throw new AuraHandledException(System.Label.RET_Case_Not_Found);
			}
		}
	}

	@AuraEnabled
	public static Case saveCase(Case caseToSave) {
		try {
			update caseToSave;
		} catch (DmlException dmle) {
			throw new AuraHandledException(dmle.getDmlMessage(0));
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return caseToSave;
	}

	@AuraEnabled
	public static List<String> validateDocuments(Case caseToSubmit) {
		List<String> missingDocList = new List<String>();
		Set<Id> allAttachmentsIdsToThisCase = new Set<id>();
		Map<String, Integer> mapCasetoDoctypes = new Map<String, Integer>();
		if (caseToSubmit != null) {
			for (Attachment att : [SELECT Id, Name FROM Attachment WHERE parentId = :caseToSubmit.Id]) {
				allAttachmentsIdsToThisCase.add(att.Id);
			}
			for (RET_Document_Data__c ret : [
				SELECT Id, Document_Type__c
				FROM RET_Document_Data__c
				WHERE Attachment_ID__c IN :allAttachmentsIdsToThisCase
			]) {
				if (!mapCasetoDoctypes.containskey(ret.Document_Type__c)) {
					mapCasetoDoctypes.put(ret.Document_Type__c, 0);
				}
				mapCasetoDoctypes.put(ret.Document_Type__c, mapCasetoDoctypes.get(ret.Document_Type__c) + 1);
			}
			for (RET_Required_Documents__c retDoc : RET_Required_Documents__c.getAll().values()) {
				if (!mapCasetoDoctypes.containskey(retDoc.Document_Name__c)) {
					missingDocList.add(retDoc.Document_Name__c);
				} else if ((retdoc.Minimum_Quantity__c > mapCasetoDoctypes.get(retDoc.Document_Name__c))) {
					missingDocList.add(retDoc.Document_Name__c);
				}
			}
		}
		return missingDocList;
	}

	@AuraEnabled
	public static Boolean submitTaxCase(Case caseToSubmit) {
		Datetime caseLastSubmitted = caseToSubmit.RET_Last_Submission_Date__c;
		if (caseLastSubmitted == null) {
			caseLastSubmitted = caseToSubmit.createdDate;
		}
		caseToSubmit.Status = 'Submitted';
		if (caseToSubmit.RET_Initial_Submission_Date__c == null) {
			caseToSubmit.RET_Initial_Submission_Date__c = Datetime.now();
		}
		caseToSubmit.RET_Last_Submission_Date__c = Datetime.now();

		String integrationException;
		try {
			submitCaseToGREX(getTaxSubmissionJson(caseToSubmit, caseLastSubmitted));
		} catch (Exception e) {
			integrationException = e.getMessage();
		}

		try {
			update caseToSubmit;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		if (!String.isBlank(integrationException)) {
			throw new AuraHandledException(System.Label.RET_Integration_Error);
		}
		return true;
	}

	private static String getTaxSubmissionJson(Case caseToSubmit, Datetime caseLastSubmitted) {
		JSONGenerator gen = JSON.createGenerator(true);
		gen.writeStartObject();

		Map<Id, Attachment> attachmentMap = new Map<Id, Attachment>();
		for (Attachment attach : [SELECT Id, Name, LastModifiedDate FROM Attachment WHERE parentId = :caseToSubmit.Id]) {
			attachmentMap.put(attach.Id, attach);
		}
		gen.writeIdField('caseId', caseToSubmit.Id);
		gen.writeStringField('leaseNumber', caseToSubmit.PBS_Lease__r.Lease_Number__c);

		if (String.isBlank(caseToSubmit.RET_Base_Tax_Year__c)) {
			gen.writeNullField('leaseBaseTaxYear');
		} else {
			gen.writeStringField('leaseBaseTaxYear', caseToSubmit.RET_Base_Tax_Year__c);
		}
		if (String.isBlank(caseToSubmit.RET_Tax_County__c)) {
			gen.writeNullField('leaseTaxCounty');
		} else {
			gen.writeStringField('leaseTaxCounty', caseToSubmit.RET_Tax_County__c);
		}
		gen.writeDatetimeField('initialSubmissionDate', caseToSubmit.RET_Initial_Submission_Date__c);

		gen.writeFieldName('documents');
		gen.writeStartArray();
		if (!attachmentMap.isEmpty()) {
			for (RET_Document_Data__c docData : [
				SELECT
					Id,
					Name,
					Attachment_ID__c,
					Tax_Year__c,
					Document_Type__c,
					Tax_County__c,
					Tax_Bill_Frequency__c,
					Tax_Block_Number__c,
					Tax_Lot_Number__c,
					Tax_Period_End__c,
					Tax_Period_Start__c,
					Tax_Authority_for_Document__c,
					Tax_Bill_Due_Date__c,
					LastModifiedDate,
					Full_File_Name__c
				FROM RET_Document_Data__c
				WHERE Attachment_ID__c IN :attachmentMap.keySet() AND LastModifiedDate > :caseLastSubmitted
			]) {
				gen.writeStartObject();
				gen.writeIdField('attachmentId', docData.Attachment_ID__c);
				gen.writeStringField('fileName', docData.Full_File_Name__c);
				gen.writeStringField('documentType', docData.Document_Type__c);
				gen.writeStringField('taxBillFrequency', docData.Tax_Bill_Frequency__c);
				gen.writeStringField('taxBlockNumer', docData.Tax_Block_Number__c != null ? docData.Tax_Block_Number__c : '');
				gen.writeStringField('taxLotNumber', docData.Tax_Lot_Number__c != null ? docData.Tax_Lot_Number__c : '');
				gen.writeDateField('taxPeriodStart', docData.Tax_Period_Start__c);
				gen.writeDateField('taxPeriodEnd', docData.Tax_Period_End__c);
				gen.writeStringField('taxYear', docData.Tax_Year__c);
				gen.writeDateTimeField('lastModifiedDate', docData.LastModifiedDate);
				gen.writeEndObject();
			}
		}
		gen.writeEndArray();
		gen.writeEndObject();
		system.debug('**' + gen.getAsString());
		return gen.getAsString();
	}

	private static void submitCaseToGREX(String reqStr) {
		RET_GREX_Integration_Settings__c settings = RET_GREX_Integration_Settings__c.getOrgDefaults();
		if (settings == null || settings.Endpoint_URL__c == null) {
			sendIntegrationErrorEmail('GREX Integration endpoint not defined.');
			throw new AuraHandledException(System.Label.RET_Integration_Error);
		}

		HttpResponse response = null;
		HttpRequest req = new HttpRequest();
		req.setTimeout(120000); //ticket# RITM0646135
		req.setEndpoint(settings.Endpoint_URL__c);
		req.setMethod('POST');
		req.setHeader('Content-Type', 'application/json');
		Blob headerValue = Blob.valueOf(settings.Username__c + ':' + settings.Password__c);
		String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
		req.setHeader('Authorization', authorizationHeader);
		req.setBody(reqStr);

		Http http = new Http();
		try {
			response = http.send(req);
		} catch (Exception e) {
		}
		system.debug('response: ' + response);
		if (response == null || response.getStatusCode() != 200) {
			sendIntegrationErrorEmail('GREX integration response unsuccessful: ' + response);
			throw new AuraHandledException(System.Label.RET_Integration_Error);
		} else {
			// May also want to parse response, ensure request was successful....
			System.debug(' *** responseBody: ' + response.getBody());
		}
	}

	private static void sendIntegrationErrorEmail(String error) {
		RET_GREX_Integration_Email_Settings__c emailSettings1 = RET_GREX_Integration_Email_Settings__c.getInstance(
			'O&M Integration Failure'
		);
		RET_GREX_Integration_Email_Settings__c emailSettings2 = RET_GREX_Integration_Email_Settings__c.getInstance(
			'GREX Team Integration Failure'
		);
		if (emailSettings1 != null || emailSettings2 != null) {
			try {
				//Messaging.reserveSingleEmailCapacity(2);
				Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
				mail.setSenderDisplayName(emailSettings1.Sender_Display_Name__c);
				mail.setToAddresses(new List<String>{ emailSettings1.To_Address__c, emailSettings2.To_Address__c });
				mail.setSubject(emailSettings1.Email_Subject__c);
				mail.setHtmlBody(emailSettings1.Email_Body__c + error);
				Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
				system.debug('**' + mail);
			} catch (Exception e) {
				System.debug(' *** email error: ' + e.getMessage());
				throw new AuraHandledException(e.getMessage());
			}
		}
	}
}