force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Attachments__c/PBS_AAAP_Offer_Attachments__c.object-meta.xml
<CustomObject>
    <label>Offer Attachments</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Offer Attachments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Taxes</fullName>
            </value>
            <value>
                <fullName>Change of Ownership / Novation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Full_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_File_Name__c</fullName>
    <label>Full File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RET Document Data</relationshipLabel>
    <relationshipName>RET_Document_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RET_UploadAttachmentController.cls
public without sharing class RET_UploadAttachmentController {

    @AuraEnabled
    public static List<DocumentWrapper> insertDocumentLinkRecords(String leaseNumber, List<DocumentWrapper> contentdocumentRecords){
        List<RET_Document_Data__c> RET_DocumentList = new List<RET_Document_Data__c>();
        Map<Id,ContentDocument> contentDocumentMap = new Map<Id,ContentDocument>();
        String caseId = getCaseId(leaseNumber);
        for(integer i=0; i< contentdocumentRecords.Size(); i++){
            RET_Document_Data__c Documents = new RET_Document_Data__c();
            Documents.Attachment_ID__c = contentdocumentRecords[i].contentDocumentId;
            Documents.Full_File_Name__c =contentdocumentRecords[i].name;
            Documents.Parent_Case__c = caseId;
            Documents.Document_Type__c = contentdocumentRecords[i].documentType;
            Documents.Document_Category__c = contentdocumentRecords[i].documentCategory;
            RET_DocumentList.add(Documents);
            contentDocumentMap.put(contentdocumentRecords[i].contentDocumentId,new ContentDocument());
        }
        if(RET_DocumentList.Size()>0){
            insert RET_DocumentList;
        }
        
        List<ContentDocumentLink> contentDocumentLinkRecords = new List<ContentDocumentLink>();
        for(integer i=0; i< contentdocumentRecords.Size(); i++){
            ContentDocumentLink obj = new ContentDocumentLink();
            obj.ContentDocumentId = contentdocumentRecords[i].contentDocumentId;
            obj.LinkedEntityId = caseId;
            obj.ShareType = 'V';
            obj.Visibility = 'AllUsers';
            contentDocumentLinkRecords.add(obj);
            contentdocumentRecords[i].caseId =caseId;
        }
        
        if(contentDocumentLinkRecords.Size()>0){
            insert contentDocumentLinkRecords;
            contentDocumentMap = new Map<Id,ContentDocument>([SELECT Id, LatestPublishedVersion.Title, LatestPublishedVersionId FROM ContentDocument Where Id=:contentDocumentMap.keyset()]);
            List<ContentDistribution> contentDistributionRecords = new List<ContentDistribution>();
            for(ContentDocument contentDocumentRecord : contentDocumentMap.values()){
                ContentDistribution cdl = new ContentDistribution(
                    Name = contentDocumentRecord.LatestPublishedVersion.Title,
                    ContentVersionId = contentDocumentRecord.LatestPublishedVersionId,
                    PreferencesAllowViewInBrowser= true,
                    PreferencesNotifyOnVisit= false
                );
                contentDistributionRecords.add(cdl);
            }
            insert contentDistributionRecords;
            List<ContentDocument> contentDocumentRecordsToUpdate = new List<ContentDocument>();
            for(ContentDistribution cd : [SELECT DistributionPublicUrl, ContentVersion.ContentDocumentId FROM ContentDistribution WHERE Id In: contentDistributionRecords]){
                ContentDocument contentDocumentObj = new ContentDocument();
                contentDocumentObj.Id = cd.ContentVersion.ContentDocumentId;
                contentDocumentObj.Description  = cd.DistributionPublicUrl;
                contentDocumentRecordsToUpdate.add(contentDocumentObj);
            }
            update contentDocumentRecordsToUpdate;
        }
        return contentdocumentRecords;
    }
    
    @AuraEnabled
    public static String getCaseId(String leaseNumber){
        System.debug('getCaseId() leaseNumber: ' + leaseNumber);
        String leaseId = [SELECT Id FROM PBS_Lease__c WHERE Lease_Number__c =: leaseNumber LIMIT 1].Id;
        System.debug('leaseId: ' + leaseId);
        String myUserId = UserInfo.getUserId();
        List<Case> caseList = [SELECT Id FROM Case WHERE Status = 'Draft' AND PBS_Lease__c =: leaseId and OwnerId =: myUserId ORDER BY CreatedDate DESC Limit 1];
        //If no case is found then create a new Case for this Lease and signed-on-user
        if (caseList.size() == 0) {
            Case newCase = new Case();
            newCase.Status = 'Draft';
            newCase.PBS_Lease__c = leaseId;
            insert newCase;
            return newCase.Id;
        } else {
            return caseList[0].Id;
        }
    }
    
    @AuraEnabled
    public static void deleteTheUploadedDocuments(List<DocumentWrapper> contentdocumentRecords){
        List<ContentDocument> contentRecords = new List<ContentDocument>();
        for(DocumentWrapper contentdocumentRecord : contentdocumentRecords){
            contentRecords.add(new ContentDocument(Id=contentdocumentRecord.contentDocumentId));
            //offerAttachments.add(new PBS_AAAP_Offer_Attachments__c(Id=contentdocumentRecord.offerAttachmentId));
        }
        if(contentRecords.size() >0){
            delete contentRecords;
        }
    }
 
    public class DocumentWrapper{
        @AuraEnabled Public Boolean isShowOthers{get;set;}
        @AuraEnabled Public String contentDocumentId{get;set;}
        @AuraEnabled Public String name{get;set;}
        @AuraEnabled Public String caseId{get;set;}
        @AuraEnabled Public String documentCategory{get;set;}
        @AuraEnabled Public String documentType{get;set;}
        public DocumentWrapper(){
            this.isShowOthers = false;
            this.documentCategory = '';
            this.documentType = '';
        }
    }
}