force-app/main/default/objects/Case/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Full_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_File_Name__c</fullName>
    <label>Full File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RET_DocumentsListControllerTest.cls
@IsTest(SeeAllData=false)
public class RET_DocumentsListControllerTest {
    @testSetup static void createTestData() {
        PBS_Lease__c newPBS = new PBS_Lease__c(Lease_Number__c='98462383', Name ='98462383Test', Lease_Effective_Date__c = date.today(), Lease_Expiration_Date__c = date.today().adddays(365));
        Insert newPBS;
    
        Case recCase = new case(origin='Web',Status='Submitted',PBS_Lease__c =newPBS.ID);
        Insert recCase;
        
        List<Attachment> collAtt = new List<Attachment>();
        collAtt.add(new Attachment(parentid=recCase.Id,name='98462383 - Real Estate Tax - Bill(2017)_1.pdf',body=Blob.valueOf('Unit Test Attachment Body')));
        collAtt.add(new Attachment(parentid=recCase.Id,name='98462383 - Proof of Ownership(2016)_1.pdf',body=Blob.valueOf('Unit Test Attachment Body1')));
        collAtt.add(new Attachment(parentid=recCase.Id,name='98462383 - Proof of Ownership(2016)_2.pdf',body=Blob.valueOf('Unit Test Attachment Body2')));
        Insert collAtt;
        
        List<RET_Document_Data__c> collRet = new List<RET_Document_Data__c>();
        collRet.add(new RET_Document_Data__c(Attachment_ID__c =collAtt[0].Id,name ='test ret', Full_File_Name__c='98462383 - Real Estate Tax - Bill(2017)_1.pdf',Tax_Year__c ='2017',Document_Type__c ='Real Estate Tax - Bill'));
        collRet.add(new RET_Document_Data__c(Attachment_ID__c =collAtt[1].Id,name ='test ret1', Full_File_Name__c='98462383 - Proof of Ownership(2016)_1.pdf',Tax_Year__c ='2016',Document_Type__c ='Proof of Ownership'));
        collRet.add(new RET_Document_Data__c(Attachment_ID__c =collAtt[2].Id,name ='test ret2', Full_File_Name__c='98462383 - Proof of Ownership(2016)_2.pdf',Tax_Year__c ='2016',Document_Type__c ='Proof of Ownership'));
        Insert collRet;

        List<RET_Document_Data__c> collRetlst = [Select id from RET_Document_Data__c];
        system.assertEquals(3,collRetlst.size());

    }

    @isTest static void testgeturls(){
        List<case> collCase = [select id from case];
        Map<String,String> url = RET_DocumentsListController.getUrls(collCase[0].id);
        System.assertEquals(3, url.size());
    }
    
    @isTest static void testPositiveDelete(){
        List<case> collCase = [select id from case];
        System.assertNotEquals(null, collCase);
        System.assertEquals(1, collCase.size());
        List<RET_Document_Data__c> collRet = [select id from RET_Document_Data__c];
        System.assertNotEquals(null, collRet);
        System.assertEquals(3, collRet.size());
        List<Attachment> collAtt = [select id from Attachment];
        System.assertNotEquals(null, collAtt);
        System.assertEquals(3, collAtt.size());
        RET_DocumentsListController.deleteSelectedDocument(collAtt[0].Id,collCase[0].Id);
        collCase = [select id from case];
        System.assertEquals(1, collCase.size());
        collRet = [select id from RET_Document_Data__c];
        System.assertEquals(2, collRet.size());
        collAtt = [select id from Attachment];
        System.assertEquals(2, collAtt.size());
        System.debug(RET_DocumentsListController.getHostName());
    }
    @isTest static void testNegativeDelete(){
        List<case> collCase = [select id from case];
        System.assertEquals(1, collCase.size());
        Try{
            RET_DocumentsListController.deleteSelectedDocument(collCase[0].Id,collCase[0].Id);
        }catch(exception e){
            System.assertEquals('Script-thrown exception', e.getMessage(),e.getMessage());
        }
    }


}