force-app/main/default/objects/Case/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Base_Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>RET_Base_Tax_Year__c</fullName>
    <description>Real Estate Tax submission base tax year.</description>
    <inlineHelpText>Real Estate Tax submission base tax year.</inlineHelpText>
    <label>RET Base Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Last_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Last_Submission_Date__c</fullName>
    <description>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</description>
    <inlineHelpText>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</inlineHelpText>
    <label>RET Last Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Tax_County__c.field-meta.xml
<CustomField>
    <fullName>RET_Tax_County__c</fullName>
    <label>RET Tax County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Full_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_File_Name__c</fullName>
    <label>Full File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Bill_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Tax_Bill_Frequency__c</fullName>
    <label>Tax Bill Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Block_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Block_Number__c</fullName>
    <label>Tax Block Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Lot_Number__c</fullName>
    <label>Tax Lot Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Tax_Period_End__c</fullName>
    <label>Tax Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Tax_Period_Start__c</fullName>
    <label>Tax Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/RET_GREX_Integration_Email_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains email settings for notifications used by Real Estate Tax GREX integration.</description>
    <label>RET GREX Integration Email Settings</label>
</CustomObject>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>The email body. Additional information (integration error messages, etc.) may be appended.</description>
    <inlineHelpText>The email body. Additional information (integration error messages, etc.) may be appended.</inlineHelpText>
    <label>Email Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>The email subject line.</description>
    <inlineHelpText>The email subject line.</inlineHelpText>
    <label>Email Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Sender_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Display_Name__c</fullName>
    <description>The name displayed in the email &quot;From&quot; Field.</description>
    <inlineHelpText>The name displayed in the email &quot;From&quot; Field.</inlineHelpText>
    <label>Sender Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <description>The email address or distribution list that the email will be sent to.</description>
    <inlineHelpText>The email address or distribution list that the email will be sent to.</inlineHelpText>
    <label>To Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Settings__c/RET_GREX_Integration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RET GREX Integration Settings</label>
</CustomObject>

force-app/main/default/objects/RET_GREX_Integration_Settings__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <inlineHelpText>The GREX endpoint URL that the Real Estate Tax application will connect to.</inlineHelpText>
    <label>Endpoint URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Required_Documents__c/RET_Required_Documents__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies the type of documents and the quantity that must attached to a case before being submitted to GSA.</description>
    <label>RET Required Documents</label>
</CustomObject>

force-app/main/default/objects/RET_Required_Documents__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RET_TaxSubmissionSummaryControllerTest.cls
@istest
private class RET_TaxSubmissionSummaryControllerTest {
	@testsetup
	static void createData() {
		insert new Account(Name = 'Real Estate Tax Bucket');
		RET_GREX_Integration_Settings__c cs1 = new RET_GREX_Integration_Settings__c();
		cs1.Endpoint_URL__c = 'https://test.com';
		insert cs1;
		List<RET_GREX_Integration_Email_Settings__c> intEmailList = new List<RET_GREX_Integration_Email_Settings__c>();
		RET_GREX_Integration_Email_Settings__c cs2 = new RET_GREX_Integration_Email_Settings__c();
		cs2.Name = 'Integration Failure';
		cs2.To_Address__c = 'xyz@test.com';
		cs2.Email_Subject__c = 'test email';
		cs2.Sender_Display_Name__c = 'Test Sender';
		cs2.Email_Body__c = 'Test Body';
		intEmailList.add(cs2);
		RET_GREX_Integration_Email_Settings__c cs3 = new RET_GREX_Integration_Email_Settings__c();
		cs3.Name = 'O&M Integration Failure';
		cs3.To_Address__c = 'xyz@test.com';
		cs3.Email_Subject__c = 'test email';
		cs3.Sender_Display_Name__c = 'Test Sender';
		cs3.Email_Body__c = 'Test Body';
		intEmailList.add(cs3);
		RET_GREX_Integration_Email_Settings__c cs4 = new RET_GREX_Integration_Email_Settings__c();
		cs4.Name = 'GREX Team Integration Failure';
		cs4.To_Address__c = 'xyz@test.com';
		cs4.Email_Subject__c = 'test email';
		cs4.Sender_Display_Name__c = 'Test Sender';
		cs4.Email_Body__c = 'Test Body';
		intEmailList.add(cs4);
		insert intEmailList;

		//Create Lease Record
		PBS_Lease__c leaseRec = new PBS_Lease__c(
			Name = 'Test Lease',
			Lease_Number__c = '1234',
			Lease_Effective_Date__c = date.today()
		);
		insert leaseRec;
		System.assertNotEquals(null, leaseRec.Id, 'DML - insertion issue');

		insert new PBS_Lease_Access__c(PBS_Lease__c = leaseRec.Id, Requestor__c = UserInfo.getUserId(), Status__c = 'POC');

		//create a case record
		Case tmpCase = new case(
			origin = 'Web',
			Status = 'Submitted',
			RET_Last_Submission_Date__c = datetime.now().addDays(-1),
			RET_Base_Tax_Year__c = '2017',
			PBS_Lease__c = leaseRec.id,
			RET_Tax_County__c = 'US'
		);
		insert tmpCase;

		List<Attachment> collAtt = new List<Attachment>();
		collAtt.add(
			new Attachment(parentid = tmpCase.Id, name = 'Bill desk', body = Blob.valueOf('Unit Test Attachment Body'))
		);
		collAtt.add(
			new Attachment(parentid = tmpCase.Id, name = 'Bill desk2', body = Blob.valueOf('Unit Test Attachment Body'))
		);
		collAtt.add(
			new Attachment(parentid = tmpCase.Id, name = 'Bill desk3', body = Blob.valueOf('Unit Test Attachment Body'))
		);

		insert collAtt;

		List<RET_Document_Data__c> collDocData = new List<RET_Document_Data__c>();
		collDocData.add(
			new RET_Document_Data__c(
				Attachment_ID__c = collAtt[0].Id,
				name = 'test ret',
				Full_File_Name__c = 'ret test',
				Tax_Year__c = '2017',
				Document_Type__c = 'Real Estate Tax - Bill',
				Tax_Bill_Frequency__c = 'Annual',
				Tax_Block_Number__c = '123',
				Tax_Lot_Number__c = 'ABC',
				Tax_Period_Start__c = date.today().addyears(-2),
				Tax_Period_End__c = date.today().addyears(-1)
			)
		);
		collDocData.add(
			new RET_Document_Data__c(
				Attachment_ID__c = collAtt[1].Id,
				name = 'test ret',
				Full_File_Name__c = 'ret test',
				Tax_Year__c = '2017',
				Document_Type__c = 'Real Estate Tax - Appeal Notice',
				Tax_Bill_Frequency__c = 'Annual',
				Tax_Block_Number__c = '123',
				Tax_Lot_Number__c = 'ABC',
				Tax_Period_Start__c = date.today().addyears(-3),
				Tax_Period_End__c = date.today().addyears(-2)
			)
		);
		collDocData.add(
			new RET_Document_Data__c(
				Attachment_ID__c = collAtt[2].Id,
				name = 'test ret',
				Full_File_Name__c = 'ret test',
				Tax_Year__c = '2017',
				Document_Type__c = 'Proof of Ownership',
				Tax_Bill_Frequency__c = 'Annual',
				Tax_Block_Number__c = '123',
				Tax_Lot_Number__c = 'ABC',
				Tax_Period_Start__c = date.today().addyears(-1),
				Tax_Period_End__c = date.today()
			)
		);

		insert collDocData;

		List<RET_Required_Documents__c> collReqDocs = new List<RET_Required_Documents__c>();
		collReqDocs.add(
			new RET_Required_Documents__c(
				name = 'Real Estate Tax - Bill',
				Document_Name__c = 'Real Estate Tax - Bill',
				minimum_quantity__c = 1
			)
		);
		collReqDocs.add(
			new RET_Required_Documents__c(
				name = 'Real Estate Tax - Appeal Notice',
				Document_Name__c = 'Real Estate Tax - Appeal Notice',
				minimum_quantity__c = 1
			)
		);
		collReqDocs.add(
			new RET_Required_Documents__c(
				name = 'Proof of Ownership',
				Document_Name__c = 'Proof of Ownership',
				minimum_quantity__c = 2
			)
		);
		insert collReqDocs;
	}
	@isTest
	static void SubmitCasePositiveScenario() {
		case caseRec = [
			SELECT
				id,
				RET_Last_Submission_Date__c,
				PBS_Lease__r.Lease_Number__c,
				PBS_Lease__c,
				RET_Base_Tax_Year__c,
				RET_Tax_County__c
			FROM case
			LIMIT 1
		];
		Map<String, String> tmpData = RET_TaxSubmissionSummaryController.getPageData();
		system.assertEquals(1, tmpData.values().size());
		system.assertEquals(true, tmpData.containskey('userName'));
		List<String> tmpList = RET_TaxSubmissionSummaryController.getDocumentTypes();
		set<String> tmpSet = new Set<String>(tmpList);
		Schema.DescribeFieldResult fieldResult = RET_Document_Data__c.Document_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		system.assertEquals(ple.size(), tmpList.size());
		System.assertEquals(true, tmpSet.contains(ple[0].getLabel()));
		tmpList = RET_TaxSubmissionSummaryController.validateDocuments(caseRec);
		tmpSet = new Set<String>(tmpList);
		system.assertEquals(true, tmpSet.contains('Proof of Ownership')); //created records in this type
		case recCase = RET_TaxSubmissionSummaryController.getCase(caseRec.Id);
		system.assertEquals('1234', recCase.PBS_Lease__r.Lease_Number__c);
		recCase.RET_Base_Tax_Year__c = '2018';
		case recCase1 = RET_TaxSubmissionSummaryController.saveCase(caseRec);
		system.assertNotEquals('2018', recCase1.RET_Base_Tax_Year__c);
		test.startTest();
		test.setMock(HttpCalloutMock.class, new TaxSubmissionSummaryCalloutMockImpl());
		Boolean tmpOut;
		try {
			tmpOut = RET_TaxSubmissionSummaryController.submitTaxCase(caseRec);
		} catch (Exception e) {
			System.assertEquals(null, tmpOut);
		}
		test.stopTest();
	}
	@isTest
	static void SubmitCaseExceptions() {
		case tmpCase = [
			SELECT
				id,
				PBS_Lease__c,
				RET_Submission_Comments__c,
				PBS_Lease__r.Lease_Number__c,
				RET_Last_Submission_Date__c,
				RET_Base_Tax_Year__c
			FROM case
			LIMIT 1
		];
		RET_Document_Data__c tmpRet = [SELECT id FROM RET_Document_Data__c LIMIT 1];
		case recCase;
		try {
			//exception if no caseid
			recCase = RET_TaxSubmissionSummaryController.getCase(null);
		} catch (exception e) {
			System.assertEquals(null, recCase);
		}
		try {
			//exception if wrong ID sent as caseid
			recCase = RET_TaxSubmissionSummaryController.getCase(tmpRet.id);
		} catch (exception e) {
			System.assertEquals(null, recCase);
		}
		try {
			//exception with null
			recCase = RET_TaxSubmissionSummaryController.saveCase(null);
		} catch (exception e) {
			System.assertEquals(null, recCase);
		}
		try {
			//exception when year value not Number
			tmpCase.RET_Base_Tax_Year__c = 'abc';
			recCase = RET_TaxSubmissionSummaryController.saveCase(tmpCase);
		} catch (exception e) {
			System.assertEquals(null, recCase);
		}
		tmpCase.RET_Base_Tax_Year__c = '';
		tmpCase.RET_Last_Submission_Date__c = null;
		tmpCase.RET_Tax_County__c = '';
		update tmpCase;

		Boolean tmpout;
		try {
			tmpout = RET_TaxSubmissionSummaryController.submitTaxCase(tmpCase);
		} catch (exception e) {
			System.assertEquals(null, tmpout);
		}
	}
}