force-app/main/default/objects/Case/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Base_Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>RET_Base_Tax_Year__c</fullName>
    <description>Real Estate Tax submission base tax year.</description>
    <inlineHelpText>Real Estate Tax submission base tax year.</inlineHelpText>
    <label>RET Base Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Last_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>RET_Last_Submission_Date__c</fullName>
    <description>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</description>
    <inlineHelpText>Indicates the most recent date a Real Estate Tax submission was sent to GSA.</inlineHelpText>
    <label>RET Last Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/RET_Tax_County__c.field-meta.xml
<CustomField>
    <fullName>RET_Tax_County__c</fullName>
    <label>RET Tax County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/LSR_Email_Text__c.field-meta.xml
<CustomField>
    <fullName>LSR_Email_Text__c</fullName>
    <description>Rexus use this field to save the poc email address and in before trigger, we have to validate this value and populate it to &apos;LSR Contact Email&apos; field which will be used to searching poc user.</description>
    <label>LSR Email Text</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Full_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_File_Name__c</fullName>
    <label>Full File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Bill_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Tax_Bill_Frequency__c</fullName>
    <label>Tax Bill Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Block_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Block_Number__c</fullName>
    <label>Tax Block Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Lot_Number__c</fullName>
    <label>Tax Lot Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Tax_Period_End__c</fullName>
    <label>Tax Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Tax_Period_Start__c</fullName>
    <label>Tax Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/RET_GREX_Integration_Email_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains email settings for notifications used by Real Estate Tax GREX integration.</description>
    <label>RET GREX Integration Email Settings</label>
</CustomObject>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>The email body. Additional information (integration error messages, etc.) may be appended.</description>
    <inlineHelpText>The email body. Additional information (integration error messages, etc.) may be appended.</inlineHelpText>
    <label>Email Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>The email subject line.</description>
    <inlineHelpText>The email subject line.</inlineHelpText>
    <label>Email Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/Sender_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Display_Name__c</fullName>
    <description>The name displayed in the email &quot;From&quot; Field.</description>
    <inlineHelpText>The name displayed in the email &quot;From&quot; Field.</inlineHelpText>
    <label>Sender Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Email_Settings__c/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <description>The email address or distribution list that the email will be sent to.</description>
    <inlineHelpText>The email address or distribution list that the email will be sent to.</inlineHelpText>
    <label>To Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RET_GREX_Integration_Settings__c/RET_GREX_Integration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RET GREX Integration Settings</label>
</CustomObject>

force-app/main/default/objects/RET_GREX_Integration_Settings__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <inlineHelpText>The GREX endpoint URL that the Real Estate Tax application will connect to.</inlineHelpText>
    <label>Endpoint URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Required_Documents__c/RET_Required_Documents__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies the type of documents and the quantity that must attached to a case before being submitted to GSA.</description>
    <label>RET Required Documents</label>
</CustomObject>

force-app/main/default/objects/RET_Required_Documents__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Required_Documents__c/fields/Minimum_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Quantity__c</fullName>
    <description>The minimum number of documents of this type that must be included with a valid tax submission.</description>
    <inlineHelpText>The minimum number of documents of this type that must be included with a valid tax submission.</inlineHelpText>
    <label>Minimum Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PBSLeaseAccessTriggerHelperTest.cls
@isTest
public class PBSLeaseAccessTriggerHelperTest {
     @testsetup static void createData() { 
         //Create RET and POC users
        /* Commented out for 2024-2025 RET Surge to remove all Access Request/Approval functionality
        Id retProfileId = [select Id, name from Profile where Name = :RET_LeaseShareUtility.RET_CCP_Profile limit 1].Id;
        Id systemUserProfileId = [select Id, name from Profile where Name Like 'GSA System Administrator%' limit 1].Id;
     
        Account ac = new Account(name ='RET Test Bucket Account') ;
        insert ac; 
        List<Contact> conList = new List<Contact>();
        Contact retCon = new Contact(FirstName='TestRETFName', LastName='TestRETLName', Email='retUserTestEmail420@test.org',AccountId = ac.Id); 
        conList.add(retCon); 
        Contact pocCon = new Contact(FirstName='TestPOCFName', LastName='TestPOCLName', Email='pocUserTestEmail420@test.org',AccountId = ac.Id);
        conList.add(pocCon);
        insert conList;  
        
         List<User> uList = new List<User>();
        User retUser = new User(Alias = 'rlfna', Email='retUserTestEmail420@test.org',
                emailencodingkey='UTF-8', FirstName='TestRETFName', LastName='TestRETLName', languagelocalekey='en_US',
                localesidkey='en_US', profileid = retProfileId, country='United States',IsActive =true,
                ContactId = retCon.Id,
                timezonesidkey='America/Los_Angeles', username='retUserTestEmail420@test.org');
        uList.add(retUser);
        User pocUser = new User(Alias = 'plgna', Email='pocUserTestEmail420@test.org',
                emailencodingkey='UTF-8', FirstName='TestPOCFName', LastName='TestPOCLName', languagelocalekey='en_US',
                localesidkey='en_US', profileid = retProfileId, country='United States',IsActive =true,
                ContactId = pocCon.Id,
                timezonesidkey='America/Los_Angeles', username='pocUserTestEmail420@test.org');
        uList.add(pocUser);
        insert uList;
        User castIronUser = new User(Alias = 'csirn', Email='castIronUserTestEmail@test.org',
                                    emailencodingkey='UTF-8', FirstName='Cast', LastName='IronPrd', languagelocalekey='en_US',
                                    localesidkey='en_US', profileid = systemUserProfileId, country='United States',IsActive =true,
                                    timezonesidkey='America/Los_Angeles', username='castIronUserTestEmail@test.org');
       
        insert castIronUser;
        
        PBS_Lease__c newPBS = new PBS_Lease__c(Lease_Number__c='98462383', Name ='98462383Test', Lease_Effective_Date__c = date.today(), Lease_Expiration_Date__c = date.today().adddays(365));
        Insert newPBS; 
         
        RET_GREX_Integration_Settings__c cs1 = new RET_GREX_Integration_Settings__c();
        cs1.Endpoint_URL__c = 'https://test.com';
        insert cs1;
        
        RET_GREX_Integration_Email_Settings__c cs2 = new RET_GREX_Integration_Email_Settings__c();
        cs2.Name = 'Integration Failure';
        cs2.To_Address__c = 'xyz@test.com';
        cs2.Email_Subject__c = 'test email';
        cs2.Sender_Display_Name__c = 'Test Sender';
        cs2.Email_Body__c = 'Test Body';
        insert cs2;
         
        //Create Lease Record
        PBS_Lease__c leaseRec = new PBS_Lease__c(Name='Test Lease', Lease_Number__c='1234', LSR_Email_Text__c ='pocUserTestEmail420@test.org',
                                                 Lease_Effective_Date__c=date.today());
        Insert leaseRec;
        System.assertNotEquals(null, leaseRec.Id,'DML - insertion issue');
        
        //create a case record
        Case tmpCase = new case(origin='Web',Status='Submitted',RET_Last_Submission_Date__c=datetime.now().addDays(-1),
                                RET_Base_Tax_Year__c='2017',PBS_Lease__c = leaseRec.id,RET_Tax_County__c = 'US', ownerId=retUser.Id);
        Insert tmpCase;
        
        List<Attachment> collAtt = new List<Attachment>();
        collAtt.add(new Attachment(parentid=tmpCase.Id,name='Bill desk',body=Blob.valueOf('Unit Test Attachment Body')));
        collAtt.add(new Attachment(parentid=tmpCase.Id,name='Bill desk2',body=Blob.valueOf('Unit Test Attachment Body')));
        collAtt.add(new Attachment(parentid=tmpCase.Id,name='Bill desk3',body=Blob.valueOf('Unit Test Attachment Body')));
       
        insert collAtt;
        
        List<RET_Document_Data__c> collDocData = new List<RET_Document_Data__c>();
        collDocData.add(new RET_Document_Data__c(Attachment_ID__c =collAtt[0].Id,name ='test ret',Full_File_Name__c='ret test',Tax_Year__c ='2017',
                                                 Document_Type__c ='Real Estate Tax - Bill',Tax_Bill_Frequency__c='Annual',Tax_Block_Number__c='123',
                                                 Tax_Lot_Number__c='ABC',Tax_Period_Start__c=date.today().addyears(-2),Tax_Period_End__c=date.today().addyears(-1)));
        collDocData.add(new RET_Document_Data__c(Attachment_ID__c =collAtt[1].Id,name ='test ret', Full_File_Name__c='ret test',Tax_Year__c ='2017',
                                                 Document_Type__c ='Real Estate Tax - Appeal Notice',Tax_Bill_Frequency__c='Annual',Tax_Block_Number__c='123',
                                                 Tax_Lot_Number__c='ABC',Tax_Period_Start__c=date.today().addyears(-3),Tax_Period_End__c=date.today().addyears(-2)));
        collDocData.add(new RET_Document_Data__c(Attachment_ID__c =collAtt[2].Id,name ='test ret', Full_File_Name__c='ret test',Tax_Year__c ='2017',
                                                 Document_Type__c ='Proof of Ownership',Tax_Bill_Frequency__c='Annual',Tax_Block_Number__c='123',
                                                 Tax_Lot_Number__c='ABC',Tax_Period_Start__c=date.today().addyears(-1),Tax_Period_End__c=date.today()));
        
        Insert collDocData;
        
        List<RET_Required_Documents__c> collReqDocs = new List<RET_Required_Documents__c>();
        collReqDocs.add(new RET_Required_Documents__c(name ='Real Estate Tax - Bill',Document_Name__c ='Real Estate Tax - Bill',minimum_quantity__c =1));
        collReqDocs.add(new RET_Required_Documents__c(name ='Real Estate Tax - Appeal Notice',Document_Name__c ='Real Estate Tax - Appeal Notice',minimum_quantity__c =1));
        collReqDocs.add(new RET_Required_Documents__c(name ='Proof of Ownership',Document_Name__c ='Proof of Ownership',minimum_quantity__c =2));
        insert collReqDocs;
        */
    }
    /* Commented out code for 2024-2025 RET Surge to remove all Access Request and Approval process functionality
    @isTest static void OnBeforeInsertUpdateTest() {
        User castIronUser = [Select Id from user where email = 'castIronUserTestEmail@test.org' limit 1];
        system.runAs(castIronUser){
            
            PBS_Lease__c leaseRec = [select Id, Name, LSR_Contact_Email__c, LSR_Email_Text__c  from PBS_Lease__c where Name = 'Test Lease' limit 1];
            User retUser = [select Id, Name from user where email ='retUserTestEmail420@test.org' limit 1];
            PBS_Lease_Access__c lsac = new PBS_Lease_Access__c(PBS_Lease__c = leaseRec.id, Requestor__c=retUser.Id, Status__c = 'Requested');
            insert lsac; 
            system.assertNotEquals(null, lsac.Id);
            lsac.Status__c = 'Approved';
            update lsac;
            system.assertNotEquals(null, lsac.Id);
            lsac.Status__c = 'Revoked';
            update lsac; 
            system.assertNotEquals(null, lsac.Id);
            lsac.Status__c = 'Denied';
            update lsac; 
            system.assertNotEquals(null, lsac.Id);
            //Test deleting lease access record
            delete lsac; 
            system.assertNotEquals(null, lsac.Id);
            PBS_Lease_Access__c lsac1 = new PBS_Lease_Access__c(PBS_Lease__c = leaseRec.id, Requestor__c=retUser.Id, Status__c = 'Approved');
            insert lsac1;
            system.assertNotEquals(null, lsac1.Id);
            leaseRec.LSR_Email_Text__c ='retUserTestEmail420@test.org';
            update leaseRec;
            system.assertNotEquals(null, leaseRec.Id);
        }
    }
    */
     @isTest static void test1(){
         boolean checkit = PBSLeaseAccessTriggerHelper.codeCoverageTest();
         system.assert(checkit);
     }
}