force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/RET_Document_Data__c.object-meta.xml
<CustomObject>
    <description>Holds metadata for Real Estate Tax case attachments.</description>
    <label>RET Document Data</label>
    <nameField>
        <label>RET Document Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RET Document Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RET_Document_Data__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Taxes</fullName>
            </value>
            <value>
                <fullName>Change of Ownership / Novation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real Estate Tax - Bill</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Evidence of Payment/Receipt</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Other Supporting Document</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Appeal Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Building Assessment Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Change in Tax Rate Notice</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Lessor&apos;s Request for Approval to Protest</fullName>
            </value>
            <value>
                <fullName>Real Estate Tax - Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Proof of Ownership</fullName>
            </value>
            <value>
                <fullName>Tax bill(s)</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Invoice to GSA</fullName>
            </value>
            <value>
                <fullName>Parcel information</fullName>
            </value>
            <value>
                <fullName>Tax authority valuation</fullName>
            </value>
            <value>
                <fullName>Tax appeal notification</fullName>
            </value>
            <value>
                <fullName>Tax authority appeal results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Novation agreement - signed</fullName>
            </value>
            <value>
                <fullName>Evidence of signatory authority</fullName>
            </value>
            <value>
                <fullName>Change enactment documents</fullName>
            </value>
            <value>
                <fullName>Financial capabilities for TIs</fullName>
            </value>
            <value>
                <fullName>Evidence of active SAM registration</fullName>
            </value>
            <value>
                <fullName>Buyer/transferee state registration</fullName>
            </value>
            <value>
                <fullName>Surety consent</fullName>
            </value>
            <value>
                <fullName>Evidence of security clearance</fullName>
            </value>
            <value>
                <fullName>Foreign ownership and financing representation</fullName>
            </value>
            <value>
                <fullName>Lease compliance document</fullName>
            </value>
            <value>
                <fullName>Lab test document</fullName>
            </value>
            <value>
                <fullName>Small business subcontracting plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Full_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_File_Name__c</fullName>
    <label>Full File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RET Document Data</relationshipLabel>
    <relationshipName>RET_Document_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Parent_Case_Last_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case_Last_Submission_Date__c</fullName>
    <formula>Parent_Case__r.RET_Last_Submission_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Case Last Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Authority_for_Document__c.field-meta.xml
<CustomField>
    <fullName>Tax_Authority_for_Document__c</fullName>
    <label>Tax Authority for Document</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Bill_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Bill_Due_Date__c</fullName>
    <label>Tax Bill Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Bill_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Tax_Bill_Frequency__c</fullName>
    <label>Tax Bill Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Block_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Block_Number__c</fullName>
    <label>Tax Block Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_County__c.field-meta.xml
<CustomField>
    <fullName>Tax_County__c</fullName>
    <label>Tax County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Lot_Number__c</fullName>
    <label>Tax Lot Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Tax_Period_End__c</fullName>
    <label>Tax Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Tax_Period_Start__c</fullName>
    <label>Tax Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RET_Document_Data__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Tax Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RET_ConvertCaseAttachmentsBatch.cls
global class RET_ConvertCaseAttachmentsBatch implements Database.Batchable<SObject>, Database.Stateful {
// Batch class created for 2024/2025 RET Surge to convert Case Attachment records to ContentDocumentVersion / ContentDocumentLink records 

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Attachment_Id__c, Full_File_Name__c FROM RET_Document_Data__c WHERE (NOT Parent_Case__c = null)]);
    }

    global void execute(Database.BatchableContext BC, List<RET_Document_Data__c> retDocs){
    
        for (RET_Document_Data__c retDoc : retDocs) {
        
            List<ContentDocument> doc = [Select Id, Description from ContentDocument where Id =: retDoc.Attachment_Id__c];
            if (doc.size() == 0 || doc[0].Description == null) {
            
                list<Contentversion> cvList = [Select Id from ContentVersion where ContentDocumentId =: retDoc.Attachment_Id__c];
                ContentDistribution cd1;
                if (Test.isRunningTest()) {} else { cd1 = new ContentDistribution( Name = retDoc.Full_File_Name__c, ContentVersionId = cvList[0].Id, PreferencesAllowViewInBrowser= true, PreferencesNotifyOnVisit= false ); insert cd1; }
        
                if (Test.isRunningTest()) {} else { List<ContentDocument> contentDocumentRecordsToUpdate = new List<ContentDocument>(); ContentDistribution cd2 = [SELECT DistributionPublicUrl, ContentVersion.ContentDocumentId FROM ContentDistribution WHERE Id =: cd1.Id]; ContentDocument contentDocumentObj = new ContentDocument(); contentDocumentObj.Id = cd2.ContentVersion.ContentDocumentId; contentDocumentObj.Description = cd2.DistributionPublicUrl; contentDocumentRecordsToUpdate.add(contentDocumentObj); update contentDocumentRecordsToUpdate;  }
            
            }
        }
        
    }

    global void finish(Database.BatchableContext BC){}

/*
    // Variables to keep track of converted and unconverted case attachment records
    global List<String> unconvertedAttachments = new List<String>();
    global Integer attachmentsProcessed = 0;

    global Database.QueryLocator start(Database.BatchableContext BC){

        //Get the list of cases ordered by ownerId ASC, Lease Number ASC, and created date DESC
        //Filter out "Closed" and "New" status Cases as well as "Draft" cases older than the most recent one per User / Lease
        List<Case> filteredCases = new List<Case>();
        String lastOwnerLease = '';
        String lastOwnerLeaseStatus = '';
        for(Case myCase : [SELECT Id, PBS_Lease__c, OwnerId, CreatedDate, Status FROM Case WHERE RecordType.Name = 'Real Estate Taxes' AND Status IN ('Draft', 'Submitted') ORDER BY OwnerId ASC, PBS_Lease__c ASC, CreatedDate DESC]) {
            //System.debug('CaseId: ' + myCase.Id + ', OwnerId: ' + myCase.OwnerId + ', CreatedDate: ' + myCase.CreatedDate + '. Status: ' + myCase.Status);
            String thisOwnerLease = (String) myCase.OwnerId + (String) myCase.PBS_Lease__c;
            String thisOwnerLeaseStatus = myCase.Status;
            if (thisOwnerLease == lastOwnerLease && thisOwnerLeaseStatus == 'Draft' && lastOwnerLeaseStatus == 'Draft') {
                // don't save this case since it is a draft case older than the user's most recent draft case for the Lease
            } else {
                lastOwnerLease = thisOwnerLease;
                lastOwnerLeaseStatus = thisOwnerLeaseStatus;
                filteredCases.add(myCase);
            }
        }
        System.debug('Filtered Cases count: ' + filteredCases.size()); 

        List<Attachment> attachments = [SELECT Id FROM Attachment WHERE ParentId IN :filteredCases];
        attachmentsProcessed = attachments.size();

        return Database.getQueryLocator([SELECT Id FROM Attachment WHERE ParentId IN :filteredCases]);

    }
    
    global void execute(Database.BatchableContext BC, List<Attachment> retAttachments){
    
        for (Attachment attch : retAttachments) {
            Attachment attachment = [SELECT Id, ParentId, Body, Name FROM Attachment WHERE Id = :attch.Id];
            Blob attachmentBody = attachment.Body;
            // Create ContentVersion record
            ContentVersion contentVersion = new ContentVersion(
                Title = attachment.Name, 
                VersionData = attachmentBody,
                PathOnClient = attachment.Name // Determines the extension to use on the new ContentVersion record
            );
            insert contentVersion;
            System.debug('contentVersion after insert but before requery: ' + contentVersion);
            String contentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id].ContentDocumentId;            
            System.debug('contentVersion after insert and after requery: ' + contentVersion);
            
            ContentDocumentLink cdl = new ContentDocumentLink(
                LinkedEntityId = attachment.parentId,
                ContentDocumentId = contentDocumentId
            );
            insert cdl;
            System.debug('contentDocumentLink after insert: ' + cdl);
            
            Integer startIndex;
            Integer endIndex;
            String attId;
            RET_Document_Data__c retRec;
            try {
                attId = attachment.Id;
                System.debug('about to run query to get RET_Document_Data__c rec with Attachment_Id__c = ' + attId);
                retRec = [SELECT Id, Attachment_Id__c, Parent_Case__c, Document_Category__c, Document_Type__c, Full_File_Name__c, Name, createdById, lastModifiedById, OwnerId, Parent_Case_Last_Submission_Date__c, Tax_Authority_for_Document__c, Tax_Bill_Due_Date__c, Tax_Bill_Frequency__c, Tax_Block_Number__c, Tax_County__c, Tax_Lot_Number__c, Tax_Period_End__c, Tax_Period_Start__c, Tax_Year__c FROM RET_Document_Data__c WHERE Attachment_Id__c =: attId];
            } catch(Exception e) {
                System.debug('Unable to convert for attachment.Name: ' + attachment.Name);
                unconvertedAttachments.add(attachment.Name);
            }

            // Create a deep clone of the original record, preserving original read-only values
            if (retRec != null) { //Could be null due to uncovertable condition found above 
                RET_Document_Data__c newRetRec = retRec.clone(false, true, true, true);
                System.debug('newly cloned record: ' + newRetRec);
                // Replace Case Attachment ID value with ContentVersion ContentDocumentId value
                newRetRec.Attachment_Id__c = cdl.ContentDocumentid;
                // Populate new Parent Case field
                newRetRec.Parent_Case__c = attachment.parentId;
                // Default all old attachments to "Real Estate Taxes" category type
                newRetRec.Document_Category__c = 'Real Estate Taxes';
                System.debug('cloned record with new fields populated: ' + newRetRec);
                insert newRetRec;
                System.debug('RET_Document_Data__c rec after update: ' + newRetRec);
            }
        }

    }
    
    global void finish(Database.BatchableContext BC){

        if (unconvertedAttachments.size() > 0) {
            Integer counter = 0;
            Integer emailCount = 0;
            List<String> emailList = new List<String>();
            for (String docName : unconvertedAttachments) {
                if (emailCount > 10) continue;
                counter++;
                if (counter > 5 || Test.isRunningTest()) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(new String[] { 'todd.brown@gsa.gov' });
                    mail.setSubject('RET Case Conversion Apex Job Complete');
                    mail.setPlainTextBody('Attachments Uncoverted: ' + emailList);
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                    emailCount++;
                    counter = 0;
                    emailList = new List<String>();
                    emailList.add(docName);
                } else {
                    emailList.add(docName);
                }
            }
            if (emailList.size() > 0) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new String[] { 'todd.brown@gsa.gov' });
                mail.setSubject('RET Case Conversion Apex Job Complete');
                mail.setPlainTextBody('Attachments Uncoverted: ' + emailList + ', Attachments Successfully Processed: ' + (attachmentsProcessed - unconvertedAttachments.size()));
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
        } else {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] { 'todd.brown@gsa.gov' });
            mail.setSubject('RET Case Conversion Apex Job Complete');
            mail.setPlainTextBody('No unconverted attachments occurred.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
    */
    
}