force-app/main/default/objects/NCMT_HelpContent__c/NCMT_HelpContent__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>NCMT Help Content in google docs</description>
    <label>NCMT_HelpContent</label>
</CustomObject>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site_RA_WorkItem_Detail__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site_RA_WorkItem_Detail__c</fullName>
    <label>NCMT Help Site RA WorkItem Detail</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/NCMT_clsRAWIHelpPageDetails.cls
public with sharing class NCMT_clsRAWIHelpPageDetails {

    public string redirectURL{get;set;}

    public pageReference redirectHelp() {
        
        NCMT_HelpContent__c ncmt_customsettings = NCMT_HelpContent__c.getOrgDefaults();
        redirectURL = ncmt_customsettings.NCMT_Help_Site_RA_WorkItem_Detail__c;
        PageReference pageRef= new PageReference(redirectURL);
        pageRef.setRedirect(true);
        return pageRef ;
    }

}