force-app/main/default/objects/NCMT_HelpContent__c/NCMT_HelpContent__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>NCMT Help Content in google docs</description>
    <label>NCMT_HelpContent</label>
</CustomObject>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site__c</fullName>
    <label>NCMT Help Site</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site_New_Construction_LPOE__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site_New_Construction_LPOE__c</fullName>
    <label>NCMT Help Site New Construction LPOE</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site_New_Construction_Oth__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site_New_Construction_Oth__c</fullName>
    <label>NCMT Help Site New Construction Oth</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site_New_Construction_PG__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site_New_Construction_PG__c</fullName>
    <label>NCMT Help Site New Construction PG</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site_RA_Parametric__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site_RA_Parametric__c</fullName>
    <label>NCMT Help Site RA Parametric</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NCMT_HelpContent__c/fields/NCMT_Help_Site_RA_WorkItem__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Help_Site_RA_WorkItem__c</fullName>
    <label>NCMT Help Site RA WorkItem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/NCMT_clsHelpPageDetails.cls
public with sharing class NCMT_clsHelpPageDetails{
public string redirectURL1{get;set;}
public string strProjectType {get;set;} 
public string strBuildingType {get;set;} 
    
    public pageReference load() {
    
        NCMT_HelpContent__c ncmt_customsettings = NCMT_HelpContent__c.getOrgDefaults();
        strProjectType = ApexPages.currentPage().getParameters().get('ProjectType');
        strBuildingType = ApexPages.currentPage().getParameters().get('BuildingType');
        
         if(strProjectType=='Parametric Entry' && strBuildingType != '')
        {
            redirectURL1 = ncmt_customsettings.NCMT_Help_Site_RA_Parametric__c;
        }
        else if(strProjectType=='Work Item Detail' && strBuildingType != '')
        {
            redirectURL1 = ncmt_customsettings.NCMT_Help_Site_RA_WorkItem__c;
        }
        else if(strProjectType=='New Construction' && strBuildingType == 'LPOE')
        {
            redirectURL1 = ncmt_customsettings.NCMT_Help_Site_New_Construction_LPOE__c;
        }
        else if(strProjectType=='New Construction' && strBuildingType == 'Parking Garage')
        {
            redirectURL1 = ncmt_customsettings.NCMT_Help_Site_New_Construction_PG__c;
        }   
        else if(strProjectType=='New Construction' && (strBuildingType != 'LPOE' || strBuildingType != 'Parking Garage'))
        {
            redirectURL1 = ncmt_customsettings.NCMT_Help_Site_New_Construction_Oth__c;
        }   
        else{
            redirectURL1 = ncmt_customsettings.NCMT_Help_Site__c;
        }    
        //system.debug('redirectURL=='+redirectURL);
        PageReference pageRef1 = new PageReference(redirectURL1);
        pageRef1.setRedirect(true);
        return pageRef1 ;

    }
}