force-app/main/default/objects/NCMT_Cost_Category__c/NCMT_Cost_Category__c.object-meta.xml
<CustomObject>
    <description>NCMT Cost Category</description>
    <label>Cost Category</label>
    <nameField>
        <label>Category ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Cost_Category__c/fields/CatDesc__c.field-meta.xml
<CustomField>
    <fullName>CatDesc__c</fullName>
    <formula>Name + &apos;-&apos; +  Category_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CatDesc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Cost_Category__c/fields/Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Category_Description__c</fullName>
    <description>Cost Category Description</description>
    <label>Category Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NCMT_Cost_Category__c/fields/Estimate_Format__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Format__c</fullName>
    <label>Estimate Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uniformat</fullName>
            </value>
            <value>
                <fullName>IRIS Format</fullName>
            </value>
            <value>
                <fullName>Master Format</fullName>
            </value>
            <value>
                <fullName>Assemblies</fullName>
            </value>
            <value>
                <fullName>GSA Assemblies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Cost_Category__c/fields/Has_Lookups__c.field-meta.xml
<CustomField>
    <fullName>Has_Lookups__c</fullName>
    <label>Has Lookups</label>
    <summaryForeignKey>NCMT_DES_Lookup_details__c.Level_2__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/NCMT_DES_Lookup_details__c.object-meta.xml
<CustomObject>
    <label>NCMT DES Lookup Detail</label>
    <nameField>
        <label>Surrogate Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT DES Lookup Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/ItemDesc__c.field-meta.xml
<CustomField>
    <fullName>ItemDesc__c</fullName>
    <formula>Line_Item_Number__c + &apos; - &apos; +  Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ItemDesc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Level_2_Description__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Description__c</fullName>
    <formula>Level_2__r.Category_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level 2 Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Level_3_Description__c.field-meta.xml
<CustomField>
    <fullName>Level_3_Description__c</fullName>
    <label>Level 3 Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Level_4_Description__c.field-meta.xml
<CustomField>
    <fullName>Level_4_Description__c</fullName>
    <label>Level 4 Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Level_5_Description__c.field-meta.xml
<CustomField>
    <fullName>Level_5_Description__c</fullName>
    <label>Level 5 Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Lvl2Desc__c.field-meta.xml
<CustomField>
    <fullName>Lvl2Desc__c</fullName>
    <formula>Level_2__r.CatDesc__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lvl2Desc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Lvl3Desc__c.field-meta.xml
<CustomField>
    <fullName>Lvl3Desc__c</fullName>
    <formula>Level_3_Line_Item__c + &apos;-&apos; +  Level_3_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lvl3Desc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Lvl4Desc__c.field-meta.xml
<CustomField>
    <fullName>Lvl4Desc__c</fullName>
    <formula>Level_4_Line_Item__c + &apos;-&apos; +  Level_4_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lvl4Desc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_DES_Lookup_details__c/fields/Lvl5Desc__c.field-meta.xml
<CustomField>
    <fullName>Lvl5Desc__c</fullName>
    <formula>Level_5_Line_Item__c + &apos;-&apos; +  Level_5_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lvl5Desc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Cost_Parameter_Date_FY__c.field-meta.xml
<CustomField>
    <fullName>Cost_Parameter_Date_FY__c</fullName>
    <formula>Text(YEAR(Cost_Parameter_Date__c + 92))</formula>
    <label>Cost Parameter Date FY</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/NCMT_Tree_structure__c.object-meta.xml
<CustomObject>
    <label>NCMT Tree structure</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Tree Structure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Tree structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Estimate_Format__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Format__c</fullName>
    <label>Estimate Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uniformat</fullName>
            </value>
            <value>
                <fullName>IRIS Format</fullName>
            </value>
            <value>
                <fullName>Master Format</fullName>
                <default>true</default>
                <label>Master Format</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Tree_structures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/NCMT_TreeView_Ctrl_LC.cls
/** 
This Apex class is referenced on lightning component NCMT_TreeView_LC 
which is not used anywhere within NCMT Application.
Hence this artifact can be marked as redundant **/

public with sharing class NCMT_TreeView_Ctrl_LC {
    
    public static Id treeId {get;set;}
    public static Id projId {get;set;}
    public static String projName {get;set;}
    public static String estFormat {get;set;}
    public static Map<String, String> costCatOptions {get;set;}
    public static String selectedCat {get;set;}
    public static String fiscalYear {get;set;}
    
    @AuraEnabled
    public static ESTFormat populateCostCategories(String treeId)
    {
        //Get ID of current tree structure and query for field values
        System.debug('TreeID: ' + treeId);
        ESTFormat response = new ESTFormat();
        List<NCMT_Tree_structure__c>  treestruc = [select Estimate_Format__c, Project_ID__c, Name,
                                                   Project_ID__r.name, Project_ID__r.Cost_Parameter_Date_FY__c
                                                   from NCMT_Tree_structure__c 
                                                   where id = :treeId];
        
        //Set project ID, name, and estimate format
        projId = treestruc[0].Project_ID__c;
        projName = treestruc[0].Project_ID__r.Name;
        estFormat = treestruc[0].Estimate_Format__c;
        fiscalYear = treestruc[0].Project_ID__r.Cost_Parameter_Date_FY__c;
        
        //Get all cost categories associated with the estimate format of this tree structure
        costCatOptions = new Map<String, String>();
        List<NCMT_Cost_Category__c> cats = [SELECT CatDesc__c, Category_Description__c, Estimate_Format__c 
                                            FROM NCMT_Cost_Category__c
                                            WHERE Estimate_Format__c =: estFormat
                                            AND Has_Lookups__c >0 
                                            ORDER BY CatDesc__c];
        
        //Set the first cost category in the list as the default 
        // selectedCat = allCats[0].Lvl2Desc__c;
            selectedCat = cats[0].CatDesc__c;
        
        // Construct list of category descriptions to populate the cost category dropdown menu
        for(Integer i = 0; i < cats.size(); i++)
        {
            costCatOptions.put(String.valueOf(i), cats[i].CatDesc__c);
        }
        response.descriptionMap=costCatOptions;
        response.ESTFormat= estFormat;
        response.fiscalYear = fiscalYear;

        return response;                                        
    }
    
    @AuraEnabled
    public static List<TreeItem> populateTree(String selectedCat, string ESTFormat, String fiscalYear)
    {
        System.debug('Selected: ' + selectedCat);
        System.debug('estFormat: ' + estFormat);
        List<TreeItem> level2 = new List<TreeItem>();
        
      IF(estFormat == 'Master Format'){
        //Get tree structure levels for selected cost category
        string[] excludedFiles = new string[]{'%GSA 2020 FMR_PM_ASSMUP.xlsx%', '%GSA_ 2020 M&R Unit Price Data.xls%'};

        List<NCMT_DES_Lookup_details__c> tempDetails = [SELECT Level_2_Description__c, Lvl2Desc__c, //ItemDesc__c,
                                                        Level_3_Description__c, Lvl3Desc__c,
                                                        Level_4_Description__c, Lvl4Desc__c,
                                                        Level_5_Description__c, Lvl5Desc__c
                                                        FROM NCMT_DES_Lookup_details__c
                                                        WHERE Level_2_Description__c = :selectedCat 
                                                        AND Fiscal_Year__c =: fiscalYear
                                                        AND (NOT File_Name__c LIKE :excludedFiles)                           
                                                        ORDER BY Lvl3Desc__c,Lvl4Desc__c,Lvl5Desc__c];
          
        System.debug('Master Format items Size: ' + tempDetails.size());
          
        // Set all IDs to null so that duplicates may be removed from the details list
        for(NCMT_DES_Lookup_details__c d : tempDetails)
        {
            d.Id = null;
        }
        
        //Remove duplicates from tempDetails list (Sets by default include no duplicates)
        Set<NCMT_DES_Lookup_details__c> tempSet = new Set<NCMT_DES_Lookup_details__c>();
        List<NCMT_DES_Lookup_details__c> details = new List<NCMT_DES_Lookup_details__c>();
        tempSet.addall(tempDetails);
        details.addAll(tempSet);
        
        
        System.debug('Size = ' + details.size());
        
        //Populate tree
        for(Integer i = 0; i < details.size(); i++)
        {
            System.debug('i = ' + i);
            Integer l2size = level2.size();
            NCMT_DES_Lookup_details__c d = details[i];
            NCMT_DES_Lookup_details__c d2 = null;
            if(i != 0)
                d2 = details[i-1];
            
            List<TreeItem> level5 = new List<TreeItem>();
            List<TreeItem> level4 = new List<TreeItem>();
            List<TreeItem> level3 = new List<TreeItem>();
            
            System.debug('d = ' + d);
            System.debug('d2 = ' + d2 + '\n');
            if(d.Level_2_Description__c != null)
            {
                if(d.level_3_Description__c != null)
                {
                    if(d.level_4_Description__c != null)
                    {
                        //All 5 levels are populated
                        if(d.level_5_description__c != null)
                        {
                            //Add Level 5 item
                            TreeItem t = new TreeItem(d.Lvl5Desc__c, constructName(d), false, true, null);//, d.ItemDesc__c);
                            level5.add(t);  
                            
                            //If first item in list, add all rows without further checks
                            if(d2 == null || (d.Level_4_Description__c != d2.Level_4_Description__c && d.Level_3_Description__c != d2.Level_3_Description__c))
                            {
                                t = new TreeItem(d.Lvl4Desc__c, 'N', false, true, level5);//, null);
                                level4.add(t);
                                
                                t = new TreeItem(d.Lvl3Desc__c, 'N', false, true, level4);//, null);
                                level3.add(t);
                                level2.add(t);
                                System.debug('level2 size = ' +  level2.size());
                            }
                            //Level 5 item is a child of previous level 4
                            else if(d.Level_4_Description__c == d2.Level_4_Description__c)
                            {
                                Integer l3size = level2.get(l2size-1).items.size();
                                level2.get(l2size-1).items.get(l3size-1).items.add(t);
                            }
                            //Level 4 item is a child of previous level 3
                            else if(d.Level_3_Description__c == d2.Level_3_Description__c)
                            {
                                System.debug('CURRENT = ' + d);
                                System.debug('l2size = ' + l2size);
                                System.debug(level2.get(l2size-1));
                                System.debug(level2.get(l2size-1).items);
                                
                                t = new TreeItem(d.Lvl4Desc__c, 'N', false, true, level5);//, null);
                                level4.add(t);
                                
                                //Add to previous level 3 list of children
                                //level2.get(i-1).items.add(t);
                                level2.get(l2size-1).items.add(t);
                                
                            }
                        } 
                        
                        //TreeItem is populated up to level 4
                        else
                        {
                            TreeItem t = new TreeItem(d.Lvl4Desc__c, 'N', false, true, null);//, null);
                            level4.add(t);
                            
                            t = new TreeItem(d.Lvl3Desc__c, 'N', false, true, level4);//, null);
                            level3.add(t);
                            level2.add(t);
                            System.debug('level2 size = ' +  level2.size());
                        }
                    }
                    //TreeItem is populated up to level 3
                    else
                    {
                        TreeItem t = new TreeItem(d.Lvl3Desc__c, 'N', false, true, null);//, null);
                        level3.add(t);
                        level2.add(t);
                        System.debug('level2 size = ' +  level2.size());
                    }
                }
                
            }
        }
      }
        return level2;
    }
    
    public static String constructName(NCMT_DES_Lookup_details__c d)
    {
        String s = d.Level_5_Description__c + '|' +
            d.Level_4_Description__c + '|' +
            d.Level_3_Description__c + '|' +
            d.Level_2_Description__c;
        
        return s;
    }
    
    //Wrapper class
    public class TreeItem
    {
        @AuraEnabled public String label {get;set;}
        @AuraEnabled public String name {get;set;}
        @AuraEnabled public Boolean disabled {get;set;}
        @AuraEnabled public Boolean expanded {get;set;}
        @AuraEnabled public List<TreeItem> items {get;set;}
        //@AuraEnabled public string itemDescription {get;set;}

        public TreeItem(String label, String name, Boolean disabled, Boolean expanded, List<TreeItem> items)//, string itemDescription)
        {
            this.label = label;
            this.name = name;
            this.disabled = disabled;
            this.expanded = false;
            this.items = items;
            //this.itemDescription = itemDescription;
        }
        
             
    } 
    public class ESTFormat{
        @auraenabled public map<string,string> descriptionMap{get;set;}
        @auraenabled public string estFormat{get;set;}
        @auraenabled public string fiscalYear {get;set;}

        public ESTFormat(){
            this.descriptionMap= new map<string,string>();
            this.estFormat='';
            this.fiscalYear='';

        }
    }
}