force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/fields/ActualUtilitySav__c.field-meta.xml
<CustomField>
    <fullName>ActualUtilitySav__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual savings when calculated at a project building level</description>
    <inlineHelpText>Enter calculated building-level utility savings (Btu/yr).</inlineHelpText>
    <label>Utility Savings Actual</label>
    <referenceTo>PBS_gBUILD_UtilitySavings__c</referenceTo>
    <relationshipLabel>gBUILD Project Buildings (Utility Savings Actual)</relationshipLabel>
    <relationshipName>gBUILD_Project_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestPBS_gBUILD_UtilitySavingsController.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_UtilitySavingsController
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        string usId = [select ActualUtilitySav__c from PBS_gBUILD_ProjectBuilding__c where id=:pb.id].ActualUtilitySav__c;

        PageReference pr = TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(pb.id);
        pr.getParameters().put(PBS_gBUILD_Utility.queryStringUtilitySavingsContext, 'All Savings');
        pr.getParameters().put(PBS_gBUILD_Utility.queryStringUtilitySavingsId, usId);
        Test.setCurrentPageReference(pr);

        PBS_gBUILD_UtilitySavingsController ctrl = new PBS_gBUILD_UtilitySavingsController();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assertEquals('All Savings', ctrl.contextName);
        system.assertEquals(usId, ctrl.itemId);
        system.assert(ctrl.item!=null);
        system.assertEquals(usId, ctrl.item.id);

        ctrl.edit();
        ctrl.save();
        ctrl.cancel();
    }
}