force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/fields/ModifiedReason__c.field-meta.xml
<CustomField>
    <fullName>ModifiedReason__c</fullName>
    <description>The reason this object was modified</description>
    <inlineHelpText>The reason this object was modified</inlineHelpText>
    <label>Last Modified Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_PBuildingCloseoutController.cls
public with sharing class PBS_gBUILD_PBuildingCloseoutController extends PBS_gBUILD_ProjectIdBaseController
{
    public PBS_gBUILD_ProjectBuilding__c clo { get; private set; }
    public string epmCatalog { get; private set; }
    
    public PBS_gBUILD_PBuildingCloseoutController()
    {
        super('Closeout', true);
        try
        {
            epmCatalog = PBS_gBUILD_Utility.epmCatalogCloseout;
            bind();
        }
        catch (Exception ex)
        {
            handleConstructorError(ex);
        }
    }
    
    protected override void bind()
    {    
        super.bind();
        clo = PBS_gBUILD_Utility.loadProjectBuilding(pbuildingid);
    }

    public PageReference edit() 
    {
        viewMode = false;
        bind();
        return null;
    }  
         
    public PageReference cancel() 
    {
        return createPageLink(ProjectPageRefs.PbCloseout, true);
    }  
    
    public PageReference save() 
    {
        clo.ModifiedReason__c = 'Closeout information was updated';
        update clo;
        return createPageLink(ProjectPageRefs.PbCloseout, true);
    }  
}