force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/PBS_gBUILD_PBuildingInnovation__c.object-meta.xml
<CustomObject>
    <description>gBUILD PBuilding Innovation:  Innovations that were produced during this building modification.</description>
    <label>gBUILD Innovation</label>
    <nameField>
        <displayFormat>gbI_{00000}</displayFormat>
        <label>gBUILDI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Innovations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/Rahd_ProjectBldgParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ProjectBldgParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_ProjectBuilding.</inlineHelpText>
    <label>RAHD_Project Building Parent ID</label>
    <referenceTo>PBS_gBUILD_ProjectBuilding__c</referenceTo>
    <relationshipLabel>gBUILD Innovation</relationshipLabel>
    <relationshipName>gBUILD_PBuilding_to_Innovation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPBS_gBUILD_ProjectBInnovationNew.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_ProjectBInnovationNew
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(pb.id);

        PBS_gBUILD_PBInnovationNew ctrl = new PBS_gBUILD_PBInnovationNew();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assertEquals(null, ctrl.item.id);
        system.assertEquals(pb.id, ctrl.item.Rahd_ProjectBldgParentId__c);

        ctrl.saveAndNew();
        system.assert(ctrl.item.id!=null);

        ctrl.edit();
        ctrl.cancel();
    }

    public static testMethod void testLoadingAnExistingItem()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        PBS_gBUILD_PBuildingInnovation__c item = new PBS_gBUILD_PBuildingInnovation__c(Rahd_ProjectBldgParentId__c=pb.id);
        insert item;
        PageReference pr = TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(pb.id);
        pr.getParameters().put(PBS_gBUILD_Utility.queryStringPInnovationId, item.id);
        Test.setCurrentPageReference(pr);
        PBS_gBUILD_PBInnovationNew ctrl = new PBS_gBUILD_PBInnovationNew();
        system.assert(ctrl.item!=null);
    }
}