force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/PBS_gBUILD_PBuildingInnovation__c.object-meta.xml
<CustomObject>
    <description>gBUILD PBuilding Innovation:  Innovations that were produced during this building modification.</description>
    <label>gBUILD Innovation</label>
    <nameField>
        <displayFormat>gbI_{00000}</displayFormat>
        <label>gBUILDI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Innovations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>GPG category</description>
    <inlineHelpText>Please select the green proving ground (GPG) category for this building.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdvancedMetering</fullName>
            </value>
            <value>
                <fullName>BuildingEnvelopeInterior</fullName>
            </value>
            <value>
                <fullName>CoGenerationSystems</fullName>
            </value>
            <value>
                <fullName>DemandRespond,LoadManagement</fullName>
            </value>
            <value>
                <fullName>Heating</fullName>
            </value>
            <value>
                <fullName>HVAC_Controls_Diagnostics</fullName>
            </value>
            <value>
                <fullName>HVAC_Equipment_SystemDesign</fullName>
            </value>
            <value>
                <fullName>Lighting(Controls)</fullName>
            </value>
            <value>
                <fullName>Lighting(Luminaries,Design)</fullName>
            </value>
            <value>
                <fullName>OperationsAndMaintenance</fullName>
            </value>
            <value>
                <fullName>RenewableEnergySystems</fullName>
            </value>
            <value>
                <fullName>SanitationWaterConservationChemReduction</fullName>
            </value>
            <value>
                <fullName>WorkplaceAndInterior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other(PleaseEnterBelow)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/CategoryOther__c.field-meta.xml
<CustomField>
    <fullName>CategoryOther__c</fullName>
    <description>GPG Other category decription</description>
    <inlineHelpText>If GPG category was not included in the above list, please specify here.</inlineHelpText>
    <label>Category Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/FundingStatus__c.field-meta.xml
<CustomField>
    <fullName>FundingStatus__c</fullName>
    <description>Funding Status</description>
    <inlineHelpText>Please select the funding status of this building.</inlineHelpText>
    <label>Funding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FundedByArra</fullName>
            </value>
            <value>
                <fullName>FundedByNonArra</fullName>
            </value>
            <value>
                <fullName>NeedsFunding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/IsBaselineDataAvailable__c.field-meta.xml
<CustomField>
    <fullName>IsBaselineDataAvailable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Baseline Data Available</description>
    <inlineHelpText>Please indicate if there is baseline data available to measure and verify the anticipated savings or impact of this technology (organized either by system or building affected).</inlineHelpText>
    <label>Baseline Data Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/PotentialImpact__c.field-meta.xml
<CustomField>
    <fullName>PotentialImpact__c</fullName>
    <description>Potential impact of use of GPG technology</description>
    <inlineHelpText>Potential Impact - Please explain the potential or anticipated impact of your innovative technology and how it will mitigate or solve the stated problem.</inlineHelpText>
    <label>Potential Impact</label>
    <length>32767</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/ProblemStatement__c.field-meta.xml
<CustomField>
    <fullName>ProblemStatement__c</fullName>
    <description>Statement of the problem</description>
    <inlineHelpText>Problem Statement for Innovative Green Technology - Please explain the problem to be addressed with the proposed innovative technology or approach.</inlineHelpText>
    <label>Problem Statement</label>
    <length>32767</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/Rahd_ProjectBldgParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ProjectBldgParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_ProjectBuilding.</inlineHelpText>
    <label>RAHD_Project Building Parent ID</label>
    <referenceTo>PBS_gBUILD_ProjectBuilding__c</referenceTo>
    <relationshipLabel>gBUILD Innovation</relationshipLabel>
    <relationshipName>gBUILD_PBuilding_to_Innovation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/TechDescription__c.field-meta.xml
<CustomField>
    <fullName>TechDescription__c</fullName>
    <description>Description of GPG technology</description>
    <inlineHelpText>Please describe the technology being proposed and explain why the technology is considered innovative compared to similar technologies/solutions.</inlineHelpText>
    <label>Innovative Technology Description</label>
    <length>32767</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/WasMeasurementVerificationIncluded__c.field-meta.xml
<CustomField>
    <fullName>WasMeasurementVerificationIncluded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Was Measurement And Verification Included</description>
    <inlineHelpText>Was Measurement and Verification work included in your budget?  If so, please check the box.</inlineHelpText>
    <label>Was Measurement &amp; Verification Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_PBInnovationNew.cls
public with sharing class PBS_gBUILD_PBInnovationNew extends PBS_gBUILD_ProjectIdBaseController 
{
    public PBS_gBUILD_PBuildingInnovation__c item { get; private set; }
    
    public PBS_gBUILD_PBInnovationNew() 
    {       
        super(
            'Details', 
            true,
            new List<string>{
                'Innovation', 'PBS_gBUILD_PBuildingInnovation'                      
            });
        bind();
    }
    
    protected override void bind()
    {    
        super.bind();
        string id = ApexPages.currentPage().getParameters().get(PBS_gBUILD_Utility.queryStringPInnovationId);
        if (id!=null)
        {
            item = 
            [
                select 
                    id,
                    name,
                    Category__c,
                    CategoryOther__c,
                    FundingStatus__c,
                    IsBaselineDataAvailable__c,
                    WasMeasurementVerificationIncluded__c,                  
                    Rahd_ProjectBldgParentId__c,
                    ProblemStatement__c,
                    TechDescription__c, 
                    PotentialImpact__c
                from PBS_gBUILD_PBuildingInnovation__c 
                where id=:id
            ]; 
        }
        if (item==null)
        {
            item = new PBS_gBUILD_PBuildingInnovation__c();
            item.Rahd_ProjectBldgParentId__c = pbuildingId;
            viewMode = false;
        }   
    }

    public PageReference edit()
    {
        PBS_gBUILD_Utility.showDebugMessage('EDIT');
        bind();
        viewMode = false;
        return null;
    }
    
    public PageReference save()
    {
        PBS_gBUILD_Utility.showDebugMessage('SAVE');
        viewMode = true;
        upsert item;
        PBS_gBUILD_Utility.RecordProjectBuildingModifiedReason(pbuildingId, 'Innovation added/updated');
        bind();
        return null;
    }

    public PageReference saveAndNew()
    {
        save();
        return createPageLink(ProjectPageRefs.PbInnovationsItem, true);
    }

    public PageReference cancel()
    {
        return createPageLink(ProjectPageRefs.PbInnovations);
    }   
}