force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/PBS_gBUILD_PBuildingInnovation__c.object-meta.xml
<CustomObject>
    <description>gBUILD PBuilding Innovation:  Innovations that were produced during this building modification.</description>
    <label>gBUILD Innovation</label>
    <nameField>
        <displayFormat>gbI_{00000}</displayFormat>
        <label>gBUILDI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Innovations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_PBuildingInnovation__c/fields/Rahd_ProjectBldgParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ProjectBldgParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_ProjectBuilding.</inlineHelpText>
    <label>RAHD_Project Building Parent ID</label>
    <referenceTo>PBS_gBUILD_ProjectBuilding__c</referenceTo>
    <relationshipLabel>gBUILD Innovation</relationshipLabel>
    <relationshipName>gBUILD_PBuilding_to_Innovation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPBS_gBUILD_ProjectBInnovation.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_ProjectBInnovation
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(pb.id);

        PBS_gBUILD_PBuildingInnovation__c i = new PBS_gBUILD_PBuildingInnovation__c(Rahd_ProjectBldgParentId__c=pb.id);
        insert i;

        PBS_gBUILD_PBuildingInnovationController ctrl = new PBS_gBUILD_PBuildingInnovationController();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assert(ctrl.items.size()>0);

        system.assert(ctrl.add()!=null);
                                     
        ctrl.actionid=i.id;
        ctrl.open();
        ctrl.del();
    }
}