force-app/main/default/objects/NCMT_Housing_Plan_Cost_Parameter__c/NCMT_Housing_Plan_Cost_Parameter__c.object-meta.xml
<CustomObject>
    <label>NCMT Housing Plan Cost Parameter</label>
    <nameField>
        <displayFormat>HP-Cost-{00000}</displayFormat>
        <label>NCMT Housing Plan Cost Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Cost Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Cost_Parameter__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Cost_Parameter__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Cost_Parameter__c/fields/NCMT_Housing_Plan_Option__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan Option</label>
    <referenceTo>NCMT_Housing_Plan_Option__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Cost Parameters</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Cost_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Cost_Parameter__c/fields/Space_Type__c.field-meta.xml
<CustomField>
    <fullName>Space_Type__c</fullName>
    <label>Space Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCMT_Space_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/NCMT_Housing_Plan_Option__c.object-meta.xml
<CustomObject>
    <label>NCMT Housing Plan Option</label>
    <nameField>
        <displayFormat>Option-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/Choice_Text__c.field-meta.xml
<CustomField>
    <fullName>Choice_Text__c</fullName>
    <inlineHelpText>Displayed to the user, brief description of the cost option.</inlineHelpText>
    <label>Choice Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/NCMT_Housing_Plan_Option_Template__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option_Template__c</fullName>
    <label>NCMT Housing Plan Option Template</label>
    <referenceTo>NCMT_Housing_Plan_Option_Template__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Options</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/Recurs_on_TCO_Tenant_Renewal_Years__c.field-meta.xml
<CustomField>
    <fullName>Recurs_on_TCO_Tenant_Renewal_Years__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This cost will be added on the Retrofit years specified in the project&apos;s TCO Lifecycle Input in addition to the years specified in Replace Every X Years.</inlineHelpText>
    <label>Recurs on TCO Tenant Renewal Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>Sets the order the options will be displayed to users within a particular Template Record Type and Type.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/TCO_Default_Repair_Cost_Percentage__c.field-meta.xml
<CustomField>
    <fullName>TCO_Default_Repair_Cost_Percentage__c</fullName>
    <label>TCO Default Repair Cost (Percentage)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/TCO_Default_Repair_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Default_Repair_Every_X_Years__c</fullName>
    <defaultValue>1</defaultValue>
    <label>TCO Default Repair Every X Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/TCO_Default_Replacement_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Default_Replacement_Every_X_Years__c</fullName>
    <defaultValue>1</defaultValue>
    <label>TCO Default Replacement Every X Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/NCMT_Housing_Plan_Option_Selection__c.object-meta.xml
<CustomObject>
    <description>Created when a Housing Plan Selection Option is selected on the Housing Plan selection page. Deleted if unselected.</description>
    <label>NCMT Housing Plan - Option Selection</label>
    <nameField>
        <displayFormat>Select-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Option Selection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Housing_Plan_Option__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan Option</label>
    <referenceTo>NCMT_Housing_Plan_Option__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/NCMT_Housing_Plan_Option_Template__c.object-meta.xml
<CustomObject>
    <description>The NCMT Housing Plan Option Choices related to a template are displayed on the NCMT Housing Plan Option Selection page, filtered by the Record Type.</description>
    <label>NCMT Housing Plan Option Template</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>NCMT Housing Plan Option Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Option Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>Sets the order of the Type when all related Options are displayed (options are grouped by Type).</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Housing_Plan_Cost_Sub_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Housing_Plan_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/recordTypes/Other_Cost.recordType-meta.xml
<RecordType>
    <fullName>Other_Cost</fullName>
    <active>true</active>
    <label>Other Cost</label>
</RecordType>

force-app/main/default/objects/NCMT_Other_Cost__c/NCMT_Other_Cost__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>NCMT Other Cost</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Other Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Other Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Housing_Plan_Cost_Parameter__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Cost_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan Cost Parameter</label>
    <referenceTo>NCMT_Housing_Plan_Cost_Parameter__c</referenceTo>
    <relationshipLabel>NCMT Other Costs</relationshipLabel>
    <relationshipName>NCMT_Other_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Housing_Plan_Option_Selection__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option_Selection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan - Option Selection</label>
    <referenceTo>NCMT_Housing_Plan_Option_Selection__c</referenceTo>
    <relationshipLabel>NCMT Other Costs</relationshipLabel>
    <relationshipName>NCMT_Other_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Other_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/Space_Type__c.field-meta.xml
<CustomField>
    <fullName>Space_Type__c</fullName>
    <formula>Text(NCMT_Housing_Plan_Cost_Parameter__r.Space_Type__c)</formula>
    <label>Space Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/recordTypes/New_Construction_TCO.recordType-meta.xml
<RecordType>
    <fullName>New_Construction_TCO</fullName>
    <active>true</active>
    <description>New Construction - TCO</description>
    <label>New Construction - TCO</label>
</RecordType>

force-app/main/default/objects/NCMT_Project__c/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>false</active>
    <description>Federal Office Building</description>
    <label>Office</label>
</RecordType>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/NCMT_TCO_Lifecycle_Input__c.object-meta.xml
<CustomObject>
    <label>NCMT TCO Lifecycle Input</label>
    <nameField>
        <displayFormat>Lifecycle-{00000}</displayFormat>
        <label>TCO Lifecycle Input Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT TCO Lifecycle Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Construction__c.field-meta.xml
<CustomField>
    <fullName>Construction__c</fullName>
    <label>Construction/Move in (months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <label>Design (months)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/End_Major_Maint_System_Replace_Early__c.field-meta.xml
<CustomField>
    <fullName>End_Major_Maint_System_Replace_Early__c</fullName>
    <inlineHelpText>Number of years to be subtracted from the End of Maintenance &amp; Operations date for applying periodic Core Shell Cost Details where the related Core Shell Cost Parameter Type1 field equals &quot;Maintenance&quot;.</inlineHelpText>
    <label>(deprecated) End Major Maint &amp; Replace</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/End_Routine_Periodic_Maintenance_Early__c.field-meta.xml
<CustomField>
    <fullName>End_Routine_Periodic_Maintenance_Early__c</fullName>
    <inlineHelpText>Number of years to be subtracted from the End of Maintenance &amp; Operations date for applying periodic Core Shell Cost Details where the related Core Shell Cost Parameter Type1 field equals &quot;Major Repair&quot;.</inlineHelpText>
    <label>(deprecated) End Routine Periodic Maint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Include_Tenant_Refresh_Costs__c.field-meta.xml
<CustomField>
    <fullName>Include_Tenant_Refresh_Costs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Tenant Refresh Costs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>TCO_Lifecycle_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/New_fit_out_every_years__c.field-meta.xml
<CustomField>
    <fullName>New_fit_out_every_years__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New fit-out every (years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Number_of_Years_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_of_Operation__c</fullName>
    <label>Number of Years of Operation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Period_of_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Period_of_Analysis__c</fullName>
    <label>Period of Analysis (years)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Planning_and_Pre_design__c.field-meta.xml
<CustomField>
    <fullName>Planning_and_Pre_design__c</fullName>
    <label>Planning and Pre-design (months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Refresh_every_years__c.field-meta.xml
<CustomField>
    <fullName>Refresh_every_years__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Refresh every (years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Housing_Plan_Cost_Sub_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Move Out</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Move In</fullName>
    </customValue>
    <masterLabel>Housing Plan Cost Sub-Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Housing_Plan_Cost_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Moving Costs</fullName>
    </customValue>
    <masterLabel>Housing Plan Cost Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NCMT_Space_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General Office Space Type, 20% Open</fullName>
        <label>Closed Offices</label>
    </customValue>
    <customValue>
        <fullName>General Office Space Type, 50% Open</fullName>
    </customValue>
    <customValue>
        <fullName>General Office Space Type, 80% Open</fullName>
    </customValue>
    <customValue>
        <fullName>General Office Space Type, 100% Open</fullName>
        <label>Workstations/Open Offices</label>
    </customValue>
    <customValue>
        <fullName>Enhanced Office Space Type</fullName>
    </customValue>
    <customValue>
        <fullName>General Storage</fullName>
    </customValue>
    <customValue>
        <fullName>High Density Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Dry/Electronic Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Wet Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Holding cell</fullName>
    </customValue>
    <customValue>
        <fullName>USMS Suite: Administrative Area</fullName>
    </customValue>
    <customValue>
        <fullName>USMS Suite, Sally Port</fullName>
    </customValue>
    <customValue>
        <fullName>USMS Operations Area</fullName>
    </customValue>
    <customValue>
        <fullName>USMS Suite: Central Holding Area</fullName>
    </customValue>
    <customValue>
        <fullName>Private Toilet</fullName>
    </customValue>
    <customValue>
        <fullName>Clinic/Health Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness/Exercise</fullName>
    </customValue>
    <customValue>
        <fullName>Childcare TI</fullName>
    </customValue>
    <customValue>
        <fullName>Conference/Classrooms</fullName>
    </customValue>
    <customValue>
        <fullName>Teleconference</fullName>
    </customValue>
    <customValue>
        <fullName>Auditorium</fullName>
    </customValue>
    <customValue>
        <fullName>Library</fullName>
    </customValue>
    <customValue>
        <fullName>ADP Mainframe</fullName>
    </customValue>
    <customValue>
        <fullName>ADP - High Density PCs</fullName>
    </customValue>
    <customValue>
        <fullName>Courtroom - District Court</fullName>
    </customValue>
    <customValue>
        <fullName>Courtroom, District Grand Jury</fullName>
    </customValue>
    <customValue>
        <fullName>Courtroom - Bankruptcy</fullName>
    </customValue>
    <customValue>
        <fullName>Courtroom - Magistrate</fullName>
    </customValue>
    <masterLabel>NCMT Space Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NCMT_HousingPlan_optSelection_Test.cls
@isTest
public class NCMT_HousingPlan_optSelection_Test {
    @testSetup static void setup()
    {
        

        //NCMT_TestTCOProjectClass.CreateTCOProject('testProjCodeCovTCOOff1','Virginia','State Average'
        //    ,'Lowrise (2 - 3 stories)', true, false, false, 1000000, true, false, false, false, false);
        NCMT_TestTCOProjectClass.CreateTCOProject('testProjCodeCov2','Virginia','State Average'
            ,'Lowrise (2 - 3 stories)', true, false, false, 1000000, false, false, false, false, false);
        
        NCMT_GenerateTCOProjectDetailsExt.runTriggers = true;
        NCMT_Project__c proj = [SELECT Id, Name FROM NCMT_Project__c LIMIT 1];

        //Not sure why this needs to be done, but....
        Id tcoRecordTypeId = NCMT_Utilities.getProjectRecordTypeId('New_Construction_TCO');
        proj.RecordTypeId = tcoRecordTypeId;
        System.debug('About to update to TCO Record Type.....');
        update proj;
        

    }



    static testMethod void testOptionSelection(){
        NCMT_Project__c proj = [SELECT Id, Name FROM NCMT_Project__c LIMIT 1];
        

        NCMT_TCO_Lifecycle_Input__c lifecycle = new NCMT_TCO_Lifecycle_Input__c(
            NCMT_Project__c = proj.Id,
            Include_Tenant_Refresh_Costs__c = true,
            New_fit_out_every_years__c = 7,
            Refresh_every_years__c = 7,
            Period_of_Analysis__c = 35,
            Planning_and_Pre_design__c = 6,
            Design__c = 6, 
            Construction__c = 12,
            End_Routine_Periodic_Maintenance_Early__c = 1,
            End_Major_Maint_System_Replace_Early__c = 3,
            Number_of_Years_of_Operation__c = 35
        );
        insert lifecycle;

        Id otherRT = NCMT_Housing_Plan_Option_Template__c.SobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Other_Cost').getRecordTypeId();

        NCMT_Housing_Plan_Option_Template__c temp = new NCMT_Housing_Plan_Option_Template__c(
            Sort_Order__c = 1,
            Sub_Type__c = 'Acquisition',
            Type__c = 'Moving Costs',
            RecordTypeId = otherRT
        );
        insert temp;

        NCMT_Housing_Plan_Option__c opt = new NCMT_Housing_Plan_Option__c(
            Choice_Text__c = 'My choice',
            NCMT_Housing_Plan_Option_Template__c = temp.Id,
            Recurs_on_TCO_Tenant_Renewal_Years__c = true,
            Sort_Order__c = 1,
            TCO_Default_Repair_Cost_Percentage__c = 25,
            TCO_Default_Repair_Every_X_Years__c = 1,
            TCO_Default_Replacement_Every_X_Years__c = 5
        );
        insert opt;

        List<NCMT_Housing_Plan_Cost_Parameter__c> params = new List<NCMT_Housing_Plan_Cost_Parameter__c>();
        params.add(new NCMT_Housing_Plan_Cost_Parameter__c(
            Cost__c = 2,
            Fiscal_Year__c = '2017',
            NCMT_Housing_Plan_Option__c = opt.Id,
            Space_Type__c = 'General Office Space Type, 50% Open'
        ));
        params.add(new NCMT_Housing_Plan_Cost_Parameter__c(
            Cost__c = 2,
            Fiscal_Year__c = '2017',
            NCMT_Housing_Plan_Option__c = opt.Id,
            Space_Type__c = 'General Storage'
        ));
        
        insert params;

        
        
        
        ApexPages.StandardController controller = new ApexPages.StandardController(proj);
        NCMT_HousingPlan_OptionSelection ctrl = new NCMT_HousingPlan_OptionSelection(controller);

        List<NCMT_HousePlan_TypeOptions> pageOpts = NCMT_HousingPlan_OptionSelection.retrieveOptions('Other_Cost', 'Moving Costs', proj.Id);
        for (NCMT_HousePlan_TypeOptions to : pageOpts){
            for (NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence i : to.recurrences){
                for (NCMT_HousePlan_TypeOptions.HousingPlan_SubType sub : i.subTypes){
                    for (NCMT_HousePlan_TypeOptions.HousingPlan_Option o : sub.options){
                        o.selected = true;
                    }
                }
            }
        }
        Test.startTest();
        NCMT_GenerateProjectDetailsExt.genHPRun = false;
        NCMT_GenerateTCOProjectDetailsExt.runTriggers = true;
        NCMT_TCO_Lifecycle_Input_TriggerHandler.triggerHandlerUpdate = false;
        String resp = NCMT_HousingPlan_OptionSelection.saveHousingPlanOpts(pageOpts);
        System.assertEquals(null, resp);
        System.assertEquals(1, [Select Id from NCMT_Housing_Plan_Option_Selection__c where NCMT_Project__c =: proj.Id].size());
        System.assertEquals(1, [Select Id from NCMT_Other_Cost__c where NCMT_Project__c =: proj.Id AND NCMT_Housing_Plan_Cost_Parameter__c <> null].size()); // 

        ctrl = new NCMT_HousingPlan_OptionSelection(controller);

        NCMT_HousePlan_TypeOptions t = new NCMT_HousePlan_TypeOptions();
        NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence r = new NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence();
        NCMT_HousePlan_TypeOptions.HousingPlan_SubType s = new NCMT_HousePlan_TypeOptions.HousingPlan_SubType();
        NCMT_HousePlan_TypeOptions.HousingPlan_Option op = new NCMT_HousePlan_TypeOptions.HousingPlan_Option();

        ApexPages.currentPage().getParameters().put('ProjectID', Proj.id);
        NCMT_ReportData objTest = new NCMT_ReportData();
        objTest.getMovingCosts();
        

        pageOpts = NCMT_HousingPlan_OptionSelection.retrieveOptions('Other_Cost', 'Moving Costs', proj.Id);
        for (NCMT_HousePlan_TypeOptions to : pageOpts){
            for (NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence i : to.recurrences){
                for (NCMT_HousePlan_TypeOptions.HousingPlan_SubType sub : i.subTypes){
                    for (NCMT_HousePlan_TypeOptions.HousingPlan_Option o : sub.options){
                        o.selected = false;
                    }
                }
            }
        }
        System.debug('About to stop test and fire future methods');
        Test.stopTest();

        NCMT_GenerateProjectDetailsExt.genHPRun = false;
        NCMT_GenerateTCOProjectDetailsExt.runTriggers = true;
        NCMT_TCO_Lifecycle_Input_TriggerHandler.triggerHandlerUpdate = false;
        resp = NCMT_HousingPlan_OptionSelection.saveHousingPlanOpts(pageOpts);
        System.assertEquals(null, resp);
    }
}