force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_DEFAULT_MONTH_BEGIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DEFAULT_MONTH_BEGIN__c</fullName>
    <label>Default Start</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_DEFAULT_MONTH_END__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DEFAULT_MONTH_END__c</fullName>
    <label>Default End</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_MOVE_DEFAULT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_MOVE_DEFAULT__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>Total Estimated Physical Move Costs / ABOA SF. Not an Annual Rate.</inlineHelpText>
    <label>Estimated Phys Move Costs per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_PV_OTHER_UPFRONT_COSTS__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PV_OTHER_UPFRONT_COSTS__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Estimated $/ANSI BOMA ABOA Build out Cost, in excess of the TI for both a new and continuing lease</description>
    <inlineHelpText>Total Estimated Build Out Costs / ABOA SF, in excess of TI. Not an Annual Rate.</inlineHelpText>
    <label>Estimated Build Out Over TI per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Region__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region__c</fullName>
    <label>RLP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Region 1</fullName>
            </value>
            <value>
                <fullName>Region 2</fullName>
            </value>
            <value>
                <fullName>Region 3</fullName>
            </value>
            <value>
                <fullName>Region 4</fullName>
            </value>
            <value>
                <fullName>Region 5</fullName>
            </value>
            <value>
                <fullName>Region 6</fullName>
            </value>
            <value>
                <fullName>Region 7</fullName>
            </value>
            <value>
                <fullName>Region 8</fullName>
            </value>
            <value>
                <fullName>Region 9</fullName>
            </value>
            <value>
                <fullName>Region 10</fullName>
            </value>
            <value>
                <fullName>Region 11</fullName>
            </value>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
            <value>
                <fullName>10/5 Term - All Regions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_STATUS__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
            <value>
                <fullName>Posted/Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_TELCOMM_DEFAULT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TELCOMM_DEFAULT__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Help Button - Total Estimated Telecom Cost / ABOA SF. Not an Annual Rate.</description>
    <inlineHelpText>Total Estimated Telecom Cost / ABOA SF. Not an Annual Rate.</inlineHelpText>
    <label>Estimated Telecom Cost per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Title__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Title__c</fullName>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_TIUSED_FOR_FIRM_TERM_NEW__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TIUSED_FOR_FIRM_TERM_NEW__c</fullName>
    <inlineHelpText>Total Estimated TI Allowance for New Space / ABOA SF. Not an amortized annual rate.</inlineHelpText>
    <label>Min TI for New Space per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_TIUSED_FOR_FIRM_TERM_SUCC__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TIUSED_FOR_FIRM_TERM_SUCC__c</fullName>
    <inlineHelpText>Total Estimated TI Allowance for Continuing Space / ABOA SF. Not an amortized annual rate.</inlineHelpText>
    <label>Min TI for Continuing Space per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Year__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Year__c</fullName>
    <label>RLP FY/Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/recordTypes/AAAP.recordType-meta.xml
<RecordType>
    <fullName>AAAP</fullName>
    <active>true</active>
    <label>AAAP</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_RLP_Attachments__c/PBS_AAAP_RLP_Attachments__c.object-meta.xml
<CustomObject>
    <label>RLP Attachments</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RLP Attachments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLP Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP_Attachments__c/fields/PBS_AAAP_Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP_Attachments__c/fields/PBS_AAAP_RLP__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP__c</fullName>
    <label>RLP</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>RLP Attachments</relationshipLabel>
    <relationshipName>RLP_Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP_Attachments__c/fields/PBS_AAAP_Title__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Title__c</fullName>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_PBS_AAAP_PublishRLPController.cls
@isTest
public with sharing class Test_PBS_AAAP_PublishRLPController {
	@isTest
    public static void getAttachmentsTesting(){
        Id RecTypeId = Schema.SObjectType.PBS_AAAP_RLP__c.getRecordTypeInfosByName().get('AAAP').getRecordTypeId();
        PBS_AAAP_RLP__c rlp1 = new PBS_AAAP_RLP__c();
        rlp1.PBS_AAAP_RLP_Number__c = '123456';
        rlp1.PBS_AAAP_Title__c = 'RLP TEST';
        rlp1.PBS_AAAP_Region__c = 'Region 2';
        rlp1.PBS_AAAP_Year__c = '2019';
        rlp1.PBS_AAAP_STATUS__c = 'Posted/Active';
        rlp1.PBS_AAAP_TELCOMM_DEFAULT__c = 10;
        rlp1.PBS_AAAP_PV_OTHER_UPFRONT_COSTS__c = 10;
        rlp1.PBS_AAAP_TIUSED_FOR_FIRM_TERM_NEW__c = 10;
        rlp1.PBS_AAAP_TIUSED_FOR_FIRM_TERM_SUCC__c = 10;
        rlp1.PBS_AAAP_MOVE_DEFAULT__c = 10;
        rlp1.PBS_AAAP_DEFAULT_MONTH_BEGIN__c = '1';
        rlp1.PBS_AAAP_DEFAULT_MONTH_END__c = '15';
        rlp1.RecordTypeId = RecTypeId;
        insert rlp1;
        
        PBS_AAAP_RLP_Attachments__c rlpatt1 = new PBS_AAAP_RLP_Attachments__c(PBS_AAAP_Title__c = 'Sample', PBS_AAAP_RLP__c = rlp1.id, PBS_AAAP_Attachment_Type__c = 'Standard');
        insert rlpatt1;
        
        List<PBS_AAAP_RLP_Attachments__c> attachments = PBS_AAAP_PublishRLPController.getAttachments(rlp1.Id);
        System.assertEquals(1, attachments.size(),'The size is not equals');
    }
}