force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/PBS_gBUILD_PBuildingScopeSystem__c.object-meta.xml
<CustomObject>
    <description>gBUILD PBuilding Scope System: Summary level information for a scope</description>
    <label>gBUILD Scope System</label>
    <nameField>
        <displayFormat>gbSs_{00000}</displayFormat>
        <label>PBSgBUILDSS</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Scope Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/fields/Rahd_ProjectBldgParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ProjectBldgParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</inlineHelpText>
    <label>RAHD_Project Building Parent ID</label>
    <referenceTo>PBS_gBUILD_ProjectBuilding__c</referenceTo>
    <relationshipLabel>gBUILD Scope Systems</relationshipLabel>
    <relationshipName>C_PBS_gBUILD_PBuildingScopeSystem_P_PBS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/recordTypes/Other_ChilledWaterHotH2OAndSteamDistSys.recordType-meta.xml
<RecordType>
    <fullName>Other_ChilledWaterHotH2OAndSteamDistSys</fullName>
    <active>true</active>
    <description>Other Category -&gt; Other Scope -&gt; Chilled Water/ Hot Water and Steam Distribution Systems</description>
    <label>Other Category -&gt; Other Scope -&gt; Chilled</label>
</RecordType>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/recordTypes/R_NewReplacement.recordType-meta.xml
<RecordType>
    <fullName>R_NewReplacement</fullName>
    <active>true</active>
    <description>Building Envelope  -&gt; Roof -&gt; New/Replacement</description>
    <label>Building Envelope  -&gt; Roof -&gt; New/Replac</label>
</RecordType>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystemDetail__c/PBS_gBUILD_PBuildingScopeSystemDetail__c.object-meta.xml
<CustomObject>
    <description>gBUILD PBuilding Scope Details: Detailed information for each scope system</description>
    <label>gBUILD Scope System Detail</label>
    <nameField>
        <displayFormat>gbSsd-{00000}</displayFormat>
        <label>PBSgBUILDSSD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Scope System Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystemDetail__c/fields/Rahd_ScopeSysParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ScopeSysParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_ScopeSystem</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_ScopeSystem</inlineHelpText>
    <label>RAHD_Scope System Parent ID</label>
    <referenceTo>PBS_gBUILD_PBuildingScopeSystem__c</referenceTo>
    <relationshipLabel>gBUILD Scope System Details</relationshipLabel>
    <relationshipName>C_PBS_gBUILD_PBuildingScopeSystemDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystemDetail__c/recordTypes/Other_ChilledWaterHotH2OAndSteamDistSys.recordType-meta.xml
<RecordType>
    <fullName>Other_ChilledWaterHotH2OAndSteamDistSys</fullName>
    <active>true</active>
    <description>Other Category -&gt; Other Scope -&gt; Chilled Water/ Hot Water and Steam Distribution Systems Details</description>
    <label>Other Category -&gt; Other Scope -&gt; Chilled</label>
</RecordType>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystemDetail__c/recordTypes/R_NewReplacement.recordType-meta.xml
<RecordType>
    <fullName>R_NewReplacement</fullName>
    <active>true</active>
    <description>Building Envelope  -&gt; Roof -&gt; New/Replacement</description>
    <label>Building Envelope  -&gt; Roof -&gt; New/Replac</label>
</RecordType>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPBS_gBUILD_PBuildingScopeSysContrl.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_PBuildingScopeSysContrl
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        PBS_gBUILD_PBuildingScopeSystem__c ss = new PBS_gBUILD_PBuildingScopeSystem__c(Rahd_ProjectBldgParentId__c=pb.id, RecordTypeId=TestPBS_gBUILD_Utility.getRecordTypeId('PBS_gBUILD_PBuildingScopeSystem__c', 'R_NewReplacement'));
        insert ss;
        PBS_gBUILD_PBuildingScopeSystemDetail__c ssd = new PBS_gBUILD_PBuildingScopeSystemDetail__c(Rahd_ScopeSysParentId__c=ss.id, RecordTypeId=TestPBS_gBUILD_Utility.getRecordTypeId('PBS_gBUILD_PBuildingScopeSystemDetail__c', 'Other_ChilledWaterHotH2OAndSteamDistSys'));
        insert ssd;

        test.startTest();
        
        PageReference pr = TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(pb.id);
        pr.getParameters().put(PBS_gBUILD_Utility.queryStringRecordTypeId, TestPBS_gBUILD_Utility.acScopeL3.Name);
        pr.getParameters().put(PBS_gBUILD_Utility.queryStringScopeSystemId, ss.id);
        Test.setCurrentPageReference(pr);

        PBS_gBUILD_PBuildingScopeSysController ctrl = new PBS_gBUILD_PBuildingScopeSysController();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assertEquals(pb.id, ctrl.scopeSystem.Rahd_ProjectBldgParentId__c);

        system.assertEquals(1, ctrl.systemInfos.size());

        system.assert(ctrl.newSystem()!=null);
        ctrl.paramSystemInfoId = ssd.id;
        system.assert(ctrl.openSystem()!=null);
        ctrl.deleteSystem();

        ctrl.cancel();
        ctrl.edit();
        ctrl.descope();
        ctrl.save();
        
        test.stopTest();
    }
}