force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/PBS_gBUILD_PBuildingScopeSystem__c.object-meta.xml
<CustomObject>
    <description>gBUILD PBuilding Scope System: Summary level information for a scope</description>
    <label>gBUILD Scope System</label>
    <nameField>
        <displayFormat>gbSs_{00000}</displayFormat>
        <label>PBSgBUILDSS</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Scope Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/fields/Rahd_ProjectBldgParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ProjectBldgParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_ProjectBuilding</inlineHelpText>
    <label>RAHD_Project Building Parent ID</label>
    <referenceTo>PBS_gBUILD_ProjectBuilding__c</referenceTo>
    <relationshipLabel>gBUILD Scope Systems</relationshipLabel>
    <relationshipName>C_PBS_gBUILD_PBuildingScopeSystem_P_PBS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_PBuildingScopeSystem__c/recordTypes/R_NewReplacement.recordType-meta.xml
<RecordType>
    <fullName>R_NewReplacement</fullName>
    <active>true</active>
    <description>Building Envelope  -&gt; Roof -&gt; New/Replacement</description>
    <label>Building Envelope  -&gt; Roof -&gt; New/Replac</label>
</RecordType>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestPBS_gBUILD_PBuildingScopeDetCntr.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_PBuildingScopeDetCntr
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        PBS_gBUILD_PBuildingScopeSystem__c ss = new PBS_gBUILD_PBuildingScopeSystem__c(Rahd_ProjectBldgParentId__c=pb.id, RecordTypeId=TestPBS_gBUILD_Utility.getRecordTypeId('PBS_gBUILD_PBuildingScopeSystem__c', 'R_NewReplacement'));
        insert ss;

        List<Cookie> cookies = TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(pb.id).getCookies().values();
        PageReference pr;
        PBS_gBUILD_PBuildingScopeDetController ctrl;

        test.startTest();

        pr = PBS_gBUILD_Utility.getScopeSystemDetailsPageRef(ss.id, '', 'R_NewReplacement', true);
        pr.setCookies(cookies);
        Test.setCurrentPageReference(pr);
        ctrl = new PBS_gBUILD_PBuildingScopeDetController();
        ctrl.edit();
        ctrl.cancel();

        pr = PBS_gBUILD_Utility.getScopeSystemDetailsPageRef(ss.id, '', 'R_NewReplacement', true);
        pr.setCookies(cookies);
        Test.setCurrentPageReference(pr);
        ctrl = new PBS_gBUILD_PBuildingScopeDetController();
        system.assert(ctrl!=null);
        system.assert(ctrl.ssd!=null);
        system.assertEquals(null, ctrl.ssd.id);
        system.assert(ctrl.ssd.Rahd_ScopeSysParentId__c!=null);
        system.assert(ctrl.projectId!=null);
        system.assert(ctrl.pbuildingId!=null);
        ctrl.saveAndNew();
        system.assert(ctrl.ssd.id!=null);

        pr = PBS_gBUILD_Utility.getScopeSystemDetailsPageRef(ss.id, ctrl.ssd.id, 'R_NewReplacement', true);
        pr.setCookies(cookies);
        Test.setCurrentPageReference(pr);
        ctrl = new PBS_gBUILD_PBuildingScopeDetController();
        system.assert(ctrl.ssd.id!=null);
        ctrl.save();
       
        test.stopTest();
    }
}