force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>This is the standard account record type.</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/PBS_AAAP_Company__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Company__c</fullName>
    <label>Company</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_PIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PIN__c</fullName>
    <inlineHelpText>PIN is used for added security while submitting the Offer.</inlineHelpText>
    <label>PIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_StatesOfInterest__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_StatesOfInterest__c</fullName>
    <description>This is a multi-select list that allows the user to select all of the states in which the offerer is interested in creating offers.</description>
    <inlineHelpText>You may select multiple states in which you have an interest of creating offers.</inlineHelpText>
    <label>States Of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District Of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>Virginia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>By clicking the checkbox, you agree to the terms in the Content to Use Information and the Online Terms and Conditions documents.</description>
    <label>Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/GSA.recordType-meta.xml
<RecordType>
    <fullName>GSA</fullName>
    <active>true</active>
    <description>This contact record is used to track information for GSA employees.</description>
    <label>GSA</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/PBS_AAAP_RLP_Regions_Map__c.object-meta.xml
<CustomObject>
    <label>RLP Regions Map</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>RLP Regions Map Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLP Regions Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/fields/PBS_AAAP_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region_Name__c</fullName>
    <label>RLP Region Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/fields/PBS_AAAP_RLP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_State__c</fullName>
    <label>RLP State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/fields/PBS_AAAP_RLP_State_Abbrevation__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_State_Abbrevation__c</fullName>
    <label>RLP State Abbrevation</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PBS_AAAP_PIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PIN__c</fullName>
    <label>PIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PBS_AAAP_StatesOfInterest__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_StatesOfInterest__c</fullName>
    <description>This is a multi-select list that allows the user to select all of the states in which the offerer is interested in creating offers.</description>
    <inlineHelpText>You may select multiple states in which you have an interest of creating offers.</inlineHelpText>
    <label>States Of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District Of Columbia</fullName>
                <label>District of Columbia</label>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>Virginia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_SiteRegisterController.cls
@isTest(SeeAllData=false)
private class Test_SiteRegisterController {

    
    static testMethod void createCustomerPortalUserTest() {  

         SiteRegisterController cpTest = new SiteRegisterController();  

        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles();  
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id; 
        
        
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        
        cpTest.c = new Contact(firstName='TestFirstName', lastName='TestLastName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = false, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');  
        cpTest.actionChkTermsAndConds();
        cpTest.c = new Contact(firstName='TestFirstName', lastName='TestLastName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');
         
        Test.startTest();  
        insert rlps1;
        insert rlps;
        System.assert(rlps1.id!= null);
        PageReference testPageRef= cpTest.createPortaluser();
        System.assert(testPageRef== null); 
        
        Test.stopTest();  

        PageReference testPageRef2 = cpTest.reset();  
     
     }  

     static testMethod void createCustomerPortalUserCreateTestError() {  

         SiteRegisterController cpTest = new SiteRegisterController();  

        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles(); 
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id; 
        
        cpTest.c = new Contact(firstName='TestFirstName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;New York;');
         
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        PBS_AAAP_RLP_Regions_Map__c rlps2 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 2', PBS_AAAP_RLP_State_Abbrevation__c='NY', PBS_AAAP_RLP_State__c='New York');
                  

        Test.startTest(); 
        insert rlps1;
        System.assert(rlps1.id!= null);
        insert rlps;
        insert rlps2;
        PageReference testPageRef= cpTest.createPortaluser();
        System.assert(testPageRef== null);
        Test.stopTest();  

        PageReference testPageRef2 = cpTest.reset();  
         
     }
     
     static testMethod void createCustomerPortalUserError() {  

        SiteRegisterController cpTest = new SiteRegisterController();  

        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles(); 
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id;
        User u = new User(firstname='firstname', lastname='testlastname', alias='testa', email='test@testorg.com', emailencodingkey='UTF-8',        
                            languagelocalekey='en_US', localesidkey='en_US', profileid = profile.id, timezonesidkey='America/Los_Angeles', 
                            username='test@testorg.com', street='123 street', city='Vienna', state='Virginia', country='USA', postalcode='22102',
                            phone='202-202-2202', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');
                             
        cpTest.c = new Contact(firstName='TestFirstName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;New York;');
                
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        
        Test.startTest(); 
        insert rlps1;
        System.assert(rlps1.id!= null);
        insert rlps;
        PageReference testPageRef= cpTest.createPortaluser();
        System.assert(testPageRef== null);
        Test.stopTest();  

        PageReference testPageRef2 = cpTest.reset();  
         
     }      
     
     static testMethod void validate_UserExist() {  
 
        Account portalAccount1 = new Account(Name = 'TestAccount');
        Database.insert(portalAccount1);

        //Create contact
        Contact contact1 = new Contact(
                                FirstName = 'Test',
                                Lastname = 'McTesty',
                                AccountId = portalAccount1.Id,
                                Email = System.now().millisecond() + 'test@test.com'
                                );
        Database.insert(contact1);
        
        // create user
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%GSA RET Community Plus Login User%' limit 1];
        User user1 = new User(
                            Username = contact1.Email,
                            ContactId = contact1.Id,
                            ProfileId = profile.Id,
                            Alias = 'test123',
                            Email = 'test12345@test.com',
                            EmailEncodingKey = 'UTF-8',
                            LastName = 'McTesty',
                            CommunityNickname = 'test12345',
                            TimeZoneSidKey = 'America/Los_Angeles',
                            LocaleSidKey = 'en_US',
                            LanguageLocaleKey = 'en_US'
                            );
                            Database.insert(user1);
                
        SiteRegisterController cpTest = new SiteRegisterController();  
        cpTest.c = contact1;
        cpTest.createPortaluser();
        ApexPages.currentPage().getHeaders().put('referer','RSAP');
        cpTest.getReferer();
        ApexPages.currentPage().getHeaders().put('referer','SF');
        cpTest.getReferer();
        System.assert(true);
     }
    //@isTest(SeeAllData=true); 

    static testMethod void createCustomerPortalUserTest1() {  

        SiteRegisterController cpTest = new SiteRegisterController();

        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles();  
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id; 
        
        
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        
        cpTest.c = new Contact(firstName='TestFirstName', lastName='TestLastName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = false, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');  
        cpTest.actionChkTermsAndConds();
        cpTest.c = new Contact(firstName='TestFirstName', lastName='TestLastName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');
         
        Test.startTest();  
        insert rlps1;
        insert rlps;
        System.assert(rlps1.Id != null);
		Test.setMock(HttpCalloutMock.class, new reCAPTCHACalloutMockImpl());     
		System.currentPageReference().getParameters().put('g-recaptcha-response', 'testGoogleResponse');        
        PageReference testPageRef= cpTest.createPortaluser(); 
        Test.stopTest();  

        PageReference testPageRef2 = cpTest.reset();  

     }  

     static testMethod void createCustomerPortalUserCreateTestError1() {  
        Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Id customRecTypeId = recordTypes.get('AAAP Portal').getRecordTypeId();
        
        Account a = new Account(Name=PBS_AAAP_GlobalConstants.CUSTOMER_PORTAL_ACCOUNT_NAME, RecordTypeId=customRecTypeId);
        insert a;

        SiteRegisterController cpTest = new SiteRegisterController();
         
        SiteRegisterController.selectRegions('Virginia;Maryland;District of Columbia');

        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles(); 
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id; 
        
        cpTest.c = new Contact(firstName='TestFirstName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;New York;');
         
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        PBS_AAAP_RLP_Regions_Map__c rlps2 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 2', PBS_AAAP_RLP_State_Abbrevation__c='NY', PBS_AAAP_RLP_State__c='New York');
                  

        Test.startTest(); 
        insert rlps1;
        insert rlps;
        insert rlps2;
        System.assert(rlps1.Id != null);
		Test.setMock(HttpCalloutMock.class, new reCAPTCHACalloutMockImpl());     
		System.currentPageReference().getParameters().put('g-recaptcha-response', 'testGoogleResponse');        
        PageReference testPageRef= cpTest.createPortaluser();
        
        System.assert(testPageRef == null);
        Test.stopTest();  

        PageReference testPageRef2 = cpTest.reset();  
        
     }
     
     static testMethod void createCustomerPortalUserError1() {  
        Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Id customRecTypeId = recordTypes.get('AAAP Portal').getRecordTypeId();
        
        Account a = new Account(Name=PBS_AAAP_GlobalConstants.CUSTOMER_PORTAL_ACCOUNT_NAME, RecordTypeId=customRecTypeId);
        insert a;
        
        SiteRegisterController cpTest = new SiteRegisterController();  

        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles(); 
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id;
        User u = new User(firstname='firstname', lastname='testlastname', alias='testa', email='sguni@acumensolutions.com', emailencodingkey='UTF-8',       
                            languagelocalekey='en_US', localesidkey='en_US', profileid = profile.id, timezonesidkey='America/Los_Angeles', 
                            username='sguni@acumensolutions.com', street='123 street', city='Vienna', state='Virginia', country='USA', postalcode='22102',
                            phone='202-202-2202', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');
        User u1 = new User(firstname='firstname', lastname='testlastname', alias='testa', email='sguni@acumensolutions.com', emailencodingkey='UTF-8',      
                            languagelocalekey='en_US', localesidkey='en_US', profileid = profile.id, timezonesidkey='America/Los_Angeles', 
                            username='sguni@acumensolutions.com', street='123 street', city='Vienna', state='Virginia', country='USA', postalcode='22102',
                            phone='202-202-2202', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');
           
        cpTest.c = new Contact(firstName='TestFirstName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;New York;');
                
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        
        Test.startTest(); 
        insert rlps1;
        System.assert(rlps1.id != null);
        insert rlps;
		Test.setMock(HttpCalloutMock.class, new reCAPTCHACalloutMockImpl());     
		System.currentPageReference().getParameters().put('g-recaptcha-response', 'testGoogleResponse');        
        PageReference testPageRef= cpTest.createPortaluser();
        System.assert(testPageRef == null);
        Test.stopTest();  

        PageReference testPageRef2 = cpTest.reset();  
         
     }   
  
     static testMethod void createCustomerPortalUserTest2() {  
        Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Id customRecTypeId = recordTypes.get('AAAP Portal').getRecordTypeId();
        
        Account a = new Account(Name=PBS_AAAP_GlobalConstants.CUSTOMER_PORTAL_ACCOUNT_NAME, RecordTypeId=customRecTypeId);
        insert a;
        
        Contact con = new Contact(firstName='RETFirstNameContact', lastName='RETLastNameContact', email='test@testorg.com', accountId=a.Id); 
        insert con;
        
        Profile p = [Select p.name, p.id From Profile p where p.Name like '%GSA RET Community Plus Login User%' limit 1];
        
        User usr = new User(FirstName='RETFirstNameContact',LastName='RETLastNameContact', alias='rretl', email='test@testorg.com', 
                            username='test@testorg.com',emailencodingkey='UTF-8',       
                            languagelocalekey='en_US', localesidkey='en_US', profileid = p.id, timezonesidkey='America/Los_Angeles',contactId=con.Id);
                            
        insert usr;
                                
        SiteRegisterController cpTest = new SiteRegisterController();  
        List<SelectOption> profileOptions = cpTest.getCustomerPortalProfiles();  
        Profile profile = [Select p.name, p.id From Profile p where p.Name like '%AAAP Customer Portal%' limit 1];
        cpTest.selectedProfileId = profile.id; 
        
        
        PBS_AAAP_RLP_Regions_Map__c rlps = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='VA', PBS_AAAP_RLP_State__c='Virginia');
        PBS_AAAP_RLP_Regions_Map__c rlps1 = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c='Region 3', PBS_AAAP_RLP_State_Abbrevation__c='MD', PBS_AAAP_RLP_State__c='Maryland');
        
        cpTest.c = new Contact(firstName='TestFirstName', lastName='TestLastName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = false, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');  

        
        PageReference pageRef = Page.PBS_AAAP_UserRegistration;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('confirmTempEmail', 'test@testorg.com');
	    cpTest.confirmTempEmail = 'test@testorg.com';
                
        cpTest.actionChkTermsAndConds();
        cpTest.c = new Contact(firstName='TestFirstName', lastName='TestLastName', email='test@testorg.com', PBS_AAAP_Terms_and_Conditions__c = true, PBS_AAAP_Company__c = 'Acumen',
                                MailingStreet = '1660 International Drive', MailingCity = 'McLean', MailingState = 'VA', MailingCountry='USA', MailingPostalCode = '22102',
                                Phone='202-202-2022', PBS_AAAP_PIN__c='123456', PBS_AAAP_StatesOfInterest__c='Virginia;Maryland;');
         
        Test.startTest();  
        insert rlps1;
        insert rlps;
        System.assert(rlps1.Id != null);
        
		Test.setMock(HttpCalloutMock.class, new reCAPTCHACalloutMockImpl());     
		System.currentPageReference().getParameters().put('g-recaptcha-response', 'testGoogleResponse');
        PageReference testPageRef= cpTest.createPortaluser(); 
        Test.stopTest();  
        
        PageReference testPageRef2 = cpTest.reset();  
        
        SiteRegisterController.createUser(null, 'abcGmail.com',  'fname', 'lName', 'userName@username.com', 'Phone', 'street', 'state', 'pin', 'city', 'country',  'zip',  'company',  'sofi',  'sofreg',  'altPhone', null, 'Mr.');
        
        Account accUser = new Account();
        accUser.Name = 'User Name';
        insert accUser;
        
        Contact conUser = new Contact();
        conUser.LastName = 'TestConhere';
        conUser.accountId = accUser.Id;
        insert conUser;
        
         User u = new User(
         ProfileId = [Select name, id From Profile where Name like '%GSA RET Community Plus Login User%' limit 1].Id,
         LastName = 'last',
         Email = 'puser000@amamama.com',
         Username = 'puser000@amamama.com007_',
         CompanyName = 'TEST',
         Title = 'title',
         Alias = 'alias',
         TimeZoneSidKey = 'America/Los_Angeles',
         EmailEncodingKey = 'UTF-8',
         LanguageLocaleKey = 'en_US',
         LocaleSidKey = 'en_US',
         ContactId = conUser.Id
        );
        insert u;
        
        cpTest.conf1 = true;
        cpTest.conf2 = true;
        cpTest.regions = null;
        
        system.runAs(u){

            PermissionSet[] permSet = [Select name, id FROm PermissionSet where Name like '%AAAP_User%' limit 1];
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = permSet[0].Id, AssigneeId = UserInfo.getUserId());
            insert psa;
            SiteRegisterController.assignPermissionSet(UserInfo.getUserId());
            
            Contact con1 =  new Contact();
            con1.email = 'puser000@amamama.com007_';            
            cpTest.c = con1;
            Test.setMock(HttpCalloutMock.class, new reCAPTCHACalloutMockImpl());     
            System.currentPageReference().getParameters().put('g-recaptcha-response', 'testGoogleResponse');           
            cpTest.createPortaluser();
        }
        
     } 
    
}