force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>This is the standard account record type.</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_Agency_Requirement__c/PBS_AAAP_Agency_Requirement__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object store all information related to an Agency requirement in AAAP</description>
    <label>Agency Requirement</label>
    <nameField>
        <label>Agency Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Agency_Requirement__c/fields/PBS_AAAP_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Requirements</relationshipLabel>
    <relationshipName>Agency_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer</relationshipLabel>
    <relationshipName>Offer_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/PBS_AAAP_Offer_Select_Award_Info__c.object-meta.xml
<CustomObject>
    <description>This is the Offer_Select_Award_Info table in the source AAAP system.</description>
    <label>Offer Select Award Info</label>
    <nameField>
        <displayFormat>OSAI-{00000000}</displayFormat>
        <label>Offer Select Award Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Select Award Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_AGENCY_REQUIREMENT_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_AGENCY_REQUIREMENT_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Requirement ID</label>
    <referenceTo>PBS_AAAP_Agency_Requirement__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer ID</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <label>Offer Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_Space_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Space_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Space</label>
    <referenceTo>PBS_AAAP_Space__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Space__c/PBS_AAAP_Space__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores information on the spaces related to a AAAP Offer</description>
    <label>Space</label>
    <nameField>
        <displayFormat>Space-{000000000}</displayFormat>
        <label>Space Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Space__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <description>The offer number with which the space will be associated.</description>
    <inlineHelpText>Offer Number</inlineHelpText>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Spaces</relationshipLabel>
    <relationshipName>Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_PBS_AAAP_OfferSelectAwardInfo_Contr.cls
@IsTest
private class Test_PBS_AAAP_OfferSelectAwardInfo_Contr {


    public static testMethod void constructorTest() {
        PBS_AAAP_OfferSelectAwardInfo_Contr aphc = new PBS_AAAP_OfferSelectAwardInfo_Contr();
        System.assert(aphc != null);
    }

    public static testMethod void getAphListTest() {
        PBS_AAAP_OfferSelectAwardInfo_Contr aphc = new PBS_AAAP_OfferSelectAwardInfo_Contr();
        PBS_AAAP_Offer_Select_Award_Info__c[] aph = [SELECT a.PBS_AAAP_AGENCY_REQUIREMENT_ID__c FROM PBS_AAAP_Offer_Select_Award_Info__c a LIMIT 1];
        List<PBS_AAAP_Offer_Select_Award_Info__c> aphList = new List<PBS_AAAP_Offer_Select_Award_Info__c>();

        // Test getting an empty list of PBS_AAAP_Offer_Select_Award_Info__c objects
        aphList = aphc.aphList;
        System.assert(aphList != null);

        // Test getting a populated list of PBS_AAAP_Offer_Select_Award_Info__c objects
        if (aph != null && !aph.isEmpty()) {
            aphc.targetObjId = aph[0].Id;
            aphList = aphc.aphList;
        }
    }

    public static testMethod void actionDeselectOfferTest() {
        test.startTest();
        PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
        insert offer;
        PBS_AAAP_Space__c space = PBS_AAAP_UtilityTest.createSpace();
        space.PBS_AAAP_OFFER_NUMBER__c = offer.Id;
        insert space;
        RecordType rec = [SELECT r.Id, r.Name, r.SobjectType FROM RecordType r WHERE SobjectType = 'Account' LIMIT 1];
        Account acc = new Account(RecordTypeId = rec.Id, Name = 'Sample Account');
        insert acc;
        PBS_AAAP_Agency_Requirement__c agency = PBS_AAAP_UtilityTest.createAgencyRequirement();

        agency.PBS_AAAP_Account_Name__c = acc.Id;
        insert agency;
        System.assert(agency.id != null);
        PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        osai.PBS_AAAP_Offer_ID__c = offer.Id;
        osai.PBS_AAAP_Space_ID__c = space.Id;
        osai.PBS_AAAP_AGENCY_REQUIREMENT_ID__c = agency.Id;
        insert osai;


        PBS_AAAP_OfferSelectAwardInfo_Contr aphc = new PBS_AAAP_OfferSelectAwardInfo_Contr();
        aphc.selectedOfferId = offer.Id;
        aphc.selectedSpaceId = space.Id;
        aphc.agencyRequirementId = agency.Id;
        PageReference pref = aphc.actionDeSelectOfferSpace();

        System.assertNotEquals(pref, null);

        aphc.offerSelectAwardID = osai.Id;

        pref = aphc.actionShowOfferSelectAwardInfo();
        System.assertNotEquals(pref, null);

        pref = aphc.actionAwardOfferSpace();
        System.assertNotEquals(pref, null);

        aphc.prepareDocument();
        test.stopTest();
    }
    
    
}