force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>This is the standard account record type.</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APIMuleHelperTest.cls
@IsTest public with sharing class APIMuleHelperTest {

    @IsTest(SeeAllData=true) public static void testBasicAuth() {
        APIMuleHelper.APIAttributes attrs = APIMuleHelper.populateAPIAttributes('For_Test_Class_BasicAuth');
        System.assertEquals(true, true);
    }

    @IsTest(SeeAllData=true) public static void testSSOAuth() {
        APIMuleHelper.APIAttributes attrs = APIMuleHelper.populateAPIAttributes('For_Test_Class_SSOAuth');
        System.assertEquals(true, true);
    }

    @isTest static void PositiveTest(){
        
        Account retb = new Account(Name = 'Real Estate Tax Bucket');
        insert retb;
        //Create Lease Record
        PBS_Lease__c leaseRec = new PBS_Lease__c(Name='Test Lease', Lease_Number__c='1234', Lease_Effective_Date__c=date.today());
        Insert leaseRec;
        //Create Lease Access Record
        PBS_Lease_Access__c leaseAccessRec = new PBS_Lease_Access__c(PBS_Lease__c=leaseRec.Id, Requestor__c=UserInfo.getUserId(), Status__c='Approved');
        Insert leaseAccessRec;
        
        test.startTest();
            test.setMock(HttpCalloutMock.class, new GoodMock());
            //List <RET_LeaseDetailsController.LeaseDetails> details = RET_LeaseDetailsController.getLeaseDetails(leaseRec.Id);
            List <APIMuleHelperMockConsumer.LeaseDetails> details = APIMuleHelperMockConsumer.getLeaseDetails(leaseRec.Id);
            System.assertEquals(details[0].LeaseNumber, '1234');
        test.stopTest();
        
    }
    
    @isTest static void testSendIntegrationErrorEmail(){
        test.startTest();
            APIMuleHelper.sendIntegrationErrorEmail(APIMuleHelper.populateAPIAttributes('For_Test_Class_BasicAuth'), 'This is my Error');
            System.assertEquals(true, true);
        test.stopTest();
    }
    
    private class GoodMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"totalSize": 1, "pageSize": 1, "success": "true", "status": 200, "records": [ { "CurrentAnnualRent": 456009.16, "ExpirationNotificationMonths": 18, "LeaseEffectiveDate": "2011-02-01T00:00:00", "LeaseExpirationDate": "2021-01-31T00:00:00", "LeaseId": 15899, "LEASE_NUM": "1234", "LeaseRSF": 27693, "LeaseStatusCode": "AC", "TeamCode": "5401" } ]}');
            return res;
        }
    }  
    
}