force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>This is the standard account record type.</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/NCMT_Core_Shell_Cost_Detail__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>Core Shell Cost Detail</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Core Shell Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Shell Cost Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/fields/Core_Shell_Cost_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Core_Shell_Cost_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Core Shell Cost Parameter</label>
    <referenceTo>NCMT_Core_Shell_Cost_Parameter__c</referenceTo>
    <relationshipLabel>Core Shell Cost Detail</relationshipLabel>
    <relationshipName>Core_Shell_Cost_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/fields/Project_Cost_Summary__c.field-meta.xml
<CustomField>
    <fullName>Project_Cost_Summary__c</fullName>
    <label>Project Cost Summary</label>
    <referenceTo>NCMT_Project_Cost_Summary__c</referenceTo>
    <relationshipLabel>Core Shell Cost Detail</relationshipLabel>
    <relationshipName>Core_Shell_Cost_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/fields/Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Cost__c</fullName>
    <formula>IF( Core_Shell_Cost_Parameter__r.Duplicate_Maintenance_Related__c = true,( Unit_Cost__c * Total_Units__c * Core_Shell_Cost_Parameter__r.PCT__c * 100 * Project_Cost_Summary__r.Project_Name__r.Core_Shell_Adjustment_Factor__c) ,(Total_Cost__c *  Core_Shell_Cost_Parameter__r.PCT__c * Project_Cost_Summary__r.Project_Name__r.Core_Shell_Adjustment_Factor__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/fields/Replacement_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Frequency__c</fullName>
    <formula>Core_Shell_Cost_Parameter__r.Period__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Replacement Frequency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/NCMT_Core_Shell_Cost_Parameter__c.object-meta.xml
<CustomObject>
    <description>NCMT Core Shell Cost Parameters</description>
    <label>Core Shell Cost Parameter</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Core Shell Cost Parameters</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Shell Cost Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Type1__c.field-meta.xml
<CustomField>
    <fullName>Type1__c</fullName>
    <label>Type1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Cost</fullName>
            </value>
            <value>
                <fullName>Operation</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Retro-Commissioning</fullName>
            </value>
            <value>
                <fullName>Major Repair</fullName>
            </value>
            <value>
                <fullName>System Replacement</fullName>
            </value>
            <value>
                <fullName>Residual Cost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/NCMT_Other_Cost__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>NCMT Other Cost</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Other Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Other Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/Frequency_Years__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Years__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Frequency (Years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Other_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/Total1__c.field-meta.xml
<CustomField>
    <fullName>Total1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/recordTypes/Other_Capital_Renewal_Cost.recordType-meta.xml
<RecordType>
    <fullName>Other_Capital_Renewal_Cost</fullName>
    <active>true</active>
    <description>For TCO - User Option</description>
    <label>Other Capital Renewal Cost</label>
</RecordType>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Start_Construction__c.field-meta.xml
<CustomField>
    <fullName>Start_Construction__c</fullName>
    <description>Start Construction Date</description>
    <label>Start Construction</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/NCMT_Project_Cost_Summary__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>Project Cost Summary</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Cost Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Cost Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>Project Cost Summary</relationshipLabel>
    <relationshipName>Project_Cost_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_LCC__c/NCMT_TCO_LCC__c.object-meta.xml
<CustomObject>
    <label>NCMT TCO LCC</label>
    <nameField>
        <displayFormat>LCC-{000000}</displayFormat>
        <label>NCMT TCO LCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT TCO LCCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TCO_LCC__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT TCO LCCs</relationshipLabel>
    <relationshipName>NCMT_TCO_LCCs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_LCC__c/fields/Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Cost__c</fullName>
    <label>Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/NCMT_TCO_Lifecycle_Input__c.object-meta.xml
<CustomObject>
    <label>NCMT TCO Lifecycle Input</label>
    <nameField>
        <displayFormat>Lifecycle-{00000}</displayFormat>
        <label>TCO Lifecycle Input Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT TCO Lifecycle Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Construction__c.field-meta.xml
<CustomField>
    <fullName>Construction__c</fullName>
    <label>Construction/Move in (months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <label>Design (months)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/End_Major_Maint_System_Replace_Early__c.field-meta.xml
<CustomField>
    <fullName>End_Major_Maint_System_Replace_Early__c</fullName>
    <inlineHelpText>Number of years to be subtracted from the End of Maintenance &amp; Operations date for applying periodic Core Shell Cost Details where the related Core Shell Cost Parameter Type1 field equals &quot;Maintenance&quot;.</inlineHelpText>
    <label>(deprecated) End Major Maint &amp; Replace</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/End_Routine_Periodic_Maintenance_Early__c.field-meta.xml
<CustomField>
    <fullName>End_Routine_Periodic_Maintenance_Early__c</fullName>
    <inlineHelpText>Number of years to be subtracted from the End of Maintenance &amp; Operations date for applying periodic Core Shell Cost Details where the related Core Shell Cost Parameter Type1 field equals &quot;Major Repair&quot;.</inlineHelpText>
    <label>(deprecated) End Routine Periodic Maint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Include_Tenant_Refresh_Costs__c.field-meta.xml
<CustomField>
    <fullName>Include_Tenant_Refresh_Costs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Tenant Refresh Costs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>TCO_Lifecycle_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/New_fit_out_every_years__c.field-meta.xml
<CustomField>
    <fullName>New_fit_out_every_years__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New fit-out every (years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Number_of_Years_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_of_Operation__c</fullName>
    <label>Number of Years of Operation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Period_of_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Period_of_Analysis__c</fullName>
    <label>Period of Analysis (years)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Planning_and_Pre_design__c.field-meta.xml
<CustomField>
    <fullName>Planning_and_Pre_design__c</fullName>
    <label>Planning and Pre-design (months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/Refresh_every_years__c.field-meta.xml
<CustomField>
    <fullName>Refresh_every_years__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Refresh every (years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NCMT_TCO_Lifecycle_Input_Trigger_Test.cls
@isTest
public class NCMT_TCO_Lifecycle_Input_Trigger_Test {
    @testSetup static void setup()
    {
       

        NCMT_TestTCOProjectClass.CreateTCOProject('testProjCodeCovTCOOff1','Virginia','State Average'
            ,'Lowrise (2 - 3 stories)', true, false, false, 1000000, true, false, false, false, false);
       
    }

    static testMethod void test_Triggs()
    {
        NCMT_Project__c proj = [SELECT Id, Name FROM NCMT_Project__c LIMIT 1];
        Id otherRenewalRT = [Select Id from RecordType where DeveloperName = 'Other_Capital_Renewal_Cost'][0].Id;
        
        
        Test.startTest();
        
        
        NCMT_TCO_Lifecycle_Input__c lifecycle = new NCMT_TCO_Lifecycle_Input__c(
            NCMT_Project__c = proj.Id,
            Include_Tenant_Refresh_Costs__c = true,
            New_fit_out_every_years__c = 7,
            Refresh_every_years__c = 7,
            Period_of_Analysis__c = 35,
            Planning_and_Pre_design__c = 6,
            Design__c = 6, 
            Construction__c = 12,
            End_Routine_Periodic_Maintenance_Early__c = 1,
            End_Major_Maint_System_Replace_Early__c = 3,
            Number_of_Years_of_Operation__c = 35
        );
        insert lifecycle;

        //Does full LCC grouping and calculation
        NCMT_TCO_Project tco = new NCMT_TCO_Project(proj.Id, true);
        System.assertEquals(35, tco.lccs.size());

        NCMT_TCO_Lifecycle_Input_TriggerHandler.triggerHandlerUpdate = false;
        
        //Core Shell trigger...
        for (NCMT_Core_Shell_Cost_Detail__c c : [Select Id, Project_Cost_Summary__r.Project_Name__c,
                    Replacement_Cost__c, Replacement_Frequency__c, Core_Shell_Cost_Parameter__r.Type1__c
                    from NCMT_Core_Shell_Cost_Detail__c 
                    where Project_Cost_Summary__r.Project_Name__c =: proj.Id AND Replacement_Cost__c > 0
                    LIMIT 1]
        ){
            update c;
        }
        
        //Project trigger
        NCMT_TCO_Lifecycle_Input_TriggerHandler.triggerHandlerUpdate = false;
        proj.Start_Construction__c = System.today().addMonths(-12);
        update proj;

        NCMT_Other_Cost__c otherCost = new NCMT_Other_Cost__c(
            RecordTypeId = otherRenewalRT,
            Frequency_Years__c = 6, 
            Total1__c = 100000,
            NCMT_Project__c = proj.Id
        );
        NCMT_TCO_Lifecycle_Input_TriggerHandler.triggerHandlerUpdate = false;
        insert otherCost;

        Test.stopTest();

        
        NCMT_TCO_Lifecycle_Input_TriggerHandler.triggerHandlerUpdate = false;
        lifecycle.Period_of_Analysis__c = 40;
        update lifecycle;

        System.assertEquals(40, [Select Id from NCMT_TCO_LCC__c].size());
        
    }

    static testMethod void testClone(){
        Account acc = new Account(Name = 'Platy IT');
        insert acc;
        Contact c  = new Contact(FirstName = 'Jessie', LastName = 'Grenfell', AccountId = acc.Id);
        insert c;
        NCMT_Utilities.cloneMe('Account', acc.Id, new Set<String>{'Contact'}, true);
        
        System.assertEquals(2, [Select Id from Contact].size());
    }
}