force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>This is the standard account record type.</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <formula>PBS_Lease__r.Lease_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <formula>PBS_Lease__r.Lease_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated lease for real estate tax submissions.</description>
    <inlineHelpText>Associated lease for real estate tax submissions.</inlineHelpText>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/GSA.recordType-meta.xml
<RecordType>
    <fullName>GSA</fullName>
    <active>true</active>
    <description>This contact record is used to track information for GSA employees.</description>
    <label>GSA</label>
</RecordType>

force-app/main/default/objects/PBS_Lease__c/PBS_Lease__c.object-meta.xml
<CustomObject>
    <description>PBS Common Lease Object</description>
    <label>PBS Lease</label>
    <nameField>
        <label>PBS Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Effective_Date__c</fullName>
    <label>Lease Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Expiration_Date__c</fullName>
    <label>Lease Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/Lease_Number__c.field-meta.xml
<CustomField>
    <fullName>Lease_Number__c</fullName>
    <label>Lease Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/LSR_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>LSR_Contact_Email__c</fullName>
    <label>LSR Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PBS_Lease__c/fields/LSR_Email_Text__c.field-meta.xml
<CustomField>
    <fullName>LSR_Email_Text__c</fullName>
    <description>Rexus use this field to save the poc email address and in before trigger, we have to validate this value and populate it to &apos;LSR Contact Email&apos; field which will be used to searching poc user.</description>
    <label>LSR Email Text</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/PBS_Lease_Access__c.object-meta.xml
<CustomObject>
    <label>PBS Lease Access</label>
    <nameField>
        <displayFormat>LA-{00000}</displayFormat>
        <label>PBS Lease Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Lease Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Lease_Access__c/fields/PBS_Lease__c.field-meta.xml
<CustomField>
    <fullName>PBS_Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBS Lease</label>
    <referenceTo>PBS_Lease__c</referenceTo>
    <relationshipLabel>PBS Lease Access</relationshipLabel>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PBS_Lease_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Lease_Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RET_LeaseShareUtilityTest.cls
@isTest
public class RET_LeaseShareUtilityTest {
    @testsetup static void createData(){
        //Create RET users
        
        Account ac = new Account(name ='Real Estate Tax Bucket') ;
        insert ac; 
        Id retProfileId = [select Id, name from Profile where Name = :RET_LeaseShareUtility.RET_CCP_Profile limit 1].Id;
        Id systemUserProfileId = [select Id, name from Profile where Name Like 'GSA System Administrator%' limit 1].Id;
        
        Contact con = new Contact(FirstName='TestRETFName', LastName='TestRETLName', Email='retUserTestEmail420@test.org',AccountId = ac.Id);
        insert con;  
        User castIronUser = new User(Alias = 'csirn', Email='castIronUserTestEmail@test.org',
                                     emailencodingkey='UTF-8', FirstName='Cast', LastName='IronPrd', languagelocalekey='en_US',
                                     localesidkey='en_US', profileid = systemUserProfileId, country='United States',IsActive =true,
                                     timezonesidkey='America/Los_Angeles', username='castIronUserTestEmail@test.org');
        
        insert castIronUser;
        system.runAs(castIronUser){
            User user = new User(Alias = 'rlfna', Email='retUserTestEmail420@test.org',
                                 emailencodingkey='UTF-8', FirstName='TestRETFName', LastName='TestRETLName', languagelocalekey='en_US',
                                 localesidkey='en_US', profileid = retProfileId, country='United States',IsActive =true,
                                 ContactId = con.Id,
                                 timezonesidkey='America/Los_Angeles', username='retUserTestEmail420@test.org');
            
            insert user;
            
            
            PBS_Lease__c newPBS = new PBS_Lease__c(Lease_Number__c='98462383', Name ='98462383Test', Lease_Effective_Date__c = date.today(), Lease_Expiration_Date__c = date.today().adddays(365));
            Insert newPBS;
            PBS_Lease_Access__c lsac1 = new PBS_Lease_Access__c(PBS_Lease__c = newPBS.id, Requestor__c=user.Id, Status__c = 'Requested');
            Insert lsac1;
            List<Case> collCase = new List<Case>();
            collCase.add(new case(origin='Web',Status='Submitted',PBS_Lease__c =newPBS.ID));
            collCase.add(new case(origin='Phone',Status='Submitted',PBS_Lease__c =newPBS.ID));
            Insert collCase;
        }
    }
    
    @isTest static void testPositive(){
        User castIronUser = [Select Id from user where email = 'castIronUserTestEmail@test.org' limit 1];
        system.runAs(castIronUser){
            List<String> statusFilters = new List<String>();
            List<Id> lsacIdList = new List<Id>();
            statusFilters.add('Requested');
            List<PBS_Lease__c> leaseList = [select Id, Name, OwnerId, LSR_Email_Text__c, LSR_Contact_Email__c from PBS_Lease__c];
            List<PBS_Lease_Access__c> lsacList = [select id, PBS_Lease__c, PBS_Lease__r.Lease_Number__c, 
                                                  Requestor__c, Status__c from PBS_Lease_Access__c];
            for(PBS_Lease_Access__c lsac : lsacList){lsacIdList.add(lsac.id);}
            
            RET_LeaseShareUtility.getLeaseAccessList(statusFilters,1,3);
            RET_LeaseShareUtility.getPendingApprovalsCount(statusFilters);
            RET_LeaseShareUtility.ApproveRejectLeaseAccess(lsacList, 'Approve');
            RET_LeaseShareUtility.ApproveRejectLeaseAccess(lsacList, 'Reject');
            RET_LeaseShareUtility.getLeaseAccessMap(leaseList);
            RET_LeaseShareUtility.revokePOCLeaseAccess(leaseList);
            RET_LeaseShareUtility.revokeRETLeaseAccess(leaseList);
            RET_LeaseShareUtility.revokePBSLeaseAccess(lsacIdList);
            RET_LeaseShareUtility.getCastIronUserId();
            RET_LeaseShareUtility.getPBSLeaseAccessRecords('leaseNumber');
            RET_LeaseShareUtility.InsertCaseShares(lsacList);
            String uType = RET_LeaseShareUtility.getUserType();
            system.assertNotEquals(null, uType);
        }
    }    
    
}