force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>This is the standard account record type.</description>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/PBS_AAAP_Alternate_Phone__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Alternate_Phone__c</fullName>
    <label>Extension</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_Company__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Company__c</fullName>
    <label>Company</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_PIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PIN__c</fullName>
    <inlineHelpText>PIN is used for added security while submitting the Offer.</inlineHelpText>
    <label>PIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_Regions__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Regions__c</fullName>
    <label>Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_StatesOfInterest__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_StatesOfInterest__c</fullName>
    <description>This is a multi-select list that allows the user to select all of the states in which the offerer is interested in creating offers.</description>
    <inlineHelpText>You may select multiple states in which you have an interest of creating offers.</inlineHelpText>
    <label>States Of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District Of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PBS_AAAP_Website__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Website__c</fullName>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/GSA.recordType-meta.xml
<RecordType>
    <fullName>GSA</fullName>
    <active>true</active>
    <description>This contact record is used to track information for GSA employees.</description>
    <label>GSA</label>
</RecordType>

force-app/main/default/objects/User/fields/PBS_AAAP_Alternate_Phone__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Alternate_Phone__c</fullName>
    <label>Alternate Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User/fields/PBS_AAAP_PIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PIN__c</fullName>
    <label>PIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PBS_AAAP_Regions__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Regions__c</fullName>
    <label>Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
            <value>
                <fullName>Region 1</fullName>
            </value>
            <value>
                <fullName>Region 2</fullName>
            </value>
            <value>
                <fullName>Region 3</fullName>
            </value>
            <value>
                <fullName>Region 4</fullName>
            </value>
            <value>
                <fullName>Region 5</fullName>
            </value>
            <value>
                <fullName>Region 6</fullName>
            </value>
            <value>
                <fullName>Region 7</fullName>
            </value>
            <value>
                <fullName>Region 8</fullName>
            </value>
            <value>
                <fullName>Region 9</fullName>
            </value>
            <value>
                <fullName>Region 10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PBS_AAAP_StatesOfInterest__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_StatesOfInterest__c</fullName>
    <description>This is a multi-select list that allows the user to select all of the states in which the offerer is interested in creating offers.</description>
    <inlineHelpText>You may select multiple states in which you have an interest of creating offers.</inlineHelpText>
    <label>States Of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District Of Columbia</fullName>
                <label>District of Columbia</label>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PBS_AAAP_UserProfileController.cls
public with sharing class PBS_AAAP_UserProfileController {

    public User usrinfo { get; set; }
    public boolean isEdit { get; set; }
    // Variables used for User De-Registration
    public String userid { get; set; }
    public String pin { get; set; }
    public String statusMessage { get; set; }
    public String oldEmail { get; set; }
    public boolean isLOP { get; set; }


    public PBS_AAAP_UserProfileController() {
        string requestType = ApexPages.currentPage().getParameters().get('Type');
        if (requestType == 'LOP') {
            isLOP = true;
        } else {
            isLOP = false;
        }

        List<User> tempUsrinfo = [
                SELECT id, email, Name, username, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                        street, city, country, CompanyName, postalcode, state, localesidkey, mobilephone, extension, fax, contact.email, contact.PBS_AAAP_Website__c,
                        PBS_AAAP_StatesOfInterest__c, PBS_AAAP_PIN__c,PBS_AAAP_Regions__c, PBS_AAAP_Alternate_Phone__c
                FROM User
                WHERE id = :UserInfo.getUserId()
        ];

        User currentUser = [select id,email from user where Id = :UserInfo.getUserId()];  
             oldEmail = currentUser.Email;
        for (User u : tempUsrinfo) {
            usrinfo = u;
            
        }
        
        
    }

    public void save() {
        
        
            if(usrinfo.email != oldEmail){
            statusMessage = 'To finalize the change of the email address registered to this account, please check your email address and read the instructions for verifying your new email address. Failure to do so will cause access issues.';
            }
        if (usrinfo.contact != null) {
            usrinfo.contact.title = usrinfo.title;
            usrinfo.contact.firstname = usrinfo.firstname;
            usrinfo.contact.lastname = usrinfo.lastname;
            usrinfo.contact.email = usrinfo.email;
            usrinfo.contact.phone = usrinfo.phone;
            usrinfo.contact.mobilephone = usrinfo.mobilephone;
            usrinfo.contact.mailingstreet = usrinfo.street;
            usrinfo.contact.mailingcity = usrinfo.city;
            usrinfo.contact.mailingstate = usrinfo.state;
            usrinfo.contact.mailingpostalcode = usrinfo.postalcode;
            usrinfo.contact.mailingcountry = usrinfo.country;
            usrinfo.contact.title = usrinfo.title;
            usrinfo.contact.PBS_AAAP_Company__c = usrinfo.CompanyName;
            usrinfo.contact.PBS_AAAP_Alternate_Phone__c = usrinfo.PBS_AAAP_Alternate_Phone__c;
            usrinfo.contact.PBS_AAAP_StatesOfInterest__c = usrinfo.PBS_AAAP_StatesOfInterest__c;
            usrinfo.PBS_AAAP_Regions__c = SiteRegisterController.selectRegions(usrinfo.PBS_AAAP_StatesOfInterest__c);
            usrinfo.contact.PBS_AAAP_Regions__c = usrinfo.PBS_AAAP_Regions__c;
        }
        if (usrinfo.email != null && isUsernameTaken(usrinfo.email, usrinfo.Id)) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR,
                'The Username for this application is the same as the registered email address, and the new email address you attempted to update already exists in the system for another account. If you have access to the new email address account, please use the \'Forgot your password?\' option on the Log in screen. Otherwise, use a different email address or keep the established one.'
            ));
            
        }
        else{
            try {
                
                update usrinfo;
                
                if (usrinfo.contact != null) {
                    update usrinfo.contact;
                }
                isEdit = false;
            } catch (DmlException e) {
                ApexPages.addMessages(e);
                
            }
        }
    }


    public void cancel() {
        isEdit = false;
        usrinfo = [
                SELECT id, email, Name, username, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                        street, city, country, CompanyName, postalcode, state, localesidkey, mobilephone, extension, fax, contact.email, contact.PBS_AAAP_Website__c,
                        PBS_AAAP_StatesOfInterest__c, PBS_AAAP_PIN__c, PBS_AAAP_Regions__c, PBS_AAAP_Alternate_Phone__c
                FROM User
                WHERE id = :UserInfo.getUserId()
        ];
    }

    public PageReference actionredirecttoDeregister() {
        PageReference p = Page.PBS_AAAP_User_Deregistration;
        //p.getParameters().put('offerId', offerBuilding.Id);
        p.setRedirect(true);
        return p;

    }
    public Boolean getIsEdit() {
        return isEdit;
    }

    public void edit() {
        isEdit = true;
    }
    public Boolean isUsernameTaken(String username, Id currentUserId) {
        List<User> users = [
            SELECT Id FROM User 
            WHERE Username = :username AND Id != :UserInfo.getUserId()
            LIMIT 1
        ];
        return !users.isEmpty();
    }
    public PageReference actionDeRegistration() {
        PageReference p = null;
        if (userid != '' && pin != '') {
            System.debug('********** userid:::: ' + userid);
            System.debug('**********PIN:::: ' + pin);
            try {
                User usr = [SELECT id, Name, PBS_AAAP_PIN__c, username FROM User WHERE username = :userid AND PBS_AAAP_PIN__c = :pin];
                if (usr.id != null) {
                    System.debug('********** Future Method:::: ' + usr);
                    //makePortalUserInactive(userid);
                    // Send an email to email service handler
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    String[] toAddresses = new String[]{
                            'email_service_for_deregistering_portal_user@7-4nadul3uf273h6wo1h6h7i19g.v1b8cmaa.v.apex.sandbox.salesforce.com'
                    };
                    mail.setToAddresses(toAddresses);
                    mail.setReplyTo('aaap.manager@gsa.gov');
                    mail.setSenderDisplayName('User Support');
                    mail.setSubject('usr-' + usr.username);
                    mail.setPlainTextBody('aaap.manager@gsa.gov'); // mail.setPlainTextBody('sguni@acumensolutions.com');                 
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                            mail
                    });


                    p = new PageReference('/secur/logout.jsp');
                    p.setRedirect(true);

                }
            } catch (Exception ex) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Either the userid or PIN is incorrect. Please try it again or contact AAAP Manager.');
                ApexPages.addMessage(myMsg);
                return null;
            }
        }

        return p;
    }


}