force-app/main/default/objects/Login_History__c/Login_History__c.object-meta.xml
<CustomObject>
    <description>Stores successful and failed login attempts for Salesforce production organization and enabled portals.</description>
    <label>Login History</label>
    <nameField>
        <label>Login History Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Login_History__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <label>API Version</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <label>Browser</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Client_Version__c.field-meta.xml
<CustomField>
    <fullName>Client_Version__c</fullName>
    <label>Client Version</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Login_Time__c</fullName>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Login_Type__c.field-meta.xml
<CustomField>
    <fullName>Login_Type__c</fullName>
    <label>Login Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Login_URL__c.field-meta.xml
<CustomField>
    <fullName>Login_URL__c</fullName>
    <label>Login URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Source_IP__c.field-meta.xml
<CustomField>
    <fullName>Source_IP__c</fullName>
    <label>Source IP</label>
    <length>39</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Salesforce Username</description>
    <label>Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleLoginHistoryBatchTest.cls
@isTest
Public class ScheduleLoginHistoryBatchTest{
   
    static testMethod void ScheduleTestMethod(){
		DateTime n = datetime.now().addMinutes(1);
   		String cron = '';
   		cron += n.second();
   		cron += ' ' + n.minute();
   		cron += ' ' + n.hour();
   		cron += ' ' + n.day();
   		cron += ' ' + n.month();
   		cron += ' ' + '?';
   		cron += ' ' + n.year();
   		
   		String jobId = System.schedule('LoginHistoryBatchJob', cron, new ScheduleLoginHistoryBatch());
   		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime 
                          FROM CronTrigger 
                          WHERE id = :jobId];
   		System.assertEquals(cron, ct.CronExpression);
   		System.assertEquals(0, ct.TimesTriggered);
	}
    
    static testMethod void DeleteBatchTestMethod(){
        Login_History__c l = new Login_History__c();
       	l.Username__c	='00530000009TyoYAAS';
 	 	l.Login_Time__c = system.today();
        l.Source_IP__c = '69.255.192.143';
        l.Login_Type__c = 'Application';
        l.Status__c = 'Failed:Computer activation required';
        l.Browser__c = 'Chrome 56';
        l.Platform__c = 'Mac OSX';
        l.Application__c = 'Browser';	  	 
		l.Client_Version__c	= 'N/A';
 	    l.API_Type__c = 'N/A';
        l.API_Version__c ='38.0';
        l.Login_URL__c = 'Test.salesforce.com';
        insert l;
        
        test.startTest();
        	LoginHistoryDeleteBatch lb = new LoginHistoryDeleteBatch();
        	ID batchID = database.executeBatch(lb);
        test.stopTest();
        AsyncApexJob ajob = [SELECT ID, Status, NumberOfErrors, JobItemsProcessed,
        				 TotalJobItems, CreatedBy.Email, ExtendedStatus
                         FROM AsyncApexJob WHERE ID =:batchID];
        
        system.assertEquals('Completed', ajob.Status);
	}
}