force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/NCMT_Core_Shell_Cost_Detail__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>Core Shell Cost Detail</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Core Shell Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Shell Cost Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/fields/Core_Shell_Cost_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Core_Shell_Cost_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Core Shell Cost Parameter</label>
    <referenceTo>NCMT_Core_Shell_Cost_Parameter__c</referenceTo>
    <relationshipLabel>Core Shell Cost Detail</relationshipLabel>
    <relationshipName>Core_Shell_Cost_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/NCMT_Core_Shell_Cost_Parameter__c.object-meta.xml
<CustomObject>
    <description>NCMT Core Shell Cost Parameters</description>
    <label>Core Shell Cost Parameter</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Core Shell Cost Parameters</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Shell Cost Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Core_Shell_Cost_Parameter_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Core_Shell_Cost_Parameter_Identifier__c</fullName>
    <label>Core Shell Cost Parameter Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <description>Cost Category ID</description>
    <label>Cost Category</label>
    <referenceTo>NCMT_Cost_Category__c</referenceTo>
    <relationshipLabel>Core Shell Cost Parameters</relationshipLabel>
    <relationshipName>Core_Shell_Cost_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Cost_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sub_Type__c</fullName>
    <description>NCMT Cost Sub Type</description>
    <label>Cost Sub Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Cost_Sub_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sub_Type_Description__c</fullName>
    <description>Cost Sub Type Description</description>
    <label>Cost Sub Type Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Other_Space_Unit__c.field-meta.xml
<CustomField>
    <fullName>Other_Space_Unit__c</fullName>
    <label>Other Space Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>BGSF</fullName>
            </value>
            <value>
                <fullName>CFM</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>KVA</fullName>
            </value>
            <value>
                <fullName>KW</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>LF</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>Mbtu</fullName>
            </value>
            <value>
                <fullName>pgross</fullName>
            </value>
            <value>
                <fullName>SF</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>STOP</fullName>
            </value>
            <value>
                <fullName>GSF</fullName>
            </value>
            <value>
                <fullName>KBtu</fullName>
            </value>
            <value>
                <fullName>TON</fullName>
            </value>
            <value>
                <fullName>GPD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Other_Space_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Other_Space_Unit_Cost__c</fullName>
    <description>Other Space Unit Cost</description>
    <label>Other Space Unit Cost</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Core_Shell_Cost_Parameter__c/fields/Parking_Space_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Parking_Space_Unit_Cost__c</fullName>
    <description>Parking Space Unit Cost</description>
    <label>Parking Space Unit Cost</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Cost_Category__c/NCMT_Cost_Category__c.object-meta.xml
<CustomObject>
    <description>NCMT Cost Category</description>
    <label>Cost Category</label>
    <nameField>
        <label>Category ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Cost_Category__c/fields/Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Category_Description__c</fullName>
    <description>Cost Category Description</description>
    <label>Category Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NCMT_Cost_Category__c/fields/Cost_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category_Type__c</fullName>
    <label>Cost Category Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/NCMT_Project_Cost_Summary__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>Project Cost Summary</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Cost Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Cost Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/fields/Cost_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category_Type__c</fullName>
    <formula>TEXT(Cost_Category_ID__r.Estimate_Format__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Category Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/NCMT_Security_Parameters__c.object-meta.xml
<CustomObject>
    <description>NCMT Security Price</description>
    <label>Security Parameter</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Security Criteria ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <referenceTo>NCMT_Cost_Category__c</referenceTo>
    <relationshipLabel>Security Parameters</relationshipLabel>
    <relationshipName>Security_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>Fiscal Year</description>
    <inlineHelpText>Fiscal Year</inlineHelpText>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Level_I_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Level_I_Minimum__c</fullName>
    <description>Level I - Minimum cost</description>
    <inlineHelpText>Level I - Minimum cost</inlineHelpText>
    <label>Level I - Minimum</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Level_II_Low__c.field-meta.xml
<CustomField>
    <fullName>Level_II_Low__c</fullName>
    <description>Level II - Low cost</description>
    <inlineHelpText>Level II - Low cost</inlineHelpText>
    <label>Level II - Low</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Level_III_Medium__c.field-meta.xml
<CustomField>
    <fullName>Level_III_Medium__c</fullName>
    <description>Level III - Medium cost</description>
    <inlineHelpText>Level III - Medium cost</inlineHelpText>
    <label>Level III - Medium</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Level_IV_High__c.field-meta.xml
<CustomField>
    <fullName>Level_IV_High__c</fullName>
    <description>Level IV - High cost</description>
    <inlineHelpText>Level IV - High cost</inlineHelpText>
    <label>Level IV - High</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Level_V_Very_High__c.field-meta.xml
<CustomField>
    <fullName>Level_V_Very_High__c</fullName>
    <description>Level V - Very High cost</description>
    <inlineHelpText>Level V - Very High cost</inlineHelpText>
    <label>Level V - Very High</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Security_Parameters__c/fields/Security_Criterion__c.field-meta.xml
<CustomField>
    <fullName>Security_Criterion__c</fullName>
    <description>Security Criterion</description>
    <inlineHelpText>Security Criterion</inlineHelpText>
    <label>Security Criterion</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_TI_TRCS_Cost_Detail__c/NCMT_TI_TRCS_Cost_Detail__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>TI-TRCS Cost Detail</label>
    <nameField>
        <displayFormat>TITRCS-{0000}</displayFormat>
        <label>TI-TRCS Cost Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TI-TRCS Cost Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TI_TRCS_Cost_Detail__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <formula>TI_TRCS_Cost_Parameter__r.Cost_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TI_TRCS_Cost_Parameter__c/TI_TRCS_Cost_Parameter__c.object-meta.xml
<CustomObject>
    <description>NCMT TI-TRCS Cost Parameters</description>
    <label>TI-TRCS Cost Parameter</label>
    <nameField>
        <displayFormat>TI-TRCS-{00000}</displayFormat>
        <label>TI-TRCS Cost Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TI-TRCS Cost Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TI_TRCS_Cost_Parameter__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <description>NCMT Cost Category</description>
    <label>Cost Category</label>
    <referenceTo>NCMT_Cost_Category__c</referenceTo>
    <relationshipLabel>TI-TRCS Cost Parameters</relationshipLabel>
    <relationshipName>TI_TRCS_Cost_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TI_TRCS_Cost_Parameter__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NCMT_ReportData_Tests.cls
@isTest
public with sharing class NCMT_ReportData_Tests {
    

    @testSetup static void setup()
    {
        NCMT_Cost_Category__c costCat = new NCMT_Cost_Category__c(
            Name = 'B10',
            Category_Description__c = 'The B10 one',
            Cost_Category_Type__c = 'New Construction'
        );
        insert costCat;
        NCMT_Security_Parameters__c secParam = new NCMT_Security_Parameters__c(
            SECURITY_CRITERION__C = 'Blast Resistance - Windows',
            LEVEL_I_MINIMUM__C = 0,
            LEVEL_II_LOW__C = 0,
            LEVEL_III_MEDIUM__C = 0,
            LEVEL_IV_HIGH__C = 0,
            LEVEL_V_VERY_HIGH__C = 0,
            COST_CATEGORY__C = costCat.ID,
            FISCAL_YEAR__C = '2017');
        insert secParam;
        secParam = new NCMT_Security_Parameters__c(
            SECURITY_CRITERION__C = 'Blast Resistance - Façade and Structure',
            LEVEL_I_MINIMUM__C = 0,
            LEVEL_II_LOW__C = 0,
            LEVEL_III_MEDIUM__C = 0,
            LEVEL_IV_HIGH__C = 0,
            LEVEL_V_VERY_HIGH__C = 0,
            COST_CATEGORY__C = costCat.ID,
            FISCAL_YEAR__C = '2017');
        insert secParam;
        NCMT_Core_Shell_Cost_Parameter__c coreParam = new NCMT_Core_Shell_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2017',
                        OTHER_SPACE_UNIT_COST__C = 1,
                        CORE_SHELL_COST_PARAMETER_IDENTIFIER__C = 'CC9',
                        COST_SUB_TYPE_DESCRIPTION__C = 'descrip',
                        COST_SUB_TYPE__C = 'sub',
                        OTHER_SPACE_UNIT__C = 'GSF',
                        PARKING_SPACE_UNIT_COST__C = 200,
                        PARKING_SPACE_UNIT__C = 'GSF',
                        LEVEL_3__C = 'lev3'
                    );
        insert coreParam;

        TI_TRCS_Cost_Parameter__c tiParam = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Dry/Electronic Lab',
                        Level_3__c = 'G1100', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam;
        TI_TRCS_Cost_Parameter__c tiParam2 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Firing Range',
                        Level_3__c = 'G1100', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam2;
        TI_TRCS_Cost_Parameter__c tiParam3 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Credit Union',
                        Level_3__c = 'G1100', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam3;
        
        TI_TRCS_Cost_Parameter__c tiParam4 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Secure Mailroom',
                        Level_3__c = 'A1010', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam4;
        
        TI_TRCS_Cost_Parameter__c tiParam5 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Copy Center',
                        Level_3__c = 'A1010', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam5;
        
        TI_TRCS_Cost_Parameter__c tiParam6 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Public Transaction Space, Tenant Improvement',
                        Level_3__c = 'A1010', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam6;
        TI_TRCS_Cost_Parameter__c tiParam7 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Kitchen-Break room, Tenant Improvement',
                        Level_3__c = 'A1010', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam7;
        TI_TRCS_Cost_Parameter__c tiParam8 = new TI_TRCS_Cost_Parameter__c(
                        Cost_Category__c = costCat.Id,
                        Fiscal_Year__c = '2020',
                        Space_Type__c = 'Shower and Locker Rooms, Tenant Improvement',
                        Level_3__c = 'A1010', 
                        Unit_TI_Cost__c = 20,
                        Unit_TI_Utilities_Cost__c = 0,
                        Unit_TRCS_Cost__c = 0
                    );
        insert tiParam8;

        NCMT_TestTCOProjectClass.CreateTCOProject('testProjCodeCovTCOOff1','Virginia','State Average'
           ,'Lowrise (2 - 3 stories)', true, false, false, 1000000, false, false, false, false, false);

        //NCMT_TestDataClass.CreateProject('New Construction', 'testProjCodeCovOff6','Office','Missouri','Cape Girardeau','Core/Shell with TI'
        //                                ,'Midrise (4 - 9 stories)','P100: Monumental','Level II - Low','Urban', false, true, false, true, 1000000, 10, 0, 0, false, false, false, false, true, false, false);

        //NCMT_TestDataClass.CreateProject('New Construction', 'testProjCodeCovOff1','Office','Virginia','State Average','Core/Shell only'
        //                                ,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, false, 1000000, 0, 0, 0, false, false, false, false, false, false, true);
       
        NCMT_Project__c proj = [SELECT Id, Name FROM NCMT_Project__c LIMIT 1];

        //Get list of Project Cost Summary records inserted with Project
        List<NCMT_Project_Cost_Summary__c> listCostSummary = [Select ID, Cost_Category_Description__c, Project_Name__c From NCMT_Project_Cost_Summary__c Where Project_Name__c = :Proj.Id Limit 1];
        System.assertEquals(proj.Id, listCostSummary[0].Project_Name__c);


        NCMT_GenerateTCOProjectDetailsExt.runTriggers = false;
         //Core Shell Cost Details
         NCMT_Core_Shell_Cost_Detail__c det = new NCMT_Core_Shell_Cost_Detail__c(
                Project_Cost_Summary__c = listCostSummary[0].Id,
                Core_Shell_Cost_Parameter__c = coreParam.Id, 
                Core_Shell_Cost__c = 5,
                Total_Units__c = 4,
                ParkingCost__c = 2

                );
         insert det;
         det = new NCMT_Core_Shell_Cost_Detail__c(
                Project_Cost_Summary__c = listCostSummary[0].Id,
                Core_Shell_Cost_Parameter__c = coreParam.Id, 
                Core_Shell_Cost__c = 5,
                Total_Units__c = 4,
                ParkingCost__c = 2

                );
         insert det;

         List<NCMT_Core_Shell_Cost_Detail__c> coreShell = [SELECT NCMT_Project_ID__c,
                                    Project_Cost_Summary__r.Cost_Category_ID__r.Name, Core_Shell_Cost_Parameter__r.Level_3__c,
                                    Core_Shell_Cost_Parameter__r.Level_3_Description__c
                                    
                                    FROM NCMT_Core_Shell_Cost_Detail__c
                                    WHERE Project_Cost_Summary__r.Project_Name__c =: proj.Id
                                    
                                    ];
        System.assertEquals(proj.Id, coreShell[0].NCMT_Project_ID__c);
         NCMT_TI_TRCS_Cost_Detail__c ti = new NCMT_TI_TRCS_Cost_Detail__c(
             Project_Cost_Summary__c = listCostSummary[0].Id,
             TI_TRCS_Cost_Parameter__c = tiParam.id
            );
         insert ti;

         ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam2.id
           );
        insert ti;

        ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam3.id
           );
        insert ti;
        
        ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam4.id
           );
        insert ti;
        
        ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam5.id
           );
        insert ti;
        ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam6.id
           );
        insert ti;
         ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam7.id
           );
        insert ti;
         ti = new NCMT_TI_TRCS_Cost_Detail__c(
            Project_Cost_Summary__c = listCostSummary[0].Id,
            TI_TRCS_Cost_Parameter__c = tiParam8.id
           );
        insert ti;
    }
    
    

    static testmethod void reportTest() {
        //NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Parametric Entry', 'testProjCodeCovRAOff1','Office','Virginia','State Average','Core/Shell with TI'
         //                               ,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', false,'','',true,'');

        NCMT_Project__c proj = [SELECT Id, Name FROM NCMT_Project__c LIMIT 1];
  
        
        
        ApexPages.currentPage().getParameters().put('ProjectID', Proj.id);
        Test.startTest();
        NCMT_ReportData objTest = new NCMT_ReportData();
        System.assert(objTest != null);
        objTest.DatasetProjectCostSummaryGrouped(Proj.id);
        
        objTest.getProjectInformation();

        Test.stopTest();
        

        objTest.getDatasetProjectCostSummary();  
        objTest.getDatasetHousingPlan();   

        objTest.getCoreShellData();      
     
    }

   

    
}