force-app/main/default/objects/NCMT_Core_Shell_Cost_Detail__c/NCMT_Core_Shell_Cost_Detail__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>Core Shell Cost Detail</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Core Shell Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Shell Cost Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan__c/NCMT_Housing_Plan__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Housing Plan</description>
    <label>NCMT Housing Plan</label>
    <nameField>
        <displayFormat>HP-{0000000000}</displayFormat>
        <label>NCMT Housing Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <formula>text(Project__r.Building_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Child to Project</description>
    <label>Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plans</relationshipLabel>
    <relationshipName>NCMT_Housing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <formula>TEXT(Project__r.Project_type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/NCMT_Housing_Plan_Option__c.object-meta.xml
<CustomObject>
    <label>NCMT Housing Plan Option</label>
    <nameField>
        <displayFormat>Option-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/NCMT_Housing_Plan_Option_Selection__c.object-meta.xml
<CustomObject>
    <description>Created when a Housing Plan Selection Option is selected on the Housing Plan selection page. Deleted if unselected.</description>
    <label>NCMT Housing Plan - Option Selection</label>
    <nameField>
        <displayFormat>Select-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Option Selection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/Housing_Plan_Option_Template_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Housing_Plan_Option_Template_Record_Type__c</fullName>
    <formula>NCMT_Housing_Plan_Option__r.NCMT_Housing_Plan_Option_Template__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Housing Plan Option Template Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/Housing_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Housing_Plan_Template__c</fullName>
    <formula>NCMT_Housing_Plan_Option__r.NCMT_Housing_Plan_Option_Template__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Housing Plan Template</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>NCMT Housing Plan</label>
    <referenceTo>NCMT_Housing_Plan__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Housing_Plan_Option__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan Option</label>
    <referenceTo>NCMT_Housing_Plan_Option__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/Recurs_on_TCO_Tenant_Refresh_Years__c.field-meta.xml
<CustomField>
    <fullName>Recurs_on_TCO_Tenant_Refresh_Years__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurs on TCO Tenant Refresh Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/TCO_Repair_Cost_Percentage__c.field-meta.xml
<CustomField>
    <fullName>TCO_Repair_Cost_Percentage__c</fullName>
    <label>TCO Repair Cost (Percentage)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/TCO_Repair_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Repair_Every_X_Years__c</fullName>
    <label>TCO Repair Every X Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/TCO_Replacement_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Replacement_Every_X_Years__c</fullName>
    <label>TCO Replacement Every X Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <inlineHelpText>Select Building Type (from one of the many primary building types in the PBS Portfolio).</inlineHelpText>
    <label>Building Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Childcare Center</fullName>
            </value>
            <value>
                <fullName>Courthouse</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Laboratory: Dry</fullName>
            </value>
            <value>
                <fullName>Laboratory: Wet</fullName>
            </value>
            <value>
                <fullName>Medical Clinic</fullName>
            </value>
            <value>
                <fullName>Medical Office</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>Parking Garage</fullName>
            </value>
            <value>
                <fullName>LPOE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Cost_Parameter_Date_FY__c.field-meta.xml
<CustomField>
    <fullName>Cost_Parameter_Date_FY__c</fullName>
    <formula>Text(YEAR(Cost_Parameter_Date__c + 92))</formula>
    <label>Cost Parameter Date FY</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Default_Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Default_Housing_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Housing Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Housing_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Housing Plan</description>
    <inlineHelpText>Applied when user can determine logical breakdown of functional space-types and the required area of each. See Housing Plan Analysis Help Sheet</inlineHelpText>
    <label>Housing Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Project_type__c.field-meta.xml
<CustomField>
    <fullName>Project_type__c</fullName>
    <inlineHelpText>Either new construction or repair and alteration based on the estimate type selected.</inlineHelpText>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estimate_Type_Proj__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New Construction</fullName>
            </value>
            <value>
                <fullName>Repair &amp; Alteration - Work Item Detail</fullName>
            </value>
            <value>
                <fullName>Repair &amp; Alteration - Parametric Entry</fullName>
            </value>
            <value>
                <fullName>New Construction - DES</fullName>
            </value>
            <value>
                <fullName>Repair &amp; Alteration - DES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Security_Detail__c/NCMT_Security_Detail__c.object-meta.xml
<CustomObject>
    <description>Security Detail</description>
    <label>Security Cost Detail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Security Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Cost Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Security_Detail__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;Project_Cost_Summary__r.Project_Name__r.Id,Project_Cost_Summary__r.Project_Name__r.Name, &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NCMT Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_TI_TRCS_Cost_Detail__c/NCMT_TI_TRCS_Cost_Detail__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>TI-TRCS Cost Detail</label>
    <nameField>
        <displayFormat>TITRCS-{0000}</displayFormat>
        <label>TI-TRCS Cost Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TI-TRCS Cost Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TI_TRCS_Cost_Detail__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <formula>TI_TRCS_Cost_Parameter__r.Cost_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_TI_TRCS_Cost_Detail__c/fields/NCMT_Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan</label>
    <referenceTo>NCMT_Housing_Plan__c</referenceTo>
    <relationshipLabel>TI-TRCS Cost Detail</relationshipLabel>
    <relationshipName>TI_TRCS_Cost_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_TI_TRCS_Cost_Detail__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;Project_Cost_Summary__r.Project_Name__r.Id,Project_Cost_Summary__r.Project_Name__r.Name, &quot;_parent&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NCMT Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NCMT_HousingPlan_OptSelection_Handler.cls
public with sharing class NCMT_HousingPlan_OptSelection_Handler {
    private final List<NCMT_Housing_Plan_Option_Selection__c> oldList { get; set; }
    private final List<NCMT_Housing_Plan_Option_Selection__c> newList { get; set; }
    private final Map<Id, NCMT_Housing_Plan_Option_Selection__c> oldMap { get; set; }
    private final Map<Id, NCMT_Housing_Plan_Option_Selection__c> newMap { get; set; }
    public static Boolean skipGenerateProject = false;

    public NCMT_HousingPlan_OptSelection_Handler(List<NCMT_Housing_Plan_Option_Selection__c> oldLst, List<NCMT_Housing_Plan_Option_Selection__c> newLst, Map<Id, NCMT_Housing_Plan_Option_Selection__c> oldMp, Map<Id, NCMT_Housing_Plan_Option_Selection__c> newMp) {
        oldList = (oldLst == null ? new List<NCMT_Housing_Plan_Option_Selection__c>() : oldLst);
        newList = (newLst == null ? new List<NCMT_Housing_Plan_Option_Selection__c>() : newLst);
        oldMap = (oldMp == null ? new Map<Id, NCMT_Housing_Plan_Option_Selection__c>() : oldMp);
        newMap = (newMp == null ? new Map<Id, NCMT_Housing_Plan_Option_Selection__c>() : newMp);
        
        
    }

    public void manageCostComponents(){
        if (!skipGenerateProject){
            Id projId;
            if (newList.size() > 0){
                for (NCMT_Housing_Plan_Option_Selection__c  optSel : newList){
                    projId = optSel.NCMT_Project__c;
                }
            }
            if (oldList.size() > 0){
                for (NCMT_Housing_Plan_Option_Selection__c  optSel : oldList){
                    projId = optSel.NCMT_Project__c;
                }
            }

            if (projId != null){
                

                NCMT_Project__c proj = [Select Id, building_type__c, project_type__c, Housing_Plan__c,
                    Default_Housing_Plan__c, Cost_Parameter_Date_FY__c
                    from NCMT_Project__c where Id =: projId][0];
                
                

                NCMT_GenerateProjectDetailsExt objGenerateDataExt = new NCMT_GenerateProjectDetailsExt();   
        
                objGenerateDataExt.GenerateHPOptionData(projId, proj.project_type__c, proj.Housing_Plan__c, proj.Default_Housing_Plan__c, proj.Cost_Parameter_Date_FY__c);
            }
            
        }
    }
    
    /*Did this in NCMT_GenerateProjectDtailsExt instead, maybe useful later...
    public void addCostComponents(){
        Map<Id, String> hpSpaces = new Map<Id, String>();
        Map<Id, NCMT_Housing_Plan_Option__c> options = new Map<Id, NCMT_Housing_Plan_Option__c>();
        for (NCMT_Housing_Plan_Option_Selection__c sel : newList){
            options.put(sel.NCMT_Housing_Plan_Option__c, null);
            hpSpaces.put(sel.NCMT_Housing_Plan__c, null);
        }

        Id projId; //Only one is ever processed at a time
        for (NCMT_Housing_Plan__c hp : [Select Id, Space_Type__c, Project__c from NCMT_Housing_Plan__c where Id IN: hpSpaces]){
            hpSpaces.put(hp.Id, hp.Space_Type__c);
            projId = hp.Project__c;
        }
        Set<String> rts = new Set<String>();
        for (NCMT_Housing_Plan_Option__c o : [Select Id, Housing_Plan_Option_Template_Record_Type__c, 
                Housing_Plan_Template__c, NCMT_Housing_Plan_Option__c, Recurs_on_TCO_Tenant_Refresh_Years__c, 
                TCO_Repair_Cost_Percentage__c, TCO_Repair_Every_X_Years__c, TCO_Replacement_Cost_Percent__c, 
                TCO_Replacement_Every_X_Years__c 
            from NCMT_Housing_Plan_Option__c where Id IN: options.keySet()]
        ){
            options.put(o.id, o);
            rts.add(o.Housing_Plan_Option_Template_Record_Type__c);
        }

        List<NCMT_Core_Shell_Cost_Detail__c> coreCosts = new List<NCMT_Core_Shell_Cost_Detail__c>();
        List<NCMT_TI_TRCS_Cost_Detail__c> tiCosts = new List<NCMT_TI_TRCS_Cost_Detail__c>();
        List<NCMT_Security_Detail__c> securityCosts = new List<NCMT_Security_Detail__c>();

        if (rts.contains('TI-TRCS Cost')){
            tiCosts = [Select Id, Cost_Category__c  from NCMT_TI_TRCS_Cost_Detail__c where Project__c =: projId];
        }
    }
*/
}