force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DUNS_Number__c</fullName>
    <description>What is the property owner&apos;s Unique Entity Identifier # (formerly DUNS #)?</description>
    <label>UEI Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFEROR_INTEREST__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFEROR_INTEREST__c</fullName>
    <description>8. What is your relationship as the offeror, to the property owner?</description>
    <label>Offeror Relationship to Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFEROR_INTEREST_OTHER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFEROR_INTEREST_OTHER__c</fullName>
    <description>8. What is your relationship as the offeror, to the property owner? Other???</description>
    <label>Offeror Relation to Property Owner Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Address__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Address__c</fullName>
    <description>Street Address</description>
    <label>Property Owner Street Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_City__c</fullName>
    <description>City</description>
    <label>Property Owner City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Name__c</fullName>
    <description>What is the name of the property&apos;s recorded owner?</description>
    <label>Property Owner Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_State__c</fullName>
    <description>State</description>
    <label>Property Owner State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Zip__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Zip__c</fullName>
    <description>Zip Code</description>
    <label>Property Owner Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Solicitation_Id__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Solicitation_Id__c</fullName>
    <label>Solicitation Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Region__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region__c</fullName>
    <label>RLP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Region 1</fullName>
            </value>
            <value>
                <fullName>Region 2</fullName>
            </value>
            <value>
                <fullName>Region 3</fullName>
            </value>
            <value>
                <fullName>Region 4</fullName>
            </value>
            <value>
                <fullName>Region 5</fullName>
            </value>
            <value>
                <fullName>Region 6</fullName>
            </value>
            <value>
                <fullName>Region 7</fullName>
            </value>
            <value>
                <fullName>Region 8</fullName>
            </value>
            <value>
                <fullName>Region 9</fullName>
            </value>
            <value>
                <fullName>Region 10</fullName>
            </value>
            <value>
                <fullName>Region 11</fullName>
            </value>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
            <value>
                <fullName>10/5 Term - All Regions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_G_REX_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_G_REX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Solicitation/G-REX ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_PBS_LOP_PropertyOwnerController.cls
@isTest
public class Test_PBS_LOP_PropertyOwnerController {
    @isTest
    private static void testMethodWOOfferId(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = true;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = 'Draft';
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            offernew.PBS_AAAP_OFFEROR_INTEREST_OTHER__c = 'Other';
            insert offernew;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_PropertyOwnerController obj = new PBS_LOP_PropertyOwnerController();
            obj.sameOwner = TRUE;
            obj.copyUserDetails();
            obj.showOfferorRelationShipOther();
            obj.getOtherRelationShip();
            obj.backToOfrParking();
            obj.actionSavePropertyOwner();
            obj.actionSavePropertyOwner2();
            obj.actionSavePropertyOwnerAndContinue();
            obj.actionCancel();
            //obj.updateAreaType(offernew);
            System.assert(true);
        }
    }
    
    @isTest
    private static void testMethodWithOfferId(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = false;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            insert offernew;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_PropertyOwnerController obj = new PBS_LOP_PropertyOwnerController();
            obj.copyUserDetails();
            obj.showOfferorRelationShipOther();
            obj.getOtherRelationShip();
            obj.backToOfrParking();
            obj.actionSavePropertyOwner();
            obj.actionSavePropertyOwner2();
            obj.actionSavePropertyOwnerAndContinue();
            obj.actionCancel();
            
            PBS_AAAP_RLP__c rlp1 = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp1.PBS_RSAP_Solicitation_Number__c = '123';
            rlp1.PBS_RSAP_Solicitation_Status__c = true;
            rlp1.PBS_AAAP_Region__c = 'test region';
            insert rlp1;
            
            PBS_AAAP_Offer__c offernew1 = new PBS_AAAP_Offer__c();
            offernew1.PBS_AAAP_RLP_Number__c = rlp1.id;
            offernew1.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew1.RecordTypeId = RSAPRecTypeId;
            offernew1.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew1.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            insert offernew1;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew1.Id);
            ApexPages.currentPage().getParameters().put('edit','false');
            PBS_LOP_PropertyOwnerController obj1 = new PBS_LOP_PropertyOwnerController();
            obj1.copyUserDetails();
            obj1.showOfferorRelationShipOther();
            obj1.getOtherRelationShip();
            obj1.backToOfrParking();
            obj1.actionSavePropertyOwner();
            obj1.actionSavePropertyOwner2();
            obj1.actionSavePropertyOwnerAndContinue();

            ApexPages.currentPage().getParameters().put('offerId',offernew1.Id);
            ApexPages.currentPage().getParameters().put('edit','true');
            PBS_LOP_PropertyOwnerController obj3 = new PBS_LOP_PropertyOwnerController();
            obj3.copyUserDetails();
            obj3.showOfferorRelationShipOther();
            obj3.getOtherRelationShip();
            obj3.backToOfrParking();
            obj3.actionSavePropertyOwner();
            obj3.actionSavePropertyOwner2();
            obj3.actionSavePropertyOwnerAndContinue();
            
            PBS_AAAP_Offer__c offernew2 = new PBS_AAAP_Offer__c();
            offernew2.PBS_AAAP_RLP_Number__c = rlp1.id;
            offernew2.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew2.RecordTypeId = RSAPRecTypeId;
            offernew2.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew2.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            offernew2.PBS_AAAP_OFFEROR_INTEREST__c = 'Other';
            offernew2.PBS_AAAP_OFFEROR_INTEREST_OTHER__c = '';
            offernew2.PBS_AAAP_Owner_City__c = 'Test City';
            offernew2.PBS_AAAP_Owner_Address__c = 'Test Addr';
            offernew2.PBS_AAAP_Owner_Name__c = 'Test';
            insert offernew2;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew2.Id);
            PBS_LOP_PropertyOwnerController obj2 = new PBS_LOP_PropertyOwnerController();
            obj2.copyUserDetails();
            obj2.showOfferorRelationShipOther();
            obj2.getOtherRelationShip();
            obj2.backToOfrParking();
            obj2.actionSavePropertyOwner();
            obj2.actionSavePropertyOwner2();
            obj2.actionSavePropertyOwnerAndContinue();
            
            offernew2.PBS_AAAP_Owner_Name__c = 'Test';
            offernew2.PBS_AAAP_Owner_Address__c = 'Test';
            offernew2.PBS_AAAP_Owner_City__c = 'Test';
            offernew2.PBS_AAAP_Owner_State__c = 'Test';
            offernew2.PBS_AAAP_Owner_Zip__c = 'Test';
            offernew2.PBS_AAAP_OFFEROR_INTEREST__c = 'Agent';           
            update offernew2;
            obj2.lopOffer = offernew2;
            obj2.copyUserDetails();
            obj2.showOfferorRelationShipOther();
            obj2.getOtherRelationShip();
            obj2.backToOfrParking();
            obj2.actionSavePropertyOwner();
            obj2.actionSavePropertyOwner2();
            obj2.actionSavePropertyOwnerAndContinue();
            System.assert(true);
        }
        PBS_LOP_PropertyOwnerController obj1 = new PBS_LOP_PropertyOwnerController();
    }
    
    @isTest
    private static void testMethodWithOutOfferId(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = false;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            insert offernew;
            
            //ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_PropertyOwnerController obj = new PBS_LOP_PropertyOwnerController();
            /**
            obj.copyUserDetails();
            obj.showOfferorRelationShipOther();
            obj.getOtherRelationShip();
            obj.backToOfrParking();
            obj.actionSavePropertyOwner();
            obj.actionSavePropertyOwner2();
            obj.actionSavePropertyOwnerAndContinue();
            obj.actionCancel();
            **/
            
            PBS_AAAP_RLP__c rlp1 = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp1.PBS_RSAP_Solicitation_Number__c = '123';
            rlp1.PBS_RSAP_Solicitation_Status__c = true;
            rlp1.PBS_AAAP_Region__c = 'test region';
            insert rlp1;
            
            PBS_AAAP_Offer__c offernew1 = new PBS_AAAP_Offer__c();
            offernew1.PBS_AAAP_RLP_Number__c = rlp1.id;
            offernew1.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew1.RecordTypeId = RSAPRecTypeId;
            offernew1.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew1.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            insert offernew1;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew1.Id);
            ApexPages.currentPage().getParameters().put('edit','false');
            PBS_LOP_PropertyOwnerController obj1 = new PBS_LOP_PropertyOwnerController();
            obj1.copyUserDetails();
            obj1.showOfferorRelationShipOther();
            obj1.getOtherRelationShip();
            obj1.backToOfrParking();
            obj1.actionSavePropertyOwner();
            obj1.actionSavePropertyOwner2();
            obj1.actionSavePropertyOwnerAndContinue();

            ApexPages.currentPage().getParameters().put('offerId',offernew1.Id);
            ApexPages.currentPage().getParameters().put('edit','true');
            PBS_LOP_PropertyOwnerController obj3 = new PBS_LOP_PropertyOwnerController();
            obj3.copyUserDetails();
            obj3.showOfferorRelationShipOther();
            obj3.getOtherRelationShip();
            obj3.backToOfrParking();
            obj3.actionSavePropertyOwner();
            obj3.actionSavePropertyOwner2();
            obj3.actionSavePropertyOwnerAndContinue();
            
            PBS_AAAP_Offer__c offernew2 = new PBS_AAAP_Offer__c();
            offernew2.PBS_AAAP_RLP_Number__c = rlp1.id;
            offernew2.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew2.RecordTypeId = RSAPRecTypeId;
            offernew2.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew2.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            offernew2.PBS_AAAP_OFFEROR_INTEREST__c = 'Other';
            offernew2.PBS_AAAP_OFFEROR_INTEREST_OTHER__c = '';
            offernew2.PBS_AAAP_Owner_City__c = 'Test City';
            offernew2.PBS_AAAP_Owner_Address__c = 'Test Addr';
            offernew2.PBS_AAAP_Owner_Name__c = 'Test';
            insert offernew2;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew2.Id);
            PBS_LOP_PropertyOwnerController obj2 = new PBS_LOP_PropertyOwnerController();
            obj2.copyUserDetails();
            obj2.showOfferorRelationShipOther();
            obj2.getOtherRelationShip();
            obj2.backToOfrParking();
            obj2.actionSavePropertyOwner();
            obj2.actionSavePropertyOwner2();
            obj2.actionSavePropertyOwnerAndContinue();
            
            offernew2.PBS_AAAP_Owner_Name__c = 'Test';
            offernew2.PBS_AAAP_Owner_Address__c = 'Test';
            offernew2.PBS_AAAP_Owner_City__c = 'Test';
            offernew2.PBS_AAAP_Owner_State__c = 'Test';
            offernew2.PBS_AAAP_Owner_Zip__c = 'Test';
            offernew2.PBS_AAAP_OFFEROR_INTEREST__c = 'Agent';     
            offernew2.PBS_AAAP_DUNS_Number__c = '4345425';      
            update offernew2;
            obj2.lopOffer = offernew2;
            obj2.copyUserDetails();
            obj2.showOfferorRelationShipOther();
            obj2.getOtherRelationShip();
            obj2.backToOfrParking();
            obj2.actionSavePropertyOwner();
            obj2.actionSavePropertyOwner2();
            obj2.actionSavePropertyOwnerAndContinue();
            System.assert(true);
        }

        
        //PBS_LOP_PropertyOwnerController obj1 = new PBS_LOP_PropertyOwnerController();
    }
}