force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/recordTypes/AAAP.recordType-meta.xml
<RecordType>
    <fullName>AAAP</fullName>
    <active>true</active>
    <label>AAAP</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Broker__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Broker__c</fullName>
    <description>RSAP Project Broker email from GREX</description>
    <inlineHelpText>RSAP Project Broker email from GREX</inlineHelpText>
    <label>RSAP GSA Broker Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Lease_Contracting_Officer__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Lease_Contracting_Officer__c</fullName>
    <description>RSAP GSA Project Lease Contracting Officer from GREX</description>
    <inlineHelpText>RSAP GSA Project Lease Contracting Officer from GREX</inlineHelpText>
    <label>RSAP GSA Lease Contracting Officer Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Leasing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Leasing_Specialist__c</fullName>
    <description>RSAP GSA Project Leasing Specialist from GREX</description>
    <inlineHelpText>RSAP GSA Project Leasing Specialist from GREX</inlineHelpText>
    <label>RSAP GSA Leasing Specialist Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_State__c</fullName>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/recordTypes/AAAP.recordType-meta.xml
<RecordType>
    <fullName>AAAP</fullName>
    <active>true</active>
    <label>AAAP</label>
</RecordType>

force-app/main/default/objects/Progress_Bar_Step__mdt/Progress_Bar_Step__mdt.object-meta.xml
<CustomObject>
    <label>Progress Bar Step</label>
    <pluralLabel>Progress Bar Steps</pluralLabel>
</CustomObject>

force-app/main/default/classes/PBS_Leasing_ProgressBarControllerTest.cls
@isTest
public class PBS_Leasing_ProgressBarControllerTest {
    @isTest
    public static void testPBSLeasingProgressBar(){
        
        // Create a new instance of the Progress_Bar_Step__mdt custom metadata type
        Progress_Bar_Step__mdt progressBar = new Progress_Bar_Step__mdt();
        
        // Call the apex class method to retrieve the progress bar steps by name
        List<Progress_Bar_Step__mdt> steps = PBS_Leasing_ProgressBarController.getSteps('AAAP_Workflow');
        System.assertNotEquals(steps.size(), 0 , 'Steps Should be Available');
    }
    
    @isTest
    public static void testgetPBS_AAAP_RLP_ObjRecords(){
        //Create a new RLP record and a related AAAP Offer record
        PBS_AAAP_RLP__c rlpObj = new PBS_AAAP_RLP__c(PBS_RSAP_Solicitation_Number__c = '1',PBS_RSAP_Solicitation_Status__c = true,
                                                     PBS_RSAP_City__c = 'test', PBS_RSAP_State__c = 'PA', PBS_RSAP_Broker__c = 'test',
                                                     PBS_RSAP_Lease_Contracting_Officer__c = 'test', PBS_RSAP_Leasing_Specialist__c = 'testing');
        insert rlpObj;
        PBS_AAAP_Offer__c offerRec = new PBS_AAAP_Offer__c(PBS_AAAP_Building_Name__c = 'AAAPtest', PBS_AAAP_RLP_Number__c = rlpObj.Id); 
        insert offerRec;  
        
        //Call the method to fetch RLP object records associated with the given offer
        PBS_Leasing_ProgressBarController.getPBS_AAAP_RLP_ObjRecords(offerRec.Id);
        PBS_Leasing_ProgressBarController.getPBS_AAAP_Offer_ObjRecords(offerRec.Id);
        
    }
}