force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DUNS_Number__c</fullName>
    <description>What is the property owner&apos;s Unique Entity Identifier # (formerly DUNS #)?</description>
    <label>UEI Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFEROR_INTEREST__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFEROR_INTEREST__c</fullName>
    <description>8. What is your relationship as the offeror, to the property owner?</description>
    <label>Offeror Relationship to Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFEROR_INTEREST_OTHER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFEROR_INTEREST_OTHER__c</fullName>
    <description>8. What is your relationship as the offeror, to the property owner? Other???</description>
    <label>Offeror Relation to Property Owner Other</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Address__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Address__c</fullName>
    <description>Street Address</description>
    <label>Property Owner Street Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_City__c</fullName>
    <description>City</description>
    <label>Property Owner City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Name__c</fullName>
    <description>What is the name of the property&apos;s recorded owner?</description>
    <label>Property Owner Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_State__c</fullName>
    <description>State</description>
    <label>Property Owner State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Zip__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Zip__c</fullName>
    <description>Zip Code</description>
    <label>Property Owner Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Signature_First_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Signature_First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SIGNATURE_LAST_NAME__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SIGNATURE_LAST_NAME__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Property_Owner_Same_as_Offeror__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Property_Owner_Same_as_Offeror__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Property Owner Same as Offeror</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Broker__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Broker__c</fullName>
    <description>RSAP Project Broker email from GREX</description>
    <inlineHelpText>RSAP Project Broker email from GREX</inlineHelpText>
    <label>RSAP GSA Broker Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Lease_Contracting_Officer__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Lease_Contracting_Officer__c</fullName>
    <description>RSAP GSA Project Lease Contracting Officer from GREX</description>
    <inlineHelpText>RSAP GSA Project Lease Contracting Officer from GREX</inlineHelpText>
    <label>RSAP GSA Lease Contracting Officer Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Leasing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Leasing_Specialist__c</fullName>
    <description>RSAP GSA Project Leasing Specialist from GREX</description>
    <inlineHelpText>RSAP GSA Project Leasing Specialist from GREX</inlineHelpText>
    <label>RSAP GSA Leasing Specialist Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_G_REX_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_G_REX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Solicitation/G-REX ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_State__c</fullName>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_LOP_PropertyOwnerController.cls
/**
 * Created by nkopparthi on 5/21/19.
 */

public with sharing class PBS_LOP_PropertyOwnerController {
    public boolean isValidUser { get; set; }
    public String offerId { get; set; }
    public String isNew { get; set; }
    public String action { get; set; }
    public string isEditable { get; set; }
    public User userDetail { get; set; }
    public String draftMsgFlag { get; set; }
    public Boolean viewOnly { get; set; }
    public string viewMsg { get; set; }
    public PBS_AAAP_Offer__c lopOffer { get; set; }
    public PBS_AAAP_RLP__c rlp {get; set;}
    public Boolean isTerminated { get; set; }
    public String ownerFullName { get; set; }
    public Boolean sameOwner {get; set;}
    public String pageUrl {get; set;}
    public String pageURLForRedirection{get;set;}

    public PBS_LOP_PropertyOwnerController(){

        userDetail = [SELECT u.Username, u.ProfileId,u.CompanyName, u.Name, u.Id, u.ContactId, u.LastName, u.FirstName, u.Street, u.City, u.State, u.PostalCode FROM User u WHERE u.Id = :UserInfo.getUserId()];
        action = ApexPages.currentPage().getParameters().get('action');
        offerId = ApexPages.currentPage().getParameters().get('offerId');
        isNew = ApexPages.currentPage().getParameters().get('isNew');
        isEditable = ApexPages.currentPage().getParameters().get('edit');
        draftMsgFlag = ApexPages.currentPage().getParameters().get('draftMsgFlag');

        if (isEditable == 'false') {
            viewOnly = true;
            viewMsg = 'Offer opened in view mode. Any changes made will not be saved.';
        } else {
            viewOnly = false;
        }

        if (ApexPages.currentPage().getParameters().get('offerId') != null) {
            lopOffer = PBS_AAAP_GlobalConstants.getOfferDetail(offerId);
            sameOwner = lopOffer.PBS_RSAP_Property_Owner_Same_as_Offeror__c;
            String rlpId = lopOffer.PBS_AAAP_RLP_Number__c;
            rlp = [
                    SELECT PBS_RSAP_Solicitation_G_REX_ID__c,PBS_RSAP_Solicitation_Number__c,PBS_RSAP_Solicitation_Status__c,PBS_RSAP_State__c,PBS_RSAP_Broker__c, PBS_RSAP_Lease_Contracting_Officer__c, PBS_RSAP_Leasing_Specialist__c,  //JK 2.9.21 added 3 new GREX contact email fields on RLP here
                            PBS_RSAP_Project_Number__c,PBS_RSAP_City__c
                    FROM PBS_AAAP_RLP__c
                    WHERE Id = :rlpId
                    LIMIT 1
            ];

            if (lopOffer.OwnerId == UserInfo.getUserId()) {
                isValidUser = true;
                if (lopOffer.PBS_AAAP_RLP_Number__r.PBS_RSAP_Solicitation_Status__c) {
                    isTerminated = false;
                } else {
                    isTerminated = true;
                }
                if (isTerminated) {
                    viewOnly = true;
                    viewMsg = 'Project is terminated. Offer opened in view mode. Any changes made will not be saved.';
                    System.debug('*** isEditable ***' + isEditable);
                } else if (lopOffer.PBS_AAAP_Offer_Status__c == 'Closed') {
                    viewOnly = true;
                    viewMsg = 'Project due date has elapsed. Offer opened in view mode. Any changes made will not be saved.';
                }
            } else {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, PBS_AAAP_GlobalConstants.ERROR_INAVLID_ACCESS_OWNERSHIP);
                Apexpages.addMessage(myMsg);
                isValidUser = false;
            }
        } else {
            isValidUser = true;
            lopOffer = new PBS_AAAP_Offer__c();
        }
    }

    public void copyUserDetails() {
        System.debug('inside copy User Details !!!');
        if(sameOwner) {
            ownerFullName = userDetail.FirstName + ' ' + userDetail.LastName;
            
            lopOffer.PBS_AAAP_Owner_Name__c = userDetail.FirstName + ' ' + userDetail.LastName;
            lopOffer.PBS_AAAP_SIGNATURE_LAST_NAME__c = userDetail.LastName;
            lopOffer.PBS_AAAP_Signature_First_Name__c = userDetail.FirstName;
            lopOffer.PBS_AAAP_Owner_Address__c = userDetail.Street;
            lopOffer.PBS_AAAP_Owner_City__c = userDetail.City;
            lopOffer.PBS_AAAP_Owner_State__c = userDetail.State;
            lopOffer.PBS_AAAP_Owner_Zip__c = userDetail.postalCode;
            lopOffer.PBS_RSAP_Property_Owner_Same_as_Offeror__c = TRUE;
            update lopOffer;
        } else {
            lopOffer.PBS_RSAP_Property_Owner_Same_as_Offeror__c = FALSE;
            update lopOffer;
        }
    }

    public Boolean otherRelationShip = false;
    public PageReference showOfferorRelationShipOther() {
        System.debug('Offeror Relation to property owner ::::::: ' + lopOffer.PBS_AAAP_OFFEROR_INTEREST__c);
        if (lopOffer.PBS_AAAP_OFFEROR_INTEREST__c == 'Other')
            otherRelationShip = true;
        else {
            otherRelationShip = false;
            lopOffer.PBS_AAAP_OFFEROR_INTEREST_OTHER__c = '';
        }

        return null;
    }

    public boolean getOtherRelationShip() {
        if (lopOffer.PBS_AAAP_OFFEROR_INTEREST__c == 'Other') {
            otherRelationShip = true;
        }
        return otherRelationShip;
    }

    public PageReference backToOfrParking() {

        PageReference p = new PageReference('/RSAP/Rates');
        p.getParameters().put('offerId', lopOffer.Id);
        if (isEditable == 'true') {
            p.getParameters().put('edit', 'true');
        } else {
            isEditable = 'false';
        }
       
        p.setRedirect(false);
        pageURLForRedirection = p.getUrl();
        pageURLForRedirection = pageURLForRedirection.replace('/RSAP/Rates', Label.LOP_Community_Base_URL+'RSAP-Rates');
        return null;
    }

    public void actionSavePropertyOwner() {
        try {

            
            draftMsgFlag = '';
            if (lopOffer.PBS_AAAP_Offer_Status__c == PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED) {
                PBS_AAAP_GlobalConstants.updateOfferToDraft(lopOffer);
                draftMsgFlag = 'true';
            }
            lopOffer.PBS_AAAP_SIGNATURE_LAST_NAME__c = userDetail.LastName;
            lopOffer.PBS_AAAP_Signature_First_Name__c = userDetail.FirstName;
            
            update lopOffer;
        } catch (Exception ex) {
            Apexpages.addMessages(ex);
        }

    }

    public pageReference actionSavePropertyOwner2() {
        try {

            
            PageReference p = null;
            p = new PageReference('/RSAP/PropertyOwner');
            draftMsgFlag = '';
            if (lopOffer.PBS_AAAP_Offer_Status__c == PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED) {
                PBS_AAAP_GlobalConstants.updateOfferToDraft(lopOffer);
                draftMsgFlag = 'true';
            }
            lopOffer.PBS_AAAP_SIGNATURE_LAST_NAME__c = userDetail.LastName;
            lopOffer.PBS_AAAP_Signature_First_Name__c = userDetail.FirstName;
            
            update lopOffer;
            p.getParameters().put('offerId', lopOffer.Id);
            if (draftMsgFlag == 'true') {
                p.getParameters().put('draftMsgFlag', 'true');
            }
            if (isEditable == 'true') {
                p.getParameters().put('edit', 'true');
            } else {
                isEditable = 'false';
            }
            
            p.setRedirect(false);
            pageURLForRedirection = p.getUrl();
            pageURLForRedirection = pageURLForRedirection.replace('/RSAP/PropertyOwner', Label.LOP_Community_Base_URL+'RSAP-PropertyOwner');
 
        } catch (Exception ex) {
            Apexpages.addMessages(ex);
        }
        return null;
    }

    public PageReference actionSavePropertyOwnerAndContinue() {
        PageReference p = null;
        boolean errorflag = FALSE;
        lopOffer.PBS_AAAP_SIGNATURE_LAST_NAME__c = userDetail.LastName;
        lopOffer.PBS_AAAP_Signature_First_Name__c = userDetail.FirstName;
        if(lopOffer.PBS_AAAP_Owner_Name__c == NULL || lopOffer.PBS_AAAP_Owner_Name__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '1. Property Owner Name is required'));
        }
        if(lopOffer.PBS_AAAP_Owner_Address__c == NULL || lopOffer.PBS_AAAP_Owner_Address__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '2. Property Owner Address is required'));
        }
        if(lopOffer.PBS_AAAP_Owner_City__c == NULL || lopOffer.PBS_AAAP_Owner_City__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '3. Property Owner City is required'));
        }
        if(lopOffer.PBS_AAAP_Owner_State__c == NULL || lopOffer.PBS_AAAP_Owner_State__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '4. Property Owner State is required.'));
        }
        if(lopOffer.PBS_AAAP_Owner_Zip__c == NULL || lopOffer.PBS_AAAP_Owner_Zip__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '5. Property Owner Zip is required.'));
        }
        if(lopOffer.PBS_AAAP_OFFEROR_INTEREST__c == NULL || lopOffer.PBS_AAAP_OFFEROR_INTEREST__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '6. Property Owner Relationship is required'));
        }

        if(lopOffer.PBS_AAAP_OFFEROR_INTEREST__c == 'Other' && (lopOffer.PBS_AAAP_OFFEROR_INTEREST_OTHER__c == NULL|| lopOffer.PBS_AAAP_OFFEROR_INTEREST_OTHER__c == '')){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '6a. Property Owner Relationship is required'));
        }
        if(lopOffer.PBS_AAAP_DUNS_Number__c == NULL || lopOffer.PBS_AAAP_DUNS_Number__c == ''){
            errorflag = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '7. What is the property owner’s Unique Entity Identifier (UEI)?'));
        }


        if (errorflag == true) {
            return null;
        }
        try {

            actionSavePropertyOwner();
            p = new PageReference('/RSAP/Attachments');
            p.getParameters().put('offerId', lopOffer.Id);
            if (draftMsgFlag == 'true') {
                p.getParameters().put('draftMsgFlag', 'true');
            }
            if (isEditable == 'true') {
                p.getParameters().put('edit', 'true');
            } else {
                isEditable = 'false';
            }
            p.setRedirect(true);

        } catch (Exception ex) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage());
            Apexpages.addMessage(myMsg);
        }
          if(pageURL == NULL || pageURL == ''){
                pageURLForRedirection = p.getUrl();
                pageURLForRedirection = pageURLForRedirection.replace('/RSAP/Attachments', Label.LOP_Community_Base_URL+'Offer-S-Attachments');
                p.setRedirect(false);
            } else {
                 p = new PageReference(pageURL);
                pageURLForRedirection = Label.LOP_Community_Base_URL+PBS_AAAP_Utility.getCommunityURL(p.getUrl());
                p.setRedirect(false);
              }  
      
        return null;
    }


    public PageReference actionCancel() {
        PageReference pref = new PageReference('/RSAP/PortalHome');
        
        pref.setRedirect(true);
        return pref;
    } 


}