force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_DEFAULT_MONTH_BEGIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DEFAULT_MONTH_BEGIN__c</fullName>
    <label>Default Start</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_DEFAULT_MONTH_END__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DEFAULT_MONTH_END__c</fullName>
    <label>Default End</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_MOVE_DEFAULT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_MOVE_DEFAULT__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>Total Estimated Physical Move Costs / ABOA SF. Not an Annual Rate.</inlineHelpText>
    <label>Estimated Phys Move Costs per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_PV_OTHER_UPFRONT_COSTS__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PV_OTHER_UPFRONT_COSTS__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Estimated $/ANSI BOMA ABOA Build out Cost, in excess of the TI for both a new and continuing lease</description>
    <inlineHelpText>Total Estimated Build Out Costs / ABOA SF, in excess of TI. Not an Annual Rate.</inlineHelpText>
    <label>Estimated Build Out Over TI per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Region__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region__c</fullName>
    <label>RLP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Region 1</fullName>
            </value>
            <value>
                <fullName>Region 2</fullName>
            </value>
            <value>
                <fullName>Region 3</fullName>
            </value>
            <value>
                <fullName>Region 4</fullName>
            </value>
            <value>
                <fullName>Region 5</fullName>
            </value>
            <value>
                <fullName>Region 6</fullName>
            </value>
            <value>
                <fullName>Region 7</fullName>
            </value>
            <value>
                <fullName>Region 8</fullName>
            </value>
            <value>
                <fullName>Region 9</fullName>
            </value>
            <value>
                <fullName>Region 10</fullName>
            </value>
            <value>
                <fullName>Region 11</fullName>
            </value>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
            <value>
                <fullName>10/5 Term - All Regions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_TELCOMM_DEFAULT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TELCOMM_DEFAULT__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Help Button - Total Estimated Telecom Cost / ABOA SF. Not an Annual Rate.</description>
    <inlineHelpText>Total Estimated Telecom Cost / ABOA SF. Not an Annual Rate.</inlineHelpText>
    <label>Estimated Telecom Cost per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Title__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Title__c</fullName>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_TIUSED_FOR_FIRM_TERM_NEW__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TIUSED_FOR_FIRM_TERM_NEW__c</fullName>
    <inlineHelpText>Total Estimated TI Allowance for New Space / ABOA SF. Not an amortized annual rate.</inlineHelpText>
    <label>Min TI for New Space per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_TIUSED_FOR_FIRM_TERM_SUCC__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TIUSED_FOR_FIRM_TERM_SUCC__c</fullName>
    <inlineHelpText>Total Estimated TI Allowance for Continuing Space / ABOA SF. Not an amortized annual rate.</inlineHelpText>
    <label>Min TI for Continuing Space per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Year__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Year__c</fullName>
    <label>RLP FY/Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PBS_AAAP_RLPService_Test.cls
@isTest
public class PBS_AAAP_RLPService_Test {    
    
    public static testMethod void getPhoneUser() {
        PBS_AAAP_RLPService.RequestWrapper obj = new PBS_AAAP_RLPService.RequestWrapper();
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/RLPService'; 
        req.addParameter('phoneNumber', '9876543210');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof('{		"PBS_RSAP_Solicitation_G_REX_ID" : "1234567893",		"PBS_RSAP_Solicitation_Number" : "24kjkjh325kj542",		"PBS_RSAP_Project_Number" : "1234567",		"PBS_RSAP_City" : "Washington",		"PBS_RSAP_State" : "DC",		"PBS_RSAP_Solicitation_Status" : true	}');
        RestContext.request = req;
        RestContext.response = res;        
        
        
        string resp = PBS_AAAP_RLPService.doPost();
        System.assertNotEquals(null, resp, 'Response should not be null');
        
    }
    
    public static testMethod void getPhoneUser2() {
        PBS_AAAP_RLPService.RequestWrapper obj = new PBS_AAAP_RLPService.RequestWrapper();
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/RLPService';
        req.addParameter('phoneNumber', '9876543210');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof('{		"PBS_RSAP_Solicitation_G_REX_ID" : "1234567893",		"PBS_RSAP_Solicitation_Number" : "24kjkjh325kj542",		"PBS_RSAP_Project_Number" : "1234567",		"PBS_RSAP_City" : "Washington",		"PBS_RSAP_State" : "DC",		"PBS_RSAP_Solicitation_Status" : true	}');
        RestContext.request = req;
        RestContext.response = res;
        
        
        string resp = PBS_AAAP_RLPService.doPost();
        
        PBS_AAAP_Offer__c off = new PBS_AAAP_Offer__c();
        off.PBS_AAAP_RLP_Number__c = Id.valueOf(resp);
        insert off;
        
        
        PBS_AAAP_RLPService.RequestWrapper obj2 = new PBS_AAAP_RLPService.RequestWrapper();
        
        RestRequest req2 = new RestRequest();
        RestResponse res2 = new RestResponse();
        req2.requestURI = '/services/apexrest/RLPService';
        req2.addParameter('phoneNumber', '9876543210');
        req2.httpMethod = 'POST';
        req2.requestBody = Blob.valueof('{		"PBS_RSAP_Solicitation_G_REX_ID" : "1234567893",		"PBS_RSAP_Solicitation_Number" : "24kjkjh325kj542",		"PBS_RSAP_Project_Number" : "1234567",		"PBS_RSAP_City" : "Washington",		"PBS_RSAP_State" : "DC",		"PBS_RSAP_Solicitation_Status" : false	}');
        
        RestContext.request = req2;
        RestContext.response = res2;
        
        string resp2 = PBS_AAAP_RLPService.doPost();
        System.assertNotEquals(null, resp2, 'Response should not be null');
    }
    //Julia Kantarovsky changes start here 2.9.21
    public static testMethod void testNewData() {
        //System.debug('JK testNewData');
        PBS_AAAP_RLPService.RequestWrapper obj = new PBS_AAAP_RLPService.RequestWrapper();
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/RLPService'; 
        req.addParameter('phoneNumber', '9876543210');
        req.httpMethod = 'POST';
        //req.requestBody = Blob.valueof('{		"PBS_RSAP_Solicitation_G_REX_ID" : "1234567893",		"PBS_RSAP_Solicitation_Number" : "24kjkjh325kj542",		"PBS_RSAP_Project_Number" : "1234567",		"PBS_RSAP_City" : "Washington",		"PBS_RSAP_State" : "DC",		"PBS_RSAP_Solicitation_Status" : true	}');
        
        req.requestBody = Blob.valueOf('{"PBS_RSAP_Solicitation_G_REX_ID":"321","PBS_RSAP_Solicitation_Number":"ABCDEFG","PBS_RSAP_Project_Number":"HIJKLMN","PBS_RSAP_City":"MILWAUKEE","PBS_RSAP_State":"WI","PBS_RSAP_Solicitation_Status":true,"PBS_RSAP_Agency":"SMALL BUSINESS ADMINISTRATION","PBS_RSAP_Lease_Acquisition_Strategy":"SLAT - Competitive - TI Allowance ","PBS_RSAP_Project_Contact":["Leasing Specialist, Jane Doe, N/A, jane.doe@gsa.gov","Lease Contracting Officer, John Doe, N/A, john.doe@gsa.gov","Broker Contractor, Joe Doe, N/A, joe.doe@gsa.gov"]}');       
        
        RestContext.request = req;
        RestContext.response = res;        
        
        string resp = PBS_AAAP_RLPService.doPost();
        //System.debug('JK in test resp ' + resp);
        System.assertNotEquals(null, resp, 'Response should not be null');
        
    }
    //JK changes end here
    @isTest
    public static void testChangeOffersStatus(){
        //create test data
        PBS_AAAP_RLP__c rlpRecord = new PBS_AAAP_RLP__c(PBS_AAAP_RLP_Number__c = '1234', PBS_AAAP_Title__c = 'test',
                                                        PBS_AAAP_Region__c = 'Region 1', PBS_AAAP_Year__c = '2024',
                                                        PBS_AAAP_TELCOMM_DEFAULT__c = 20.20, PBS_AAAP_PV_OTHER_UPFRONT_COSTS__c = 10.03,
                                                        PBS_AAAP_DEFAULT_MONTH_BEGIN__c	= '5', PBS_AAAP_TIUSED_FOR_FIRM_TERM_SUCC__c = 12.02,
                                                        PBS_AAAP_TIUSED_FOR_FIRM_TERM_NEW__c	= 16.02, PBS_AAAP_MOVE_DEFAULT__c = 13.05,
                                                        PBS_AAAP_DEFAULT_MONTH_END__c = '7');
        insert rlpRecord;
        
        PBS_AAAP_Offer__c offRecord = new PBS_AAAP_Offer__c(PBS_AAAP_RLP_Number__c = rlpRecord.Id, PBS_AAAP_Offer_Status__c = 'Draft');
		insert offRecord;
        Test.startTest();
        // call apex method 'changeOffersStatus'
        PBS_AAAP_RLPService.changeOffersStatus(rlpRecord.Id, 'Draft');
        test.stopTest();
        System.assertNotEquals(null, rlpRecord.Id, 'Response should not be null');
    }
}