force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_nonres_gar_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_nonres_gar_park__c</fullName>
    <description>(i) In a garage :</description>
    <label>Monthly cost nonreserved garage parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_nonres_sur_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_nonres_sur_park__c</fullName>
    <description>(ii) On a surface lot :</description>
    <label>Monthly cost nonreserved surface parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_res_gar_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_res_gar_park__c</fullName>
    <description>(i) In a garage:</description>
    <label>Monthly cost reserved garage parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_res_sur_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_res_sur_park__c</fullName>
    <description>(ii) On a surface lot:</description>
    <label>Monthly cost reserved surface parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Office_RSF_OFFERED__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Office_RSF_OFFERED__c</fullName>
    <description>What is the amount of Rentable Square Feet (RSF) offered?</description>
    <label>Rentable Square Feet (RSF) offered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Parking_Onsite__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Parking_Onsite__c</fullName>
    <label>Parking Onsite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SITE_AREA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SITE_AREA_TYPE__c</fullName>
    <description>Acres or SQFT (as entered by offeror)</description>
    <inlineHelpText>Acres or SQFT (as entered by offeror)</inlineHelpText>
    <label>Site Area Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SQFT</fullName>
                <default>true</default>
                <label>SQFT</label>
            </value>
            <value>
                <fullName>Acres</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SITE_SIZE_SQFT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SITE_SIZE_SQFT__c</fullName>
    <description>Site Size saved as SQFT</description>
    <inlineHelpText>Site Size saved as SQFT</inlineHelpText>
    <label>Site Size in SQFT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Solicitation_Id__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Solicitation_Id__c</fullName>
    <label>Solicitation Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Gov Space-Total(Srvc and Util)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Total_Ofc_ABOA_offered__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Ofc_ABOA_offered__c</fullName>
    <description>What is the amount of ANSI/BOMA Office Area Square Feet (ABOA SF) offered?</description>
    <inlineHelpText>What is the amount of ANSI/BOMA Office Area Square Feet (ABOA SF) offered?</inlineHelpText>
    <label>Total Ofc ABOA offered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Total_Structured_Parking_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Structured_Parking_Spaces__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Structured Parking Spaces</description>
    <inlineHelpText>Total Structured Parking Spaces</inlineHelpText>
    <label>Total Structured Parking Spaces</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Total_Surface_Parking_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Surface_Parking_Spaces__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Surface Parking Spaces</description>
    <label>Total Surface Parking Spaces</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Emp_Visitor_Structured_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Emp_Visitor_Structured_Spaces__c</fullName>
    <label>Structured Spaces Employee/Visitor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Emp_Visitor_Surface_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Emp_Visitor_Surface_Spaces__c</fullName>
    <label>Surface Spaces Employee/Visitor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_GOV_Structured_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_GOV_Structured_Spaces__c</fullName>
    <label>Structured Spaces Gov. Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_GOV_Surface_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_GOV_Surface_Spaces__c</fullName>
    <label>Surface Spaces Gov. Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Struct_NonResv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Struct_NonResv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered nonreserved structured parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c</fullName>
    <label>Structured Parking Annual Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Struct_Resv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Struct_Resv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered reserved structured parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Surf_NonResv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Surf_NonResv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered nonreserved surface parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Surf_Resv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Surf_Resv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered reserved surface parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c</fullName>
    <label>Surface Parking Annual cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Region__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region__c</fullName>
    <label>RLP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Region 1</fullName>
            </value>
            <value>
                <fullName>Region 2</fullName>
            </value>
            <value>
                <fullName>Region 3</fullName>
            </value>
            <value>
                <fullName>Region 4</fullName>
            </value>
            <value>
                <fullName>Region 5</fullName>
            </value>
            <value>
                <fullName>Region 6</fullName>
            </value>
            <value>
                <fullName>Region 7</fullName>
            </value>
            <value>
                <fullName>Region 8</fullName>
            </value>
            <value>
                <fullName>Region 9</fullName>
            </value>
            <value>
                <fullName>Region 10</fullName>
            </value>
            <value>
                <fullName>Region 11</fullName>
            </value>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
            <value>
                <fullName>10/5 Term - All Regions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_G_REX_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_G_REX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Solicitation/G-REX ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_PBS_LOP_ParkingController.cls
@isTest
public class Test_PBS_LOP_ParkingController {
    @isTest
    private static void testMethodWOOfferId(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            PBS_LOP_ParkingController obj = new PBS_LOP_ParkingController();
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = true;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            offernew.PBS_AAAP_Offer_Status__c = 'Closed';
            insert offernew;
            obj.backToOfrBlding();
            obj.lopOffer.PBS_RSAP_GOV_Surface_Spaces__c = 12;
            obj.lopOffer.PBS_AAAP_Total_Surface_Parking_Spaces__c = 10;
            obj.saveParkingInfo();
            
            offernew.PBS_AAAP_Monthly_cost_res_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_res_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_NonResv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_NonResv_Parking__c = 12;
            offernew.PBS_AAAP_Office_RSF_OFFERED__c = 100;
            offernew.PBS_AAAP_Total_Ofc_ABOA_offered__c = 100;
            update offernew;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_ParkingController obj1 = new PBS_LOP_ParkingController();
            obj.isEditable = 'true';
            obj.saveParkingInfo();
            obj1.saveParkingAndContinue();
            obj.actionCancel();
            offernew.PBS_AAAP_Office_RSF_OFFERED__c = null;
            offernew.PBS_AAAP_Total_Ofc_ABOA_offered__c = null;
            update offernew;
            obj.saveParkingInfo();
            System.assert(true);
        }
    }
    
    @isTest
    private static void testMethodWithOfferId(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = false;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            
            offernew.PBS_AAAP_Monthly_cost_res_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_res_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_NonResv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_NonResv_Parking__c = 12;
            
            insert offernew;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_ParkingController obj = new PBS_LOP_ParkingController();
            obj.isEditable = 'true';
            obj.backToOfrBlding();
            obj.saveParkingInfo();
            obj.saveParkingAndContinue();
            obj.actionCancel();
            
            PBS_AAAP_RLP__c rlp1 = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp1.PBS_RSAP_Solicitation_Number__c = '123';
            rlp1.PBS_RSAP_Solicitation_Status__c = true;
            rlp1.PBS_AAAP_Region__c = 'test region';
            insert rlp1;
            
            PBS_AAAP_Offer__c offernew1 = new PBS_AAAP_Offer__c();
            offernew1.PBS_AAAP_RLP_Number__c = rlp1.id;
            offernew1.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew1.RecordTypeId = RSAPRecTypeId;
            offernew1.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew1.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            insert offernew1;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew1.Id);
            ApexPages.currentPage().getParameters().put('edit','false');
            PBS_LOP_ParkingController obj1 = new PBS_LOP_ParkingController();
            
            offernew1.PBS_AAAP_SITE_SIZE_SQFT__c = 2;
            offernew1.PBS_AAAP_SITE_AREA_TYPE__c = 'Acres';
            update offernew1;
            obj.updateAreaType(offernew1);
        }
        PBS_LOP_ParkingController obj1 = new PBS_LOP_ParkingController();
        System.assert(true);
    }

    @isTest
    private static void testMethodWithOfferId2(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');

        System.runAs(u) {
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = false;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;

            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();

            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            
            offernew.PBS_AAAP_Monthly_cost_res_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_res_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_NonResv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_NonResv_Parking__c = 12;
            insert offernew;

            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            ApexPages.currentPage().getParameters().put('edit','true');//Added by Poorna
            PBS_LOP_ParkingController obj = new PBS_LOP_ParkingController();
			obj.isEditable = 'true';

            obj.backToOfrBlding();          
            obj.saveParkingInfo();
            
            offernew.PBS_AAAP_Total_Surface_Parking_Spaces__c = 5; 
            offernew.PBS_RSAP_Emp_Visitor_Surface_Spaces__c = 6;
            offernew.PBS_RSAP_GOV_Surface_Spaces__c = 2;
            offernew.PBS_RSAP_Emp_Visitor_Structured_Spaces__c = 7;
            offernew.PBS_AAAP_Total_Structured_Parking_Spaces__c = 6;  
            offernew.PBS_RSAP_GOV_Structured_Spaces__c = 7;             
            obj.lopOffer = offernew;
            obj.saveParkingInfo();
            obj.saveParkingAndContinue();
            obj.actionCancel();

            PBS_AAAP_RLP__c rlp1 = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp1.PBS_RSAP_Solicitation_Number__c = '123';
            rlp1.PBS_RSAP_Solicitation_Status__c = true;
            rlp1.PBS_AAAP_Region__c = 'test region';
            insert rlp1;

            PBS_AAAP_Offer__c offernew1 = new PBS_AAAP_Offer__c();
            offernew1.PBS_AAAP_RLP_Number__c = rlp1.id;
            offernew1.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offernew1.RecordTypeId = RSAPRecTypeId;
            offernew1.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew1.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            insert offernew1;

            ApexPages.currentPage().getParameters().put('offerId',offernew1.Id);
            ApexPages.currentPage().getParameters().put('edit','false');
            PBS_LOP_ParkingController obj1 = new PBS_LOP_ParkingController();

            offernew1.PBS_AAAP_SITE_SIZE_SQFT__c = 2;
            offernew1.PBS_AAAP_SITE_AREA_TYPE__c = 'Acres';
            update offernew1;
            obj.updateAreaType(offernew1);
        }
        PBS_LOP_ParkingController obj1 = new PBS_LOP_ParkingController();
        System.assert(true);
    }
    @isTest
    private static void testMethodForCoverage(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = true;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = 'Draft';
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            offernew.PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c = 12;
            offernew.PBS_AAAP_Office_RSF_OFFERED__c = 8000;
            offernew.PBS_AAAP_Total_Ofc_ABOA_offered__c = 7000;
            
            offernew.PBS_AAAP_Monthly_cost_res_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_res_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_NonResv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_NonResv_Parking__c = 12;
            insert offernew;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_ParkingController obj = new PBS_LOP_ParkingController();
            obj.isEditable = 'true';
            obj.backToOfrBlding();
            obj.lopOffer.PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c = 12;
            obj.lopOffer.PBS_AAAP_Office_RSF_OFFERED__c = 8000;
            obj.lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c = 9000;
            obj.lopOffer.PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c =20;
            obj.lopOffer.PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c = 1200;
            obj.lopOffer.PBS_AAAP_Parking_Onsite__c = 'Yes';            
            obj.lopOffer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;            
            obj.saveParkingInfo();
            obj.saveParkingAndContinue();
            obj.lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c = 7000;
            obj.saveParkingInfo();
            obj.lopOffer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            obj.saveParkingAndContinue();
            obj.actionCancel();
            obj.getOnsiteParkingItems();
            try{
            obj.saveData();
            }catch(Exception e){
                
            }
            obj.rlpType = 'asd';
            System.assert(true); 
        }
        
    }
    
 @isTest
    private static void testMethodForCoverage1(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testorguser@testorg.com');
            
        System.runAs(u) {
            
            PBS_AAAP_RLP__c rlp = PBS_AAAP_UtilityTest.createFY19RLP();
            rlp.PBS_RSAP_Solicitation_Number__c = '123';
            rlp.PBS_RSAP_Solicitation_Status__c = true;
            rlp.PBS_AAAP_Region__c = 'test region';
            insert RLP;
            
            Id RSAPRecTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
            
            PBS_AAAP_Offer__c offernew = new PBS_AAAP_Offer__c();
            offernew.PBS_AAAP_RLP_Number__c = RLP.id;
            offernew.PBS_AAAP_Offer_Status__c = 'Draft';
            offernew.RecordTypeId = RSAPRecTypeId;
            offernew.PBS_AAAP_Solicitation_Number__c = RLP.PBS_RSAP_Solicitation_Number__c;
            offernew.PBS_AAAP_Solicitation_Id__c = RLP.PBS_RSAP_Solicitation_G_REX_ID__c;
            offernew.PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c = 12;
            offernew.PBS_AAAP_Office_RSF_OFFERED__c = 8000;
            offernew.PBS_AAAP_Total_Ofc_ABOA_offered__c = 7000;
            
            offernew.PBS_AAAP_Monthly_cost_res_gar_park__c = null;
            offernew.PBS_RSAP_Struct_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_res_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_Resv_Parking__c = 12;
            offernew.PBS_AAAP_Monthly_cost_nonres_gar_park__c = 12;
            offernew.PBS_RSAP_Struct_NonResv_Parking__c = null;
            offernew.PBS_AAAP_Monthly_cost_nonres_sur_park__c = 12;
            offernew.PBS_RSAP_Surf_NonResv_Parking__c = 12;
            
            
            insert offernew;
            
            ApexPages.currentPage().getParameters().put('offerId',offernew.Id);
            PBS_LOP_ParkingController obj = new PBS_LOP_ParkingController();
            obj.isEditable = 'true';
            obj.backToOfrBlding();
            obj.lopOffer.PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c = 12;
            obj.lopOffer.PBS_AAAP_Office_RSF_OFFERED__c = 8000;
            obj.lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c = 7000;
            obj.lopOffer.PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c =20;
            obj.lopOffer.PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c = 1200;
            obj.lopOffer.PBS_AAAP_Parking_Onsite__c = 'Yes';
            
            obj.lopOffer.PBS_AAAP_Office_RSF_OFFERED__c = 10.10;
            obj.lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c = 15.10;
            obj.lopOffer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            obj.saveParkingInfo();
            
            obj.lopOffer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            obj.saveParkingAndContinue();
            
            obj.actionCancel();
            
            obj.getOnsiteParkingItems();
            
            try{
            obj.saveData();
            }catch(Exception e){
                
            }
            System.assert(true);
        }
    }
}