force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_STATUS__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
            <value>
                <fullName>Posted/Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Year__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Year__c</fullName>
    <label>RLP FY/Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Broker__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Broker__c</fullName>
    <description>RSAP Project Broker email from GREX</description>
    <inlineHelpText>RSAP Project Broker email from GREX</inlineHelpText>
    <label>RSAP GSA Broker Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Lease_Contracting_Officer__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Lease_Contracting_Officer__c</fullName>
    <description>RSAP GSA Project Lease Contracting Officer from GREX</description>
    <inlineHelpText>RSAP GSA Project Lease Contracting Officer from GREX</inlineHelpText>
    <label>RSAP GSA Lease Contracting Officer Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Leasing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Leasing_Specialist__c</fullName>
    <description>RSAP GSA Project Leasing Specialist from GREX</description>
    <inlineHelpText>RSAP GSA Project Leasing Specialist from GREX</inlineHelpText>
    <label>RSAP GSA Leasing Specialist Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_G_REX_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_G_REX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Solicitation/G-REX ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_State__c</fullName>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_AAAP_RLPService.cls
@RestResource(urlMapping='/RLPService')
global with sharing class PBS_AAAP_RLPService {
//Julia Kantarovsky added contacts functionality 2.12.21
    
    
    @HttpPost
    global static Id doPost(){  //string reqJSON
        
        string leasingSpecialist = '';
        string leaseContractingOfficer = '';
        string brokerContractor = '';
        
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        //System.debug('JK body ' + body);
        String requestString = body.toString();
        //System.debug('JK requestString ' + requestString);
        PBS_AAAP_RLP__c rlp = new PBS_AAAP_RLP__c();
        RequestWrapper reqWrapper = (RequestWrapper)JSON.deserialize(requestString, RequestWrapper.class);
        System.debug('reqWrapper: ' + reqWrapper);
        if(reqWrapper.PBS_RSAP_Project_Contact != null){
            for(String projectContact : reqWrapper.PBS_RSAP_Project_Contact){
                //System.debug('JK projectContact ' + projectContact);
                //System.debug('JK substring ' + projectContact.substring(projectContact.lastIndexOf(',') + 1).trim());
                if(projectContact.contains('Leasing Specialist')){
                    leasingSpecialist = projectContact.substring(projectContact.lastIndexOf(',') + 1).trim();
                }
                if(projectContact.contains('Lease Contracting Officer')){
                    leaseContractingOfficer = projectContact.substring(projectContact.lastIndexOf(',') + 1).trim();
                }
                if(projectContact.contains('Broker Contractor')){
                    brokerContractor = projectContact.substring(projectContact.lastIndexOf(',') + 1).trim();
                }
            }
        }
        
        // checing if data exist
        List<PBS_AAAP_RLP__c> lstExistingRecs = [SELECT ID, PBS_RSAP_Solicitation_Status__c
                                                        FROM PBS_AAAP_RLP__c
                                                        WHERE PBS_RSAP_Solicitation_G_REX_ID__c =: reqWrapper.PBS_RSAP_Solicitation_G_REX_ID];
        System.debug('lstExistingRecs: ' + lstExistingRecs);
        if(!lstExistingRecs.isEmpty()){
            rlp.Id = lstExistingRecs[0].Id;
            //System.debug('lstExistingRecs not empty, Id is: ' + rlp.Id);
        }
        
        // mapping data
        rlp.PBS_RSAP_Solicitation_G_REX_ID__c  = reqWrapper.PBS_RSAP_Solicitation_G_REX_ID;
        rlp.PBS_RSAP_Solicitation_Number__c  = reqWrapper.PBS_RSAP_Solicitation_Number;
        rlp.PBS_RSAP_Project_Number__c = reqWrapper.PBS_RSAP_Project_Number;
        rlp.PBS_RSAP_City__c = reqWrapper.PBS_RSAP_City;
        rlp.PBS_RSAP_State__c = reqWrapper.PBS_RSAP_State;
        rlp.PBS_RSAP_Solicitation_Status__c = reqWrapper.PBS_RSAP_Solicitation_Status; 
        rlp.PBS_AAAP_Year__c = string.ValueOf(System.Today().year());  
        //JK changes from here
        rlp.PBS_RSAP_Broker__c = brokerContractor;
        rlp.PBS_RSAP_Lease_Contracting_Officer__c = leaseContractingOfficer;
        rlp.PBS_RSAP_Leasing_Specialist__c = leasingSpecialist;
        //System.debug('JK rlp to here: ' + rlp);
        //JK changes to here
        
        // setting record type
        rlp.recordTypeId =  Schema.SObjectType.PBS_AAAP_RLP__c.getRecordTypeInfosByName().get('RSAP').getRecordTypeId();
        upsert rlp;
        
        rlp.PBS_AAAP_STATUS__c = '';
        update rlp;        
        // Todd Brown 5/7/2025 as a fix for issue found during 2025 Merge Surge UAT testing replaced the following line of code
        // to properly determine if RLP Solicitation Status changed and needs to be propogated to related Offers' Status.
        //if(rlp.PBS_RSAP_Solicitation_Status__c != reqWrapper.PBS_RSAP_Solicitation_Status){
        if(!lstExistingRecs.isEmpty() && (lstExistingRecs[0].PBS_RSAP_Solicitation_Status__c != reqWrapper.PBS_RSAP_Solicitation_Status)){
            if(reqWrapper.PBS_RSAP_Solicitation_Status){
                changeOffersStatus(rlp.Id, 'Draft');
            } else {
                changeOffersStatus(rlp.Id, 'Closed');
            }
        }        
        return rlp.Id;
    }
    
    
    public class RequestWrapper{
        public string PBS_RSAP_Solicitation_G_REX_ID {get;set;}
        public string PBS_RSAP_Solicitation_Number {get;set;}        
        public string PBS_RSAP_Project_Number {get;set;}
        public string PBS_RSAP_City {get;set;}
        public string PBS_RSAP_State {get;set;}
        public Boolean PBS_RSAP_Solicitation_Status {get;set;}    
        //JK changes start here:
        public List<string> PBS_RSAP_Project_Contact {get; set;}
        //JK changes end here
    }

    @future
    public static void changeOffersStatus(Id rlpId, String status){
        System.debug('changeOffersStatus start, rlpId: ' + rlpId + ' status: ' + status);
        List<PBS_AAAP_Offer__c> offrLst = new List<PBS_AAAP_Offer__c>();
        List<PBS_AAAP_Offer__c> lstUpdOffer = new List<PBS_AAAP_Offer__c>();
        offrLst = [
                    SELECT
                            Id,
                            PBS_AAAP_Offer_Status__c
                    FROM PBS_AAAP_Offer__c
                    WHERE PBS_AAAP_RLP_Number__c = :rlpId
        ];

        if(offrLst.size() > 0) {
            for (PBS_AAAP_Offer__c off : offrLst) {
                off.PBS_AAAP_Offer_Status__c = status;
                lstUpdOffer.add(off);
            }
        }

        if(!lstUpdOffer.isEmpty()){
            update lstUpdOffer;
        }
    }
    
}