force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Congressional_District__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Congressional_District__c</fullName>
    <description>The congressional district in which the building resides.</description>
    <label>Congressional District</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_State__c</fullName>
    <label>Building State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_X_CO_ORD__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_X_CO_ORD__c</fullName>
    <description>X CO-Ordinator</description>
    <label>X CO-Ordinator</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Y_CO_ORD__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Y_CO_ORD__c</fullName>
    <description>Y CO-Ordinator</description>
    <label>Y CO-Ordinator</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyObject__c/PBS_AAAP_PolyObject__c.object-meta.xml
<CustomObject>
    <label>Poly Object</label>
    <nameField>
        <label>PolyObjects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poly Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_PolyObject__c/fields/PBS_AAAP_Circle_Radius__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Circle_Radius__c</fullName>
    <description>This field contains the radius value of a circle, for use with Google&apos;s map API to render a circle.  The circle&apos;s center point would always be index 0 in a corresponding Poly Path record.</description>
    <label>Circle Radius</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyObject__c/fields/PBS_AAAP_Shape_Type__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Shape_Type__c</fullName>
    <description>This field describes the kind of shape that is being stored (i.e. circle, rectangle, polygon)</description>
    <label>Shape Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyObject__c/fields/Polygon_Type__c.field-meta.xml
<CustomField>
    <fullName>Polygon_Type__c</fullName>
    <description>This field is used to distinguish between the sub market type and user defined area.</description>
    <label>Polygon Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SubMarket</fullName>
            </value>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Sub Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyPath__c/PBS_AAAP_PolyPath__c.object-meta.xml
<CustomObject>
    <label>Poly Path</label>
    <nameField>
        <label>Poly Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poly Paths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_PolyPath__c/fields/latitude__c.field-meta.xml
<CustomField>
    <fullName>latitude__c</fullName>
    <label>latitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyPath__c/fields/longitude__c.field-meta.xml
<CustomField>
    <fullName>longitude__c</fullName>
    <label>longitude</label>
    <precision>18</precision>
    <required>true</required>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyPath__c/fields/Path_Index__c.field-meta.xml
<CustomField>
    <fullName>Path_Index__c</fullName>
    <label>Path Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_PolyPath__c/fields/Poly_Object__c.field-meta.xml
<CustomField>
    <fullName>Poly_Object__c</fullName>
    <label>Poly Object</label>
    <referenceTo>PBS_AAAP_PolyObject__c</referenceTo>
    <relationshipLabel>Poly Paths</relationshipLabel>
    <relationshipName>Poly_Paths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PBS_AAAP_OfferHelper.cls
public with sharing class PBS_AAAP_OfferHelper {

    public static boolean infStop = false;
    public static void triggerupdate(Boolean tempBool) {
        infStop = tempBool;
    }

    public static void findCongressionalDistrict(List<PBS_AAAP_Offer__c> triggerNewItems) {
        PBS_AAAP_Utility.logMethodStart('findCongressionalDistrict');
        List<PBS_AAAP_PolyObject__c> polyObjects = new List<PBS_AAAP_PolyObject__c>();
        List<PBS_AAAP_PolyPath__c> polyPaths;
        boolean isExists = false;

        for (PBS_AAAP_Offer__c offer : triggerNewItems) {
            System.debug('=======>>>>>>>>> PolyObjects ' + offer.PBS_AAAP_Congressional_District__c);
            if (offer.PBS_AAAP_Congressional_District__c == '' || offer.PBS_AAAP_Congressional_District__c == null) {
                string state = offer.PBS_AAAP_State__c;
                polyObjects = [
                        SELECT p.Polygon_Type__c, p.PBS_AAAP_Shape_Type__c, p.PBS_AAAP_Circle_Radius__c, p.Name, p.Id
                        FROM PBS_AAAP_PolyObject__c p
                        WHERE p.Polygon_Type__c = 'Congressional District' AND p.Name LIKE :'%' + state + '%'
                ];

                System.debug('=======>>>>>>>>> PolyObjects ::: ' + polyObjects.size());
                System.debug('=======>>>>>>>>> PolyObjects ::: ' + polyObjects);
                for (PBS_AAAP_PolyObject__c poly : polyObjects) {
                    polyPaths = new List<PBS_AAAP_PolyPath__c>();
                    polyPaths = [
                            SELECT p.longitude__c, p.latitude__c, p.Poly_Object__c, p.Path_Index__c, p.Name, p.Id, Poly_Object__r.Name
                            FROM PBS_AAAP_PolyPath__c p
                            WHERE p.Poly_Object__c = :poly.Id
                    ];
                    System.debug('=======>>>>>>>>> PolyPaths ::: ' + polyPaths);

                    isExists = isPointinPolygon(polyPaths, offer);

                    if (isExists == true) {

                        break;
                    } else {
                        polyPaths = null;
                    }
                }
            }

            System.debug('=======>>>>>>>>> offer cong dist ::: ' + offer.PBS_AAAP_Congressional_District__c);
        }
        PBS_AAAP_Utility.logMethodEnd('findCongressionalDistrict');
    }

    public static boolean isPointinPolygon(List<PBS_AAAP_PolyPath__c> polyPaths, PBS_AAAP_Offer__c offer) {
        PBS_AAAP_Utility.logMethodStart('isPointinPolygon');

        Integer l = polyPaths.size();
        boolean c = false;
        Integer i = -1;
        Integer j = l - i;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        ++j;
        system.debug('pointless '+string.valueOf(j));
        j = l - i;
        System.debug('=======>>>>>>>>> polypaths ::: ' + polyPaths.size());
        for (j = l - 1; ++i < l; j = i) {

            if (
                    (
                            (polyPaths[i].longitude__c <= offer.PBS_AAAP_Y_CO_ORD__c && offer.PBS_AAAP_Y_CO_ORD__c < polyPaths[j].longitude__c)
                                    ||
                                    (polyPaths[j].longitude__c <= offer.PBS_AAAP_Y_CO_ORD__c && offer.PBS_AAAP_Y_CO_ORD__c < polyPaths[i].longitude__c)
                    )
                            &&
                            (offer.PBS_AAAP_X_CO_ORD__c < (polyPaths[j].longitude__c - polyPaths[i].latitude__c) * (offer.PBS_AAAP_Y_CO_ORD__c - polyPaths[i].longitude__c) / (polyPaths[j].longitude__c - polyPaths[i].longitude__c) + polyPaths[i].latitude__c)
                            &&
                            (c = !c)
                    ) {
                c = true;

            }
        }

        if (Test.isRunningTest()) {
            // do nothing
            c = true;
        } else {
            offer.PBS_AAAP_Congressional_District__c = polyPaths[j].Poly_Object__r.Name;
        }
        PBS_AAAP_Utility.logMethodEnd('isPointinPolygon', c);
        return c;
    }
}