force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Common_Parent_TIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Common_Parent_TIN__c</fullName>
    <label>Common Parent TIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_CONTROLLED_BY_PARENT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_CONTROLLED_BY_PARENT__c</fullName>
    <description>Is the property owner owned or controlled by a common parent?</description>
    <label>Controlled by Common Parent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_DUNS_Number__c</fullName>
    <description>What is the property owner&apos;s Unique Entity Identifier # (formerly DUNS #)?</description>
    <label>UEI Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFEROR_INTEREST__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFEROR_INTEREST__c</fullName>
    <description>8. What is your relationship as the offeror, to the property owner?</description>
    <label>Offeror Relationship to Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Address__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Address__c</fullName>
    <description>Street Address</description>
    <label>Property Owner Street Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_City__c</fullName>
    <description>City</description>
    <label>Property Owner City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Country__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Country__c</fullName>
    <description>Country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Deps</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Main_Phone__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Main_Phone__c</fullName>
    <description>What is the main phone number for the property&apos;s recorded owner?</description>
    <label>Owner Main Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Name__c</fullName>
    <description>What is the name of the property&apos;s recorded owner?</description>
    <label>Property Owner Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_State__c</fullName>
    <description>State</description>
    <label>Property Owner State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_TIN_Assigned__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_TIN_Assigned__c</fullName>
    <label>Owner TIN Assigned</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_TIN_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_TIN_Status__c</fullName>
    <description>What is the status of the property owner&apos;s taxpayer identification number (TIN)?</description>
    <label>Owner TIN Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Applied for</fullName>
            </value>
            <value>
                <fullName>KNOWN</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Zip__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Zip__c</fullName>
    <description>Zip Code</description>
    <label>Property Owner Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_PARENT_NAME__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PARENT_NAME__c</fullName>
    <description>What is the name of the common parent?</description>
    <label>Common Parent Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_PROPERTY_OWNER_TYPE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PROPERTY_OWNER_TYPE__c</fullName>
    <description>13. Is the property owner&apos;s ownership interest in the property fee simple or lease hold interest*?</description>
    <label>Property Ownership Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee Simple</fullName>
            </value>
            <value>
                <fullName>Lease hold interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_TYPE_OF_ORG__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TYPE_OF_ORG__c</fullName>
    <description>What is the property owner&apos;s type of recorded relationship?</description>
    <label>Propert Owner Type Of Recorded Relation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Corporate entity (not tax-exempt)</fullName>
            </value>
            <value>
                <fullName>Corporate entity (tax-exempt)</fullName>
            </value>
            <value>
                <fullName>Government entity(Federal,State,or local)</fullName>
            </value>
            <value>
                <fullName>Foreign government</fullName>
            </value>
            <value>
                <fullName>International organization per 26 CFR 1.6049-4</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_PBS_AAAP_OfferPropertyOwnerContr.cls
@IsTest
private class Test_PBS_AAAP_OfferPropertyOwnerContr {

    static testMethod void myOfferPropertyOwnerConstructorTest() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_DRAFT;
            offer.PBS_AAAP_OFFEROR_INTEREST__c = 'Other';
            offer.PBS_AAAP_TYPE_OF_ORG__c = 'Other';
            offer.PBS_AAAP_Owner_TIN_Status__c = 'KNOWN';
            offer.PBS_AAAP_CONTROLLED_BY_PARENT__c = 'Yes';
            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;

            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();

            List<SelectOption> items = opc.getItems();
            System.assert(items.size() > 0);

            List<SelectOption> partialItems = opc.getTINNotRequiredReasonItems();
            System.assert(partialItems.size() > 0);

            Boolean flag = opc.getOtherRelationShip();
            System.assert(flag == true);
            PageReference page = opc.showOfferorRelationShipOther();
            System.assert(page == null);

            flag = opc.getRecordOwnershipOther();
            System.assert(flag == true);

            opc.showPropertyOwnerCommonParentSection();
            flag = opc.getParentName();
            System.assert(flag == true);

            page = opc.showRecordOwnershipOther();
            System.assert(page == null);

            flag = opc.getTinStatusKnown();
            System.assert(flag == true);

            page = opc.showTINStatus();
            System.assert(page == null);

            page = opc.actionSavePropertyOwnerAndContinue();
            System.assert(page == null);
            
            opc.sameOwner = TRUE;
            opc.copyUserDetails();
            Test.stopTest();


        }
    }
    static testMethod void myOfferPropertyOwnerConstructorTestErrors() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_DRAFT;
            offer.PBS_AAAP_OFFEROR_INTEREST__c = 'Other';
            offer.PBS_AAAP_TYPE_OF_ORG__c = 'Other';
            offer.PBS_AAAP_Owner_TIN_Status__c = 'KNOWN';
            offer.PBS_AAAP_CONTROLLED_BY_PARENT__c = 'Yes';
            offer.PBS_AAAP_Owner_Name__c  = null;
            offer.PBS_AAAP_Owner_Address__c  = null;
            offer.PBS_AAAP_Owner_Country__c  = null;
            offer.PBS_AAAP_Owner_City__c  = null;
            offer.PBS_AAAP_OFFEROR_INTEREST__c  = null;
            offer.PBS_AAAP_OFFEROR_INTEREST__c  = null;
            offer.PBS_AAAP_DUNS_Number__c  = null;

            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;

            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();

            List<SelectOption> items = opc.getItems();
            System.assert(items.size() > 0);

            List<SelectOption> partialItems = opc.getTINNotRequiredReasonItems();
            System.assert(partialItems.size() > 0);

            Boolean flag = opc.getOtherRelationShip();
            opc.sameOwner = TRUE;
            opc.copyUserDetails();
            Test.stopTest();
        }
    }

    static testMethod void myOfferPropertyOwnerConstructorTest1() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_DRAFT;
            offer.PBS_AAAP_OFFEROR_INTEREST__c = 'Agent';
            offer.PBS_AAAP_TYPE_OF_ORG__c = 'Partnership';
            offer.PBS_AAAP_Owner_TIN_Status__c = 'Not Required';
            offer.PBS_AAAP_CONTROLLED_BY_PARENT__c = 'No';
            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;


            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();
            opc.sameOwner = TRUE;//JKantarovsky added this line for code coverage 7/2021

            Boolean flag = opc.getOtherRelationShip();
            System.assert(flag == false);
            PageReference page = opc.showOfferorRelationShipOther();
            System.assert(page == null);

            flag = opc.getRecordOwnershipOther();
            System.assert(flag == false);

            page = opc.showRecordOwnershipOther();
            System.assert(page == null);

            opc.showPropertyOwnerCommonParentSection();

            flag = opc.getTinStatusNotRequired();
            System.assert(flag == true);

            page = opc.showTINStatus();
            System.assert(page == null);

            page = opc.actionDeleteOffer();
            System.assert(page != null);

            page = opc.backToOfrParking();
            System.assert(page == null);

            page = opc.actionSavePropertyOwner();
            Test.stopTest();
        }
    }

    static testMethod void myOfferPropertyOwnerConstructorTest2() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offer.PBS_AAAP_Owner_TIN_Status__c = 'Applied for';
            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;


            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();

            PageReference page = opc.showTINStatus();
            System.assert(page == null);

            page = opc.actionDeleteOffer();
            System.assert(page == null);
            Test.stopTest();
        }
    }

    static testMethod void myOfferPropertyOwnerExceptionTest2() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offer.PBS_AAAP_Owner_TIN_Status__c = null;
            offer.PBS_AAAP_Owner_Name__c = null;
            offer.PBS_AAAP_Owner_Address__c = null;
            offer.PBS_AAAP_Owner_Country__c = null;
            offer.PBS_AAAP_Owner_City__c = null;
            offer.PBS_AAAP_Owner_State__c = null;
            offer.PBS_AAAP_Owner_Zip__c = null;
            offer.PBS_AAAP_Owner_Main_Phone__c = null;
            offer.PBS_AAAP_Common_Parent_TIN__c = null;
            offer.PBS_AAAP_DUNS_Number__c = null;
            offer.PBS_AAAP_OFFEROR_INTEREST__c = null;
            offer.PBS_AAAP_TYPE_OF_ORG__c = null;
            offer.PBS_AAAP_PROPERTY_OWNER_TYPE__c = null;
            offer.PBS_AAAP_CONTROLLED_BY_PARENT__c = null;

            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;

            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();

            PageReference page = opc.actionSavePropertyOwnerAndContinue(); // throws exception as we are not passing id to update the offer.
            System.assert(page == null);
            Test.stopTest();
        }
    }

    static testMethod void myOfferPropertyOwnerExceptionTest3() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            offer.PBS_AAAP_Owner_TIN_Status__c = PBS_AAAP_GlobalConstants.TIN_KNOWN;
            offer.PBS_AAAP_Owner_Name__c = null;
            offer.PBS_AAAP_Owner_Address__c = null;
            offer.PBS_AAAP_Owner_Country__c = 'United States';
            offer.PBS_AAAP_Owner_City__c = null;
            offer.PBS_AAAP_Owner_State__c = null;
            offer.PBS_AAAP_Owner_Zip__c = null;
            offer.PBS_AAAP_Owner_Main_Phone__c = null;
            offer.PBS_AAAP_Common_Parent_TIN__c = null;
            offer.PBS_AAAP_DUNS_Number__c = null;
            offer.PBS_AAAP_OFFEROR_INTEREST__c = null;
            offer.PBS_AAAP_TYPE_OF_ORG__c = null;
            offer.PBS_AAAP_PROPERTY_OWNER_TYPE__c = null;
            offer.PBS_AAAP_CONTROLLED_BY_PARENT__c = 'Yes';
            offer.PBS_AAAP_PARENT_NAME__c = null;
            offer.PBS_AAAP_Owner_TIN_Assigned__c = null;
            offer.PBS_AAAP_Building_Name__c = null;

            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;

            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();

            PageReference page = opc.actionSavePropertyOwnerAndContinue(); // throws exception as we are not passing id to update the offer.
            System.assert(page == null);

            Test.stopTest();
        }
    }
    
    static testMethod void myOfferPropertyOwnerExceptionTest4() {

        User u = PBS_AAAP_UtilityTest.createPortalUser();

        System.runAs(u) {

            PageReference currentPage = new PageReference('/apex/PBS_AAAP_OfferPropertyOwner');
            Test.setCurrentPage(currentPage);
            PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
            offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
            insert offer;
            ApexPages.currentPage().getParameters().put('offerId', offer.id);
            PBS_AAAP_OfferPropertyOwner opc;

            Test.startTest();
            opc = new PBS_AAAP_OfferPropertyOwner();
            opc.sameOwner = TRUE;

            PageReference page = opc.actionSavePropertyOwnerAndContinue();
            System.assert(page == null);

            page = opc.actionCancel();
            System.assert(page != null);
            Test.stopTest();
        }
    }
}