force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_PBS_AAAP_insideHeaderController.cls
@isTest
public class Test_PBS_AAAP_insideHeaderController {
    @testSetup
    static void setup () {
        PBS_AAAP_Offer__c offer1 = new PBS_AAAP_Offer__c();
        offer1.PBS_AAAP_Offer_Status__c = 'Draft';
        insert offer1;
        
        PBS_AAAP_Offer__c offer2 = new PBS_AAAP_Offer__c();
        offer2.PBS_AAAP_Offer_Status__c = 'Submitted';
        insert offer2;
    }

	@isTest
    static void updateOfferStatusTest () {
        List<PBS_AAAP_Offer__c> offers = [SELECT Id FROM PBS_AAAP_Offer__c WHERE PBS_AAAP_Offer_Status__c = 'Submitted'];
        System.assertEquals(1, offers.size());
        
        PageReference pg = Page.PBS_AAAP_IdentifyWinnerSearch;
        System.Test.setCurrentPage(pg);
        ApexPages.currentPage().getParameters().put('offerId', offers[0].Id);
        
        PBS_AAAP_insideHeaderController controller = new PBS_AAAP_insideHeaderController();
        
        System.Test.startTest();
        	controller.updateOfferStatus();
        System.Test.stopTest();
        
        offers = [SELECT Id, PBS_AAAP_Offer_Status__c FROM PBS_AAAP_Offer__c WHERE Id = :offers[0].Id];
        System.assertEquals(1, offers.size());
        System.assertEquals('Pending Modification', offers[0].PBS_AAAP_Offer_Status__c);
    }
}