force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Country__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Country__c</fullName>
    <defaultValue>&quot;United States&quot;</defaultValue>
    <description>Country</description>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_County__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_County__c</fullName>
    <description>The county in which the building resides.</description>
    <label>County</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Submission_Date__c</fullName>
    <label>Offer Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Signature_First_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Signature_First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SIGNATURE_LAST_NAME__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SIGNATURE_LAST_NAME__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_State__c</fullName>
    <label>Building State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Street_Address__c</fullName>
    <description>Street Address</description>
    <label>Building Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Vacant_Premise_Rate__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Vacant_Premise_Rate__c</fullName>
    <description>Adjustment for Vacant premises</description>
    <inlineHelpText>Adjustment for Vacant premises</inlineHelpText>
    <label>Adj for Vacant Premises Rate per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ZipCode__c</fullName>
    <description>Zip Code</description>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/recordTypes/AAAP.recordType-meta.xml
<RecordType>
    <fullName>AAAP</fullName>
    <active>true</active>
    <label>AAAP</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_Property__c/PBS_AAAP_Property__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains relevant information about a building, flex space, or warehouse used in an offer.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Property__c/fields/PBS_AAAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Property__c/fields/PBS_AAAP_Country__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Property__c/fields/PBS_AAAP_County__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Property__c/fields/PBS_AAAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Property__c/fields/PBS_AAAP_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Street_Address__c</fullName>
    <label>Building Street Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Property__c/fields/PBS_AAAP_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_isActive__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_Region__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region__c</fullName>
    <label>RLP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Region 1</fullName>
            </value>
            <value>
                <fullName>Region 2</fullName>
            </value>
            <value>
                <fullName>Region 3</fullName>
            </value>
            <value>
                <fullName>Region 4</fullName>
            </value>
            <value>
                <fullName>Region 5</fullName>
            </value>
            <value>
                <fullName>Region 6</fullName>
            </value>
            <value>
                <fullName>Region 7</fullName>
            </value>
            <value>
                <fullName>Region 8</fullName>
            </value>
            <value>
                <fullName>Region 9</fullName>
            </value>
            <value>
                <fullName>Region 10</fullName>
            </value>
            <value>
                <fullName>Region 11</fullName>
            </value>
            <value>
                <fullName>National Capital Region</fullName>
            </value>
            <value>
                <fullName>10/5 Term - All Regions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_STATUS__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
            <value>
                <fullName>Posted/Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_G_REX_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_G_REX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Solicitation/G-REX ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/recordTypes/AAAP.recordType-meta.xml
<RecordType>
    <fullName>AAAP</fullName>
    <active>true</active>
    <label>AAAP</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/PBS_AAAP_RLP_Regions_Map__c.object-meta.xml
<CustomObject>
    <label>RLP Regions Map</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>RLP Regions Map Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLP Regions Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/fields/PBS_AAAP_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Region_Name__c</fullName>
    <label>RLP Region Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/fields/PBS_AAAP_RLP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_State__c</fullName>
    <label>RLP State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP_Regions_Map__c/fields/PBS_AAAP_RLP_State_Abbrevation__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_State_Abbrevation__c</fullName>
    <label>RLP State Abbrevation</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_Leasing_OfferRLPControllerTest.cls
@isTest
public class PBS_Leasing_OfferRLPControllerTest {
    @testSetup
    static void setupTestData() {
        Id offerRecordType = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('AAAP').getRecordTypeId();
        
        Id rlpRecordType = Schema.SObjectType.PBS_AAAP_RLP__c.getRecordTypeInfosByName().get('AAAP').getRecordTypeId();
        
        PBS_AAAP_Property__c testProperty = new PBS_AAAP_Property__c(PBS_AAAP_County__c = 'Fillmore County', PBS_AAAP_City__c = 'Spring Valley',
                                                                     PBS_AAAP_State__c = 'MN');
        insert testProperty;
        
        List<PBS_AAAP_RLP__c> rlpList = new List<PBS_AAAP_RLP__c>();
        rlpList.add(new PBS_AAAP_RLP__c(PBS_AAAP_RLP_Number__c = 'NCR', PBS_RSAP_Project_Number__c = 'Proj-12',
                                        PBS_RSAP_Solicitation_Number__c = 'Sol-12345', PBS_RSAP_Solicitation_G_REX_ID__c = 'G-REX-2025',
                                        PBS_RSAP_Solicitation_Status__c = true, PBS_AAAP_Region__c = 'Region 1',
                                        RecordTypeId = rlpRecordType, PBS_AAAP_STATUS__c = 'Posted/Active',
                                        PBS_AAAP_isActive__c = TRUE));
        insert rlpList;
        
        
        PBS_AAAP_RLP_Regions_Map__c testMap = new PBS_AAAP_RLP_Regions_Map__c(PBS_AAAP_Region_Name__c = 'National Capital Region',
                                                                              PBS_AAAP_RLP_State_Abbrevation__c = testProperty.PBS_AAAP_State__c, 
                                                                              PBS_AAAP_RLP_State__c = 'Herndon');
        insert testMap;  
        
        PBS_AAAP_Offer__c offerRec = new PBS_AAAP_Offer__c(PBS_AAAP_Building_Name__c = 'Test Building', PBS_AAAP_Street_Address__c = '123 Test St',
                                                           PBS_AAAP_Country__c = 'Test Country',PBS_AAAP_City__c = 'Test City', RecordTypeId = offerRecordType,
                                                           PBS_AAAP_State__c = 'Test State',PBS_AAAP_ZipCode__c = '12345', //PBS_AAAP_RLP_Number__c = rlpList.Id,  
                                                           PBS_AAAP_Offer_Status__c = 'Draft', PBS_AAAP_Offer_Submission_Date__c = Date.today(),PBS_AAAP_Vacant_Premise_Rate__c = 10,
                                                           PBS_AAAP_Signature_First_Name__c = 'test', PBS_AAAP_SIGNATURE_LAST_NAME__c = 'user',PBS_AAAP_GEN_PURPOSE_RENTABLE__c = 1000,
                                                           PBS_AAAP_OFFICE_SPACE_RSF__c = 600, PBS_AAAP_RETAIL_SPACE_RSF__c = 200, PBS_AAAP_GARAGE_SPACE_RSF__c = 200, 
                                                           PBS_AAAP_OFFEROR_INTEREST__c = 'Owner', PBS_AAAP_ACK_LTR_COMPLETED__c = 'No',PBS_AAAP_ACK_REPRESENT_OTHERS__c = 'No',
                                                           PBS_AAAP_Owner_Name__c = 'Test User', PBS_AAAP_X_CO_ORD__c = 123.00, PBS_AAAP_ACCEPTED_TERMS_AND_COND__c = true, 
                                                           PBS_AAAP_Y_CO_ORD__c = 456.60, PBS_AAAP_Is_Offer_Valid__c = true);
        insert offerRec;    
    }
    
    @isTest
    static void testSearchRecords() {
        setupTestData();
        PBS_AAAP_Property__c prop = [SELECT Id FROM PBS_AAAP_Property__c LIMIT 1];
        List<PBS_AAAP_RLP__c> rlp = [SELECT Id, PBS_RSAP_Solicitation_Number__c, PBS_AAAP_RLP_Number__c FROM PBS_AAAP_RLP__c  where PBS_RSAP_Solicitation_Number__c = 'Sol-12345' LIMIT 1];
        
        PBS_Leasing_OfferRLPController.RLPResponseWrapper response0 = PBS_Leasing_OfferRLPController.searchRecords('', prop.Id);
        
        PBS_Leasing_OfferRLPController.RLPResponseWrapper response = PBS_Leasing_OfferRLPController.searchRecords('Sol-12345', prop.Id);
        rlp[0].PBS_AAAP_STATUS__c = 'Posted/Active';
        rlp[0].PBS_RSAP_Solicitation_Number__c = '';
        update rlp;
        System.debug([SELECT Id, PBS_AAAP_RLP_Number__c, PBS_RSAP_Project_Number__c, PBS_RSAP_Solicitation_Number__c, PBS_RSAP_Solicitation_G_REX_ID__c, PBS_RSAP_Solicitation_Status__c, recordtype.name, PBS_AAAP_Region__c FROM PBS_AAAP_RLP__c WHERE PBS_AAAP_STATUS__c = 'Posted/Active' AND PBS_AAAP_isActive__c = TRUE AND PBS_AAAP_RLP_Number__c = 'NCR']);
        PBS_Leasing_OfferRLPController.RLPResponseWrapper response1 = PBS_Leasing_OfferRLPController.searchRecords('NCR', prop.Id);
       	
        rlp[0].PBS_AAAP_STATUS__c = 'Draft';
        update rlp;
        rlp[0].PBS_AAAP_Region__c = 'Region 1';
        rlp[0].PBS_AAAP_RLP_Number__c = 'Region 1';
        rlp[0].PBS_AAAP_STATUS__c = 'Posted/Active';
        rlp[0].PBS_RSAP_Solicitation_Number__c = '';
        update rlp;
        
        PBS_Leasing_OfferRLPController.RLPResponseWrapper response2 = PBS_Leasing_OfferRLPController.searchRecords('Region 1', prop.Id);
            
        System.assert(response != null, 'Response should not be null');
    }
    
    @isTest
    static void testCreateOfferRecord() {
        PBS_AAAP_Offer__c testOffer = [SELECT Id, PBS_AAAP_Common_Area_Factor__c FROM PBS_AAAP_Offer__c LIMIT 1];
        Test.startTest();
        PBS_Leasing_OfferRLPController.ResponseWrapper response = PBS_Leasing_OfferRLPController.createOfferRecord(testOffer, 'Offer-RLP', 'AAAP');
        Test.stopTest();
        System.assert(response != null, 'Response should not be null');
    }
    
    @isTest
    static void testGetPropertyOfferDetails() {
        PBS_AAAP_Offer__c testOffer = [SELECT Id FROM PBS_AAAP_Offer__c LIMIT 1];
        Test.startTest();
        PBS_Leasing_OfferPropertyWrapper.objectWrapper response = PBS_Leasing_OfferRLPController.getPropertyOfferDetails(testOffer.Id);
        Test.stopTest();
        System.assert(response != null, 'Response should not be null');
    }
    
    @isTest
    static void testUpdateOfferRecord() {
        PBS_AAAP_Offer__c testOffer = [SELECT Id FROM PBS_AAAP_Offer__c LIMIT 1];
        testOffer.PBS_AAAP_Building_Name__c = 'Test-Building-offer';
        update testOffer;
        Test.startTest();
        PBS_Leasing_OfferRLPController.ResponseWrapper response = PBS_Leasing_OfferRLPController.updateOfferRecord(testOffer, 'offer-RLP');
        Test.stopTest();
        System.assert(response.isSuccess, 'Update should be successful');
    }
    
    @isTest
    static void testValidateOffer() {
        
        PBS_AAAP_Offer__c testoffer = new PBS_AAAP_Offer__c(PBS_AAAP_Building_Name__c = 'Test Building', PBS_AAAP_Street_Address__c = '123 Test St',
                                                            PBS_AAAP_Country__c = 'Test Country',PBS_AAAP_City__c = 'Test City');
        insert testoffer;
        
        Test.startTest();
        PBS_Leasing_OfferRLPController.ResponseWrapper response = PBS_Leasing_OfferRLPController.validateOffer(testOffer, 'Offer-M-Eligibility');
        
        Test.stopTest();
        System.assert(response != null, 'Response should not be null');
    }
}