force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Common_Area_Factor__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Common_Area_Factor__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Common Area Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_nonres_gar_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_nonres_gar_park__c</fullName>
    <description>(i) In a garage :</description>
    <label>Monthly cost nonreserved garage parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_nonres_sur_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_nonres_sur_park__c</fullName>
    <description>(ii) On a surface lot :</description>
    <label>Monthly cost nonreserved surface parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_res_gar_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_res_gar_park__c</fullName>
    <description>(i) In a garage:</description>
    <label>Monthly cost reserved garage parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Monthly_cost_res_sur_park__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Monthly_cost_res_sur_park__c</fullName>
    <description>(ii) On a surface lot:</description>
    <label>Monthly cost reserved surface parking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Office_RSF_OFFERED__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Office_RSF_OFFERED__c</fullName>
    <description>What is the amount of Rentable Square Feet (RSF) offered?</description>
    <label>Rentable Square Feet (RSF) offered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OP_COST_COST_PER_ABOA__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OP_COST_COST_PER_ABOA__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Operating Cost per ABOA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OP_COST_COST_PER_RSF__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OP_COST_COST_PER_RSF__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Operating Cost per RSF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Parking_Onsite__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Parking_Onsite__c</fullName>
    <label>Parking Onsite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SITE_AREA_TYPE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SITE_AREA_TYPE__c</fullName>
    <description>Acres or SQFT (as entered by offeror)</description>
    <inlineHelpText>Acres or SQFT (as entered by offeror)</inlineHelpText>
    <label>Site Area Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SQFT</fullName>
                <default>true</default>
                <label>SQFT</label>
            </value>
            <value>
                <fullName>Acres</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SITE_SIZE_SQFT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SITE_SIZE_SQFT__c</fullName>
    <description>Site Size saved as SQFT</description>
    <inlineHelpText>Site Size saved as SQFT</inlineHelpText>
    <label>Site Size in SQFT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Gov Space-Total(Srvc and Util)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Total_Ofc_ABOA_offered__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Ofc_ABOA_offered__c</fullName>
    <description>What is the amount of ANSI/BOMA Office Area Square Feet (ABOA SF) offered?</description>
    <inlineHelpText>What is the amount of ANSI/BOMA Office Area Square Feet (ABOA SF) offered?</inlineHelpText>
    <label>Total Ofc ABOA offered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Total_Structured_Parking_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Structured_Parking_Spaces__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Structured Parking Spaces</description>
    <inlineHelpText>Total Structured Parking Spaces</inlineHelpText>
    <label>Total Structured Parking Spaces</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Total_Surface_Parking_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Surface_Parking_Spaces__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Surface Parking Spaces</description>
    <label>Total Surface Parking Spaces</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Emp_Visitor_Structured_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Emp_Visitor_Structured_Spaces__c</fullName>
    <label>Structured Spaces Employee/Visitor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Emp_Visitor_Surface_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Emp_Visitor_Surface_Spaces__c</fullName>
    <label>Surface Spaces Employee/Visitor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_GOV_Structured_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_GOV_Structured_Spaces__c</fullName>
    <label>Structured Spaces Gov. Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_GOV_Surface_Spaces__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_GOV_Surface_Spaces__c</fullName>
    <label>Surface Spaces Gov. Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Struct_NonResv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Struct_NonResv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered nonreserved structured parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c</fullName>
    <label>Structured Parking Annual Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Struct_Resv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Struct_Resv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered reserved structured parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Surf_NonResv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Surf_NonResv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered nonreserved surface parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Surf_Resv_Parking__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Surf_Resv_Parking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offered reserved surface parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c</fullName>
    <label>Surface Parking Annual cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_RSAP_Total_Parking_Annual_Amount__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Total_Parking_Annual_Amount__c</fullName>
    <label>Total Parking Annual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Broker__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Broker__c</fullName>
    <description>RSAP Project Broker email from GREX</description>
    <inlineHelpText>RSAP Project Broker email from GREX</inlineHelpText>
    <label>RSAP GSA Broker Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Lease_Contracting_Officer__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Lease_Contracting_Officer__c</fullName>
    <description>RSAP GSA Project Lease Contracting Officer from GREX</description>
    <inlineHelpText>RSAP GSA Project Lease Contracting Officer from GREX</inlineHelpText>
    <label>RSAP GSA Lease Contracting Officer Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Leasing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Leasing_Specialist__c</fullName>
    <description>RSAP GSA Project Leasing Specialist from GREX</description>
    <inlineHelpText>RSAP GSA Project Leasing Specialist from GREX</inlineHelpText>
    <label>RSAP GSA Leasing Specialist Email</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_G_REX_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_G_REX_ID__c</fullName>
    <externalId>true</externalId>
    <label>Solicitation/G-REX ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_State__c</fullName>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_LOP_ParkingController.cls
/**
 * Created by nkopparthi on 5/20/19.
 */

public with sharing class PBS_LOP_ParkingController {

    public boolean isValidUser { get; set; }
    public String offerId { get; set; }
    public String isNew { get; set; }
    public String action { get; set; }
    public string isEditable { get; set; }
    public User userDetail { get; set; }
    public String draftMsgFlag { get; set; }
    public Boolean viewOnly { get; set; }
    public string viewMsg { get; set; }
    public PBS_AAAP_Offer__c lopOffer { get; set; }
    public PBS_AAAP_RLP__c rlp {get; set;}
    public Boolean isTerminated { get; set; }
    public String pageURL {get; set;}
    public PBS_AAAP_QuestionLabels qLabels { get; set; }
    public String pageURLForRedirection{get;set;}    // j.rogers 1/18/2023  SFWS-2107

    public PBS_LOP_ParkingController() {

        userDetail = [SELECT u.Username, u.ProfileId,u.CompanyName, u.Name, u.Id, u.ContactId, u.LastName, u.FirstName, u.Street, u.City, u.State, u.PostalCode FROM User u WHERE u.Id = :UserInfo.getUserId()];
        action = ApexPages.currentPage().getParameters().get('action');
        offerId = ApexPages.currentPage().getParameters().get('offerId');
        isNew = ApexPages.currentPage().getParameters().get('isNew');
        isEditable = ApexPages.currentPage().getParameters().get('edit');
        draftMsgFlag = ApexPages.currentPage().getParameters().get('draftMsgFlag');

        qLabels = new PBS_AAAP_QuestionLabels();

        if (isEditable == 'false') {
            viewOnly = true;
            viewMsg = 'Offer opened in a View mode';
        } else {
            viewOnly = false;
        }

        if (ApexPages.currentPage().getParameters().get('offerId') != null) {
            lopOffer = PBS_AAAP_GlobalConstants.getOfferDetail(offerId);

            // jrogers testing
            system.debug('PBS_AAAP_Parking_Onsite__c ===> '+ lopOffer.PBS_AAAP_Parking_Onsite__c);
            
            String rlpId = lopOffer.PBS_AAAP_RLP_Number__c;
            rlp = [
                    SELECT PBS_RSAP_Solicitation_G_REX_ID__c,PBS_RSAP_Solicitation_Number__c,PBS_RSAP_Solicitation_Status__c,PBS_RSAP_State__c,PBS_RSAP_Broker__c, PBS_RSAP_Lease_Contracting_Officer__c, PBS_RSAP_Leasing_Specialist__c,  //JK 2.9.21 added 3 new GREX contact email fields on RLP here
                            PBS_RSAP_Project_Number__c,PBS_RSAP_City__c
                    FROM PBS_AAAP_RLP__c
                    WHERE Id = :rlpId
                    LIMIT 1
            ];

            if (lopOffer.OwnerId == UserInfo.getUserId()) {
                isValidUser = true;
                if (lopOffer.PBS_AAAP_RLP_Number__r.PBS_RSAP_Solicitation_Status__c) {
                    isTerminated = false;
                } else {
                    isTerminated = true;
                }
                if (isTerminated) {
                    viewOnly = true;
                    viewMsg = 'Project is terminated. Offer opened in a view mode';
                    System.debug('*** isEditable ***' + isEditable);
                } else if (lopOffer.PBS_AAAP_Offer_Status__c == PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED) {
                    viewOnly = true;
                    viewMsg = 'Project due date has elapsed. Offer opened in a view mode';
                }
            } else {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, PBS_AAAP_GlobalConstants.ERROR_INAVLID_ACCESS_OWNERSHIP);
                Apexpages.addMessage(myMsg);
                isValidUser = false;
            }
        } else {
            isValidUser = true;
            lopOffer = new PBS_AAAP_Offer__c();
        }
   
        
    }

    public PageReference backToOfrBlding() {

        system.debug('***** started backToOfrBlding ******');
        PageReference p = new PageReference('/RSAP/Building');
        //PageReference p = Page.PBS_LOP_Building;
        p.getParameters().put('offerId', offerId);
        if (isEditable == 'true') {
            p.getParameters().put('edit', 'true');
        } else {
            isEditable = 'false';
        }

        /* SFWS-2107  01/18/2023 j.rogers */
          //  p.setRedirect(true);
          // return p;
       

        p.setRedirect(false);
        
        pageURLForRedirection = p.getUrl();
        pageURLForRedirection = pageURLForRedirection.replace('/RSAP/Building', Label.LOP_Community_Base_URL+'RSAP-Building');

        
        system.debug('***** finished backToOfrBlding ******');
        return null;
        /* end 2107 */


    }

    public PageReference saveParkingInfo() {
        PageReference p = null;

        Boolean flag = false;
        if (lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c == null || lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, PBS_AAAP_GlobalConstants.LOP_SPACE_RATES_ANSI_BOMA_SF));
            flag = true;
        }
        if (lopOffer.PBS_AAAP_Office_RSF_OFFERED__c == null || lopOffer.PBS_AAAP_Office_RSF_OFFERED__c == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, PBS_AAAP_GlobalConstants.LOP_SPACE_RATES_RSF));
            flag = true;
        }
        if (lopOffer.PBS_AAAP_Office_RSF_OFFERED__c == null) {
            lopOffer.PBS_AAAP_Office_RSF_OFFERED__c = 0;
        }
        if (lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c == null) {
            lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c = 0;
        }

        /*if (lopOffer.PBS_AAAP_Office_RSF_OFFERED__c <= lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, PBS_AAAP_GlobalConstants.LOP_SPACE_RATES_RSF_GT_ABOA));
            flag = true;
        }*/

        /* Todd Brown 10/08/2021 commented out edits for removed parking fields and added edits for new fields for SFWS-1400
        if (lopOffer.PBS_AAAP_Total_Surface_Parking_Spaces__c < lopOffer.PBS_RSAP_Emp_Visitor_Surface_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '3. Employee/Visitor Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_GOV_Surface_Spaces__c > lopOffer.PBS_AAAP_Total_Surface_Parking_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '4. Official Government Vehicles Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_Emp_Visitor_Structured_Spaces__c > lopOffer.PBS_AAAP_Total_Structured_Parking_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '3. Employee/Visitor Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_GOV_Structured_Spaces__c > lopOffer.PBS_AAAP_Total_Structured_Parking_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '4. Official Government Vehicles Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c == null || lopOffer.PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '5.  Annual Cost Per Space Surface / Structured are required fields.  Please put 0.00 if there is no separate charge for parking.'));
            flag = true;
        }
        */
        if (lopOffer.PBS_AAAP_Parking_Onsite__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '2. Onsite parking response is required.'));
            flag = true;
        } 
        if (lopOffer.PBS_AAAP_Monthly_cost_res_gar_park__c == null ||
            lopOffer.PBS_AAAP_Monthly_cost_nonres_gar_park__c == null ||
            lopOffer.PBS_AAAP_Monthly_cost_res_sur_park__c == null ||
            lopOffer.PBS_AAAP_Monthly_cost_nonres_sur_park__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR,
                    '4. Please enter rates for all types of parking. Please put $0.00 if you are either not charging for, or not offering, that type of parking space. You may not leave any fields blank.'));
            flag = true;
         }
         //added by Ramya 07/2022
          if (lopOffer.PBS_RSAP_Surf_Resv_Parking__c  == null ||
            lopOffer.PBS_RSAP_Surf_NonResv_Parking__c == null ||
            lopOffer.PBS_RSAP_Struct_Resv_Parking__c == null ||
            lopOffer.PBS_RSAP_Struct_NonResv_Parking__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR,
                    '5. Please enter number of parking spaces offered to satisfy the parking requirements of the RLP. You may not leave any fields blank.'));
            flag = true;  
        }
        if (flag == true) {
            return null;
        }
        try {
            lopOffer.PBS_AAAP_Common_Area_Factor__c = (lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c > 0) ? (100 * (lopOffer.PBS_AAAP_Office_RSF_OFFERED__c - lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c) / lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c).setScale(2) : 0.00;
            draftMsgFlag = '';
            //updateAreaType(lopOffer);
            if (lopOffer.PBS_AAAP_Offer_Status__c == PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED) {
                PBS_AAAP_GlobalConstants.updateOfferToDraft(lopOffer);
                draftMsgFlag = 'true';
            }
            //SFWS-847
            lopOffer.PBS_AAAP_OP_COST_COST_PER_ABOA__c = (lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c > 0) ? (lopOffer.PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c / lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c) : 0;
            lopOffer.PBS_AAAP_OP_COST_COST_PER_RSF__c = (lopOffer.PBS_AAAP_Office_RSF_OFFERED__c > 0) ? (lopOffer.PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c / lopOffer.PBS_AAAP_Office_RSF_OFFERED__c) : 0;
            //SFWS-847
            update lopOffer;
        } catch (Exception ex) {
            Apexpages.addMessages(ex);
        }

        p = new PageReference('/RSAP/SpacesAndParking');
        p.getParameters().put('offerId', offerId);
        p.getParameters().put('draftMsg', draftMsgFlag);

        // SFWS 2107 - j. rogers 1/18/2023
            //p.setRedirect(true);
            //return p;      
        pageURLForRedirection = p.getUrl();
        pageURLForRedirection = pageURLForRedirection.replace('/RSAP/SpacesAndParking', Label.LOP_Community_Base_URL+'RSAP-SpacesAndParking');
        
        return null;
    }

    public PageReference saveParkingAndContinue() {

        //system.debug('***************offer Parking ID :'+offerParking);
        PageReference p = null;

        Boolean flag = false;
        
        //Parking
      
        /*Todd Brown 10/08/2021 commented out edits for removed parking fields and added edits for new fields for SFWS-1400
        if (lopOffer.PBS_AAAP_Total_Surface_Parking_Spaces__c < lopOffer.PBS_RSAP_Emp_Visitor_Surface_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '3. Employee/Visitor Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_GOV_Surface_Spaces__c > lopOffer.PBS_AAAP_Total_Surface_Parking_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '4. Official Government Vehicles Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_Emp_Visitor_Structured_Spaces__c > lopOffer.PBS_AAAP_Total_Structured_Parking_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '3. Employee/Visitor Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_GOV_Structured_Spaces__c > lopOffer.PBS_AAAP_Total_Structured_Parking_Spaces__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '4. Official Government Vehicles Parking cannot exceed total building parking.'));
            flag = true;
        }
        if (lopOffer.PBS_RSAP_SURFACE_PARKING_ANNUAL_COST__c == null || lopOffer.PBS_RSAP_STRUCT_PARKING_ANNUAL_COST__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '5.  Annual Cost Per Space Surface / Structured are required fields.  Please put 0.00 if there is no separate charge for parking.'));
            flag = true;
        }*/
                    
            
        if (lopOffer.PBS_AAAP_Parking_Onsite__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, '2. Onsite parking response is required.'));
            flag = true;
        } 
        //added by Ramya 07/2022
         if (lopOffer.PBS_AAAP_Monthly_cost_res_gar_park__c == null ||
            lopOffer.PBS_AAAP_Monthly_cost_nonres_gar_park__c == null ||
            lopOffer.PBS_AAAP_Monthly_cost_res_sur_park__c == null ||
            lopOffer.PBS_AAAP_Monthly_cost_nonres_sur_park__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR,
                    '4. Please enter rates for all types of parking. Please put $0.00 if you are either not charging for, or not offering, that type of parking space. You may not leave any fields blank.'));
            flag = true;
         }
          if (lopOffer.PBS_RSAP_Surf_Resv_Parking__c  == null ||
            lopOffer.PBS_RSAP_Surf_NonResv_Parking__c == null ||
            lopOffer.PBS_RSAP_Struct_Resv_Parking__c == null ||
            lopOffer.PBS_RSAP_Struct_NonResv_Parking__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR,
                    '5. Please enter number of parking spaces offered to satisfy the parking requirements of the RLP. You may not leave any fields blank.'));
            flag = true;  
        }
              
        if (flag == true) {
            return null;
        }

        try {
        
              lopOffer.PBS_RSAP_Total_Parking_Annual_Amount__c = (((lopOffer.PBS_AAAP_Monthly_cost_res_gar_park__c*lopOffer.PBS_RSAP_Struct_Resv_Parking__c)
                                                                 +(lopOffer.PBS_AAAP_Monthly_cost_res_sur_park__c*lopOffer.PBS_RSAP_Surf_Resv_Parking__c)
                                                                 +(lopOffer.PBS_AAAP_Monthly_cost_nonres_gar_park__c*lopOffer.PBS_RSAP_Struct_NonResv_Parking__c)
                                                                 +(lopOffer.PBS_AAAP_Monthly_cost_nonres_sur_park__c*lopOffer.PBS_RSAP_Surf_NonResv_Parking__c))*12).setScale(2);
            draftMsgFlag = '';
            if (lopOffer.PBS_AAAP_Offer_Status__c == PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED) {
                PBS_AAAP_GlobalConstants.updateOfferToDraft(lopOffer);
                draftMsgFlag = 'true';
            }
            //updateAreaType(lopOffer);
            //SFWS-847
            lopOffer.PBS_AAAP_OP_COST_COST_PER_ABOA__c = (lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c > 0) ? (lopOffer.PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c / lopOffer.PBS_AAAP_Total_Ofc_ABOA_offered__c) : 0;
            lopOffer.PBS_AAAP_OP_COST_COST_PER_RSF__c = (lopOffer.PBS_AAAP_Office_RSF_OFFERED__c > 0) ? (lopOffer.PBS_AAAP_SRVC_UTIL_TOTAL_GOV__c / lopOffer.PBS_AAAP_Office_RSF_OFFERED__c) : 0;
            //SFWS-847
            update lopOffer;
            String offerId = lopOffer.Id;
            lopOffer = null; // clears ViewState for visual force page

            p = new PageReference('/RSAP/OperatingCost');
            p.getParameters().put('offerId', offerId);
            if (draftMsgFlag == 'true') {
                p.getParameters().put('draftMsgFlag', 'true');
            }
            if (isEditable == 'true') {
                p.getParameters().put('edit', 'true');
            } else {
                isEditable = 'false';
            }
            // j.rogers 12/22/2022 SFWS-2107
                // p.setRedirect(true);
            // 
            if(pageURL == NULL || pageURL == ''){
            pageURLForRedirection = p.getUrl();
            pageURLForRedirection = pageURLForRedirection.replace('/RSAP/OperatingCost', Label.LOP_Community_Base_URL+'RSAP-OperatingCost');
            p.setRedirect(false);
                } else {
                 p = new PageReference(pageURL);
                pageURLForRedirection = Label.LOP_Community_Base_URL+PBS_AAAP_Utility.getCommunityURL(pageURL);
                 p.setRedirect(false);   
                //return pr;
            }
        
            return null;
            // end 2107
            
        } catch (Exception ex) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage());
            Apexpages.addMessage(myMsg);
        }
  
            if(pageURL == NULL || pageURL == ''){
                return p;
            } else {
                p = new PageReference(pageURL);
                pageURLForRedirection = Label.LOP_Community_Base_URL+PBS_AAAP_Utility.getCommunityURL(p.getUrl());
                return null;
            }
                
    }

    public PageReference actionCancel() {
        PageReference pref = new PageReference('/RSAP/PortalHome');
        //PageReference pref = Page.PBS_LOP_PortalHome;
        pref.setRedirect(true);
        return pref;
    }
    
    public void saveData() {        
        update lopOffer;
    }

    @TestVisible private void updateAreaType(PBS_AAAP_OFFER__C lopOffer) {
        //added by syam for FY16 changes
        String areaType = lopOffer.PBS_AAAP_SITE_AREA_TYPE__c;
        System.debug('*** areaType is ' + areaType);
        Decimal siteSize = lopOffer.PBS_AAAP_SITE_SIZE_SQFT__c;
        //siteSize.setScale(2, RoundingMode.HALF_UP);
        System.debug('*** siteSize is ' + siteSize);
        if (lopOffer.PBS_AAAP_SITE_SIZE_SQFT__c != null && areaType == 'Acres') {
            siteSize = siteSize * 43560;
            System.debug('*** siteSize inside is ' + siteSize);
            lopOffer.PBS_AAAP_SITE_SIZE_SQFT__c = siteSize;
        }

    }
    
    public List<SelectOption> getOnsiteParkingItems() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = PBS_AAAP_Offer__c.PBS_AAAP_Parking_Onsite__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        } 
        return options;
    }

}