force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RLP Number</label>
    <referenceTo>PBS_AAAP_RLP__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/PBS_AAAP_RLP__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains information related to Solicitations for Offer (RLPs)</description>
    <label>RLP</label>
    <nameField>
        <displayFormat>RLP-{000000}</displayFormat>
        <label>RLP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RLPs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_AAAP_RLP_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RLP_Number__c</fullName>
    <label>RLP Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Number__c</fullName>
    <label>Solicitation Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_RLP__c/fields/PBS_RSAP_Solicitation_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_RSAP_Solicitation_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitation Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Progress_Bar__mdt/Progress_Bar__mdt.object-meta.xml
<CustomObject>
    <label>Progress Bar</label>
    <pluralLabel>Progress Bars</pluralLabel>
</CustomObject>

force-app/main/default/objects/Progress_Bar_Step__mdt/Progress_Bar_Step__mdt.object-meta.xml
<CustomObject>
    <label>Progress Bar Step</label>
    <pluralLabel>Progress Bar Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Progress_Bar_Step__mdt/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Bar_Step__mdt/fields/Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Page_URL__c</fullName>
    <label>Page URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Bar_Step__mdt/fields/Progress_Bar__c.field-meta.xml
<CustomField>
    <fullName>Progress_Bar__c</fullName>
    <label>Progress Bar</label>
    <referenceTo>Progress_Bar__mdt</referenceTo>
    <relationshipLabel>Progress Bar Steps</relationshipLabel>
    <relationshipName>Progress_Bar_Steps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/PBS_Leasing_ProgressBarController.cls
public with sharing class PBS_Leasing_ProgressBarController {
    // Method to fetch progress bar steps based on the provided progress bar name.
    @AuraEnabled
    public static List<Progress_Bar_Step__mdt> getSteps(String progressBarName){
        // Query to retrieve progress bar steps from the metadata based on the developer name.
        // The steps are ordered by the 'Order_Number__c' field in ascending order.
        return [Select Id,Label, Progress_Bar__c, Page_URL__c, Order_Number__c,DeveloperName
                From Progress_Bar_Step__mdt where Progress_Bar__r.DeveloperName =:progressBarName order by Order_Number__c Asc];
    }
    // Method to retrieve PBS_AAAP_RLP__c records related to a given offer ID.
    @AuraEnabled(cacheable = true)
    public static PBS_AAAP_Offer__c getPBS_AAAP_RLP_ObjRecords(String offerId){
        // Query to get the offer record using the provided offer ID.
       return [Select id, PBS_AAAP_RLP_Number__c, RecordType.Name from PBS_AAAP_Offer__c Where id =: offerId];
        // Query to retrieve related PBS_AAAP_RLP__c records based on the RLP number 
        // and ensuring the solicitation status is true (active).
        
    }
    @AuraEnabled(cacheable = true)
    public static List<PBS_AAAP_Offer__c> getPBS_AAAP_Offer_ObjRecords(String offerId){
        // Query to get the offer record using the provided offer ID.
        List<PBS_AAAP_Offer__c> offerRec =[Select id, PBS_AAAP_Building_Name__c,PBS_AAAP_RLP_Number__r.PBS_AAAP_RLP_Number__c,
                                           PBS_AAAP_RLP_Number__r.PBS_RSAP_Solicitation_Number__c,
                                           PBS_AAAP_RLP_Number__r.PBS_RSAP_Solicitation_Status__c, PBS_AAAP_Offer_Status__c from PBS_AAAP_Offer__c  Where id =: offerId];
        return offerRec;
    }
}