force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_AC_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_AC_MAINTENANCE__c</fullName>
    <label>AC Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_AC_UTILITIES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_AC_UTILITIES__c</fullName>
    <label>AC Utilities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_BLDG_ENGINEERCOST__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_BLDG_ENGINEERCOST__c</fullName>
    <label>Bldg. Engineer Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_BUILDING_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_BUILDING_MAINTENANCE__c</fullName>
    <label>Building Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_CLEANING_CONTRACT_SERVICES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_CLEANING_CONTRACT_SERVICES__c</fullName>
    <label>Cleaning Contract Services</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_CLEANING_SALARIES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_CLEANING_SALARIES__c</fullName>
    <label>Cleaning Salaries</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_CLEANING_SUPPLIES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_CLEANING_SUPPLIES__c</fullName>
    <label>Cleaning Supplies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_COST_PER_ABOA__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_COST_PER_ABOA__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total Operating Costs per ABOA SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ELECTRICAL_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ELECTRICAL_MAINTENANCE__c</fullName>
    <label>Electrical Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ELECTRICAL_POWER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ELECTRICAL_POWER__c</fullName>
    <label>Electrical Power</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ELECTRICAL_REPLACEMENT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ELECTRICAL_REPLACEMENT__c</fullName>
    <label>Electrical Replacement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ELECTRICAL_SPECIALEQUIP__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ELECTRICAL_SPECIALEQUIP__c</fullName>
    <label>Electrical Special Equipment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ELEVATOR_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ELEVATOR_MAINTENANCE__c</fullName>
    <label>Elevator Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ELEVATOR_SALARIES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ELEVATOR_SALARIES__c</fullName>
    <label>Elevator Salaries</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_GEN_PURPOSE_RENTABLE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_GEN_PURPOSE_RENTABLE__c</fullName>
    <description>Total amount of rentable square feet (RSF) in the building?</description>
    <label>Total Building RSF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_HEATING_FUEL__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_HEATING_FUEL__c</fullName>
    <label>Heating Fuel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>----</fullName>
                <default>true</default>
                <label>----</label>
            </value>
            <value>
                <fullName>Oil</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_HEATING_FUEL_COST__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_HEATING_FUEL_COST__c</fullName>
    <label>Heating Fuel Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_HEATING_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_HEATING_MAINTENANCE__c</fullName>
    <label>Heating Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_HEATING_SALARIES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_HEATING_SALARIES__c</fullName>
    <label>Heating Salaries</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_INSURANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_INSURANCE__c</fullName>
    <label>Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_LANDSCAPING_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_LANDSCAPING_MAINTENANCE__c</fullName>
    <label>Landscaping Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_LEASE_COMMISSION__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_LEASE_COMMISSION__c</fullName>
    <label>Lease Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_MANAGEMENT__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_MANAGEMENT__c</fullName>
    <label>Management</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_MAX_CONT_ABOA_AVAIL__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_MAX_CONT_ABOA_AVAIL__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Max Contiguous ABOA SF Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFICE_SF_OFFERED_MAX__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFICE_SF_OFFERED_MAX__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total ABOA SF Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFICE_SF_OFFERED_MIN__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFICE_SF_OFFERED_MIN__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Minimum ABOA SF Available</description>
    <label>Minimum ABOA SF Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFICE_SPACE_RSF__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFICE_SPACE_RSF__c</fullName>
    <description>Office Space :</description>
    <label>General Purpose (Office) Space RSF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_PLUMBING_MAINTENANCE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PLUMBING_MAINTENANCE__c</fullName>
    <label>Plumbing Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_PLUMBING_SUPPLIES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PLUMBING_SUPPLIES__c</fullName>
    <label>Plumbing Supplies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_PLUMBING_WATER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_PLUMBING_WATER__c</fullName>
    <label>Plumbing Water</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_REAL_ESTATE_TAXES__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_REAL_ESTATE_TAXES__c</fullName>
    <label>Real Estate Taxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_RU_FACTOR__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_RU_FACTOR__c</fullName>
    <label>R/U Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SECT2_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SECT2_TOTAL__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total (Cost of Ownership)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SECURITY__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SECURITY__c</fullName>
    <label>Security</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SRVC_UTIL_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SRVC_UTIL_TOTAL__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total (Service and Utilities)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_SSTAX_WORKCOMP__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SSTAX_WORKCOMP__c</fullName>
    <label>Social Security Tax &amp; Workers Comp</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_TOTAL_BOMA_USF_OFFERED__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TOTAL_BOMA_USF_OFFERED__c</fullName>
    <description>15. Total ANSI/BOMA Office Area Square Feet (ABOA) in the building*?</description>
    <label>Total Building ABOA SF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_TOTAL_OTHER_COSTS__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_TOTAL_OTHER_COSTS__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total Other Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/recordTypes/AAAP.recordType-meta.xml
<RecordType>
    <fullName>AAAP</fullName>
    <active>true</active>
    <label>AAAP</label>
</RecordType>

force-app/main/default/objects/PBS_AAAP_Offer_Attachments__c/PBS_AAAP_Offer_Attachments__c.object-meta.xml
<CustomObject>
    <label>Offer Attachments</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Offer Attachments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer_Attachments__c/fields/PBS_AAAP_Offer__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer__c</fullName>
    <label>Offer</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer Attachments</relationshipLabel>
    <relationshipName>Offer_Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Space__c/PBS_AAAP_Space__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores information on the spaces related to a AAAP Offer</description>
    <label>Space</label>
    <nameField>
        <displayFormat>Space-{000000000}</displayFormat>
        <label>Space Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Space__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Formula field is used for identify winner page</description>
    <formula>PBS_AAAP_OFFER_NUMBER__r.PBS_AAAP_Building_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_AAAP_OfferTriggerBIBU_Test.cls
@IsTest
private class PBS_AAAP_OfferTriggerBIBU_Test {
    
    static testMethod void submittedOfferCheck() {      
        
        
        PBS_AAAP_Offer__c testOffer0 = new PBS_AAAP_Offer__c(
                PBS_AAAP_Building_Name__c = 'Unit Test Bldg',
                PBS_AAAP_OFFICE_SF_OFFERED_MIN__c = null,
                PBS_AAAP_OFFICE_SF_OFFERED_MAX__c = null,
                PBS_AAAP_MAX_CONT_ABOA_AVAIL__c = null,
                PBS_AAAP_RU_FACTOR__c = 0.00,
                PBS_AAAP_COST_PER_ABOA__c = 0.0,
                PBS_AAAP_TOTAL_BOMA_USF_OFFERED__c = 12000,
                PBS_AAAP_OFFICE_SPACE_RSF__c = 1000.00,
                PBS_AAAP_CLEANING_SALARIES__c = 1.00,
                PBS_AAAP_CLEANING_SUPPLIES__c = 1.00,
                PBS_AAAP_CLEANING_CONTRACT_SERVICES__c = 1.00,
                PBS_AAAP_HEATING_SALARIES__c = 1.00,
                PBS_AAAP_HEATING_FUEL__c = 'Coal',
                PBS_AAAP_HEATING_FUEL_COST__c = 1.00,
                PBS_AAAP_HEATING_MAINTENANCE__c = 1.00,
                PBS_AAAP_ELECTRICAL_POWER__c = 1.00,
                PBS_AAAP_ELECTRICAL_REPLACEMENT__c = 1.00,
                PBS_AAAP_ELECTRICAL_SPECIALEQUIP__c = 1.00,
                PBS_AAAP_ELECTRICAL_MAINTENANCE__c = 1.00,
                PBS_AAAP_PLUMBING_WATER__c = 1.00,
                PBS_AAAP_PLUMBING_SUPPLIES__c = 1.00,
                PBS_AAAP_PLUMBING_MAINTENANCE__c = 1.00,
                PBS_AAAP_AC_UTILITIES__c = 1.00,
                PBS_AAAP_AC_MAINTENANCE__c = 1.00,
                PBS_AAAP_ELEVATOR_SALARIES__c = 1.00,
                PBS_AAAP_ELEVATOR_MAINTENANCE__c = 1.00,
                PBS_AAAP_BLDG_ENGINEERCOST__c = 1.00,
                PBS_AAAP_SECURITY__c = 1.00,
                PBS_AAAP_SSTAX_WORKCOMP__c = 1.00,
                PBS_AAAP_LANDSCAPING_MAINTENANCE__c = 1.00,
                PBS_AAAP_REAL_ESTATE_TAXES__c = 2.00,
                PBS_AAAP_INSURANCE__c = 2.00,
                PBS_AAAP_BUILDING_MAINTENANCE__c = 2.00,
                PBS_AAAP_LEASE_COMMISSION__c = 2.00,
                PBS_AAAP_MANAGEMENT__c = 2.00,
                PBS_AAAP_SECT2_TOTAL__c = 10.00,
                PBS_AAAP_SRVC_UTIL_TOTAL__c = 22.00,
                PBS_AAAP_TOTAL_OTHER_COSTS__c = 1.00,
                PBS_AAAP_GEN_PURPOSE_RENTABLE__c = 28664.495,
                PBS_AAAP_Offer_Status__c = 'Draft' 
        );
        insert testOffer0;  
        
            PBS_AAAP_Offer__c testOffer1 = new PBS_AAAP_Offer__c(
                PBS_AAAP_Building_Name__c = 'Unit Test Bldg',
                PBS_AAAP_OFFICE_SF_OFFERED_MIN__c = null,
                PBS_AAAP_OFFICE_SF_OFFERED_MAX__c = null,
                PBS_AAAP_MAX_CONT_ABOA_AVAIL__c = null,
                PBS_AAAP_RU_FACTOR__c = 0.00,
                PBS_AAAP_COST_PER_ABOA__c = 0.0,
                PBS_AAAP_TOTAL_BOMA_USF_OFFERED__c = 12000,
                PBS_AAAP_OFFICE_SPACE_RSF__c = 1000.00,
                PBS_AAAP_CLEANING_SALARIES__c = 1.00,
                PBS_AAAP_CLEANING_SUPPLIES__c = 1.00,
                PBS_AAAP_CLEANING_CONTRACT_SERVICES__c = 1.00,
                PBS_AAAP_HEATING_SALARIES__c = 1.00,
                PBS_AAAP_HEATING_FUEL__c = 'Coal',
                PBS_AAAP_HEATING_FUEL_COST__c = 1.00,
                PBS_AAAP_HEATING_MAINTENANCE__c = 1.00,
                PBS_AAAP_ELECTRICAL_POWER__c = 1.00,
                PBS_AAAP_ELECTRICAL_REPLACEMENT__c = 1.00,
                PBS_AAAP_ELECTRICAL_SPECIALEQUIP__c = 1.00,
                PBS_AAAP_ELECTRICAL_MAINTENANCE__c = 1.00,
                PBS_AAAP_PLUMBING_WATER__c = 1.00,
                PBS_AAAP_PLUMBING_SUPPLIES__c = 1.00,
                PBS_AAAP_PLUMBING_MAINTENANCE__c = 1.00,
                PBS_AAAP_AC_UTILITIES__c = 1.00,
                PBS_AAAP_AC_MAINTENANCE__c = 1.00,
                PBS_AAAP_ELEVATOR_SALARIES__c = 1.00,
                PBS_AAAP_ELEVATOR_MAINTENANCE__c = 1.00,
                PBS_AAAP_BLDG_ENGINEERCOST__c = 1.00,
                PBS_AAAP_SECURITY__c = 1.00,
                PBS_AAAP_SSTAX_WORKCOMP__c = 1.00,
                PBS_AAAP_LANDSCAPING_MAINTENANCE__c = 1.00,
                PBS_AAAP_REAL_ESTATE_TAXES__c = 2.00,
                PBS_AAAP_INSURANCE__c = 2.00,
                PBS_AAAP_BUILDING_MAINTENANCE__c = 2.00,
                PBS_AAAP_LEASE_COMMISSION__c = 2.00,
                PBS_AAAP_MANAGEMENT__c = 2.00,
                PBS_AAAP_SECT2_TOTAL__c = 10.00,
                PBS_AAAP_SRVC_UTIL_TOTAL__c = 22.00,
                PBS_AAAP_TOTAL_OTHER_COSTS__c = 1.00,
                PBS_AAAP_GEN_PURPOSE_RENTABLE__c = 28664.495,
                PBS_AAAP_Offer_Status__c = 'Draft' 
        );
        insert testOffer1;  
        
         PBS_AAAP_Space__c sp = new PBS_AAAP_Space__c(
         PBS_AAAP_OFFER_NUMBER__c	= testOffer0.Id,
         PBS_AAAP_IDENTIFIER_ID__c = '0',
         PBS_AAAP_SF_OFFERED__c = 1000,
         PBS_AAAP_IDENTIFIER_FROM__c = 50,
         PBS_AAAP_BASE_OPERATING_COSTS__c = 1,
         PBS_AAAP_GC_OVERHEAD_AND_PROF__c = 2,
         PBS_AAAP_ARCHITECTURAL_AND_ENG_FEES_UOM__c = '$ Per ABOA SF',
         PBS_AAAP_MIN_OFFERABLE_SPACE__c =1,
         PBS_AAAP_Max_Contiguous_Space__c=1,
         PBS_AAAP_IDENTIFIER_TO__c = 1,
         PBS_AAAP_DATE_SPACE_AVAILABILITY__c = System.Today(),
         PBS_AAAP_ARCH_ENG_FEES__c = 1000,
         PBS_AAAP_MAX_OFFERABLE_SPACE__c= 18,
         PBS_AAAP_TOTAL_MARKUP__c=2
         ); 
 		Insert sp;
        
        PBS_AAAP_Space__c sp1 = new PBS_AAAP_Space__c(
            PBS_AAAP_OFFER_NUMBER__c	= testOffer0.Id,
            PBS_AAAP_Master_Space__c = sp.id,
            PBS_AAAP_IDENTIFIER_ID__c = '0',
            PBS_AAAP_SF_OFFERED__c = 1000,
            PBS_AAAP_IDENTIFIER_FROM__c = 50,
            PBS_AAAP_BASE_OPERATING_COSTS__c = 1,
            PBS_AAAP_GC_OVERHEAD_AND_PROF__c = 2,
            PBS_AAAP_ARCHITECTURAL_AND_ENG_FEES_UOM__c = '$ Per ABOA SF',
            PBS_AAAP_MIN_OFFERABLE_SPACE__c =1,
            PBS_AAAP_Max_Contiguous_Space__c=1,
            PBS_AAAP_IDENTIFIER_TO__c = 1,
            PBS_AAAP_DATE_SPACE_AVAILABILITY__c = System.Today(),
            PBS_AAAP_ARCH_ENG_FEES__c = 1000,
            PBS_AAAP_MAX_OFFERABLE_SPACE__c= 18,
            PBS_AAAP_TOTAL_MARKUP__c=2
        ); 
        Insert sp1;
        
        testOffer0.PBS_AAAP_Offer_Status__c = 'Draft';
        testOffer0.PBS_AAAP_Energy_Star__c = PBS_AAAP_GlobalConstants.YES;
        testOffer0.PBS_AAAP_Close_To_Metro__c = PBS_AAAP_GlobalConstants.YES;
        testOffer0.PBS_AAAP_HIST_PROP_IN_NON_HIST_DIST__c  = PBS_AAAP_GlobalConstants.YES;
        update testOffer0;
        
        testOffer0.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
        testOffer0.RecordTypeId = Schema.SObjectType.PBS_AAAP_Offer__c.getRecordTypeInfosByName().get('AAAP').getRecordTypeId();
        testOffer0.Master_Offer__c = testOffer1.ID;
        update testOffer0;
        
        Test.setMock(HttpCalloutMock.class, new PBS_AAAP_OfferTriggerBIBU_MockTest());          
        
        PBS_AAAP_Offer_Attachments__c offeratt = new PBS_AAAP_Offer_Attachments__c();
        offeratt.PBS_AAAP_Offer__c = testOffer0.Id;
        insert offeratt;
        
        Attachment a = new Attachment();
        a.Body = Blob.valueOf('TEST');
        a.ParentID = offeratt.Id;
        a.Name = 'OfferForm3518.pdf';
        insert a;   

        PBS_AAAP_SendOfferDetailsAPI.sendOfferDetails(JSON.serialize(testOffer0));          
        System.assert(true);
    }
    
}