force-app/main/default/objects/Audit__c/Audit__c.object-meta.xml
<CustomObject>
    <description>Holds Setup Audit Trail information</description>
    <label>Audit</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Login_History__c/Login_History__c.object-meta.xml
<CustomObject>
    <description>Stores successful and failed login attempts for Salesforce production organization and enabled portals.</description>
    <label>Login History</label>
    <nameField>
        <label>Login History Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Login_History__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <label>API Version</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <label>Browser</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Client_Version__c.field-meta.xml
<CustomField>
    <fullName>Client_Version__c</fullName>
    <label>Client Version</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Login_Time__c</fullName>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Login_Type__c.field-meta.xml
<CustomField>
    <fullName>Login_Type__c</fullName>
    <label>Login Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Login_URL__c.field-meta.xml
<CustomField>
    <fullName>Login_URL__c</fullName>
    <label>Login URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Source_IP__c.field-meta.xml
<CustomField>
    <fullName>Source_IP__c</fullName>
    <label>Source IP</label>
    <length>39</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Salesforce Username</description>
    <label>Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoginHistoryInsertBatch.cls
/*
 * 	Class Description: This batch job retreives the records from System object LoginHistory
 * and inserts in the custom object Login_History__c. It also stores the data in a csv and 
 * creates a zip file document and stores in LoginHistory  document folder which is 
 * Accessible only by the users with in the public group Audit Reporting Users CEO Org. 
 * The Batch is called from the finish method of the LoginHistoryDelete.apxc class to 
 * run the operations in sequence. 
 *  *********************************************************
	  Created By      | Version |  Date    | Description     
 *  *********************************************************
	  Ramesh Dugar       1.0      04/19/2017  Created 
      Murugaboopathi Natarajan       1.1     01/12/2020  Modified 
*  *********************************************************/

global with sharing class LoginHistoryInsertBatch implements Database.Batchable<sObject>,Database.Stateful{
	global String query = '';   
    global string csv = 'UserId,Login Time,SourceIP,Login Type,Status,Browser,Platform,Application,Client Version,API Type,API Version,Login URL\n';
    //global List<Audit__c> auditLst;
    global Integer fileCountValue = 1;
    global Database.QueryLocator start(Database.BatchableContext BC){
        if(Test.isRunningTest()){
        	return Database.getQueryLocator([Select UserId, Status, SourceIp, Platform, LoginUrl, LoginType, LoginTime, Id, ClientVersion, Browser, Application, ApiVersion, ApiType From LoginHistory LIMIT 10]);

        }
        Integer currentMonth = Integer.valueOf(System.Today().month());
        System.debug('currentMonth:'+currentMonth);
        Integer archivalMonth = (currentMonth <= 6)?currentMonth + 6:currentMonth - 6;
        System.debug('archivalMonth:'+archivalMonth);
    	return Database.getQueryLocator([Select UserId, Status, SourceIp, Platform, LoginUrl, LoginType, LoginTime, Id, ClientVersion, Browser, Application, ApiVersion, ApiType From LoginHistory WHERE CALENDAR_MONTH(LoginTime) = :archivalMonth]);
   }

	global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<LoginHistory> login= new List<LoginHistory>();
        List<Login_History__c> loginLog = new List<Login_History__c>();
        login = scope;
        for(LoginHistory l : login){
            csv += l.UserId + ','+ l.LoginTime + ',' + l.SourceIP + ',' + l.LoginType + ',' + l.Status + ',' + l.Browser + ',' + l.Platform + ',' + l.Application + ',' + l.ClientVersion + ',' + l.APIType + ',' + l.APIVersion + ',' + l.LoginURL + '\n';
            Login_History__c logVal = new Login_History__c();
            if(l.UserId!=null){
                logVal.Username__c = l.UserId;
            }
            
            if(l.Status!=null){
                logVal.Status__c = l.Status;
            }
            
            if(l.SourceIp!=null){
                logVal.Source_IP__c = l.SourceIp;
            }
            
            if(l.Platform!=null){
                logVal.Platform__c = l.Platform;
            }
            
            if(l.LoginUrl!=null){
                logVal.Login_Url__c = l.LoginUrl;
            }
            
            if(l.LoginType!=null){
                logVal.Login_Type__c = l.LoginType;
            }
            
            if(l.LoginTime!=null){
                logVal.Login_Time__c = l.LoginTime;
            }
            
            if(l.ClientVersion!=null){
                logVal.Client_Version__c = l.ClientVersion;
            }
            
            if(l.Browser!=null){
                logVal.Browser__c = l.Browser;
            }
            
            if(l.Application!=null){
                logVal.Application__c = l.Application;
            }
            
            if(l.ApiVersion!=null){
                logVal.Api_Version__c = l.ApiVersion;
            }
            
            if(l.ApiType!=null){
                logVal.Api_Type__c = l.ApiType;
            }
            
            loginLog.add(logVal);
        }
        insert loginLog;
        if((Limits.getHeapSize() + 50000) >= Limits.getLimitHeapSize()) {
            //Zippex zip = new Zippex();
            //system.debug('****'+csv);
            //zip.addFile('LoginHistory.csv', Blob.valueOf(csv), null);
            //Blob zipBlob = zip.getZipArchive();
            Id folderid = [Select Id,Name from Folder where Name='LoginHistory' Limit 1].ID;
            Document doc = new Document();
            doc.FolderId = folderid;
            //doc.Body = zipBlob;
            doc.Body = Blob.valueOf(csv);
            doc.Name = 'LoginHistory-'+fileCountValue+'-'+system.today()+'.csv';
            insert doc;
            fileCountValue = fileCountValue + 1;
            // implement logic to reduce
            csv = null;
            csv = 'UserId,Login Time,SourceIP,Login Type,Status,Browser,Platform,Application,Client Version,API Type,API Version,Login URL\n';
        }
  
    }

    global void finish(Database.BatchableContext BC){ 
    	//Zippex zip = new Zippex();
        //system.debug('****'+csv);
        //zip.addFile('LoginHistory.csv', Blob.valueOf(csv), null);
        //Blob zipBlob = zip.getZipArchive();
        Id folderid = [Select Id,Name from Folder where Name='LoginHistory' Limit 1].ID;
        Document doc = new Document();
        doc.FolderId = folderid;
        doc.Body = Blob.valueOf(csv);
        //doc.Body = zipBlob;
        //doc.Name = 'LoginHistory'+system.today()+'.zip';
        doc.Name = 'LoginHistory-'+fileCountValue+'-'+system.today()+'.csv';
        insert doc;
    }
}