force-app/main/default/objects/Audit__c/Audit__c.object-meta.xml
<CustomObject>
    <description>Holds Setup Audit Trail information</description>
    <label>Audit</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action</description>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Audit Date</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <description>Section</description>
    <label>Section</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>User Email</description>
    <label>User</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ScheduleSetupAuditTrailBatchTest.cls
@isTest
Public class ScheduleSetupAuditTrailBatchTest{
   
    static testMethod void ScheduleTestMethod(){
		DateTime n = datetime.now().addMinutes(1);
   		String cron = '';
   		cron += n.second();
   		cron += ' ' + n.minute();
   		cron += ' ' + n.hour();
   		cron += ' ' + n.day();
   		cron += ' ' + n.month();
   		cron += ' ' + '?';
   		cron += ' ' + n.year();
   		
   		String jobId = System.schedule('SetupAuditTrailBatch', cron, new ScheduleSetupAuditTrailBatch());
   		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime 
                          FROM CronTrigger 
                          WHERE id = :jobId];
   		System.assertEquals(cron, ct.CronExpression);
   		System.assertEquals(0, ct.TimesTriggered);
	}
    
    static testMethod void DeleteBatchTestMethod(){
        Audit__c a = new Audit__c();
        a.User__c = 'test@gsa.gov';
        a.Action__c = 'TestChange';
        a.Section__c = 'TestSection';
        a.Date__c = system.today();
        insert a;
        
        test.startTest();
        	SetUpAuditTrailDeleteBatch s = new SetUpAuditTrailDeleteBatch();
        	ID jobID = database.executeBatch(s);
        test.stopTest();
        AsyncApexJob ajob = [SELECT ID, Status, NumberOfErrors, JobItemsProcessed,
        				 TotalJobItems, CreatedBy.Email, ExtendedStatus
                         FROM AsyncApexJob WHERE ID =:jobID];
        
        system.assertEquals('Completed', ajob.Status);
	}
}