force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ModifiedReason__c.field-meta.xml
<CustomField>
    <fullName>ModifiedReason__c</fullName>
    <description>The reason this object was modified</description>
    <inlineHelpText>The reason this object was modified</inlineHelpText>
    <label>Last Modified Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/txtProgramArea_FullCode__c.field-meta.xml
<CustomField>
    <fullName>txtProgramArea_FullCode__c</fullName>
    <description>Clone of the PBS_Project__c.txtProgramArea_FullCode__c field.  Here so we can use SF declarative security.  This is populated via a trigger.</description>
    <label>Program Area Full Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/WorkflowPhaseId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current workflow phase for this project</description>
    <inlineHelpText>Current workflow phase for this project</inlineHelpText>
    <label>Workflow Phase ID</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>PBS_gBUILD_Project -&amp;amp;amp;amp;gt; gBUILD_ApplicationConfig</relationshipLabel>
    <relationshipName>L_PBS_gBUILD_Project_2_gBUILD_Applicatio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtCreatedIn__c.field-meta.xml
<CustomField>
    <fullName>txtCreatedIn__c</fullName>
    <label>Created In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gBUILD</fullName>
            </value>
            <value>
                <fullName>GPGIS</fullName>
            </value>
            <value>
                <fullName>ePM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCurrentState__c.field-meta.xml
<CustomField>
    <fullName>txtCurrentState__c</fullName>
    <label>Current State [from ePM]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Formative</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProgramArea_FullCode__c.field-meta.xml
<CustomField>
    <fullName>txtProgramArea_FullCode__c</fullName>
    <label>Program Area Full Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARRA</fullName>
            </value>
            <value>
                <fullName>ARRA.BS</fullName>
            </value>
            <value>
                <fullName>ARRA.CT</fullName>
            </value>
            <value>
                <fullName>ARRA.FBM</fullName>
            </value>
            <value>
                <fullName>ARRA.FBM1</fullName>
            </value>
            <value>
                <fullName>ARRA.NP</fullName>
            </value>
            <value>
                <fullName>ARRA.O</fullName>
            </value>
            <value>
                <fullName>NONARRA</fullName>
            </value>
            <value>
                <fullName>NONARRA.BS</fullName>
            </value>
            <value>
                <fullName>NONARRA.CT</fullName>
            </value>
            <value>
                <fullName>NONARRA.ED</fullName>
            </value>
            <value>
                <fullName>NONARRA.FBM</fullName>
            </value>
            <value>
                <fullName>NONARRA.NP</fullName>
            </value>
            <value>
                <fullName>NONARRA.O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_ProjectProposeController.cls
public with sharing class PBS_gBUILD_ProjectProposeController extends PBS_gBUILD_ProjectCreateBaseController
{
    public PBS_gBUILD_Project__c proj { get; private set; }
    public PBS_Project__c pbsProj { get; private set; }
    
    public PBS_gBUILD_ProjectProposeController()
    {
        super('Propose Project');
        proj = new PBS_gBUILD_Project__c();
        pbsProj = new PBS_Project__c();
    }
    
    public PageReference cancel()
    {
        return PBS_gBUILD_Utility.createLinkProjects();
    }
    
    public PageReference create()
    {
        pbsProj.txtCreatedIn__c=PBS_gBUILD_Utility.commonProjCreatorGbuild;
        pbsProj.txtCurrentState__c='Formative';      
        pbsProj.txtProgramArea_FullCode__c='NONARRA.ED';
        insert pbsProj;
        proj.ProjectId__c = pbsProj.Id;        
        proj.WorkflowPhaseId__c = PBS_gBUILD_Utility.findInitialWfStateId(PBS_gBUILD_Utility.WfStateMachineTypes.Proposed);
        proj.ModifiedReason__c = 'Project was created';        
        insert proj;
        return PBS_gBUILD_Utility.createLinkPBuildingsManage(proj.id);
    }
}