force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/fields/Rahd_ProjectParentId__c.field-meta.xml
<CustomField>
    <fullName>Rahd_ProjectParentId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_Project</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_Project</inlineHelpText>
    <label>RAHD_Project Parent ID</label>
    <referenceTo>PBS_gBUILD_Project__c</referenceTo>
    <relationshipLabel>gBUILD Project Buildings</relationshipLabel>
    <relationshipName>C_PBS_gBUILD_ProjectBuilding_P_PBS_gBUIL</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtProlianceAccountName__c.field-meta.xml
<CustomField>
    <fullName>txtProlianceAccountName__c</fullName>
    <label>Proliance Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPBS_gBUILD_UploadCController.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_UploadCController
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    private static void Construct(string projectBuildingId)
    {
        TestPBS_gBUILD_Utility.setCurrentPageProjectBuildingReference(projectBuildingId);

        PBS_gBUILD_PBuildingBasicsController page = new PBS_gBUILD_PBuildingBasicsController();
        system.assert(page!=null);
        system.assertEquals(null, page.projectIdBaseControllerException);

        PBS_gBUILD_UploadCController ctrl = new PBS_gBUILD_UploadCController();
        system.assert(ctrl!=null);

        page.DocInfos_p = new List<PBS_gBUILD_Utility.DocInfo>();
        page.DocInfos_p.add(new PBS_gBUILD_Utility.DocInfo(page.projectid, page.pbuildingid, 'Mpc1d3' ));
                
        ctrl.pageController = page;
        ctrl.key = 'jason';

        ctrl.tags = 'tags';
        ctrl.description = 'description';
        ctrl.epmCatalog = 'epmCatalog';
        ctrl.contextualTitle = 'contextualTitle';
        ctrl.readableWaiverKeyPattern = 'Mpc[TOKEN]Waiver';
        ctrl.readableWaiverKeyTokens = '1,2,3,4';
        ctrl.readableUploadKeys = 'Mpc1d2,Mpc1d3';
        ctrl.intro = 'intro';
        ctrl.noAccessContactName = 'noAccessContactName';
        system.assertEquals('jason', ctrl.key);
        system.assert(ctrl.fileManagerUrl!=null);
        system.assertEquals(1, ctrl.DocCount);
        ctrl.actionId=projectBuildingId;
        ctrl.del();
    }

    public static testMethod void testConstructorGb()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();
        Construct(pb.id);
    }

    public static testMethod void testConstructorEpm()
    {
        PBS_gBUILD_ProjectBuilding__c pb = td.createGbProjectBuildingOnPbsProjectEpm1();

        string pbsProjectId  = [select Projectid__c from PBS_gBUILD_Project__c where id=:pb.Rahd_ProjectParentId__c].Projectid__c;
        PBS_Project__c pbsProject = [select id, txtProlianceAccountName__c from PBS_Project__c where id=:pbsProjectId];
        pbsProject.txtProlianceAccountName__c = 'proliance';
        update pbsProject;
        Construct(pb.id);
    }
}