force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/PBS_gBUILD_ProjectFunding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Funding information.</description>
    <label>gBUILD Project Funding</label>
    <nameField>
        <displayFormat>gbPf_{00000}</displayFormat>
        <label>PBSgBUILDPF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Fundings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_ProjectFunding__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <description>This is the parent ID for this object&apos;s RAHD_Project</description>
    <inlineHelpText>This is the parent ID for this object&apos;s RAHD_Project</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_gBUILD_Project__c</referenceTo>
    <relationshipLabel>gBUILD Project Funding</relationshipLabel>
    <relationshipName>gBUILD_Project_to_Funding</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TestPBS_gBUILD_PFundingItemController.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_PFundingItemController
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_Project__c p = td.createGbProjectOnPbsProjectEpm1();

        PageReference pr=TestPBS_gBUILD_Utility.setCurrentPageReference(p.id);

        PBS_gBUILD_PFundingItemController ctrl = new PBS_gBUILD_PFundingItemController();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assert(ctrl.item!=null);

        ctrl.save();
        PBS_gBUILD_ProjectFunding__c[] afterItems = [select id, ProjectId__c from PBS_gBUILD_ProjectFunding__c limit 900];
        system.assertEquals(1, afterItems.size());
        system.assertEquals(p.id, afterItems[0].ProjectId__c);

        ctrl.saveAndNew();
        ctrl.cancel();
        ctrl.edit();
        
        //Force the error path to get run
        delete p;
        ctrl.save();
        
        
        pr.getParameters().put(PBS_gBUILD_Utility.queryStringPFundingId,string.valueof(ctrl.item.id));
        Test.setCurrentPageReference(pr);
        ctrl = new PBS_gBUILD_PFundingItemController();
    }
}