force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor10__c.field-meta.xml
<CustomField>
    <fullName>CpEditor10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 10</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 10)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSe9T</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor1__c.field-meta.xml
<CustomField>
    <fullName>CpEditor1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 1</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 1)</relationshipLabel>
    <relationshipName>gBUILD_Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor2__c.field-meta.xml
<CustomField>
    <fullName>CpEditor2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 2)</relationshipLabel>
    <relationshipName>gBUILD_Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor3__c.field-meta.xml
<CustomField>
    <fullName>CpEditor3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 2)</relationshipLabel>
    <relationshipName>gBUILD_Projects5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor4__c.field-meta.xml
<CustomField>
    <fullName>CpEditor4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 4</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 4)</relationshipLabel>
    <relationshipName>gBUILD_Projects6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor5__c.field-meta.xml
<CustomField>
    <fullName>CpEditor5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 5</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 5)</relationshipLabel>
    <relationshipName>gBUILD_Projects7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor6__c.field-meta.xml
<CustomField>
    <fullName>CpEditor6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 6</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 6)</relationshipLabel>
    <relationshipName>gBUILD_Projects8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor7__c.field-meta.xml
<CustomField>
    <fullName>CpEditor7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 7</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 7)</relationshipLabel>
    <relationshipName>gBUILD_Projects9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor8__c.field-meta.xml
<CustomField>
    <fullName>CpEditor8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 8</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 8)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSdiE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpEditor9__c.field-meta.xml
<CustomField>
    <fullName>CpEditor9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has EDIT rights.</description>
    <inlineHelpText>Customer Portal Contact who has EDIT rights.</inlineHelpText>
    <label>Customer Portal Editor 9</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Editor 9)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSdsm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer1__c.field-meta.xml
<CustomField>
    <fullName>CpViewer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>gBUILD_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer2__c.field-meta.xml
<CustomField>
    <fullName>CpViewer2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Viewer 2)</relationshipLabel>
    <relationshipName>gBUILD_Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer3__c.field-meta.xml
<CustomField>
    <fullName>CpViewer3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Viewer 3)</relationshipLabel>
    <relationshipName>gBUILD_Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer4__c.field-meta.xml
<CustomField>
    <fullName>CpViewer4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has VIEW rights.</description>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 4</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Viewer 4)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSgb7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer5__c.field-meta.xml
<CustomField>
    <fullName>CpViewer5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has VIEW rights.</description>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 5</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Viewer 5)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSgfJ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer6__c.field-meta.xml
<CustomField>
    <fullName>CpViewer6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has VIEW rights.</description>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 6</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Viewer 6)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSgiq</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/CpViewer7__c.field-meta.xml
<CustomField>
    <fullName>CpViewer7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Portal Contact who has VIEW rights.</description>
    <inlineHelpText>Customer Portal Contact who has VIEW rights.</inlineHelpText>
    <label>Customer Portal Viewer 7</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>contains</operation>
            <value>gBUILD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gBUILD Projects (Customer Portal Viewer 7)</relationshipLabel>
    <relationshipName>gBUILD_ProjectsSgp4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_PContactsController.cls
public with sharing class PBS_gBUILD_PContactsController extends PBS_gBUILD_ProjectIdBaseController
{
    public List <Actor> ProjectActors { get; private set; }
    public List <Actor> GlobalActors { get; private set; }
    public string actionId { get; set; }
    public PBS_gBUILD_Project__c pro { get; private set; }
    
    public PBS_gBUILD_PContactsController()
    {
        super('Contact Roles');
        try
        {
            bind();
        }
        catch (Exception ex)
        {
            handleConstructorError(ex);
        }           
        this.ProjectActors = ProjectActors; 
        system.debug('Action ID---->' + actionId);   
    }

    public class Actor implements Comparable 
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Type { get; set; }
        public string UserOrGroupId { get; set; }
        public string AccessLevel { get; set; }
        public string RowCause { get; set; }
        public string ShareId { get; set; }

        public string Link
        {
            get 
            { 
                if(Type=='User' || Type=='Group') return '/'+UserOrGroupId;
                return null;
            }
        }

        public integer compareTo(object other) 
        {
            Actor that = (Actor) other;
            return Name.compareto(that.name);
        }
    }

    protected override void bind()
    {
        super.bind();
        
        readonlyMode = !(IsOwner || hasPermissionGbAppConfig || isProjectAdmin);
        System.debug('#project Id:' + ProjectId);
        pro = 
        [
            select
                name,
                id, 
                CpEditor1__c,
                CpEditor2__c,
                CpEditor3__c,
                CpEditor4__c,
                CpEditor5__c,
                CpEditor6__c,
                CpEditor7__c,
                CpEditor8__c,
                CpEditor9__c,
                CpEditor10__c,
                CpViewer1__c,
                CpViewer2__c,
                CpViewer3__c,
                CpViewer4__c,
                CpViewer5__c,
                CpViewer6__c,
                CpViewer7__c,
                CpViewer8__c, 
                CpViewer9__c,
                CpViewer10__c
            from PBS_gBUILD_Project__c
            where id=:ProjectId
        ];        

        map<string, PBS_gBUILD_Project__Share> shareByUGId = new map<string, PBS_gBUILD_Project__Share>();
        List<string> userOrGroupIds = new List<string>();
        for (PBS_gBUILD_Project__Share s : 
        [
            select Id, UserOrGroupId, AccessLevel, RowCause
            from PBS_gBUILD_Project__Share
            where ParentId=:projectId           
            limit :PBS_gBUILD_Utility.soqlLimit
        ])
        {
            shareByUGId.put(s.UserOrGroupId, s);
            userOrGroupIds.add(s.UserOrGroupId);
        }
        System.debug('#userOrGroupIds::' + userOrGroupIds);
        ProjectActors = new List<Actor>();
        GlobalActors = new List<Actor>();
        for (User u :
        [
            select Id, Name, Email
            from User
            where id in :userOrGroupIds
        ])            
        {
            PBS_gBUILD_Project__Share s = shareByUGId.get(u.Id);
            Actor a = new Actor();
            a.Name = u.Name;
            a.UserOrGroupId = u.Id;
            a.Type = 'User';
            a.Email = u.Email;
            a.AccessLevel = s.AccessLevel;
            a.RowCause = s.RowCause.removeEnd('__c');
            a.ShareId = s.Id;
            ProjectActors.add(a);
        }

        map<string, List<string>> groupIdsByAccessLevel = new map<string, List<string>>();
        for (Group g :
        [
            select Id, Name, Type, DeveloperName
            from Group
            where id in :userOrGroupIds
        ])            
        {
            PBS_gBUILD_Project__Share s = shareByUGId.get(g.Id);
            Actor a = new Actor();
            a.Name = g.Name;
            if (a.Name==null || a.Name=='') a.Name = g.DeveloperName;
            a.UserOrGroupId = g.Id;
            a.Type = g.Type;
            a.AccessLevel = s.AccessLevel;
            a.RowCause = s.RowCause.removeEnd('__c');
            a.ShareId = s.Id;
            GlobalActors.add(a);
            if (!groupIdsByAccessLevel.containsKey(s.AccessLevel))
            {
                groupIdsByAccessLevel.put(s.AccessLevel, new list<string>());
            }
            groupIdsByAccessLevel.get(s.AccessLevel).add(g.id);
        }

        PBS_gBUILD_Utility.showDebugMessage('---------');

        map<string, Group> groupById = new map<string,Group>();
        for (Group g : [select id, developername, type from group where developername like 'gB%'])
        {
            groupById.put(g.id, g);
        }

        map<string, Actor> globalActorById = new map<string,Actor>();
        set<string> userIds = new set<string>();        
        for (string accessLevel : groupIdsByAccessLevel.keySet())
        {
            List<string> groupIds = groupIdsByAccessLevel.get(accessLevel);
            PBS_gBUILD_Utility.showDebugMessage(string.Format('contact AccessLevel={0} groupCount={1}', new string[]{accessLevel, groupIds.size().format()}));
            map<string, List<string>> userIdsByGroupId = PBS_gBUILD_Utility.GetGroupMemberIds(groupIds, false);
            for (string groupId : userIdsByGroupId.keySet())
            {
                Group g = null;
                if (groupById.containsKey(groupId))
                {
                    g = groupById.get(groupId);
                }
                userIds.addAll(userIdsByGroupId.get(groupId));
                for (string userId : userIdsByGroupId.get(groupId))
                {
                    Actor a;
                    if (globalActorById.containsKey(userId))
                    {
                        a = globalActorById.get(userId);
                    }
                    else
                    {
                        a = new Actor();
                        globalActorById.put(userId, a);
                        a.UserOrGroupId = userId;
                        a.Type = 'User';                        
                    }
                    if (
                        (a.AccessLevel==PBS_gBUILD_Utility.accessLevelRead || a.AccessLevel==null) ||
                        (a.AccessLevel==PBS_gBUILD_Utility.accessLevelEdit && accessLevel==PBS_gBUILD_Utility.accessLevelAll))
                    {
                        a.AccessLevel = accessLevel;
                        a.RowCause = 'Group Membership';
                        if (g!=null) a.RowCause += ' ('+g.DeveloperName+')';
                    }
                }
            }
        }
        for (User u : 
        [
            select id, username, firstname, lastname, name, email, usertype
            from user
            where id in:PBS_gBUILD_Utility.ToList(userIds)
        ])
        {
            if (globalActorById.containsKey(u.id))
            {
                Actor a = globalActorById.get(u.id);
                a.Name = u.Name;
                a.Email = u.Email;
                GlobalActors.add(a);                        
            }
        }
        ProjectActors.sort();
        GlobalActors.sort();
    }

    public PageReference add() 
    {
        return createPageLink(ProjectPageRefs.PContactsItem);
    }       


    public PageReference del() 
    {
        PBS_gBUILD_Project__Share z;
        ShowDebugMessage('ProjectActors is '+ProjectActors);
        ShowDebugMessage('action id is '+actionId);
        try
        {
        z = [select id, UserOrGroupId from PBS_gBUILD_Project__Share where UserOrGroupId=:actionId OR id=:actionId];
        }
        catch (Exception ex)
        {
         ShowDebugMessage(ex);
         ShowDebugMessage('Action ID is '+actionId);
         ShowDebugMessage('z is '+z);
        }
        if(z != null){
            delete z;
            User u =[select name from user where id=:z.UserOrGroupId];
            if(u !=null){
                RecordLastModifiedReason('Contact removed', null, u.Name);
            }
            sendTemplatizedMessages(PBS_gBUILD_Utility.AppConfig.SendContactEmails__c, new string[]{z.UserOrGroupId}, 'ContactRemoved', null);                
        }
       // return createPageLink(ProjectPageRefs.PContacts, true);
       //SD 
       PageReference pageRef= new PageReference('/apex/PBS_gBUILD_PContacts?sfdc.tabName='+ApexPages.currentPage().getParameters().get('sfdc.tabName'));       
       pageRef.setredirect(true);
       return pageRef;
       
    }
 
    public PageReference edit() 
    {
        viewMode = false;
        bind();
        return null;
    }  
         
    public PageReference cancel() 
    {
        viewMode = true;
        bind();
        return null;
    }  
    
    public PageReference save() 
    {
        update pro;
        viewMode = true;
        bind();
        return null;
    }          
}