force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ModifiedReason__c.field-meta.xml
<CustomField>
    <fullName>ModifiedReason__c</fullName>
    <description>The reason this object was modified</description>
    <inlineHelpText>The reason this object was modified</inlineHelpText>
    <label>Last Modified Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The PBS Project associated with this record.</description>
    <inlineHelpText>The PBS Project associated with this record.</inlineHelpText>
    <label>Project ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>gBUILD Projects</relationshipLabel>
    <relationshipName>PBS_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>Small Projects: Minor improvements of systems/conditions
Lim. Scope: Improvement of single/limited component(s)
Partial Mod: Replace/restore some major systems
Full Mod: Replace/restore all major components
New Con: New structures/building extensions</description>
    <inlineHelpText>Small Projects: Minor improvements of systems/conditions
Lim. Scope: Improvement of single/limited component(s)
Partial Mod: Replace/restore some major systems
Full Mod: Replace/restore all major components
New Con: New structures/building extensions</inlineHelpText>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NewConstruction</fullName>
            </value>
            <value>
                <fullName>FullModernization</fullName>
            </value>
            <value>
                <fullName>PartialModernizations</fullName>
            </value>
            <value>
                <fullName>LimitedScope</fullName>
            </value>
            <value>
                <fullName>SmallProject</fullName>
            </value>
            <value>
                <fullName>EnergyDivision</fullName>
            </value>
            <value>
                <fullName>EnergyDiv - ENE0000</fullName>
            </value>
            <value>
                <fullName>EnergyDiv - ENWTR000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/txtProgramArea_FullCode__c.field-meta.xml
<CustomField>
    <fullName>txtProgramArea_FullCode__c</fullName>
    <description>Clone of the PBS_Project__c.txtProgramArea_FullCode__c field.  Here so we can use SF declarative security.  This is populated via a trigger.</description>
    <label>Program Area Full Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/WorkflowPhaseId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current workflow phase for this project</description>
    <inlineHelpText>Current workflow phase for this project</inlineHelpText>
    <label>Workflow Phase ID</label>
    <referenceTo>gBUILD_ApplicationConfig__c</referenceTo>
    <relationshipLabel>PBS_gBUILD_Project -&amp;amp;amp;amp;gt; gBUILD_ApplicationConfig</relationshipLabel>
    <relationshipName>L_PBS_gBUILD_Project_2_gBUILD_Applicatio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/numProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>numProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Project Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCreatedIn__c.field-meta.xml
<CustomField>
    <fullName>txtCreatedIn__c</fullName>
    <label>Created In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gBUILD</fullName>
            </value>
            <value>
                <fullName>GPGIS</fullName>
            </value>
            <value>
                <fullName>ePM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCurrentState__c.field-meta.xml
<CustomField>
    <fullName>txtCurrentState__c</fullName>
    <label>Current State [from ePM]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Formative</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtLongName__c.field-meta.xml
<CustomField>
    <fullName>txtLongName__c</fullName>
    <label>Project Long Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProgram__c.field-meta.xml
<CustomField>
    <fullName>txtProgram__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LPOE Special Programs Office Program</fullName>
            </value>
            <value>
                <fullName>Region 01 - New England Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 01 - New England Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 02 - Northeast and Caribbean Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 02 - Northeast and Caribbean Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 03 - Mid-Atlantic Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 03 - Mid-Atlantic Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 04 - Southeast Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 04 - Southeast Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 05 - Great Lakes Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 05 - Great Lakes Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 06 - Heartland Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 06 - Heartland Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 07 - Greater Southwest Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 07 - Greater Southwest Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 08 - Rocky Mountain Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 08 - Rocky Mountain Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 09 - Pacific Rim Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 09 - Pacific Rim Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 10 - Northwest / Arctic Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 10 - Northwest / Arctic Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Region 11 - National Capital Region Capital Project Program</fullName>
            </value>
            <value>
                <fullName>Region 11 - National Capital Region Small Project Program</fullName>
            </value>
            <value>
                <fullName>Central Office Soft Projects Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProgramArea_FullCode__c.field-meta.xml
<CustomField>
    <fullName>txtProgramArea_FullCode__c</fullName>
    <label>Program Area Full Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARRA</fullName>
            </value>
            <value>
                <fullName>ARRA.BS</fullName>
            </value>
            <value>
                <fullName>ARRA.CT</fullName>
            </value>
            <value>
                <fullName>ARRA.FBM</fullName>
            </value>
            <value>
                <fullName>ARRA.FBM1</fullName>
            </value>
            <value>
                <fullName>ARRA.NP</fullName>
            </value>
            <value>
                <fullName>ARRA.O</fullName>
            </value>
            <value>
                <fullName>NONARRA</fullName>
            </value>
            <value>
                <fullName>NONARRA.BS</fullName>
            </value>
            <value>
                <fullName>NONARRA.CT</fullName>
            </value>
            <value>
                <fullName>NONARRA.ED</fullName>
            </value>
            <value>
                <fullName>NONARRA.FBM</fullName>
            </value>
            <value>
                <fullName>NONARRA.NP</fullName>
            </value>
            <value>
                <fullName>NONARRA.O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtProjectManager__c.field-meta.xml
<CustomField>
    <fullName>txtProjectManager__c</fullName>
    <label>Project Manager</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtRegion__c.field-meta.xml
<CustomField>
    <fullName>txtRegion__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_ProjectCreateEpmController.cls
public with sharing class PBS_gBUILD_ProjectCreateEpmController extends PBS_gBUILD_ProjectCreateBaseController
{
    public List<EpmProjectWrapper> epmProjects { get; private set; }
    public String createFromEpmId { get; set; }
    public PBS_gBUILD_Project__c proj { get; private set; } 
    public String sortDir { get; private set; }
    public String sortExpr  { get; private set; }
    public integer pageSize { get; private set; }
    public integer pageNum { get; private set; }
    public string resortVal { get; set; }
    public boolean allowPrev
    {
        get { return pageNum > 0; }
    }
    public boolean allowNext { get; private set; }
    public string filterExpr { get; set; }
    public String selectedPbsProjectId { get; set; }

    public PBS_gBUILD_ProjectCreateEpmController()
    {
        super('Project Create');
        
        sortDir = 'ASC';
        sortExpr = 'txtLongName__c';
        pageSize = 25;
        pageNum = 0;
        filterExpr = '';

        proj = new PBS_gBUILD_Project__c();

        bind();
    }

    public PageReference nextPage()
    {
        return paginate(1);
    }

    public PageReference prevPage()
    {
        return paginate(-1);
    }

    private PageReference paginate(integer delta)
    {
        pageNum += delta;
        if (pageNum < 0) pageNum = 0;
        bind();
        return null;
    }

    public PageReference resort()
    {
        if (resortVal==sortExpr)
        {
            sortDir = sortDir=='ASC'?'DESC':'ASC';
        }
        else
        {
            sortExpr = resortVal;
            sortDir = 'ASC';
        }
        pageNum = 0;
        bind();
        return null;
    }

    public PageReference filter()
    {
        pageNum = 0;
        bind();
        return null;
    }

    protected override void bind()
    {
        super.bind();
        epmProjects = new List<EpmProjectWrapper>();
        
        List<PBS_gBUILD_Project__c> gbProjects = 
        [
            select projectid__c 
            from PBS_gBUILD_Project__c 
            LIMIT :PBS_gBUILD_Utility.soqlLimit
        ];
                    
        filterExpr = filterExpr.trim();
        boolean numCheck = pattern.matches('^[0-9]+$',filterExpr);
        system.debug('numCheck ----> ' + numCheck);
        string whereClause = '';
        if (filterExpr!='')
        {
            whereClause = string.Format(
                'AND (txtCurrentState__c like {0} or txtLongName__c like {0} or txtRegion__c like {0} or txtProjectManager__c like {0} ', 
                new string[]{'\'%'+string.escapeSingleQuotes(filterExpr)+'%\''});
                
           if (numCheck) {
            whereClause += string.Format(
                'or numProjectNumber__c = {0})', 
                new string[]{string.escapeSingleQuotes(filterExpr)});    
           } else {
           	  whereClause += ')';
           }
                    
        }

        string soql = string.Format(
'            select '+
'                id,'+
'                txtCreatedIn__c,'+
'                txtCurrentState__c,'+
'                txtProjectManager__c,'+
'                txtProgram__c,'+
'                txtProgramArea_FullCode__c, '+
'                txtLongName__c,'+
'                txtRegion__c, '+
'				 numProjectNumber__c'+
'            from PBS_Project__c'+
'            where txtCreatedIn__c in ({3}) {5}'+
'            order by {0} {1}, id'+
'            LIMIT {2}'+
'            OFFSET {4}',
            new string[]{
                sortExpr, 
                sortDir, 
                string.valueOf(pageSize+1),
                PBS_gBUILD_Utility.format(PBS_gBUILD_Utility.allowedBaseProjectCreators, ',', '{0}', true),            
                string.valueOf(pageSize*pageNum),
                whereClause
            });
            
            system.debug('SOQL ---->' +soql);
        PBS_gBUILD_Utility.showDebugMessage(soql);
        List<PBS_Project__c> commonProjects = Database.query(soql);
        allowNext = false;
        if (commonProjects.size()>pageSize)
        {
            allowNext = true;
            commonProjects.remove(pageSize);
        }
        for (PBS_Project__c cp : commonProjects)
        {
            Integer cnt = 0;
            Boolean isGB = false;
            for (PBS_gBUILD_Project__c gbp : gbProjects)
            {
                if (gbp.ProjectId__c==cp.id)
                {
                    ++cnt;
                    isGB = true;
                }
            } 
            epmProjects.add(new EpmProjectWrapper(cp, isGB, cnt));
        }
    }
    
    public PageReference view()
    {
        return new PageReference('/'+createFromEpmId);
    }
    
    public PageReference create()
    {
        PBS_gBUILD_Utility.showDebugMessage('Selected id = '+selectedPbsProjectId);
        createFromEpmId = selectedPbsProjectId;
        
        if (createFromEpmId ==null || createFromEpmId =='')
        {
            PBS_gBUILD_Utility.showWarningMessage('You must select an underlying ePM Project');
            return null;
        }
        
        if (proj.ProjectType__c==null || proj.ProjectType__c=='')
        {
            PBS_gBUILD_Utility.showWarningMessage('You must specify a Project Type');
            return null;
        }
        
        proj.ProjectId__c=createFromEpmId;        
        proj.WorkflowPhaseId__c = PBS_gBUILD_Utility.findInitialWfStateId(
            (proj.ProjectType__c==PBS_gBUILD_Utility.projectTypeNewConstruction || proj.ProjectType__c==PBS_gBUILD_Utility.projectTypeFullModernization) ?
            PBS_gBUILD_Utility.WfStateMachineTypes.Large : 
            PBS_gBUILD_Utility.WfStateMachineTypes.Small
        );
        proj.ModifiedReason__c = 'Project was created';        
        insert proj;
        system.debug('Project ID is---->' + proj.id);
        system.debug('Return URL ID is---->' + PBS_gBUILD_Utility.createLinkProjectBasics(proj.id));
        
        return new PageReference('/apex/PBS_gBUILD_Projects'); //SD
        //return null;
    }

    class EpmProjectWrapper
    {
        public PBS_Project__c rec { get; private set; }
        public Boolean isGB { get; private set; }
        public Boolean renderCreateButton { get; private set;}
        public Integer gbProjectCount { get; private set; }
        public string projectName { get; private set; }
        public EpmProjectWrapper(PBS_Project__c rec, Boolean isGB, Integer gbProjectCount)
        {
            this.rec = rec;
            this.isGB = isGB;
            this.renderCreateButton = !isGB;
            this.gbProjectCount = gbProjectCount;
            this.projectName = PBS_gBUILD_Utility.shorten(rec.txtLongName__c,100);
        }
    }   
}