force-app/main/default/objects/PBS_gBUILD_Project__c/PBS_gBUILD_Project__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project: Project data and the root for all other gBUILD objects.</description>
    <label>gBUILD Project</label>
    <nameField>
        <displayFormat>gbP_{00000}</displayFormat>
        <label>PBS gBUILD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/FirstPaymentDue__c.field-meta.xml
<CustomField>
    <fullName>FirstPaymentDue__c</fullName>
    <description>1st payment date</description>
    <inlineHelpText>Enter first payment due date</inlineHelpText>
    <label>Date First Payment Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <description>Total number of payments</description>
    <inlineHelpText>Enter total number of payments</inlineHelpText>
    <label># Payments</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_Project__c/fields/PerfPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PerfPaymentMethod__c</fullName>
    <description>Method of repayment</description>
    <inlineHelpText>Select payment method.</inlineHelpText>
    <label>Performance Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPBS_gBUILD_PFinancialsController.cls
@isTest(SeeAllData=false)
public class TestPBS_gBUILD_PFinancialsController
{  
    private static final TestPBS_gBUILD_Utility.TestData td;

    static 
    {
        TestPBS_gBUILD_Utility.setup();
        td = new TestPBS_gBUILD_Utility.TestData();
    }

    public static testMethod void testConstructor()
    {
        PBS_gBUILD_Project__c p = td.createGbProjectOnPbsProjectEpm1();

        TestPBS_gBUILD_Utility.setCurrentPageReference(p.id);

        PBS_gBUILD_PFinancialsController ctrl = new PBS_gBUILD_PFinancialsController();
        system.assert(ctrl!=null);
        system.assertEquals(null, ctrl.projectIdBaseControllerException);
        system.assert(ctrl.fin!=null);
        system.assertEquals(0, ctrl.cashFlowList.size());
        system.assertEquals(0, ctrl.cashflows.size());

        Date dt = date.parse('12/27/2009');
        dt = dt.addYears(1);
        ctrl.fin.FirstPaymentDue__c = dt;
        ctrl.fin.Payments__c = 24;
        ctrl.fin.PerfPaymentMethod__c = PBS_gBUILD_Utility.projectPerformancePaymentMethodMonthly;
        ctrl.save();

        system.assertEquals(24, ctrl.cashFlowList.size());
        system.assertEquals(24, ctrl.cashflows.size());
                
        ctrl.fin.PerfPaymentMethod__c = PBS_gBUILD_Utility.projectPerformancePaymentMethodQuarterly;
        ctrl.save();
        ctrl.fin.PerfPaymentMethod__c = PBS_gBUILD_Utility.projectPerformancePaymentMethodAnnually;
        ctrl.save();                

        ctrl.cancel();
        ctrl.edit();
    }
}