force-app/main/default/objects/App_Log__c/App_Log__c.object-meta.xml
<CustomObject>
    <description>Captures the logging info from log events and retains the information for a certain period of time</description>
    <label>App Log</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>App Log Detail	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>To capture the apex class/trigger from where the log event has been published</description>
    <inlineHelpText>To capture the apex class/trigger from where the log event has been published</inlineHelpText>
    <label>Apex Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Log__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Used to determine the unique app log</description>
    <inlineHelpText>Used to determine the unique app log</inlineHelpText>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Log_Detail__c/App_Log_Detail__c.object-meta.xml
<CustomObject>
    <description>Child object of App log. Capture each log entries for an app log</description>
    <label>App Log Detail</label>
    <nameField>
        <label>App Log Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Log Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Log_Detail__c/fields/App_Log__c.field-meta.xml
<CustomField>
    <fullName>App_Log__c</fullName>
    <label>App Log</label>
    <referenceTo>App_Log__c</referenceTo>
    <relationshipLabel>App Log Details</relationshipLabel>
    <relationshipName>App_Log_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/App_Log_Detail__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Captures log message for each log</description>
    <inlineHelpText>Captures log message for each log</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Custom platform event to leverage the functionality of advanced logging using custom objects</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>To capture the apex class/trigger from where the log event has been published</description>
    <label>Apex Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <description>Capture the Batch job Id, if present</description>
    <label>AsyncApexJobId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Captures log message for each log event</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Used to determine the unique app log</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerTest.cls
@isTest
public class LogEventTriggerTest {
    
    @isTest
    static void logEventPublishTest(){
        Test.startTest();
        
        Map<String,ID> profiles = new Map<String,ID>();  
        List<Profile> ps = [select id, name from Profile where name = 'GSA System Administrator' or name = 'System Administrator'];  
        for(Profile p : ps){  
            profiles.put(p.name, p.id);  
        }  
        User admin = [SELECT Id FROM user WHERE IsActive = True And profileid = :profiles.get('GSA System Administrator') Limit 1];  

        
        List<Database.SaveResult> results = null;
        
        system.runAs(admin){
            List<Log__e> events = new List<Log__e>();
            
            Log__e log1 = new Log__e();
            log1.Message__c = 'Test Message 1';
            log1.Apex_Class_Name__c = 'Test Class';
            log1.UUID__c = 'DFJSJ#@$46';
            events.add(log1);
            
            results =  EventBus.publish(events);
        }
        
        Test.stopTest();
        System.assertEquals(results.size(), 1);
    }
    
    
    @isTest
    static void testExistingAppLog(){
        Map<String,ID> profiles = new Map<String,ID>();  
        List<Profile> ps = [select id, name from Profile where name = 'GSA System Administrator' or name = 'System Administrator'];  
        for(Profile p : ps){  
            profiles.put(p.name, p.id);  
        }  
        User admin = [SELECT Id FROM user WHERE IsActive = True And profileid = :profiles.get('GSA System Administrator') Limit 1];  
       
        system.runAs(admin){
            App_Log__c al = new App_Log__c(Apex_Class_Name__c  = 'Test Class', UUID__c = '12389-DVF348899-389');
            insert al;
            
            List<Log__e> events = new List<Log__e>();
            
            Log__e log1 = new Log__e();
            log1.Message__c = 'Test Message 1';
            log1.Apex_Class_Name__c = 'Test Class';
            log1.UUID__c = '12389-DVF348899-389';
            log1.AsyncApexJobId__c = '01I35000000Grb8';
            events.add(log1);

            Test.startTest();
            EventBus.publish(events);
            Test.stopTest();
            
        }
        List<App_Log_Detail__c> detail = [Select ID from App_Log_Detail__c];

        system.debug('logEventTriggerTest.testExistingAppLog(), App_Log_Detail__c IDs: ' + detail);   
        system.assertEquals(detail.size(), 1);
    }
}