force-app/main/default/objects/App_Log__c/App_Log__c.object-meta.xml
<CustomObject>
    <description>Captures the logging info from log events and retains the information for a certain period of time</description>
    <label>App Log</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>App Log Detail	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Log__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>To capture the apex class/trigger from where the log event has been published</description>
    <inlineHelpText>To capture the apex class/trigger from where the log event has been published</inlineHelpText>
    <label>Apex Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Log__c/fields/Apex_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Apex_Job_Id__c</fullName>
    <description>Capture the Batch job Id, if present</description>
    <inlineHelpText>Capture the Batch job Id, if present</inlineHelpText>
    <label>Apex Job Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Log__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/App_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <description>Determines whether the log is a info/exception</description>
    <inlineHelpText>Determines whether the log is a info/exception</inlineHelpText>
    <label>Log Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Log__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/App_Log__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Used to determine the unique app log</description>
    <inlineHelpText>Used to determine the unique app log</inlineHelpText>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Log_Detail__c/App_Log_Detail__c.object-meta.xml
<CustomObject>
    <description>Child object of App log. Capture each log entries for an app log</description>
    <label>App Log Detail</label>
    <nameField>
        <label>App Log Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Log Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Log_Detail__c/fields/App_Log__c.field-meta.xml
<CustomField>
    <fullName>App_Log__c</fullName>
    <label>App Log</label>
    <referenceTo>App_Log__c</referenceTo>
    <relationshipLabel>App Log Details</relationshipLabel>
    <relationshipName>App_Log_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/App_Log_Detail__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <description>Captures the batch job scope, if running a Batch/Queueable apex</description>
    <inlineHelpText>Captures the batch job scope, if running a Batch/Queueable apex</inlineHelpText>
    <label>Job Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Log_Detail__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Captures log message for each log</description>
    <inlineHelpText>Captures log message for each log</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Custom platform event to leverage the functionality of advanced logging using custom objects</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>To capture the apex class/trigger from where the log event has been published</description>
    <label>Apex Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <description>Capture the Batch job Id, if present</description>
    <label>AsyncApexJobId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/JobScope__c.field-meta.xml
<CustomField>
    <fullName>JobScope__c</fullName>
    <description>Captures the batch job scope, if running a Batch/Queueable apex</description>
    <label>JobScope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <description>Determines whether the log is a info/exception</description>
    <label>Log Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Captures log message for each log event</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Used to determine the unique app log</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerHandler.cls
/**
* @author Vishnu G 
* @date May 2020.
*
* @group Trigger
*
* @description Trigger handler to handle custom log events 
               and create AppLog and AppLog Details accordingly 
*/
public with sharing class LogEventTriggerHandler {
    
    private List<Log__e> events;
    
    public LogEventTriggerHandler(List<Log__e> events) { 
        this.events = events;
    }
    
    /*
    * @description Processes BatchApexErrorEvents, creates App Log and App Log Details to persist the event details.
                   Uses UUID,a unique Identifier present on events, to group a App Log and AppLog Details
    * @return void
    */  
    public void handle() {
        try{
            Set<String> uuids = new Set<String>();
            Map<String, App_Log__c> appLogMap = new Map<String, App_Log__c>();
            Map<String, List<App_Log_Detail__c>> appLogDetailsById = new Map<String, List<App_Log_Detail__c>>();
            
            for(Log__e evt : events){
                uuids.add(evt.UUID__c);
                appLogDetailsById.put(evt.UUID__c, new List<App_Log_Detail__c>());
            }
                        
            //Fetch the existing App Logs with the Unique Id present in the above UUID set
            for(App_Log__c al : [Select Id, UUID__c from App_Log__c where UUID__c IN :uuids]){
                appLogMap.put(al.UUID__c, al);
            }
                        
            for(Log__e evt: events){
                String uuid = evt.UUID__c;
                
                if(appLogMap == null || !appLogMap.containsKey(uuid)){
                    App_Log__c appLog =  new App_Log__c(
                        Apex_Class_Name__c = evt.Apex_Class_Name__c,
                        Username__c = evt.Username__c,
                        Start_Time__c = DateTime.now(),
                        End_Time__c = DateTime.now(),
                        Log_Type__c = String.isNotBlank(evt.Log_Type__c) ? evt.Log_Type__c : 'Info', 
                        Apex_Job_Id__c = String.isNotBlank(evt.AsyncApexJobId__c) ? evt.AsyncApexJobId__c : '',
                        UUID__c = uuid
                    );
                    appLogMap.put(uuid, appLog);
                } 
                
                //To populate Apex JobId if present in an event
                if(appLogMap != null && appLogMap.containsKey(uuid) && String.isNotBlank(evt.AsyncApexJobId__c)){
                    appLogMap.get(uuid).Apex_Job_Id__c =  String.isNotBlank(evt.AsyncApexJobId__c) ? evt.AsyncApexJobId__c : '';
                }
                // Add Error to Log
                appLogDetailsById.get(uuid).add(
                    new App_Log_Detail__c(
                        Username__c = evt.Username__c,
                        Message__c = evt.Message__c,
                        Job_Scope__c = evt.JobScope__c));
            }
            
            // Insert log records
            upsert appLogMap.values();
                
            List<App_Log_Detail__c> logDetails = new List<App_Log_Detail__c>();
            for(String uniqueId : appLogMap.keySet()) {
                App_Log__c log = appLogMap.get(uniqueId);
                for(App_Log_Detail__c logDetail : appLogDetailsById.get(uniqueId)) {

                    logDetail.App_Log__c = log.Id;
                    logDetails.add(logDetail);
                }        
            }
            insert logDetails;  
                
        }catch(Exception e){
            System.debug('Exception on inserting App Log and App Log Details ---> ' + e);
        }
    }

}