force-app/main/default/objects/Mule_API__mdt/Mule_API__mdt.object-meta.xml
<CustomObject>
    <label>Mule API</label>
    <pluralLabel>Mule APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mule_API__mdt/fields/Authentication_Type__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Type__c</fullName>
    <defaultValue>&apos;Basic&apos;</defaultValue>
    <label>Authentication Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
                <default>true</default>
                <label>Basic</label>
            </value>
            <value>
                <fullName>SSO</fullName>
            </value>
            <value>
                <fullName>Keys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <label>Base_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Error_Email_Body_Prelude__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Body_Prelude__c</fullName>
    <description>Opening statement for the Email that is meant to alert of an error associated with an API call.</description>
    <inlineHelpText>Example: &quot;A Mule API interface error occurred.  Error = &quot;</inlineHelpText>
    <label>Error Email Body Prelude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Error_Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Sender_Name__c</fullName>
    <label>Error Email Sender Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Error_Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Subject__c</fullName>
    <description>Brief subject line for the error email intending to alert of a Mule API interface issue.</description>
    <inlineHelpText>Example: &quot;Mule API Interface Issue&quot;</inlineHelpText>
    <label>Error Email Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Error_Email_To_Address1__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_To_Address1__c</fullName>
    <label>Error Email To Address1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Error_Email_To_Address2__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_To_Address2__c</fullName>
    <label>Error Email To Address2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/filterType__c.field-meta.xml
<CustomField>
    <fullName>filterType__c</fullName>
    <label>filterType</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Timeout_value__c.field-meta.xml
<CustomField>
    <fullName>Timeout_value__c</fullName>
    <label>Timeout_value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mule_API__mdt/fields/VFilters__c.field-meta.xml
<CustomField>
    <fullName>VFilters__c</fullName>
    <label>VFilters</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/APIMetadataModel.cls
public With Sharing class APIMetadataModel {

    private static List<Mule_API__mdt> pcustomMetadataList = null;
    public static List<Mule_API__mdt> customMetadataList {
        get {
            if (pcustomMetadataList == null) {
                pcustomMetadataList = [select Id, DeveloperName, Username__c, Password__c,Base_URL__c, 
                                       Timeout_Value__c, Error_Email_Subject__c, Error_Email_Body_Prelude__c,
                                       Error_Email_Sender_Name__c, Error_Email_To_Address1__c, Authentication_Type__c,
                                       Error_Email_To_Address2__c, Client_Id__c, Client_Secret__c, VFilters__c, filterType__c
                                       from Mule_API__mdt where Is_Active__c = true]; 
            }
            return pcustomMetadataList;
        } 
    }
    
    private static Map<String,Mule_API__mdt> pcustomMetadataMap = null;
    public static Map<String,Mule_API__mdt> customMetadataMap {
        get {
            if ( pcustomMetadataMap == null){
                pcustomMetadataMap = new Map<String,Mule_API__mdt>(); 
                for(Mule_API__mdt rt : customMetadataList){
                    pcustomMetadataMap.put(rt.DeveloperName, rt);
                } 
            }
            return pcustomMetadataMap;
        }
    }
    
    public static Mule_API__mdt lookupAPICustomMetaData (String keyName){
        System.Debug('APIMetadataModel.LookupCustomMetada starting...');
        if(customMetadataMap.containsKey(keyName)){          
            return customMetadataMap.get(keyName);
        }else { 
            //unable to locate
            System.Debug('APIMetadataModel.LookupCustomMetada unable to locate '+ keyName);
            return null;
        }  
    }
    
    
    
}