force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project_Cost_Rate__c/NCMT_Project_Cost_Rate__c.object-meta.xml
<CustomObject>
    <label>TCO Project Cost Rate</label>
    <nameField>
        <displayFormat>PCR-{000}</displayFormat>
        <label>Cost Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCO Project Cost Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project_Cost_Rate__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Project_Cost_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Annual_Cost_Summary__c/NCMT_TCO_Annual_Cost_Summary__c.object-meta.xml
<CustomObject>
    <label>NCMT TCO Annual Cost Summary</label>
    <nameField>
        <displayFormat>ACS-{000}</displayFormat>
        <label>NCMT AnnualCost Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT TCO Annual Cost Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TCO_Annual_Cost_Summary__c/fields/NCMT_TCO_Lifecycle_Input__c.field-meta.xml
<CustomField>
    <fullName>NCMT_TCO_Lifecycle_Input__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT TCO Lifecycle Input</label>
    <referenceTo>NCMT_TCO_Lifecycle_Input__c</referenceTo>
    <relationshipLabel>NCMT TCO Annual Cost Summary</relationshipLabel>
    <relationshipName>NCMT_TCO_Annual_Cost_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Annual_Cost_Summary__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>NCMT_NPV_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_LCC__c/NCMT_TCO_LCC__c.object-meta.xml
<CustomObject>
    <label>NCMT TCO LCC</label>
    <nameField>
        <displayFormat>LCC-{000000}</displayFormat>
        <label>NCMT TCO LCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT TCO LCCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TCO_LCC__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT TCO LCCs</relationshipLabel>
    <relationshipName>NCMT_TCO_LCCs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_LCC__c/fields/TCO_Lifecycle_Input__c.field-meta.xml
<CustomField>
    <fullName>TCO_Lifecycle_Input__c</fullName>
    <label>TCO Lifecycle Input</label>
    <referenceTo>NCMT_TCO_Lifecycle_Input__c</referenceTo>
    <relationshipLabel>NCMT TCO LCCs</relationshipLabel>
    <relationshipName>NCMT_TCO_LCCs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_LCC__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <inlineHelpText>Analysis year that drives Fiscal Year and refresh/retrofit calculations.</inlineHelpText>
    <label>Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/NCMT_TCO_Lifecycle_Input__c.object-meta.xml
<CustomObject>
    <label>NCMT TCO Lifecycle Input</label>
    <nameField>
        <displayFormat>Lifecycle-{00000}</displayFormat>
        <label>TCO Lifecycle Input Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT TCO Lifecycle Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>TCO_Lifecycle_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_TCO_Lifecycle_Input__c/fields/NCMT_TCO_Annual_Cost_Summary__c.field-meta.xml
<CustomField>
    <fullName>NCMT_TCO_Annual_Cost_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT TCO Annual Cost Summary</label>
    <referenceTo>NCMT_TCO_Annual_Cost_Summary__c</referenceTo>
    <relationshipName>TCO_Lifecycle_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Level_Parameter__c/Project_Level_Parameter__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project Level Parameters

parametric cost estimating is a technique used in planning, budgeting, and performance stages of the acquisition process. The technique is used to expedite the development of cost estimates when discrete estimating techniques would require inordinate amounts of time and resources and would produce similar results. The concept includes the use of Cost-Estimating-Relationships (CER&apos;s) such as those defined in the varied Unit Cost Studies of which the models in the PCPG are based. Parametric techniques focus on the cost drivers, not the miscellaneous details.</description>
    <label>Project Level Parameter</label>
    <nameField>
        <displayFormat>PLP-{00000}</displayFormat>
        <label>Project Level Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Level Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Level_Parameter__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>Project Level Parameters</relationshipLabel>
    <relationshipName>Project_Level_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NCMT_TCO_Project.cls
public with sharing class NCMT_TCO_Project {
    /*
        Class to store a TCO NCMT_Project__c record and related records/classes
    
        Create a new NCMT_TCO_Project object by passing in project Id:
            NCMT_TCO_Project p = projectMap.get(projectId);
        OR, to include LCC cost breakouts...
            NCMT_TCO_Project p = projectMap.get(projectId, true);
    
        The related records are queried and populated in the variables 
        with get/set methods at the top of this class
            e.g. annualCost is a NCMT_TCO_Annual_Cost_Summary__c record, 
            so tcoProject.annualCost.<field_name> returns that field value
        
        lccs is a list of the custom class NCMT_TCO_LCC with the NCMT_TCO_LCC__C record
        and, if populateCostDate = true, properties that gather 
        and store the cost data by category, which summaries at the LCC record
        level (fiscal year) and for each category (Facilities, Construction, Utilities...)
    
        5/27/20- Created, JG
    */
        
        @AuraEnabled public NCMT_Project__c record {get;set;}
        //The Project only has one of each of these records
        @AuraEnabled public NCMT_TCO_Annual_Cost_Summary__c annualCost {get;set;}
        @AuraEnabled public NCMT_Project_Cost_Rate__c costRates {get;set;}
        @AuraEnabled public Project_Level_Parameter__c projectParam {get;set;}
        @AuraEnabled public NCMT_TCO_Lifecycle_Input__c lifeCycle {get;set;}
        @AuraEnabled public List<NCMT_TCO_LCC> lccs {get;set;}
        @AuraEnabled public Decimal totalCost {get;set;}
        @AuraEnabled public Decimal totalEscalated {get;set;}
        @AuraEnabled public Decimal totalEscalatedDiscounted {get;set;}
        @AuraEnabled public NCMT_TCO_LCC totalLCC {get;set;}
    
        public NCMT_TCO_Project(Id projId, Boolean populateCostData) {
    
            //May not need every field here so if size becomes an issue, par down
            String soql = 'Select ' +NCMT_Utilities.getFieldSoQL('NCMT_Project__c', 'all');
            soql += ' from NCMT_Project__c where Id = \'' +projId +'\'';
            for (NCMT_Project__c proj : Database.query(soql))
                record =  proj;
    
            soql = 'Select ' +NCMT_Utilities.getFieldSoQL('NCMT_TCO_Annual_Cost_Summary__c', 'all');
            soql += ' from NCMT_TCO_Annual_Cost_Summary__c where Project_Name__c = \'' +projId +'\'';
            for (NCMT_TCO_Annual_Cost_Summary__c annual : Database.query(soql))
                annualCost =  annual;
        
            soql = 'Select ' +NCMT_Utilities.getFieldSoQL('NCMT_Project_Cost_Rate__c', 'all');
            soql += ' from NCMT_Project_Cost_Rate__c where Project_Name__c = \'' +projId +'\'';
            for (NCMT_Project_Cost_Rate__c rate : Database.query(soql))
                costRates =  rate;
        
            soql = 'Select ' +NCMT_Utilities.getFieldSoQL('NCMT_TCO_Lifecycle_Input__c', 'all');
            soql += ' from NCMT_TCO_Lifecycle_Input__c where NCMT_Project__c = \'' +projId +'\'';
            for (NCMT_TCO_Lifecycle_Input__c life : Database.query(soql))
                lifeCycle =  life;

            soql = 'Select ' +NCMT_Utilities.getFieldSoQL('Project_Level_Parameter__c', 'all');
            soql += ' from Project_Level_Parameter__c where NCMT_Project__c = \'' +projId +'\'';
            for (Project_Level_Parameter__c pp : Database.query(soql))
                projectParam =  pp;
            
            lccs = new List<NCMT_TCO_LCC>();
            String lccFieldString = NCMT_Utilities.getFieldSoQL('NCMT_TCO_LCC__c', 'all');
            //These fields hit an error when doing recalculateFormulas on the LCC, so skip them...
            lccFieldString.replace(', tco_lifecycle_input__c', '').replace(', ncmt_project__c', '');
            soql = 'Select ' +lccFieldString;
            soql += ' from NCMT_TCO_LCC__c where NCMT_Project__c = \'' +projId +'\' Order By Year__c';
            for (NCMT_TCO_LCC__c l : Database.query(soql))
                lccs.add(new NCMT_TCO_LCC(l, populateCostData));
            
            if (populateCostData){
                totalCost = 0;
                totalEscalated = 0;
                totalEscalatedDiscounted = 0;
    
                Map<String, NCMT_TCO_LCC.Category> catMap = new Map<String, NCMT_TCO_LCC.Category>();
                Map<String, NCMT_TCO_LCC.Cost> costMap = new Map<String, NCMT_TCO_LCC.Cost>();
                //Grab project totals
                List<String> catNames = new List<String>();
                Map<String, List<String>> costLabels = new Map<String, List<String>>();
                totalLCC = new NCMT_TCO_LCC();
                if (lccs.size() > 0){

                    for (NCMT_TCO_LCC lcc : lccs){
                        for (NCMT_TCO_LCC.Category cat : lcc.categories){
                            if (catMap.get(cat.name) == null){
                                catMap.put(cat.name, new NCMT_TCO_LCC.Category(cat.Name));
                                catNames.add(cat.name);
                            }
                            catMap.get(cat.name).cost += cat.cost;
                            catMap.get(cat.name).escalatedCost += cat.escalatedCost;
                            catMap.get(cat.name).escalatedDiscountedCost += cat.escalatedDiscountedCost;
        
                            for (NCMT_TCO_LCC.Cost c : cat.costs){
                                if (costMap.get(c.label) == null){
                                    costMap.put(c.label, new NCMT_TCO_LCC.Cost(c.label));
                                    if (costLabels.get(cat.name) == null) costLabels.put(cat.name, new List<String>());
                                    costLabels.get(cat.name).add(c.label);
                                }
                                costMap.get(c.label).cost += c.cost;
                                costMap.get(c.label).escalatedCost += c.escalatedCost;
                                costMap.get(c.label).escalatedDiscountedCost += c.escalatedDiscountedCost;
                
                            }
                        }
                        totalCost += lcc.totalCost;
                        totalEscalated += lcc.totalEscalated;
                        totalEscalatedDiscounted += lcc.totalEscalatedDiscounted;
                    }  
                    for (String catName : catNames){
                        NCMT_TCO_LCC.Category cat = catMap.get(catName);
                        
                        for (String costLabel : costLabels.get(catName)){
                            cat.costs.add(costMap.get(costLabel));
                        }
                        for (Integer i = 0; i < totalLCC.categories.size(); i++){
                            NCMT_TCO_LCC.Category c = totalLCC.categories[i];
                            if (c.name == catName) totalLCC.categories[i] = cat;
                        }
                        //totalLCC.categories.add(cat);
                        System.debug('total catName ----------------------- ' +catName);
                    }
                }
            
            }
        }
    }