force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Tree_structure__c/NCMT_Tree_structure__c.object-meta.xml
<CustomObject>
    <label>NCMT Tree structure</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Tree Structure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Tree structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <inlineHelpText>Name associated with the selected level of project tree</inlineHelpText>
    <label>Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <inlineHelpText>Description of the Parent</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Include_In_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Estimate__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If checked, the value will be included in the estimate. If not checked, the value will not be included in the estimate.</inlineHelpText>
    <label>Include In Estimate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Tree_structures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Relatedtree__c.field-meta.xml
<CustomField>
    <fullName>Relatedtree__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ID of the Parent for the branch.</inlineHelpText>
    <label>Parent</label>
    <referenceTo>NCMT_Tree_structure__c</referenceTo>
    <relationshipLabel>NCMT Tree structures</relationshipLabel>
    <relationshipName>Tree_structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/NCMT_NewTreeButton_Ctrl.cls
public with sharing class NCMT_NewTreeButton_Ctrl {
    @AuraEnabled
    public static String projectId {get; set;}
    @AuraEnabled
    public static String projectName {get; set;}
    @AuraEnabled
    public static String parentTreeName {get; set;}
    @AuraEnabled
    public static String recordTypeName {get; set;}
    @AuraEnabled
    public static String branchName {get; set;}
    @AuraEnabled
    public static Boolean includeInEstimate {get; set;}
    @AuraEnabled
    public static NCMT_Tree_structure__c newCustomObject {get; set;}
    @AuraEnabled
    public static NCMT_Tree_structure__c existingCustomObject {get; set;}
    @AuraEnabled
    public static void getRecordInformation(Id recordId){
        existingCustomObject=[Select Id, Name, RecordTypeId, Project_ID__c, Project_ID__r.Name, Branch_Name__c,
                              Relatedtree__c,Relatedtree__r.Name, RecordType.Name, description__c, Include_In_Estimate__c	
                              From NCMT_Tree_structure__c Where Id=:recordId];
        projectId=existingCustomObject.Project_ID__c;
        projectName=existingCustomObject.Project_ID__r.Name;
        parentTreeName=existingCustomObject.Name;
        branchName=existingCustomObject.Branch_Name__c;
        recordTypeName='Default';
        includeInEstimate=existingCustomObject.Include_In_Estimate__c;
        newCustomObject=new NCMT_Tree_structure__c();
    }

    @AuraEnabled
    public static Id getsaveNewrecord(String projectName, Id recordId, String dsc, String branchName, Boolean check){
      System.System.debug('projectName: '+ projectName);
      try{
        existingCustomObject=[Select Id, Name, RecordTypeId, Project_ID__c, Project_ID__r.Name, Branch_Name__c,
                              Relatedtree__c,Relatedtree__r.Name, RecordType.Name, description__c, Include_In_Estimate__c	
                              From NCMT_Tree_structure__c Where Id=:recordId];
        projectId=existingCustomObject.Project_ID__c;
        parentTreeName=existingCustomObject.Name;
        recordTypeName='Default';

        newCustomObject=new NCMT_Tree_structure__c();
        newCustomObject.RecordTypeId=Schema.SObjectType.NCMT_Tree_structure__c.getRecordTypeInfosByDeveloperName().get('Default').getRecordTypeId();
        newCustomObject.Project_ID__c=existingCustomObject.Project_ID__r.Id;
        newCustomObject.Relatedtree__c=existingCustomObject.Id;
        newCustomObject.description__c=dsc;
        newCustomObject.Include_In_Estimate__c=existingCustomObject.Include_In_Estimate__c;
        newCustomObject.Branch_Name__c= branchName;
        insert newCustomObject;
        System.debug('newCustomObject: '+newCustomObject);

        return newCustomObject.Id;
      }  
      catch(Exception e){
        System.debug('An Exception: '+e);
        return null;
      }
    }
    @AuraEnabled(cacheable=true)
    public static string getProjectName(Id recordId){
        NCMT_Tree_structure__c obj=[Select Id, Name, RecordTypeId, Project_ID__c, Project_ID__r.Name, Branch_Name__c,
        Relatedtree__c,Relatedtree__r.Name, RecordType.Name, description__c, Include_In_Estimate__c	
        From NCMT_Tree_structure__c Where Id=:recordId];
        return obj.Project_ID__r.Name;
    }
    
    @AuraEnabled(cacheable=true)
    public static string getParentTree(Id recordId){
        NCMT_Tree_structure__c obj=[Select Id, Name, RecordTypeId, Project_ID__c, Project_ID__r.Name, Branch_Name__c,
        Relatedtree__c,Relatedtree__r.Name, RecordType.Name, description__c, Include_In_Estimate__c	
        From NCMT_Tree_structure__c Where Id=:recordId];
        return obj.Relatedtree__r.Name;
    }
    @AuraEnabled(cacheable=true)
    public static string getrecordTypeName(Id recordId){
        NCMT_Tree_structure__c obj=[Select Id, Name, RecordTypeId, Project_ID__c, Project_ID__r.Name, Branch_Name__c,
        Relatedtree__c,Relatedtree__r.Name, RecordType.Name, description__c, Include_In_Estimate__c	
        From NCMT_Tree_structure__c Where Id=:recordId];
        return obj.recordType.Name;
    }
    @AuraEnabled(cacheable=true)
    public static Boolean getCheck(Id recordId){
        NCMT_Tree_structure__c obj=[Select Id, Name, RecordTypeId, Project_ID__c, Project_ID__r.Name, Branch_Name__c,
        Relatedtree__c,Relatedtree__r.Name, RecordType.Name, description__c, Include_In_Estimate__c	
        From NCMT_Tree_structure__c Where Id=:recordId];
        return obj.Include_In_Estimate__c;
    }
}