force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Cost_Parameter_Date_FY__c.field-meta.xml
<CustomField>
    <fullName>Cost_Parameter_Date_FY__c</fullName>
    <formula>Text(YEAR(Cost_Parameter_Date__c + 92))</formula>
    <label>Cost Parameter Date FY</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <defaultValue>false</defaultValue>
    <description>High</description>
    <label>High</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Location_Multiplier_Washington_D_C_1_0__c.field-meta.xml
<CustomField>
    <fullName>Location_Multiplier_Washington_D_C_1_0__c</fullName>
    <label>Location Multiplier(Washington D.C =1.0)</label>
    <summarizedField>NCMT_EstimateAdjustment__c.LocationMultiplierDef__c</summarizedField>
    <summaryForeignKey>NCMT_EstimateAdjustment__c.NCMTProject__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/NCMT_Project_Cost_Summary__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>Project Cost Summary</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Cost Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Cost Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/fields/Cost_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category_Description__c</fullName>
    <formula>Cost_Category_ID__r.Category_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Category Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project_Cost_Summary__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>Project Cost Summary</relationshipLabel>
    <relationshipName>Project_Cost_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_Phasing__c/NCMT_RA_Phasing__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT_RA_Phasing</description>
    <label>Project Phasing</label>
    <nameField>
        <label>Phase Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phasing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_RA_Phasing__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project Name</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>RA_Phasing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/NCMT_RA_WI_Lookup_Details__c.object-meta.xml
<CustomObject>
    <description>RA WI Lookup Details</description>
    <label>RA WI Lookup Detail</label>
    <nameField>
        <label>RA WI Lookup Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RA WI Lookup Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/codename__c.field-meta.xml
<CustomField>
    <fullName>codename__c</fullName>
    <formula>WI_Category_Code__c + &apos; - &apos;+   WI_Category_Sub_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <referenceTo>NCMT_Cost_Category__c</referenceTo>
    <relationshipLabel>RA WI Lookup Details</relationshipLabel>
    <relationshipName>RA_WI_Lookup_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <formula>Cost_Category__r.Category_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <defaultValue>0</defaultValue>
    <label>High</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Low__c.field-meta.xml
<CustomField>
    <fullName>Low__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Low</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Quantity_SF__c.field-meta.xml
<CustomField>
    <fullName>Quantity_SF__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity SF</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SF</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>LF</fullName>
            </value>
            <value>
                <fullName>GSF</fullName>
            </value>
            <value>
                <fullName>LFR</fullName>
            </value>
            <value>
                <fullName>DR</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>RF</fullName>
            </value>
            <value>
                <fullName>Acreft</fullName>
            </value>
            <value>
                <fullName>Gallon</fullName>
            </value>
            <value>
                <fullName>kVA</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>gal</fullName>
            </value>
            <value>
                <fullName>kW</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>CFM</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/WI_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>WI_Category_Description__c</fullName>
    <label>WI Category Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/WI_Category_Sub_Description__c.field-meta.xml
<CustomField>
    <fullName>WI_Category_Sub_Description__c</fullName>
    <label>WI Category Sub Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/WI_Category_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>WI_Category_Sub_Type__c</fullName>
    <label>WI Category Sub Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Work_Item_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Item_Category_Type__c</fullName>
    <label>Work Item Category Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_RA_WI_Lookup_Details__c/fields/Work_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Item_Type__c</fullName>
    <label>Work Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NCMT_RAWI_TreeViewCtrl_LC.cls
public with sharing class NCMT_RAWI_TreeViewCtrl_LC {

    public class raWIitems{
        @AuraEnabled public NCMT_Project_Cost_Summary__c pcs {get; set;}
        @AuraEnabled public map<string, map<string, list<NCMT_RA_WI_Lookup_Details__c>>> items {get; set;}
        @AuraEnabled public Map<string, string> phases {get; set;}


    }
    @AuraEnabled
    public static raWIitems init(string pcsId){
        raWIitems wrapper = new raWIitems();
        wrapper.pcs = getPCS(pcsId);
        string projectId =  wrapper.pcs.project_name__c;
        string pcsType = wrapper.pcs.Cost_Category_Description__c;
        string projFiscalYear = wrapper.pcs.project_name__r.Cost_Parameter_Date_FY__c;
        wrapper.items = populateItemCategories(pcsType, projFiscalYear);
        wrapper.phases = getPhaseOptions(projectId);

        return wrapper;
    }

    public static NCMT_Project_Cost_Summary__c getPCS(string pcsId){
        NCMT_Project_Cost_Summary__c pcs = [SELECT Cost_Category_Description__c,  Project_name__c, project_name__r.name, project_name__r.Cost_Parameter_Date_FY__c, 
                                            project_name__r.Location_Multiplier_Washington_D_C_1_0__c, Name 
                                            FROM NCMT_Project_Cost_Summary__c
                                            WHERE id = :pcsId];
        return pcs;
    }

    public static map<string, map<string, list<NCMT_RA_WI_Lookup_Details__c>>> populateItemCategories(string pcsType, string projFiscalYear){
        		system.debug('pcsTypein ctrl' + pcsType);
        		system.debug('projFiscalYear ctrl' + projFiscalYear);


        
        list<NCMT_RA_WI_Lookup_Details__c> raWis = [SELECT id, name, codename__c, Cost_Category__c, Cost_Type__c, Fiscal_Year__c,  High__c, 
                                                    Low__c, Quantity_SF__c, Rate__c,UOM__c,  WI_Category_Description__c, WI_CATEGORY_Sub_Description__c,
                                                    WI_Category_Sub_Type__c, Work_Item_Category_Type__c, Work_Item_Type__c
                                                    FROM NCMT_RA_WI_Lookup_Details__c
                                                    WHERE Cost_Type__c = :pcsType 
                                                    AND  Fiscal_Year__c =: projFiscalYear  
                                                    AND WI_Category_Description__c != 'Other'
                                                    ORDER BY Work_Item_Category_Type__c, WI_Category_Sub_Type__c,WI_Category_Description__c];
        //create map for ra lookup tree containing items 
        Map<string, map<string, list<NCMT_RA_WI_Lookup_Details__c>>> raWiMap = new Map<string, map<string, list<NCMT_RA_WI_Lookup_Details__c>>>();
		system.debug('rawis in ctrl' + raWis);
        for(NCMT_RA_WI_Lookup_Details__c wi:raWis){
            //if cat type, and sub type map levels populated, add to item list
            if(raWiMap.containsKey(wi.Work_Item_Category_Type__c) && raWiMap.get(wi.Work_Item_Category_Type__c).containsKey(wi.codename__c)){
                raWiMap.get(wi.Work_Item_Category_Type__c).get(wi.codename__c).add(wi);
            }else{
                List<NCMT_RA_WI_Lookup_Details__c> newItems = new List<NCMT_RA_WI_Lookup_Details__c>();
                newItems.add(wi);
                map<string,List<NCMT_RA_WI_Lookup_Details__c>> subTypeMap = new map<string, List<NCMT_RA_WI_Lookup_Details__c>>();
                subTypeMap.put(wi.codename__c, newItems);
                //if cat type not populated, add to cat type map
                if(!raWiMap.containsKey(wi.Work_Item_Category_Type__c)){
                    raWiMap.put(wi.Work_Item_Category_Type__c, subTypeMap);
                //if sub type map not populated, add to sub type map
                }else if(!raWiMap.get(wi.Work_Item_Category_Type__c).containsKey(wi.codename__c)){
                    raWiMap.get(wi.Work_Item_Category_Type__c).putAll(subTypeMap);
                }
            }
        }
        
         return raWiMap;

    }
    public static Map<string, string> getPhaseOptions( string projectId) {
        map<string, string> phaseOptions = new map<string, string>();
        for(NCMT_RA_Phasing__c phase:  [select id, name from NCMT_RA_Phasing__c where Project__c = :projectId]){
            phaseOptions.put(phase.id, phase.name);
        }
        return phaseOptions;
    }
    

}