force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Cost_Parameter_Date_FY__c.field-meta.xml
<CustomField>
    <fullName>Cost_Parameter_Date_FY__c</fullName>
    <formula>Text(YEAR(Cost_Parameter_Date__c + 92))</formula>
    <label>Cost Parameter Date FY</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/NCMT_Tree_structure__c.object-meta.xml
<CustomObject>
    <label>NCMT Tree structure</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Tree Structure ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Tree structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Estimate_Format__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Format__c</fullName>
    <label>Estimate Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uniformat</fullName>
            </value>
            <value>
                <fullName>IRIS Format</fullName>
            </value>
            <value>
                <fullName>Master Format</fullName>
                <default>true</default>
                <label>Master Format</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Tree_structure__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Tree_structures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NCMT_TreeStructure_CostSelection.cls
public with sharing class NCMT_TreeStructure_CostSelection {

    public String fiscalYear {get;set;}
    public NCMT_TreeStructure_CostSelection(ApexPages.StandardController stdController) {

        NCMT_Tree_structure__c treeStruc = (NCMT_Tree_structure__c)stdController.getRecord();
		System.debug('treeStruc.Id: '+treeStruc.Id);
        if (treeStruc != null && treeStruc.id != null){
            treeStruc = [select Estimate_Format__c, Project_ID__c, Project_ID__r.name, 
                                                        Project_ID__r.Cost_Parameter_Date_FY__c, Name 
                                                from NCMT_Tree_structure__c where id = :treeStruc.Id];
            fiscalYear = treeStruc.Project_ID__r.Cost_Parameter_Date_FY__c;

        } else {
            fiscalYear = '' +System.today().year();
        }
    }

    @AuraEnabled
    public static NCMT_TreeNode treeMe(Integer level, String parentKey, String fiscalYear, String searchVal, String fileType){
        System.debug(level +' ' +parentKey +' ' +fiscalYear +' ' +searchVal +' ' +true);
		parentKey=string.isNotBlank(parentKey) ? string.escapeSingleQuotes(parentKey):'';
        fiscalYear=string.isNotBlank(fiscalYear) ? string.escapeSingleQuotes(fiscalYear):'';
        searchVal=string.isNotBlank(searchVal) ? string.escapeSingleQuotes(searchVal):'';
        fileType=string.isNotBlank(fileType) ? string.escapeSingleQuotes(fileType):'';
        NCMT_TreeNode n = new NCMT_TreeNode(level, 'toplevel', parentKey, fiscalYear, fileType, searchVal, true);
        
        return n;
    }

}