force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Markup_Method__c.field-meta.xml
<CustomField>
    <fullName>Markup_Method__c</fullName>
    <label>Markup Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Delivery_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSA Markups</fullName>
                <default>true</default>
                <label>GSA Markups</label>
            </value>
            <value>
                <fullName>RSMeans - O&amp;P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project_Markup__c/NCMT_Project_Markup__c.object-meta.xml
<CustomObject>
    <label>NCMT Project Markup</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Project Markup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Project Markups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project_Markup__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Project Markups</relationshipLabel>
    <relationshipName>NCMT_Project_Markups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NCMT_MarkupsCtrl_LC.cls
public with sharing class NCMT_MarkupsCtrl_LC {

    @AuraEnabled public NCMT_Project_Markup__c projmp {get;set;}
    public NCMT_MarkupsCtrl_LC(ApexPages.StandardController controller) {
        projmp = (NCMT_Project_Markup__c)controller.getRecord(); 
    }
    public class projectWrapper{     
        @AuraEnabled public NCMT_Project_Markup__c project {get; set;}
    } 
    @AuraEnabled
    public static projectWrapper init(string recordId){
        projectWrapper wrapper = new projectWrapper();
        wrapper.project = getProjectMPData(recordId);  
        return wrapper;
    }
    @AuraEnabled
    public static NCMT_Project_Markup__c getProjectMPData(string projectId){
        NCMT_Project_Markup__c projectMPData = [SELECT id, Name, Project_Name__r.Markup_Method__c FROM NCMT_Project_Markup__c WHERE id= :projectId];
        return projectMPData;
    }
    /*public static Boolean islevelThree() {
        AggregateResult[] listCount = [select count(Id) usrs FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId() AND PermissionSet.Name ='NCMT-Users-LVL3-CRE'];
        Integer count = (integer) listCount [0].get('usrs');
        
        boolean islevelThree = (count > 0);
        return islevelThree;
        
    }*/
}