force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Estimate_Type_Proj__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Type_Proj__c</fullName>
    <inlineHelpText>Parametric: Planning or early design. 
Definitive: Later design phase/construction phase estimate.
Parametric R&amp;A: whole building renovation. 
Work Item R&amp;A: Budget estimates based on individual line item repairs.</inlineHelpText>
    <label>Estimate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parametric</fullName>
            </value>
            <value>
                <fullName>Definitive Estimating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Total_Project_Cost_Aggregate__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Cost_Aggregate__c</fullName>
    <formula>IF(RecordType.Name == &apos;New Construction - CEW&apos;|| RecordType.Name == &apos;Repair &amp; Alteration - CEW&apos;, 
CEW_Total_Cost_W_O_Markup__c,

IF(RecordType.Name == &apos;Repair &amp; Alteration - Parametric Entry&apos; || RecordType.Name == &apos;Repair &amp; Alteration - Work Item Detail&apos;, RA_Total_Project_Costs__c ,

IF(RecordType.Name == &apos;LPOE&apos;, LPOE_Total_Proj_Cost__c,
IF(RecordType.Name == &apos;Repair &amp; Alteration - DES&apos; || RecordType.Name ==  &apos;New Construction - DES&apos; || RecordType.Name == &apos;New Construction DES O&amp;P&apos;, DES_Total_Direct_Cost__c,
 
ETPC_Cost__c))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total ETPC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NCMT_DESReportDataBatch.cls
global with sharing class NCMT_DESReportDataBatch implements Database.Batchable<sObject>,Schedulable{
    global Database.QueryLocator start(Database.BatchableContext BC) {         
        String query = 'SELECT Id, Name FROM NCMT_Project__c Where Estimate_Type_Proj__c = \'Definitive Estimating\' And Total_Project_Cost_Aggregate__c > 0';
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<NCMT_Project__c> projects) {
        List<Id> projectIds = new List<Id>();
        // process each batch of records default size is 200
        for(NCMT_Project__c prj : projects) {        
            projectIds.add(prj.Id);
        }
        //system.debug(':::projectIds111:::'+projectIds);
        try {
            NCMT_DESReportDataBatchUtility.copyReportDataToObject(projectIds);
         
        } catch(Exception e) {
            System.debug(e);
            //System.debug(e.getStackTraceString());
            //System.debug(e.getMessage());
        }
         
    }   
     
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }
     global void execute(SchedulableContext sc) {
      NCMT_DESReportDataBatch b = new NCMT_DESReportDataBatch(); 
      Database.executeBatch(b,1);
   }
}