force-app/main/default/objects/NCMT_Housing_Plan__c/NCMT_Housing_Plan__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Housing Plan</description>
    <label>NCMT Housing Plan</label>
    <nameField>
        <displayFormat>HP-{0000000000}</displayFormat>
        <label>NCMT Housing Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Housing_Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Housing_Plan_Name__c</fullName>
    <label>Housing Plan Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Child to Project</description>
    <label>Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plans</relationshipLabel>
    <relationshipName>NCMT_Housing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/NCMT_Housing_Plan_Option__c.object-meta.xml
<CustomObject>
    <label>NCMT Housing Plan Option</label>
    <nameField>
        <displayFormat>Option-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/Choice_Text__c.field-meta.xml
<CustomField>
    <fullName>Choice_Text__c</fullName>
    <inlineHelpText>Displayed to the user, brief description of the cost option.</inlineHelpText>
    <label>Choice Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/NCMT_Housing_Plan_Option_Template__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option_Template__c</fullName>
    <label>NCMT Housing Plan Option Template</label>
    <referenceTo>NCMT_Housing_Plan_Option_Template__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Options</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/Recurs_on_TCO_Tenant_Renewal_Years__c.field-meta.xml
<CustomField>
    <fullName>Recurs_on_TCO_Tenant_Renewal_Years__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This cost will be added on the Retrofit years specified in the project&apos;s TCO Lifecycle Input in addition to the years specified in Replace Every X Years.</inlineHelpText>
    <label>Recurs on TCO Tenant Renewal Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>Sets the order the options will be displayed to users within a particular Template Record Type and Type.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/TCO_Default_Repair_Cost_Percentage__c.field-meta.xml
<CustomField>
    <fullName>TCO_Default_Repair_Cost_Percentage__c</fullName>
    <label>TCO Default Repair Cost (Percentage)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/TCO_Default_Repair_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Default_Repair_Every_X_Years__c</fullName>
    <defaultValue>1</defaultValue>
    <label>TCO Default Repair Every X Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option__c/fields/TCO_Default_Replacement_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Default_Replacement_Every_X_Years__c</fullName>
    <defaultValue>1</defaultValue>
    <label>TCO Default Replacement Every X Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/NCMT_Housing_Plan_Option_Selection__c.object-meta.xml
<CustomObject>
    <description>Created when a Housing Plan Selection Option is selected on the Housing Plan selection page. Deleted if unselected.</description>
    <label>NCMT Housing Plan - Option Selection</label>
    <nameField>
        <displayFormat>Select-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Option Selection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>NCMT Housing Plan</label>
    <referenceTo>NCMT_Housing_Plan__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Housing_Plan_Option__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan Option</label>
    <referenceTo>NCMT_Housing_Plan_Option__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Increase this value if this item cost should be added multiple times, for example if tenants are moving to a temporary space and then the final space.</inlineHelpText>
    <label>Recurrence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/Recurs_on_TCO_Tenant_Refresh_Years__c.field-meta.xml
<CustomField>
    <fullName>Recurs_on_TCO_Tenant_Refresh_Years__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurs on TCO Tenant Refresh Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/TCO_Repair_Cost_Percentage__c.field-meta.xml
<CustomField>
    <fullName>TCO_Repair_Cost_Percentage__c</fullName>
    <label>TCO Repair Cost (Percentage)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/TCO_Repair_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Repair_Every_X_Years__c</fullName>
    <label>TCO Repair Every X Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/TCO_Replacement_Every_X_Years__c.field-meta.xml
<CustomField>
    <fullName>TCO_Replacement_Every_X_Years__c</fullName>
    <label>TCO Replacement Every X Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/NCMT_Housing_Plan_Option_Template__c.object-meta.xml
<CustomObject>
    <description>The NCMT Housing Plan Option Choices related to a template are displayed on the NCMT Housing Plan Option Selection page, filtered by the Record Type.</description>
    <label>NCMT Housing Plan Option Template</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>NCMT Housing Plan Option Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Option Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>Sets the order of the Type when all related Options are displayed (options are grouped by Type).</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Housing_Plan_Cost_Sub_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Housing_Plan_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/NCMT_Other_Cost__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>NCMT Other Cost</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Other Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Other Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Housing_Plan_Option_Selection__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan_Option_Selection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCMT Housing Plan - Option Selection</label>
    <referenceTo>NCMT_Housing_Plan_Option_Selection__c</referenceTo>
    <relationshipLabel>NCMT Other Costs</relationshipLabel>
    <relationshipName>NCMT_Other_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Other_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Housing_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Housing Plan</description>
    <inlineHelpText>Applied when user can determine logical breakdown of functional space-types and the required area of each. See Housing Plan Analysis Help Sheet</inlineHelpText>
    <label>Housing Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/recordTypes/New_Construction_TCO.recordType-meta.xml
<RecordType>
    <fullName>New_Construction_TCO</fullName>
    <active>true</active>
    <description>New Construction - TCO</description>
    <label>New Construction - TCO</label>
</RecordType>

force-app/main/default/globalValueSets/Housing_Plan_Cost_Sub_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Move Out</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Move In</fullName>
    </customValue>
    <masterLabel>Housing Plan Cost Sub-Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Housing_Plan_Cost_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Moving Costs</fullName>
    </customValue>
    <masterLabel>Housing Plan Cost Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NCMT_HousingPlan_OptionSelection.cls
public with sharing class NCMT_HousingPlan_OptionSelection {
    
    public NCMT_HousingPlan_OptionSelection(ApexPages.StandardController stdController) {
        
    }

    /*@AuraEnabled
    public static List<NCMT_HousePlan_TypeOptions> retrieveHousingPlans(String projId){
        return [Select Id, Housing_Plan_Name__c from NCMT_Housing_Plan__c where Project__c =: projId Order by Housing_Plan_Name__c];
    }*/


    @AuraEnabled
    public static List<NCMT_HousePlan_TypeOptions> retrieveOptions(String recordType, String templateType, String projId){
        templateType = String.escapeSingleQuotes(templateType);
        recordType = String.escapeSingleQuotes(recordType);
        projId = String.escapeSingleQuotes(projId);
        System.debug('retrieveOptions- recordType = ' +recordType +' projId = ' +projId);
        Map<String, Map<Integer, Map<Id, NCMT_Housing_Plan_Option_Selection__c>>> planSelections = new Map<String, Map<Integer, Map<Id, NCMT_Housing_Plan_Option_Selection__c>>>();
        Map<String, Id> planIds = new Map<String, Id>();
        
        NCMT_Project__c proj = [Select Id, Name, Housing_Plan__c from NCMT_Project__c where Id =: projId][0];
        Boolean isHPProj = proj.Housing_Plan__c;
        Boolean isTCO = false;
        Id tcoRecordTypeId = NCMT_Utilities.getProjectRecordTypeId('New_Construction_TCO');
        if (isHPProj){
            for (NCMT_Housing_Plan__c hp : [Select Id, Name, Housing_Plan_Name__c, Project__r.RecordTypeId from NCMT_Housing_Plan__c 
                where Project__c =: projId Order by Housing_Plan_Name__c]
            ){
                String n = (hp.Housing_Plan_Name__c == null ? hp.Name : hp.Housing_Plan_Name__c);
                planSelections.put(n, new Map<Integer, Map<Id, NCMT_Housing_Plan_Option_Selection__c>>());
                planIds.put(n, hp.Id);
                if (hp.Project__r.RecordTypeId == tcoRecordTypeID) isTCO = true;
            }
        } else {
            for (NCMT_Project__c p : [Select Id, RecordTypeId from NCMT_Project__c where Id =: projId]){
                if (p.RecordTypeId == tcoRecordTypeID) isTCO = true;
            }
            planSelections.put(proj.Name, new Map<Integer, Map<Id, NCMT_Housing_Plan_Option_Selection__c>>());
        }

        //Rarely used but accounts for scenarios where move options are selected on a project and then it's updated to or from a Housing Plan project
        List<NCMT_Housing_Plan_Option_Selection__c> delSelections = new List<NCMT_Housing_Plan_Option_Selection__c>();

        for (NCMT_Housing_Plan_Option_Selection__c s : [Select Id, NCMT_Housing_Plan_Option__c, NCMT_Project__r.Name, 
            NCMT_Housing_Plan__c, NCMT_Housing_Plan__r.Name, NCMT_Housing_Plan__r.Housing_Plan_Name__c, Recurs_on_TCO_Tenant_Refresh_Years__c, 
            TCO_Repair_Cost_Percentage__c, TCO_Repair_Every_X_Years__c, TCO_Replacement_Every_X_Years__c, Recurrence__c
            from NCMT_Housing_Plan_Option_Selection__c 
                where NCMT_Project__c =: projId 
                Order by NCMT_Housing_Plan__r.Housing_Plan_Name__c, Recurrence__c]
        ){
            if ((isHPProj &&s.NCMT_Housing_Plan__c == null)){
                delSelections.add(s);
            } else {
                String groupName = (isHPProj ? (s.NCMT_Housing_Plan__r.Housing_Plan_Name__c == null ? s.NCMT_Housing_Plan__r.Name : s.NCMT_Housing_Plan__r.Housing_Plan_Name__c) : s.NCMT_Project__r.Name);
                if (s.Recurrence__c == null) s.Recurrence__c = 1;
                if (planSelections.get(groupName) == null)
                    planSelections.put(groupName, new Map<Integer, Map<Id, NCMT_Housing_Plan_Option_Selection__c>>());
                if (planSelections.get(groupName).get(Integer.valueOf(s.Recurrence__c)) == null)
                    planSelections.get(groupName).put(Integer.valueOf(s.Recurrence__c), new Map<Id, NCMT_Housing_Plan_Option_Selection__c>());

                //Clean-up for HP Projects that are switched to Gross Area to remove duplicates, generally won't come up
                if (planSelections.get(groupName).get(Integer.valueOf(s.Recurrence__c)).get(s.NCMT_Housing_Plan_Option__c) != null){
                    delSelections.add(s);
                } else {
                    planSelections.get(groupName).get(Integer.valueOf(s.Recurrence__c)).put(s.NCMT_Housing_Plan_Option__c, s);
                }
            }
        }
        if (delSelections.size() > 0){
            delete delSelections;
        }
        
        List<NCMT_Housing_Plan_Option__c> allOptions = [Select Id, Choice_Text__c, Description__c,
                TCO_Default_Repair_Cost_Percentage__c,
                TCO_Default_Repair_Every_X_Years__c, Recurs_on_TCO_Tenant_Renewal_Years__c,
                TCO_Default_Replacement_Every_X_Years__c,
                NCMT_Housing_Plan_Option_Template__r.RecordType.Name,
                NCMT_Housing_Plan_Option_Template__r.Type__c,
                NCMT_Housing_Plan_Option_Template__r.Sub_Type__c
            from NCMT_Housing_Plan_Option__c
            where NCMT_Housing_Plan_Option_Template__r.RecordType.DeveloperName =: recordType
                AND NCMT_Housing_Plan_Option_Template__r.Type__c =: templateType
            Order by NCMT_Housing_Plan_Option_Template__r.Sort_Order__c, Sort_Order__c];

        Map<String, Map<Integer, Map<String, List<NCMT_HousePlan_TypeOptions.HousingPlan_Option>>>> housingPlanOpts = new Map<String, Map<Integer, Map<String, List<NCMT_HousePlan_TypeOptions.HousingPlan_Option>>>>();
        for (String groupName : planSelections.keySet()){
            for (NCMT_Housing_Plan_Option__c opt : allOptions
            ){
                
                if (housingPlanOpts.get(groupName) == null)
                    housingPlanOpts.put(groupName, new Map<Integer, Map<String, List<NCMT_HousePlan_TypeOptions.HousingPlan_Option>>>());
                
                Set<Integer> recurrences = new Set<Integer>();
                recurrences.addAll(planSelections.get(groupName).keySet());
                if (recurrences.size() == 0) recurrences.add(1);

                for (Integer r : recurrences){
                    NCMT_HousePlan_TypeOptions.HousingPlan_Option houseOpt = new NCMT_HousePlan_TypeOptions.HousingPlan_Option(opt);
                    
                    if (planSelections.get(groupName) != null &&planSelections.get(groupName).get(r) != null)
                        houseOpt.optSelect = planSelections.get(groupName).get(r).get(opt.Id);
                    if (houseOpt.optSelect != null){
                        houseOpt.selected = true;
                    } else {
                        houseOpt.optSelect = new NCMT_Housing_Plan_Option_Selection__c(
                            NCMT_Housing_Plan__c = planIds.get(groupName),
                            NCMT_Housing_Plan_Option__c = opt.Id,
                            NCMT_Project__c = projId,
                            Recurrence__c = r,
                            TCO_Repair_Cost_Percentage__c = opt.TCO_Default_Repair_Cost_Percentage__c,
                            TCO_Repair_Every_X_Years__c = opt.TCO_Default_Repair_Every_X_Years__c,
                            TCO_Replacement_Every_X_Years__c = opt.TCO_Default_Replacement_Every_X_Years__c
                        );
                    }
                    if (housingPlanOpts.get(groupName).get(r) == null)
                        housingPlanOpts.get(groupName).put(r, new Map<String, List<NCMT_HousePlan_TypeOptions.HousingPlan_Option>>());

                    if (housingPlanOpts.get(groupName).get(r).get(opt.NCMT_Housing_Plan_Option_Template__r.Sub_Type__c) == null)
                        housingPlanOpts.get(groupName).get(r).put(opt.NCMT_Housing_Plan_Option_Template__r.Sub_Type__c, new List<NCMT_HousePlan_TypeOptions.HousingPlan_Option>());

                    housingPlanOpts.get(groupName).get(r).get(opt.NCMT_Housing_Plan_Option_Template__r.Sub_Type__c).add(houseOpt);
                }
            }
        }
        System.debug('planSelections...... ' +planSelections);
        System.debug('housingPlanOpts...... ' +housingPlanOpts);
        List<NCMT_HousePlan_TypeOptions> opts = new List<NCMT_HousePlan_TypeOptions>();
        
        for (String groupName : housingPlanOpts.keySet()){
            NCMT_HousePlan_TypeOptions hp = new NCMT_HousePlan_TypeOptions(groupName);
            hp.isTCO = isTCO;
            for (Integer r : housingPlanOpts.get(groupName).keySet()){
                List<NCMT_HousePlan_TypeOptions.HousingPlan_SubType> subs = new List<NCMT_HousePlan_TypeOptions.HousingPlan_SubType>();
                for (String subType : housingPlanOpts.get(groupName).get(r).keySet()){
                    NCMT_HousePlan_TypeOptions.HousingPlan_SubType sub = new NCMT_HousePlan_TypeOptions.HousingPlan_SubType(subType, housingPlanOpts.get(groupName).get(r).get(subType));
                    subs.add(sub);
                }
                NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence rec = new NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence(r, subs);
                hp.recurrences.add(rec);
            }
            opts.add(hp);
        }

        return opts;
    }


    @AuraEnabled
    public static String saveHousingPlanOpts(List<NCMT_HousePlan_TypeOptions> opts){

        List<NCMT_Housing_Plan_Option_Selection__c> upsertOpts = new List<NCMT_Housing_Plan_Option_Selection__c>();
        List<NCMT_Housing_Plan_Option_Selection__c> deleteOpts = new List<NCMT_Housing_Plan_Option_Selection__c>();
        Set<Id> delIds = new Set<Id>();
        for (NCMT_HousePlan_TypeOptions hpOpt : opts){
            for (NCMT_HousePlan_TypeOptions.HousingPlan_Recurrence rec : hpOpt.recurrences){
                for (NCMT_HousePlan_TypeOptions.HousingPlan_SubType subtype : rec.subTypes){
                    
                    for (NCMT_HousePlan_TypeOptions.HousingPlan_Option houseOpt : subtype.options){
                        if (houseOpt.selected){
                            houseOpt.optSelect.Recurrence__c = rec.num;
                            upsertOpts.add(houseOpt.optSelect);
                            System.debug('save it-------- ' +houseOpt.optSelect);
                        } else if (!houseOpt.selected &&houseOpt.optSelect.Id != null){
                            deleteOpts.add(houseOpt.optSelect);
                            delIds.add(houseOpt.optSelect.Id);
                            System.debug('delete it-------- ' +houseOpt.optSelect);
                        }
                    }
                }
            }
        }
        try{
            if (delIds.size() > 0){
                List<NCMT_Other_Cost__c> otherCosts = [Select Id from NCMT_Other_Cost__c where NCMT_Housing_Plan_Option_Selection__c IN: delIds];
                delete otherCosts;                           
                NCMT_HousingPlan_OptSelection_Handler.skipGenerateProject = (deleteOpts.size() > 0);
                delete deleteOpts;
            }
            NCMT_HousingPlan_OptSelection_Handler.skipGenerateProject = false;
            upsert upsertOpts;
        } catch (DMLException e){
            String err = 'Error(s): ';
            for (Integer i = 0; i < e.getNumDml(); i++) {
                err += '\n' +e.getDmlMessage(i);
            }
            return err;
        }


        return null;
    } 

}