force-app/main/default/objects/PBS_AAAP_Agency_Requirement__c/PBS_AAAP_Agency_Requirement__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object store all information related to an Agency requirement in AAAP</description>
    <label>Agency Requirement</label>
    <nameField>
        <label>Agency Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_isSelected__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_isSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field sets to true, If a AAAP Manager selects this offer against an Agency Requirement.</description>
    <label>isSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer</relationshipLabel>
    <relationshipName>Offer_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Awarded/Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Modification</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Awarded/Pending Review</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Awarded/Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/PBS_AAAP_Offer_Deselect_Reject_Reasons__c.object-meta.xml
<CustomObject>
    <label>Offer Deselect Reject Reasons</label>
    <nameField>
        <label>Offer Deselect Reject Reasons Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Deselect Reject Reasons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Action_Comments__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Action_Comments__c</fullName>
    <label>Action Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Action_Reason__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Action_Reason__c</fullName>
    <label>Action Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Requirement Changes</fullName>
            </value>
            <value>
                <fullName>Agency Requirement Canceled</fullName>
            </value>
            <value>
                <fullName>Offer Has Changed</fullName>
            </value>
            <value>
                <fullName>Building Problems Found</fullName>
            </value>
            <value>
                <fullName>Offeror Found to be Debarred</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Agency_Requirement__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Agency_Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Requirement</label>
    <referenceTo>PBS_AAAP_Agency_Requirement__c</referenceTo>
    <relationshipLabel>Offer Deselect Reject Reasons</relationshipLabel>
    <relationshipName>Offer_Deselect_Reject_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Offer_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer Deselect Reject Reasons</relationshipLabel>
    <relationshipName>Offer_Deselect_Reject_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/PBS_AAAP_Offer_Select_Award_Info__c.object-meta.xml
<CustomObject>
    <description>This is the Offer_Select_Award_Info table in the source AAAP system.</description>
    <label>Offer Select Award Info</label>
    <nameField>
        <displayFormat>OSAI-{00000000}</displayFormat>
        <label>Offer Select Award Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Select Award Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_AGENCY_REQUIREMENT_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_AGENCY_REQUIREMENT_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Requirement ID</label>
    <referenceTo>PBS_AAAP_Agency_Requirement__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_isSelected__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_isSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <label>Offer Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_SELECTED_USF__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SELECTED_USF__c</fullName>
    <label>Selected USF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_Space_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Space_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Space</label>
    <referenceTo>PBS_AAAP_Space__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Rate__c/PBS_AAAP_Rate__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object contains Rate information associated with a specific space in a AAAP Offer. These rates will be visible to all end-users.</description>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Rate__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The offer number to which this rate record is associated.</description>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Rate__c/fields/PBS_AAAP_SPACE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_SPACE__c</fullName>
    <label>Space</label>
    <referenceTo>PBS_AAAP_Space__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Space__c/PBS_AAAP_Space__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores information on the spaces related to a AAAP Offer</description>
    <label>Space</label>
    <nameField>
        <displayFormat>Space-{000000000}</displayFormat>
        <label>Space Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Space__c/fields/PBS_AAAP_isSelected__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_isSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Space__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <description>The offer number with which the space will be associated.</description>
    <inlineHelpText>Offer Number</inlineHelpText>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Spaces</relationshipLabel>
    <relationshipName>Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Space__c/fields/PBS_AAAP_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Status__c</fullName>
    <formula>Text(PBS_AAAP_OFFER_NUMBER__r.PBS_AAAP_Offer_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offer Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Space__c/fields/PBS_AAAP_Total_ABOA_Selected__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_ABOA_Selected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total ABOA SF Selected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_PBS_AAAP_SelectedOfferSpace_Contr.cls
@IsTest
private class Test_PBS_AAAP_SelectedOfferSpace_Contr {

    static testMethod void myUnitTest() {
        PageReference pageRef = Page.PBS_AAAP_SelectedOfferSpace;
        Test.setCurrentPage(pageRef);


        PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
        offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_AWARDED_SELECTED;
        insert offer;

        PBS_AAAP_Space__c space = PBS_AAAP_UtilityTest.createSpace();
        space.PBS_AAAP_OFFER_NUMBER__c = offer.Id;
        insert space;
        PBS_AAAP_Agency_Requirement__c agency = PBS_AAAP_UtilityTest.createAgencyRequirement();
        insert agency;

        PBS_AAAP_Rate__c rate = PBS_AAAP_UtilityTest.createRate();
        PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        osai.PBS_AAAP_isSelected__c = true;
        osai.PBS_AAAP_SELECTED_USF__c = 300000.00;
        osai.PBS_AAAP_AGENCY_REQUIREMENT_ID__c = agency.Id;
        insert osai;

        ApexPages.currentPage().getParameters().put('selectedOfferId', offer.Id);
        ApexPages.currentPage().getParameters().put('selectedSpaceId', space.Id);
        ApexPages.currentPage().getParameters().put('agencyRequirementId', agency.Id);
        PBS_AAAP_OfferDeselectReasonContr odrc = new PBS_AAAP_OfferDeselectReasonContr();

        PageReference pref = odrc.actionSaveDeselectReason();
        PBS_AAAP_Offer_Deselect_Reject_Reasons__c odrr = new PBS_AAAP_Offer_Deselect_Reject_Reasons__c();

        odrr.PBS_AAAP_Action_Reason__c = 'Other';
        odrr.PBS_AAAP_Action_Comments__c = null;
        odrc.offerDeselect = odrr;
        pref = odrc.actionSaveDeselectReason();

        odrr.PBS_AAAP_Action_Reason__c = 'Other';
        odrr.PBS_AAAP_Action_Comments__c = 'Other';
        odrc.offerDeselect = odrr;
        pref = odrc.actionSaveDeselectReason();

        pref = odrc.actionCancelDeselect();
        System.assertNotEquals(pref, null);

    }

    static testMethod void myUnitTestOfferAwardedSelected() {
        PageReference pageRef = Page.PBS_AAAP_AgencyRequirementEdit;
        Test.setCurrentPage(pageRef);

        PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
        offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_AWARDED_SELECTED;
        insert offer;
        PBS_AAAP_Space__c space = PBS_AAAP_UtilityTest.createSpace();
        space.PBS_AAAP_OFFER_NUMBER__c = offer.Id;
        insert space;
        PBS_AAAP_Rate__c rate = PBS_AAAP_UtilityTest.createRate();
        // rate.

        PBS_AAAP_Agency_Requirement__c agency = PBS_AAAP_UtilityTest.createAgencyRequirement();
        insert agency;

        ApexPages.currentPage().getParameters().put('selectedOfferId', offer.Id);
        ApexPages.currentPage().getParameters().put('selectedSpaceId', space.Id);
        ApexPages.currentPage().getParameters().put('agencyRequirementId', agency.Id);
        PBS_AAAP_OfferDeselectReasonContr odrc = new PBS_AAAP_OfferDeselectReasonContr();

        PageReference pref = odrc.actionSaveDeselectReason();
        PBS_AAAP_Offer_Deselect_Reject_Reasons__c odrr = new PBS_AAAP_Offer_Deselect_Reject_Reasons__c();

        odrr.PBS_AAAP_Action_Reason__c = 'Other';
        odrr.PBS_AAAP_Action_Comments__c = 'Other';
        odrc.offerDeselect = odrr;
        pref = odrc.actionSaveDeselectReason();
        System.assertEquals(pref, null);

    }
    static testMethod void myUnitTestOfferSelected() {
        PageReference pageRef = Page.PBS_AAAP_AgencyRequirementEdit;
        Test.setCurrentPage(pageRef);

        PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
        offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SELECTED;
        insert offer;
        PBS_AAAP_Space__c space = PBS_AAAP_UtilityTest.createSpace();
        space.PBS_AAAP_OFFER_NUMBER__c = offer.Id;
        insert space;
        PBS_AAAP_Rate__c rate = PBS_AAAP_UtilityTest.createRate();
        // rate.

        PBS_AAAP_Agency_Requirement__c agency = PBS_AAAP_UtilityTest.createAgencyRequirement();
        insert agency;

        ApexPages.currentPage().getParameters().put('selectedOfferId', offer.Id);
        ApexPages.currentPage().getParameters().put('selectedSpaceId', space.Id);
        ApexPages.currentPage().getParameters().put('agencyRequirementId', agency.Id);
        PBS_AAAP_OfferDeselectReasonContr odrc = new PBS_AAAP_OfferDeselectReasonContr();

        PageReference pref = odrc.actionSaveDeselectReason();
        PBS_AAAP_Offer_Deselect_Reject_Reasons__c odrr = new PBS_AAAP_Offer_Deselect_Reject_Reasons__c();

        odrr.PBS_AAAP_Action_Reason__c = 'Other';
        odrr.PBS_AAAP_Action_Comments__c = 'Other';
        odrc.offerDeselect = odrr;
        pref = odrc.actionSaveDeselectReason();
        System.assertEquals(pref, null);

    }

    static testMethod void myUnitTestSelectedOfferSpace() {
        Test.startTest();
        PageReference pageRef = Page.PBS_AAAP_SelectedOfferSpace;
        Test.setCurrentPage(pageRef);

        //PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
        offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_SUBMITTED;
        insert offer;
        PBS_AAAP_Space__c space = PBS_AAAP_UtilityTest.createSpace();
        space.PBS_AAAP_OFFER_NUMBER__c = offer.Id;
        space.PBS_AAAP_Total_ABOA_Selected__c = null;
        insert space;
        PBS_AAAP_Rate__c rate = PBS_AAAP_UtilityTest.createRate();
        // rate.

        PBS_AAAP_Agency_Requirement__c agency = PBS_AAAP_UtilityTest.createAgencyRequirement();
        insert agency;
        PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        osai.PBS_AAAP_isSelected__c = true;
        osai.PBS_AAAP_SELECTED_USF__c = 30000.00;
        osai.PBS_AAAP_AGENCY_REQUIREMENT_ID__c = agency.Id;
        osai.PBS_AAAP_Space_ID__c = space.Id;
        insert osai;

        ApexPages.currentPage().getParameters().put('selectedOfferSpaceId', osai.Id);
        ApexPages.currentPage().getParameters().put('agencyId', agency.Id);
        PBS_AAAP_SelectedOfferSpace_Contr odrc = new PBS_AAAP_SelectedOfferSpace_Contr();
        odrc.currentObj.PBS_AAAP_SELECTED_USF__c = null;
        PageReference pref = odrc.actionSave();

        odrc.currentObj.PBS_AAAP_SELECTED_USF__c = 30000.00;
        pref = odrc.actionSave();

        System.assertNotEquals(pref, null);

        ApexPages.currentPage().getParameters().put('selectedOfferSpaceId', osai.Id);
        odrc = new PBS_AAAP_SelectedOfferSpace_Contr();
        odrc.actionCancel();

        Test.stopTest();
    }

    static testMethod void myUnitTestSelectedOfferSpace1() {
        Test.startTest();
        PageReference pageRef = Page.PBS_AAAP_SelectedOfferSpace;
        Test.setCurrentPage(pageRef);

        //PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        PBS_AAAP_Offer__c offer = PBS_AAAP_UtilityTest.createOfferInfo();
        offer.PBS_AAAP_Offer_Status__c = PBS_AAAP_GlobalConstants.OFFERSTATUS_AWARDED_SUBMITTED;
        insert offer;
        PBS_AAAP_Space__c space = PBS_AAAP_UtilityTest.createSpace();
        space.PBS_AAAP_OFFER_NUMBER__c = offer.Id;
        space.PBS_AAAP_Total_ABOA_Selected__c = null;
        insert space;
        PBS_AAAP_Rate__c rate = PBS_AAAP_UtilityTest.createRate();
        // rate.

        PBS_AAAP_Agency_Requirement__c agency = PBS_AAAP_UtilityTest.createAgencyRequirement();
        insert agency;
        PBS_AAAP_Offer_Select_Award_Info__c osai = new PBS_AAAP_Offer_Select_Award_Info__c();
        osai.PBS_AAAP_isSelected__c = true;
        osai.PBS_AAAP_SELECTED_USF__c = 30000.00;
        osai.PBS_AAAP_AGENCY_REQUIREMENT_ID__c = agency.Id;
        osai.PBS_AAAP_Space_ID__c = space.Id;
        insert osai;

        ApexPages.currentPage().getParameters().put('selectedOfferSpaceId', osai.Id);
        ApexPages.currentPage().getParameters().put('agencyId', agency.Id);
        PBS_AAAP_SelectedOfferSpace_Contr odrc = new PBS_AAAP_SelectedOfferSpace_Contr();
        odrc.currentObj.PBS_AAAP_SELECTED_USF__c = null;
        PageReference pref = odrc.actionSave();

        odrc.currentObj.PBS_AAAP_SELECTED_USF__c = 30000.00;
        pref = odrc.actionSave();

        System.assertNotEquals(pref, null);

        ApexPages.currentPage().getParameters().put('selectedOfferSpaceId', osai.Id);
        odrc = new PBS_AAAP_SelectedOfferSpace_Contr();
        odrc.actionCancel();

        Test.stopTest();
    }
}