force-app/main/default/objects/PBS_AAAP_Agency_Requirement__c/PBS_AAAP_Agency_Requirement__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object store all information related to an Agency requirement in AAAP</description>
    <label>Agency Requirement</label>
    <nameField>
        <label>Agency Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Agency_Requirement__c/fields/PBS_AAAP_LEASE_TERM__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_LEASE_TERM__c</fullName>
    <label>Lease Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15 years, 13 firm</fullName>
            </value>
            <value>
                <fullName>17 years, 15 firm</fullName>
            </value>
            <value>
                <fullName>25 months, 16 firm</fullName>
            </value>
            <value>
                <fullName>19 months, 11 firm</fullName>
            </value>
            <value>
                <fullName>10 years, 8 firm</fullName>
            </value>
            <value>
                <fullName>10 years,5 firm</fullName>
                <label>10 years, 5 firm</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/Formula_RLP_Region__c.field-meta.xml
<CustomField>
    <fullName>Formula_RLP_Region__c</fullName>
    <formula>Text(PBS_AAAP_RLP_Number__r.PBS_AAAP_Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_City__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_IsAwarded__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_IsAwarded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAwarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Owner_Name__c</fullName>
    <description>What is the name of the property&apos;s recorded owner?</description>
    <label>Property Owner Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_State__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_State__c</fullName>
    <label>Building State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Street_Address__c</fullName>
    <description>Street Address</description>
    <label>Building Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_ZipCode__c</fullName>
    <description>Zip Code</description>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/PBS_AAAP_Offer_Select_Award_Info__c.object-meta.xml
<CustomObject>
    <description>This is the Offer_Select_Award_Info table in the source AAAP system.</description>
    <label>Offer Select Award Info</label>
    <nameField>
        <displayFormat>OSAI-{00000000}</displayFormat>
        <label>Offer Select Award Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Select Award Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_AGENCY_REQUIREMENT_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_AGENCY_REQUIREMENT_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Requirement ID</label>
    <referenceTo>PBS_AAAP_Agency_Requirement__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_AWARDED_USF__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_AWARDED_USF__c</fullName>
    <label>Awarded Usf</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_CONTRACT_AWARD_DATE__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_CONTRACT_AWARD_DATE__c</fullName>
    <label>Contract_Award_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_IsAwarded__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_IsAwarded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAwarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_Lease_Term__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Lease_Term__c</fullName>
    <label>Lease Term</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_NEW_GSA_LEASE_NUM__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_NEW_GSA_LEASE_NUM__c</fullName>
    <label>New GSA Lease Num</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer ID</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer Select Award Info</relationshipLabel>
    <relationshipName>Offer_Select_Award_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Select_Award_Info__c/fields/PBS_AAAP_Total_Contract_Amount__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Total_Contract_Amount__c</fullName>
    <label>Total Contract Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PBS_AAAP_AwardedOffersInfo.cls
//public with sharing class PBS_AAAP_AwardedOffersInfo {//JK removed with sharing on 2.3.21
public class PBS_AAAP_AwardedOffersInfo {

    public List<PBS_AAAP_Offer_Select_Award_Info__c> awardOffers { get; set;}
    
    public PBS_AAAP_AwardedOffersInfo() {
        /**
        awardOffers = [
            SELECT  p.PBS_AAAP_Total_Contract_Amount__c, p.PBS_AAAP_Offer_ID__r.PBS_AAAP_Street_Address__c, p.PBS_AAAP_AGENCY_REQUIREMENT_ID__r.PBS_AAAP_Lease_Term__c,
            p.PBS_AAAP_Offer_ID__r.PBS_AAAP_City__c, p.PBS_AAAP_Offer_ID__r.PBS_AAAP_State__c, p.PBS_AAAP_Offer_ID__r.PBS_AAAP_ZipCode__c,
            p.PBS_AAAP_Offer_ID__r.PBS_AAAP_Owner_Name__c, p.PBS_AAAP_Offer_ID__r.PBS_AAAP_Building_Name__c, p.PBS_AAAP_Offer_ID__c, p.PBS_AAAP_NEW_GSA_LEASE_NUM__c, 
            p.PBS_AAAP_CONTRACT_AWARD_DATE__c, p.PBS_AAAP_AWARDED_USF__c, p.PBS_AAAP_Offer_ID__r.Formula_RLP_Region__c
            FROM PBS_AAAP_Offer_Select_Award_Info__c p
            WHERE p.PBS_AAAP_IsAwarded__c = TRUE 
            ORDER BY p.PBS_AAAP_CONTRACT_AWARD_DATE__c DESC limit 500
        ];**/
        
        awardOffers = [
            SELECT  PBS_AAAP_Total_Contract_Amount__c, PBS_AAAP_Offer_ID__r.PBS_AAAP_Street_Address__c, PBS_AAAP_AGENCY_REQUIREMENT_ID__r.PBS_AAAP_Lease_Term__c,
            PBS_AAAP_Offer_ID__r.PBS_AAAP_City__c, PBS_AAAP_Offer_ID__r.PBS_AAAP_State__c, PBS_AAAP_Offer_ID__r.PBS_AAAP_ZipCode__c,
            PBS_AAAP_Offer_ID__r.PBS_AAAP_Owner_Name__c, PBS_AAAP_Offer_ID__r.PBS_AAAP_Building_Name__c, PBS_AAAP_Offer_ID__c, PBS_AAAP_NEW_GSA_LEASE_NUM__c, 
            PBS_AAAP_CONTRACT_AWARD_DATE__c, PBS_AAAP_AWARDED_USF__c, PBS_AAAP_Offer_ID__r.Formula_RLP_Region__c
            FROM PBS_AAAP_Offer_Select_Award_Info__c 
            WHERE PBS_AAAP_IsAwarded__c = TRUE 
            ORDER BY PBS_AAAP_CONTRACT_AWARD_DATE__c DESC limit 500
        ];

        system.debug('JK user ' + UserInfo.getName());
        system.debug('<<<NIKILESH>>>'+awardOffers);
        system.debug('JK street address ' + awardOffers[0].PBS_AAAP_Offer_ID__r.PBS_AAAP_Street_Address__c);
        system.debug('JK city ' + awardOffers[0].PBS_AAAP_Offer_ID__r.PBS_AAAP_City__c);
        system.debug('JK state ' + awardOffers[0].PBS_AAAP_Offer_ID__r.PBS_AAAP_State__c);
        system.debug('JK zip ' + awardOffers[0].PBS_AAAP_Offer_ID__r.PBS_AAAP_ZipCode__c);
        system.debug('JK owner name ' + awardOffers[0].PBS_AAAP_Offer_ID__r.PBS_AAAP_Owner_Name__c);
        system.debug('JK region ' + awardOffers[0].PBS_AAAP_Offer_ID__r.Formula_RLP_Region__c);
        
        for(PBS_AAAP_Offer_Select_Award_Info__c a : awardOffers){
            String i = a.PBS_AAAP_Offer_ID__r.PBS_AAAP_Building_Name__c;
            System.debug('JK i ' + i);
            if(i != '' && i != null){            
                system.debug('%%%NIK%%%1'+i);
                List<String> words = i.split(' ');
                system.debug('%%%NIK%%%2'+words);
                List<String> newwords = new List<String>();
                for(String w : words){
                    system.debug('%%%NIK%%%3'+w);
                    Integer j = w.length();
                    system.debug('%%%NIK%%%4'+j);
                    if(j>15){
                        w = w.substring(0, 8) + '-' + w.substring(9, w.length());
                        //w = w.substring(0,6);
                        //w = w+'...';
                    }
                    system.debug('%%%NIK%%%5'+w);
                    newWords.add(w);
                }
                string newi = string.join(newwords,' ');
                system.debug('%%%NIK%%%6'+newi);
                a.PBS_AAAP_Offer_ID__r.PBS_AAAP_Building_Name__c = newi;
            }
													
											
																	
        }   
        
        for(PBS_AAAP_Offer_Select_Award_Info__c a : awardOffers){
            String i = a.PBS_AAAP_Offer_ID__r.PBS_AAAP_Street_Address__c;      
            if(i != '' && i != null){     
                system.debug('%%%NIK%%%1'+i);
                List<String> words = i.split(' ');
                system.debug('%%%NIK%%%2'+words);
                List<String> newwords = new List<String>();
                for(String w : words){
                    system.debug('%%%NIK%%%3'+w);
                    Integer j = w.length();
                    system.debug('%%%NIK%%%4'+j);
                    if(j>15){
                        w = w.substring(0, 8) + '-' + w.substring(9, w.length());
                        //w = w.substring(0,6);
                        //w = w+'...';
                    }
                    system.debug('%%%NIK%%%5'+w);
                    newWords.add(w);
                }
                string newi = string.join(newwords,' ');
                system.debug('%%%NIK%%%6'+newi);
                a.PBS_AAAP_Offer_ID__r.PBS_AAAP_Street_Address__c = newi;
            }
													
											
																	 
        }   
        
        for(PBS_AAAP_Offer_Select_Award_Info__c a : awardOffers){
            String i = a.PBS_AAAP_Offer_ID__r.PBS_AAAP_Owner_Name__c;  
            if(i != '' && i != null){          
                system.debug('%%%NIK%%%1'+i);
                List<String> words = i.split(' ');
                system.debug('%%%NIK%%%2'+words);
                List<String> newwords = new List<String>();
                for(String w : words){
                    system.debug('%%%NIK%%%3'+w);
                    Integer j = w.length();
                    system.debug('%%%NIK%%%4'+j);
                    if(j>15){
                        w = w.substring(0, 8) + '-' + w.substring(9, w.length());
                        //w = w.substring(0,6);
                        //w = w+'...';
                    }
                    system.debug('%%%NIK%%%5'+w);
                    newWords.add(w);
                }
											 
								
			 
                string newi = string.join(newwords,' ');
                system.debug('%%%NIK%%%6'+newi);
                a.PBS_AAAP_Offer_ID__r.PBS_AAAP_Owner_Name__c = newi;
           }
       }        
        
    }


}