force-app/main/default/objects/PBS_AAAP_Agency_Requirement__c/PBS_AAAP_Agency_Requirement__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object store all information related to an Agency requirement in AAAP</description>
    <label>Agency Requirement</label>
    <nameField>
        <label>Agency Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/PBS_AAAP_Offer__c.object-meta.xml
<CustomObject>
    <description>AAAP - This object stores all information related to an AAAP Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>SFO-Offer-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Building_Name__c</fullName>
    <description>Building Name</description>
    <label>Building Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer__c/fields/PBS_AAAP_OFFER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_OFFER_NUMBER__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer</relationshipLabel>
    <relationshipName>Offer_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/PBS_AAAP_Offer_Deselect_Reject_Reasons__c.object-meta.xml
<CustomObject>
    <label>Offer Deselect Reject Reasons</label>
    <nameField>
        <label>Offer Deselect Reject Reasons Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Deselect Reject Reasons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Action_Comments__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Action_Comments__c</fullName>
    <label>Action Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Action_Reason__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Action_Reason__c</fullName>
    <label>Action Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Requirement Changes</fullName>
            </value>
            <value>
                <fullName>Agency Requirement Canceled</fullName>
            </value>
            <value>
                <fullName>Offer Has Changed</fullName>
            </value>
            <value>
                <fullName>Building Problems Found</fullName>
            </value>
            <value>
                <fullName>Offeror Found to be Debarred</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Agency_Requirement__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Agency_Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Requirement</label>
    <referenceTo>PBS_AAAP_Agency_Requirement__c</referenceTo>
    <relationshipLabel>Offer Deselect Reject Reasons</relationshipLabel>
    <relationshipName>Offer_Deselect_Reject_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_AAAP_Offer_Deselect_Reject_Reasons__c/fields/PBS_AAAP_Offer_Number__c.field-meta.xml
<CustomField>
    <fullName>PBS_AAAP_Offer_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Number</label>
    <referenceTo>PBS_AAAP_Offer__c</referenceTo>
    <relationshipLabel>Offer Deselect Reject Reasons</relationshipLabel>
    <relationshipName>Offer_Deselect_Reject_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PBS_AAAP_OfferDeselectComponentContr.cls
public with sharing class PBS_AAAP_OfferDeselectComponentContr extends PBS_AAAP_PageBaseController {

    public String targetObjId { public get; public set; }

    public PBS_AAAP_OfferDeselectComponentContr() {
        logMethodStart('PBS_AAAP_OfferDeselectComponentContr');
        logMethodEnd('PBS_AAAP_OfferDeselectComponentContr');
    }

    public List<PBS_AAAP_Offer_Deselect_Reject_Reasons__c> deselectList {
        public get {
            logMethodStart('deselectList');
            List<PBS_AAAP_Offer_Deselect_Reject_Reasons__c> deselectList = null;
//            if (targetObjId != null) {
                deselectList = [
                        SELECT a.Id, a.PBS_AAAP_Agency_Requirement__c, a.PBS_AAAP_Offer_Number__r.PBS_AAAP_Building_Name__c,
                                a.PBS_AAAP_Action_Comments__c, a.PBS_AAAP_Action_Reason__c, a.CreatedDate
                        FROM PBS_AAAP_Offer_Deselect_Reject_Reasons__c a
                        WHERE a.PBS_AAAP_Agency_Requirement__c = :targetObjId
                ];
//            }
            if (deselectList == null) {
                deselectList = new List<PBS_AAAP_Offer_Deselect_Reject_Reasons__c>();
            }
            logMethodEnd('deselectList', deselectList);
            return deselectList;
        }
        private set;
    }
}