force-app/main/default/objects/OrgUsersLicense__c/OrgUsersLicense__c.object-meta.xml
<CustomObject>
    <description>LMT User License is the Detail object of License Management Tool. It&apos;s synced from Other orgs to EEO org with User details.</description>
    <label>LMT User  License</label>
    <nameField>
        <displayFormat>LMT-User_License-{0}</displayFormat>
        <label>LMT User License #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMT Users License</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgUsersLicense__c/fields/ActiveUser__c.field-meta.xml
<CustomField>
    <fullName>ActiveUser__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active User?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgUsersLicense__c/fields/FederationID__c.field-meta.xml
<CustomField>
    <fullName>FederationID__c</fullName>
    <label>Federation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgUsersLicense__c/fields/OrgFedIDKey__c.field-meta.xml
<CustomField>
    <fullName>OrgFedIDKey__c</fullName>
    <externalId>true</externalId>
    <label>OrgFedIDKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgUsersLicense__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgUsersLicense__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org. Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgUsersLicense__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrgUsersLicense__c/fields/UserLicense__c.field-meta.xml
<CustomField>
    <fullName>UserLicense__c</fullName>
    <label>User License</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestLicenseManagement.cls
@isTest
private class TestLicenseManagement{

    @isTest(SeeAllData=false) 
    Static void TestTriggerOrgUserLicenseTriggerClient() {
		
		OrgUsersLicense__c objOrgUser = New OrgUsersLicense__c();
		objOrgUser.ActiveUser__c = true;
		objOrgUser.FederationID__c = 'FedID';
		objOrgUser.OrgFedIDKey__c = 'OrgIDFedID';
		objOrgUser.OrgID__c = 'OrgID';
		objOrgUser.OrgName__c = 'OrgName';
		objOrgUser.UserID__c = 'UserID@test.com.EEO';
		objOrgUser.UserLicense__c = 'Salesforce';
		Insert objOrgUser;
		
		//Check if the Object record was created sucessfully
		System.Assert(objOrgUser.ID != NULL);
		
	}
	
	/*@isTest 
	public static void UpdateUserRecord(){
		
		List<Profile> ps = [select id, name from Profile where name = 'GSA System Administrator' or name = 'System Administrator'];
		Map<String,ID> profiles = new Map<String,ID>();
		for(Profile p : ps){  
            profiles.put(p.name, p.id);  
		}
		
		User U = [SELECT Id FROM User WHERE IsActive = True And profileid = :profiles.get('GSA System Administrator') Limit 1];
        U.Title = 'Updated Title';
        Update U;
        
    }*/
    
}