force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtProjectDescription__c.field-meta.xml
<CustomField>
    <fullName>txtProjectDescription__c</fullName>
    <label>Scope / Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/PBS_Small_Projects_Historical_Database__c.object-meta.xml
<CustomObject>
    <description>Small Projects Historical Database</description>
    <label>Small Projects Historical Database</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Salesforce Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Small Projects Historical Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/Central_Facility_Repository_CFR__c.field-meta.xml
<CustomField>
    <fullName>Central_Facility_Repository_CFR__c</fullName>
    <inlineHelpText>Upload record documents, schedule of values, scope of work, and cost estimate into the CFR Project Record.</inlineHelpText>
    <label>CFR URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/PBS_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ePM Project Name</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>Small Projects Historical Database</relationshipLabel>
    <relationshipName>Small_Projects_Historical_Database</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/Property_Manager_User__c.field-meta.xml
<CustomField>
    <fullName>Property_Manager_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Small_Projects_Historical_Database</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/Scope_Description__c.field-meta.xml
<CustomField>
    <fullName>Scope_Description__c</fullName>
    <label>Scope Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/Supervisor_User__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Small_Projects_Historical_Database1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PBS_Project_TriggerHandlerTest.cls
@isTest
public class PBS_Project_TriggerHandlerTest {
  static testMethod void TestOnAfterUpdate(){
                
       PBS_Project__c proj1 = new PBS_Project__c();
       PBS_Small_Projects_Historical_Database__c sphd1 = new PBS_Small_Projects_Historical_Database__c();

       proj1.Name = 'Test 1';
       proj1.txtProjectDescription__c = 'Scope Description for Project 1';
       
       List<PBS_Project__c> prjts = new List<PBS_Project__c>();
       prjts.add(proj1);
       insert prjts;
       
       sphd1.PBS_Project_Name__c = proj1.ID;
       sphd1.Central_Facility_Repository_CFR__c = 'www.gsa.gov';
       sphd1.Scope_Description__c = 'Scope Description for Project 1 v1.0';
       sphd1.Property_Manager_User__c = UserInfo.getUserId();
       sphd1.Supervisor_User__c = UserInfo.getUserId();
       insert sphd1;
       
       proj1.txtProjectDescription__c = 'Scope Description for Project 1 v2.0';
       update proj1;
       
       List<PBS_Small_Projects_Historical_Database__c> gtList = [SELECT ID, Scope_Description__c
                                                                    FROM PBS_Small_Projects_Historical_Database__c 
                                                                    WHERE PBS_Project_Name__c IN :prjts];
       
       system.assertEquals(proj1.txtProjectDescription__c,gtList[0].Scope_Description__c); 

    } 
}