force-app/main/default/objects/PBS_Building__c/PBS_Building__c.object-meta.xml
<CustomObject>
    <description>PBS Common Building Object</description>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Building__c/fields/Location_Code_Plus__c.field-meta.xml
<CustomField>
    <fullName>Location_Code_Plus__c</fullName>
    <externalId>true</externalId>
    <label>Location Code Plus</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/PBS_BuildingProjectAssociation__c.object-meta.xml
<CustomObject>
    <description>PBS Project-Building Junction Object</description>
    <label>PBS Building Project Association</label>
    <nameField>
        <displayFormat>PBSPRJ-BLDG-{0000000000}</displayFormat>
        <label>PBS Building Project Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Building Project Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/fields/rluBuilding__c.field-meta.xml
<CustomField>
    <fullName>rluBuilding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Record ID</label>
    <referenceTo>PBS_Building__c</referenceTo>
    <relationshipLabel>PBS Building Project Associations</relationshipLabel>
    <relationshipName>PBS_Building_Project_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/fields/rluProject__c.field-meta.xml
<CustomField>
    <fullName>rluProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Record ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>PBS Building Project Associations</relationshipLabel>
    <relationshipName>PBS_Building_Project_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/PBS_Small_Projects_Historical_Database__c.object-meta.xml
<CustomObject>
    <description>Small Projects Historical Database</description>
    <label>Small Projects Historical Database</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Salesforce Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Small Projects Historical Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/Building_Number__c.field-meta.xml
<CustomField>
    <fullName>Building_Number__c</fullName>
    <label>Building Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/PBS_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ePM Project Name</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>Small Projects Historical Database</relationshipLabel>
    <relationshipName>Small_Projects_Historical_Database</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PBS_BPA_TriggerHandlerTest.cls
@isTest class PBS_BPA_TriggerHandlerTest extends TestDataFactory {
  final static String locationCodePlus = 'Test ';

  @testSetup static void makeData() {
    final PBS_Project__c[] projects = new PBS_Project__c[]{};
    final PBS_Building__c[] buildings = new PBS_Building__c[]{};

    TestDataFactory.TEST_CASES = 2;

    for (Integer i = 0; i < TestDataFactory.TEST_CASES; i++) {
      projects.add(getBasicProject());
    }

    insert projects;

    for (Integer i = 0; i < TestDataFactory.TEST_CASES; i++) {
      buildings.add(getBasicBuilding(i, String.valueOf(i)));
      buildings[i].Location_Code_Plus__c = locationCodePlus + i;
    }

    insert buildings;

    for (Integer i = 0; i < TestDataFactory.TEST_CASES; i++) {
      PBS_Small_Projects_Historical_Database__c sphd = getBasicSPHD();

      sphd.PBS_Project_Name__c = projects[i].Id;

      TestDataFactory.testRecords.add(sphd);
    }

    insert TestDataFactory.testRecords;
  }

  static PBS_BuildingProjectAssociation__c[] makeBPAs() {
    final PBS_Project__c[] projects = [SELECT Id FROM PBS_Project__c];
    final PBS_Building__c[] buildings = [SELECT Id FROM PBS_Building__c];
    final PBS_BuildingProjectAssociation__c[] bpas = new PBS_BuildingProjectAssociation__c[]{};

    for (Integer i = 0; i < projects.size(); i++) {
      final PBS_BuildingProjectAssociation__c bpa = getBasicBPA();

      bpa.rluBuilding__c = buildings[i].Id;
      bpa.rluProject__c = projects[i].Id;

      bpas.add(bpa);
    }

    return bpas;
  }

  @isTest static void testInsert() {
    Test.startTest();
      insert makeBPAs();
    Test.stopTest();

    PBS_Small_Projects_Historical_Database__c[] sphds = [SELECT Id, Building_Number__c
                                                         FROM PBS_Small_Projects_Historical_Database__c];

    for (Integer i = 0; i < sphds.size(); i++) {
      System.assertEquals(locationCodePlus + i, sphds[i].Building_Number__c);
    }
  }

  @isTest static void testUpdate() {
    final PBS_Building__c[] buildings = [SELECT Id
                                         FROM PBS_Building__c
                                         LIMIT 2];

    PBS_BuildingProjectAssociation__c[] newRecords = makeBPAs();
    insert newRecords;

    final Map<Id, PBS_BuildingProjectAssociation__c> oldRecords = new Map<Id, PBS_BuildingProjectAssociation__c>(newRecords.clone());

    newRecords[0].rluBuilding__c = buildings[1].Id;
    newRecords[1].rluBuilding__c = buildings[0].Id;

    Test.startTest();
      update newRecords;
    Test.stopTest();

    System.assert(true);
  }

  @isTest static void testDeleteUndelete() {
    TestDataFactory.testRecords = makeBPAs();

    insert TestDataFactory.testRecords;

    Test.startTest();
    delete TestDataFactory.testRecords;

    for (PBS_Small_Projects_Historical_Database__c sphd: [SELECT Id, Building_Number__c
                                                          FROM PBS_Small_Projects_Historical_Database__c]) {
      System.assert(String.isBlank(sphd.Building_Number__c));
    }

    undelete TestDataFactory.testRecords;
    Test.stopTest();

  }
}