force-app/main/default/objects/PBS_Building__c/PBS_Building__c.object-meta.xml
<CustomObject>
    <description>PBS Common Building Object</description>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Building__c/fields/Building_ID__c.field-meta.xml
<CustomField>
    <fullName>Building_ID__c</fullName>
    <externalId>true</externalId>
    <label>Building ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Location_Code_Plus__c.field-meta.xml
<CustomField>
    <fullName>Location_Code_Plus__c</fullName>
    <externalId>true</externalId>
    <label>Location Code Plus</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/PBS_BuildingProjectAssociation__c.object-meta.xml
<CustomObject>
    <description>PBS Project-Building Junction Object</description>
    <label>PBS Building Project Association</label>
    <nameField>
        <displayFormat>PBSPRJ-BLDG-{0000000000}</displayFormat>
        <label>PBS Building Project Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Building Project Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/PBS_Small_Projects_Historical_Database__c.object-meta.xml
<CustomObject>
    <description>Small Projects Historical Database</description>
    <label>Small Projects Historical Database</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Salesforce Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Small Projects Historical Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
public abstract class TestDataFactory {
  @testVisible static sObject[] testRecords = new sObject[]{};
  @testVisible static Integer TEST_CASES = 1;

  // The basic, required fields needed to perform DML on a User:
  @testVisible static User getBasicUser() {
    return new User();
  }

  @testVisible static PBS_Project__c getBasicProject() {
    return new PBS_Project__c();
  }

  @testVisible static PBS_Building__c getBasicBuilding(final Decimal buildingId, final String locationCodePlus) {
    return new PBS_Building__c(Building_ID__c = buildingId,
                               Location_Code_Plus__c = locationCodePlus);
  }

  @testVisible static PBS_BuildingProjectAssociation__c getBasicBPA() {
    return new PBS_BuildingProjectAssociation__c();
  }

  @testVisible static PBS_Small_Projects_Historical_Database__c getBasicSPHD() {
    return new PBS_Small_Projects_Historical_Database__c();
  }
}