force-app/main/default/objects/PBS_Building__c/PBS_Building__c.object-meta.xml
<CustomObject>
    <description>PBS Common Building Object</description>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Building__c/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <label>Address2</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Building_GSF__c.field-meta.xml
<CustomField>
    <fullName>Building_GSF__c</fullName>
    <label>Building GSF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Building_ID__c.field-meta.xml
<CustomField>
    <fullName>Building_ID__c</fullName>
    <externalId>true</externalId>
    <label>Building ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <label>Building Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Building_RSF__c.field-meta.xml
<CustomField>
    <fullName>Building_RSF__c</fullName>
    <label>Building RSF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Building_RU__c.field-meta.xml
<CustomField>
    <fullName>Building_RU__c</fullName>
    <label>Building RU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Building_USF__c.field-meta.xml
<CustomField>
    <fullName>Building_USF__c</fullName>
    <label>Building USF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Construct_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Construct_Complete_Date__c</fullName>
    <label>Construct Complete Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <label>Facility Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Field_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Field_Office_Code__c</fullName>
    <label>Field Office Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>17</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Location_Code_Plus__c.field-meta.xml
<CustomField>
    <fullName>Location_Code_Plus__c</fullName>
    <externalId>true</externalId>
    <label>Location Code Plus</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>17</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_Building__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/PBS_BuildingProjectAssociation__c.object-meta.xml
<CustomObject>
    <description>PBS Project-Building Junction Object</description>
    <label>PBS Building Project Association</label>
    <nameField>
        <displayFormat>PBSPRJ-BLDG-{0000000000}</displayFormat>
        <label>PBS Building Project Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Building Project Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/fields/rluBuilding__c.field-meta.xml
<CustomField>
    <fullName>rluBuilding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Record ID</label>
    <referenceTo>PBS_Building__c</referenceTo>
    <relationshipLabel>PBS Building Project Associations</relationshipLabel>
    <relationshipName>PBS_Building_Project_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_BuildingProjectAssociation__c/fields/rluProject__c.field-meta.xml
<CustomField>
    <fullName>rluProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Record ID</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>PBS Building Project Associations</relationshipLabel>
    <relationshipName>PBS_Building_Project_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PBS_gBUILD_ProjectBuilding__c/PBS_gBUILD_ProjectBuilding__c.object-meta.xml
<CustomObject>
    <description>gBUILD Project Building: Data related to a particular Project-Building</description>
    <label>gBUILD Project Building</label>
    <nameField>
        <displayFormat>gbPb_{00000}</displayFormat>
        <label>PBSgBUILDPB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gBUILD Project Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/PBS_Project__c.object-meta.xml
<CustomObject>
    <description>PBS Project Common Object</description>
    <label>PBS Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Project__c/fields/txtCreatedIn__c.field-meta.xml
<CustomField>
    <fullName>txtCreatedIn__c</fullName>
    <label>Created In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gBUILD</fullName>
            </value>
            <value>
                <fullName>GPGIS</fullName>
            </value>
            <value>
                <fullName>ePM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtCurrentState__c.field-meta.xml
<CustomField>
    <fullName>txtCurrentState__c</fullName>
    <label>Current State [from ePM]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Formative</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PBS_Project__c/fields/txtLongName__c.field-meta.xml
<CustomField>
    <fullName>txtLongName__c</fullName>
    <label>Project Long Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PBS_gBUILD_PBuildingBasicsController.cls
public with sharing class PBS_gBUILD_PBuildingBasicsController extends PBS_gBUILD_ProjectIdBaseController
{
    public string uploadCatalog { get { return PBS_gBUILD_Utility.epmCatalogExecution; } }
    public PBS_gBUILD_Utility.LinkedObjectFieldInfo buildingNameLink { get; private set; }
    public PBS_Building__c b { get; private set; }
    public PBS_BuildingProjectAssociation__c[] projectAssociations { get; private set; }
    public PBS_gBUILD_ProjectBuilding__c projectBuilding { get; private set; }
    public string actionId { get; set; }    
    public string mapEmbedUrl { get; private set; }
    public string mapLinkUrl { get; private set; }
    public string mapQuestLinkUrl{get;private set;}//added by Ramesh
    public string mapYahooLinkUrl{get; private set;}//added by Ramesh
    public boolean renderMap { get; private set; }
    public boolean renderAddress { get; private set; }
        
    public PBS_gBUILD_PBuildingBasicsController()
    {
        super('Building Basics', true);
        renderAddress = false;
        renderMap = false;
        try
        {        
            super.bind();
            projectBuilding = PBS_gBUILD_Utility.loadProjectBuilding(pbuildingid);
            b=null;
            List<PBS_Building__c >lstBuildPro=null;
             lstBuildPro= [
                select
                    Building_ID__c,
                    Building_Name__c,
                    Facility_Id__c,
                    Street_Address__c,
                    Address2__c,
                    State_Code__c,
                    Zip_Code__c,
                    Region_Code__c,
                    Building_RSF__c,
                    Building_RU__c,
                    Building_USF__c,
                    Building_GSF__c,
                    City__c,
                    Construct_Complete_Date__c,
                    Field_Office_Code__c,
                    Location_Code_Plus__c,
                    LATITUDE__C,
                    LONGITUDE__C
                from PBS_Building__c
                where id=:pbsBuildingId
                ];
                
                if(lstBuildPro.size()>0)
                {
                    b=lstBuildPro.get(0);
                    buildingNameLink = new PBS_gBUILD_Utility.LinkedObjectFieldInfo(Schema.sObjectType.PBS_Building__c.fields.Building_Name__c, b.id, b.Building_Name__c);                                
                    PageReference pr = new PageReference('https://maps.google.com/maps');
                    PageReference mq = new PageReference('https://www.mapquest.com');
                    PageReference yh = new PageReference('https://maps.yahoo.com/search/');
                    Map<string, string> params = pr.getParameters();
                    Map<string, string> mapqparams = mq.getParameters();
                    Map<string, string> yhparams = yh.getParameters();

                    params.put('z', '15');
                    mapqparams.put('z', '15');


                    if (
                        b.Street_Address__c!=null && b.Street_Address__c.length()>0 &&
                        b.City__c!=null && b.City__c.length()>0 &&
                        b.State_Code__c!=null && b.State_Code__c.length()>0)
                    {
                        params.put('q', string.format(
                            '{0} {1};{2}, {3}',
                            new string[]{ b.Street_Address__c, b.Address2__c==null?'':b.Address2__c, b.City__c, b.State_Code__c}));                        
                        
                        mapqparams.put('q', string.format(
                            '{0} {1};{2}, {3}',
                            new string[]{ b.Street_Address__c, b.Address2__c==null?'':b.Address2__c, b.City__c, b.State_Code__c}));                        

                        yhparams.put('p', string.format(
                            '{0} {1};{2}, {3}',
                            new string[]{ b.Street_Address__c, b.Address2__c==null?'':b.Address2__c, b.City__c, b.State_Code__c}));                        

                    }
                    else if (
                        b.LATITUDE__C!=null && b.LATITUDE__C!=0 &&
                        b.LONGITUDE__C!=null && b.LONGITUDE__C!=0                    
                    )
                    {
                        renderAddress = true;
                        params.put('q', string.format(
                            '{0}, {1}',
                            new string[]{ string.valueOf(b.LATITUDE__c), string.valueOf(b.LONGITUDE__c)}));                                            
                        
                        mapqparams.put('q', string.format(
                            '{0}, {1}',
                            new string[]{ string.valueOf(b.LATITUDE__c), string.valueOf(b.LONGITUDE__c)}));                                            
                        
                         yhparams.put('p', string.format(
                            '{0}, {1}',
                            new string[]{ string.valueOf(b.LATITUDE__c), string.valueOf(b.LONGITUDE__c)}));

                    }
                    else
                    {
                        renderAddress = true;
                        params = null;
                        mapqparams=null;
                        yhparams = null;
                    }
                    if (params!=null || mapqparams!=null || yhparams!=null)
                    {
                        mapLinkUrl = pr.getUrl();
                        mapQuestLinkUrl = mq.getUrl();
                        mapYahooLinkUrl = yh.getUrl();
                        params.put('output', 'embed');
                        mapEmbedUrl = pr.getUrl();
                        renderMap = true;
                    }
                }
    
            projectAssociations = 
            [
                select rluProject__r.id, rluProject__r.name, rluProject__r.txtLongName__c, rluProject__r.txtCreatedIn__c, rluProject__r.txtCurrentState__c
                from PBS_BuildingProjectAssociation__c
                where 
                    rluBuilding__c=:pbsBuildingId and
                    rluProject__c<>null
            ];
        }
        catch (Exception ex)
        {            
            handleConstructorError(ex);
        }            
    }   

    public PageReference openProject()
    {
        return new PageReference('/'+actionId);
    }
}