force-app/main/default/objects/ArcGIS_API__mdt/ArcGIS_API__mdt.object-meta.xml
<CustomObject>
    <description>Metadata Type properties for accessing the GSA GIS ArcGIS OnPrem REST services</description>
    <label>ArcGIS API</label>
    <pluralLabel>ArcGIS API</pluralLabel>
</CustomObject>

force-app/main/default/objects/ArcGIS_API__mdt/fields/GIS_Locator__c.field-meta.xml
<CustomField>
    <fullName>GIS_Locator__c</fullName>
    <label>GIS Locator</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/GIS_Locator_URL__c.field-meta.xml
<CustomField>
    <fullName>GIS_Locator_URL__c</fullName>
    <label>GIS Locator URL</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/GIS_URL_Prefix__c.field-meta.xml
<CustomField>
    <fullName>GIS_URL_Prefix__c</fullName>
    <label>GIS URL Prefix</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <label>Named Credential</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/Token_Expiration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Token_Expiration_Minutes__c</fullName>
    <label>Token Expiration Minutes</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/Token_Service_Timeout_Milliseconds__c.field-meta.xml
<CustomField>
    <fullName>Token_Service_Timeout_Milliseconds__c</fullName>
    <label>Token Service Timeout Milliseconds</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/Token_URI__c.field-meta.xml
<CustomField>
    <fullName>Token_URI__c</fullName>
    <label>Token URI</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_API__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APIArcGISMetadataModel.cls
public with sharing class APIArcGISMetadataModel {

    private static List<ArcGIS_API__mdt> pCustomMetadataList = null;
    public static List<ArcGIS_API__mdt> customMetadataList {
        get {
            if (pCustomMetadataList == null) {
                pCustomMetadataList = [select Id, DeveloperName, Username__c, Password__c, Named_Credential__c,
                                       Token_URI__c, Token_Service_Timeout_Milliseconds__c, Token_Expiration_Minutes__c,
                                       GIS_URL_Prefix__c, GIS_Locator_URL__c, GIS_Locator__c
                                       from ArcGIS_API__mdt where Is_Active__c = true]; 
            }
            return pCustomMetadataList;
        } 
    }
    
    private static Map<String, ArcGIS_API__mdt> pCustomMetadataMap = null;
    public static Map<String, ArcGIS_API__mdt> customMetadataMap {
        get {
            if (pCustomMetadataMap == null){
                pCustomMetadataMap = new Map<String, ArcGIS_API__mdt>(); 
                for(ArcGIS_API__mdt rt : customMetadataList){
                    pCustomMetadataMap.put(rt.DeveloperName, rt);
                } 
            }
            return pCustomMetadataMap;
        }
    }
    
    public static ArcGIS_API__mdt lookupAPICustomMetaData (String keyName){
        System.Debug('APIArcGISMetadataModel.LookupCustomMetada() starting...');
        if(customMetadataMap.containsKey(keyName)){          
            return customMetadataMap.get(keyName);
        }else { 
            //unable to locate
            System.Debug('APIArcGISMetadataModel.LookupCustomMetada() unable to locate '+ keyName);
            return null;
        }  
    }
    
}