force-app/main/default/objects/NCMT_Assembly_Lookup_Detail__c/NCMT_Assembly_Lookup_Detail__c.object-meta.xml
<CustomObject>
    <label>NCMT Assembly Lookup Master</label>
    <nameField>
        <label>Assembly SKey</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Assembly Lookup Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Assembly_Lookup_Detail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Assembly Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Contractor__c/NCMT_Contractor__c.object-meta.xml
<CustomObject>
    <label>NCMT SubContractor</label>
    <nameField>
        <label>NCMT SubContractor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT SubContractor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Contractor__c/fields/Contractor_Description__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Description__c</fullName>
    <label>Subcontractor Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Basis_Date_Of_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Basis_Date_Of_Estimate__c</fullName>
    <formula>Cost_Parameter_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Basis Date of Estimate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Coreshell_OPC__c.field-meta.xml
<CustomField>
    <fullName>Coreshell_OPC__c</fullName>
    <label>Coreshell OPC</label>
    <summarizedField>NCMT_Other_Cost__c.Total1__c</summarizedField>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Type__c</field>
        <operation>equals</operation>
        <value>Project Costs</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Description__c</field>
        <operation>contains</operation>
        <value>Core/Shell Cost</value>
    </summaryFilterItems>
    <summaryForeignKey>NCMT_Other_Cost__c.NCMT_Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/End_Construction__c.field-meta.xml
<CustomField>
    <fullName>End_Construction__c</fullName>
    <description>End Construction date</description>
    <label>Date of Occupancy</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Footprint_Area__c.field-meta.xml
<CustomField>
    <fullName>Footprint_Area__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Footprint Area</description>
    <label>Footprint Area</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Prorated_ODC__c.field-meta.xml
<CustomField>
    <fullName>Prorated_ODC__c</fullName>
    <label>Prorated ODC</label>
    <summarizedField>NCMT_Other_Cost__c.Total_Cost__c</summarizedField>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Type__c</field>
        <operation>equals</operation>
        <value>Direct Costs</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Description__c</field>
        <operation>equals</operation>
        <value>Pro-rated</value>
    </summaryFilterItems>
    <summaryForeignKey>NCMT_Other_Cost__c.NCMT_Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Prorated_OPC__c.field-meta.xml
<CustomField>
    <fullName>Prorated_OPC__c</fullName>
    <label>Prorated OPC</label>
    <summarizedField>NCMT_Other_Cost__c.Total1__c</summarizedField>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Type__c</field>
        <operation>equals</operation>
        <value>Project Costs</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Description__c</field>
        <operation>equals</operation>
        <value>Pro-rated</value>
    </summaryFilterItems>
    <summaryForeignKey>NCMT_Other_Cost__c.NCMT_Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Standard_Esc_Rate__c.field-meta.xml
<CustomField>
    <fullName>Standard_Esc_Rate__c</fullName>
    <label>Standard Escalation Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/TI_OPC__c.field-meta.xml
<CustomField>
    <fullName>TI_OPC__c</fullName>
    <label>TI OPC</label>
    <summarizedField>NCMT_Other_Cost__c.Total1__c</summarizedField>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Type__c</field>
        <operation>equals</operation>
        <value>Project Costs</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCMT_Other_Cost__c.Cost_Description__c</field>
        <operation>equals</operation>
        <value>Tenant Cost</value>
    </summaryFilterItems>
    <summaryForeignKey>NCMT_Other_Cost__c.NCMT_Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/NCMT_CustomLookUpController.cls
public with sharing class NCMT_CustomLookUpController {

    @AuraEnabled 
    public static List<sObject> fetchLookUpValues(string searchKeyWord, string objectName, string fiscalYear){
        system.debug('searchKeyWord-->' + searchKeyWord);
        //searchKeyWord = 'test';
        string searchKey;
        if (searchKeyWord != null &&searchKeyWord != '') searchKey = '%' + String.escapeSingleQuotes(searchKeyWord) + '%';
        String oName = '';
        if (objectName != null &&objectName != '') oName = String.escapeSingleQuotes(objectName);
        String fYear = '';
        if (fiscalYear != null &&fiscalYear != '') fYear = String.escapeSingleQuotes(fiscalYear);
        
        string searchVar;
        string whereVar = '';
    
    
        if (oName == 'NCMT_Project__c'){
            if (searchKeyWord != null &&searchKeyWord != '' &&searchKeyWord.length() > 2){
                whereVar = ' where Name LIKE: searchKey';
            } else {
               whereVar = ' where LastViewedDate != null';
            }
        } else {
            if (searchKeyWord != '' &&searchKeyWord != null){
                whereVar = ' where Name LIKE: searchKey';
            } else {
                whereVar = ' where Id <> null';
            }
        }
    
        system.debug('whereVar-->' + whereVar);
        // List<sObject> returnList = new List<sObject>();
        if(fiscalYear != null) whereVar = whereVar + ' and Fiscal_Year__c = \'' + fYear+'\'';
        if(oName == 'NCMT_Assembly_Lookup_Detail__c'){
            searchVar = 'Level_2_Description__c, Level_3_Description__c, Level_4_Description__c,Description__c';
           
        }else if(oName == 'NCMT_Contractor__c'){
        	searchVar = 'name, Contractor_Description__c';
        }
        else{ 
            searchVar = 'name';
        } 
       
        string sQuery = 'select id, ' + searchVar + '  from ' + oName + ' '+ whereVar + ' order by ';
        
        if (oName == 'NCMT_Project__c'){
            if (searchKeyWord != null &&searchKeyWord != '' &&searchKeyWord.length() > 2){
                sQuery += 'Name limit 50';
            } else {
                sQuery += 'LastViewedDate DESC limit 50';
            }
        
        } else {
            sQuery += 'name';
        }
        
        system.debug('squery' + sQuery);

        List<sObject> returnList = Database.query(sQuery);
        
        
        return returnList;
 
    }

    @AuraEnabled 
    public static List<sObject> fetchMultiSelectLookup(string searchKeyWord, string objectName, string pageName, List<sObject> ExcludeitemsList){
        if (searchKeyWord != null &&searchKeyWord != '') searchKeyWord = String.escapeSingleQuotes(searchKeyWord);
        String oName = '';
        if (objectName != null &&objectName != '') oName = String.escapeSingleQuotes(objectName);
        
         string[] alreadyAdded = new string[]{};
        for(sObject item : ExcludeitemsList ){
            alreadyAdded.add(item.id);
        }
        system.debug('already added' + alreadyAdded);

        string tCORecordTypeName = 'New Construction - TCO';
        string searchKey = '%' + searchKeyWord + '%';
        string searchVar = 'name';
        string whereVar;
        if (searchKeyWord != null &&searchKeyWord != '' &&searchKeyWord.length() > 2){
            whereVar = ' where Name LIKE: searchKey';
        } else {
            whereVar = ' where LastViewedDate !=null';
        }

        // List<sObject> returnList = new List<sObject>();
        if(pageName == 'Project_Comparison'){
            whereVar = whereVar + ' and RecordType.Name = \''+ tCORecordTypeName +'\'' ;
            searchVar = searchVar  + ', End_Construction__c, Basis_Date_Of_Estimate__c, Prorated_ODC__c, TI_OPC__c, Coreshell_OPC__c, Prorated_OPC__c, Standard_Esc_Rate__c, Footprint_Area__c';
                }
        else{
            searchVar = 'name';
        } 
        string sQuery = 'select id, ' + searchVar + '  from ' + oName + ' '+ whereVar + ' AND Id NOT IN :alreadyAdded order by ';
        if (searchKeyWord != null &&searchKeyWord != '' &&searchKeyWord.length() > 2){
            sQuery += 'createdDate DESC';
        } else {
            sQuery += 'LastViewedDate DESC limit 10';
        }
        system.debug('squery' + sQuery);
        List<sObject> returnList = Database.query(sQuery);
        
        return returnList;
    }
}