force-app/main/default/objects/NCMT_Assembly_Lookup_Detail__c/NCMT_Assembly_Lookup_Detail__c.object-meta.xml
<CustomObject>
    <label>NCMT Assembly Lookup Master</label>
    <nameField>
        <label>Assembly SKey</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Assembly Lookup Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Assembly_Lookup_Detail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Assembly Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Assembly_Lookup_Detail__c/fields/Level_2__c.field-meta.xml
<CustomField>
    <fullName>Level_2__c</fullName>
    <label>Level 2</label>
    <referenceTo>NCMT_Cost_Category__c</referenceTo>
    <relationshipLabel>NCMT Assembly Lookup Master</relationshipLabel>
    <relationshipName>NCMT_Assembly_Lookup_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Contractor__c/NCMT_Contractor__c.object-meta.xml
<CustomObject>
    <label>NCMT SubContractor</label>
    <nameField>
        <label>NCMT SubContractor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT SubContractor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Contractor__c/fields/Bond__c.field-meta.xml
<CustomField>
    <fullName>Bond__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bond</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Contractor__c/fields/Contractor_Description__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Description__c</fullName>
    <label>Subcontractor Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Contractor__c/fields/Overhead__c.field-meta.xml
<CustomField>
    <fullName>Overhead__c</fullName>
    <defaultValue>0.10</defaultValue>
    <label>Overhead</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Contractor__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <defaultValue>0.10</defaultValue>
    <label>Profit</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NCMT_Cost_Category__c/NCMT_Cost_Category__c.object-meta.xml
<CustomObject>
    <description>NCMT Cost Category</description>
    <label>Cost Category</label>
    <nameField>
        <label>Category ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Crew_Master__c/NCMT_Crew_Master__c.object-meta.xml
<CustomObject>
    <label>NCMT Crew Master</label>
    <nameField>
        <label>Crew Master Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Crew Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NCMT_Test_CustomLookupController.cls
@isTest
public  class NCMT_Test_CustomLookupController {
    
    
    @isTest static void NCMT_Test_CustomLookupController() {
        List<NCMT_Cost_Category__c> listCostCategories = Test.loadData(NCMT_Cost_Category__c.sObjectType, 'NCMT_DES_Cost_Category');
        
        NCMT_Assembly_Lookup_Detail__c  Ulookup = new NCMT_Assembly_Lookup_Detail__c();
        Ulookup.Name = 'General Requirements - 2019 -9';
        Ulookup.Level_2__c = listCostCategories [1].id;
        Ulookup.Level_3_Description__c = 'Test level 3';
        Ulookup.Level_4_Description__c = 'Test level 4';
        Ulookup.Level_5_Description__c = 'Test level 5';
        Ulookup.Fiscal_Year__c = '2019';
        insert Ulookup;
        system.debug('Ulookup' + Ulookup);
        
        NCMT_Crew_Master__c crewMaster = new NCMT_Crew_Master__c();
        crewMaster.Name = 'testCM';
        crewMaster.Description__c = 'testCM';
        insert crewMaster;
        system.debug('crewMaster' + crewMaster);
        
        NCMT_Contractor__c contractor = new NCMT_Contractor__c();
        contractor.Name = 'testContractor';
        contractor.Contractor_Description__c = 'Test Contractor';
        contractor.Overhead__c = 10;
        contractor.Profit__c = 10;
        contractor.Bond__c = 2;
        contractor.Fiscal_Year__c = '2019';

        insert contractor;
        system.debug('contractor' + contractor);
        
        
        List<NCMT_Crew_Master__c> crewMasterVal = NCMT_CustomLookUpController.fetchLookUpValues('testCM', 'NCMT_Crew_Master__c', null);
        system.assertEquals('testCM', crewMasterVal[0].Name);
        
        List<NCMT_Assembly_Lookup_Detail__c> uniformatLookupVal = NCMT_CustomLookUpController.fetchLookUpValues('General Requirements - 2019 -9', 'NCMT_Assembly_Lookup_Detail__c', '2019');
        system.assertEquals('Test level 3', uniformatLookupVal[0].Level_3_Description__c);
        
        
        List<NCMT_Contractor__c> contractorVal = NCMT_CustomLookUpController.fetchLookUpValues('testContractor', 'NCMT_Contractor__c', '2019');
        system.assertEquals('testContractor', contractorVal[0].Name);
        
    }
    
}