force-app/main/default/objects/NCMT_CustomSettings__c/NCMT_CustomSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NCMT_CustomSettings</label>
</CustomObject>

force-app/main/default/objects/NCMT_CustomSettings__c/fields/Cost_Parameter_Date__c.field-meta.xml
<CustomField>
    <fullName>Cost_Parameter_Date__c</fullName>
    <label>Cost Parameter Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan__c/NCMT_Housing_Plan__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Housing Plan</description>
    <label>NCMT Housing Plan</label>
    <nameField>
        <displayFormat>HP-{0000000000}</displayFormat>
        <label>NCMT Housing Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <formula>text(Project__r.Building_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Child to Project</description>
    <label>Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plans</relationshipLabel>
    <relationshipName>NCMT_Housing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <formula>TEXT(Project__r.Project_type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/NCMT_Housing_Plan_Option_Selection__c.object-meta.xml
<CustomObject>
    <description>Created when a Housing Plan Selection Option is selected on the Housing Plan selection page. Deleted if unselected.</description>
    <label>NCMT Housing Plan - Option Selection</label>
    <nameField>
        <displayFormat>Select-{00000}</displayFormat>
        <label>NCMT Housing Plan Option Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Housing Plan Option Selection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Housing_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>NCMT Housing Plan</label>
    <referenceTo>NCMT_Housing_Plan__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCMT_Housing_Plan_Option_Selection__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipLabel>NCMT Housing Plan Option Selection</relationshipLabel>
    <relationshipName>NCMT_Housing_Plan_Option_Selection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Other_Cost__c/NCMT_Other_Cost__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <label>NCMT Other Cost</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Other Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCMT Other Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Other_Cost__c/fields/NCMT_Project__c.field-meta.xml
<CustomField>
    <fullName>NCMT_Project__c</fullName>
    <label>NCMT Project</label>
    <referenceTo>NCMT_Project__c</referenceTo>
    <relationshipName>Other_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/NCMT_Project__c.object-meta.xml
<CustomObject>
    <customHelpPage>NCMT_HelpPage</customHelpPage>
    <description>NCMT Project</description>
    <label>NCMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NCMT_Project__c/fields/Building_Selection__c.field-meta.xml
<CustomField>
    <fullName>Building_Selection__c</fullName>
    <inlineHelpText>Applies to Parametric New and Parametric Repair and Alteration models and addresses the requirement for tenant fit out. Is it in a new building or existing building?</inlineHelpText>
    <label>Building Selection</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <inlineHelpText>Select Building Type (from one of the many primary building types in the PBS Portfolio).</inlineHelpText>
    <label>Building Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Childcare Center</fullName>
            </value>
            <value>
                <fullName>Courthouse</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Laboratory: Dry</fullName>
            </value>
            <value>
                <fullName>Laboratory: Wet</fullName>
            </value>
            <value>
                <fullName>Medical Clinic</fullName>
            </value>
            <value>
                <fullName>Medical Office</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>Parking Garage</fullName>
            </value>
            <value>
                <fullName>LPOE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Cost_Parameter_Date__c.field-meta.xml
<CustomField>
    <fullName>Cost_Parameter_Date__c</fullName>
    <label>Cost Parameter Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Estimate_Type_Proj__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Type_Proj__c</fullName>
    <inlineHelpText>Parametric: Planning or early design. 
Definitive: Later design phase/construction phase estimate.
Parametric R&amp;A: whole building renovation. 
Work Item R&amp;A: Budget estimates based on individual line item repairs.</inlineHelpText>
    <label>Estimate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parametric</fullName>
            </value>
            <value>
                <fullName>Definitive Estimating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Housing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Housing_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Housing Plan</description>
    <inlineHelpText>Applied when user can determine logical breakdown of functional space-types and the required area of each. See Housing Plan Analysis Help Sheet</inlineHelpText>
    <label>Housing Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Project_type__c.field-meta.xml
<CustomField>
    <fullName>Project_type__c</fullName>
    <inlineHelpText>Either new construction or repair and alteration based on the estimate type selected.</inlineHelpText>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estimate_Type_Proj__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New Construction</fullName>
            </value>
            <value>
                <fullName>Repair &amp; Alteration - Work Item Detail</fullName>
            </value>
            <value>
                <fullName>Repair &amp; Alteration - Parametric Entry</fullName>
            </value>
            <value>
                <fullName>New Construction - DES</fullName>
            </value>
            <value>
                <fullName>Repair &amp; Alteration - DES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Purpose_of_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_Estimate__c</fullName>
    <inlineHelpText>Defines why the estimate is being prepared.</inlineHelpText>
    <label>Purpose of Estimate</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estimate_Type_Proj__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Portfolio Planning</fullName>
            </value>
            <value>
                <fullName>Scenario Planning</fullName>
            </value>
            <value>
                <fullName>Project Screening</fullName>
            </value>
            <value>
                <fullName>Lease Scoring - Regional Office</fullName>
            </value>
            <value>
                <fullName>Lease Scoring - Central Office</fullName>
            </value>
            <value>
                <fullName>TAPS (Automated Prospectus System) Analysis</fullName>
            </value>
            <value>
                <fullName>Project Planning / Budgeting</fullName>
            </value>
            <value>
                <fullName>Project Controls</fullName>
                <default>true</default>
                <label>Project Controls</label>
            </value>
            <value>
                <fullName>FRV (Functional Replacement Value)</fullName>
            </value>
            <value>
                <fullName>Fair &amp; Reasonable Review</fullName>
            </value>
            <value>
                <fullName>Economic Optimization - Inv &amp; LCC</fullName>
            </value>
            <value>
                <fullName>Economic Optimization - LCC</fullName>
            </value>
            <value>
                <fullName>Independent Government Estimate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/fields/Start_Construction__c.field-meta.xml
<CustomField>
    <fullName>Start_Construction__c</fullName>
    <description>Start Construction Date</description>
    <label>Start Construction</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NCMT_Project__c/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>false</active>
    <description>Federal Office Building</description>
    <label>Office</label>
</RecordType>

force-app/main/default/objects/NCMT_RedirectCustomObjectpage__c/NCMT_RedirectCustomObjectpage__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NCMT_RedirectCustomObjectpage</label>
</CustomObject>

force-app/main/default/objects/NCMT_RedirectCustomObjectpage__c/fields/Building_Selection__c.field-meta.xml
<CustomField>
    <fullName>Building_Selection__c</fullName>
    <description>From NCMT Project, Building Selection field ID.</description>
    <label>Building Selection</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NCMT_MoveCostModule_Ctrl_LC.cls
public with sharing class NCMT_MoveCostModule_Ctrl_LC {

    public static NCMT_CustomSettings__c ncmt_customsettings = NCMT_CustomSettings__c.getOrgDefaults();
    
    public class moveCostWrapper {
        @AuraEnabled public NCMT_Housing_Plan__c housingPlan {get;set;}
        @AuraEnabled public List<NCMT_Other_Cost__c> otherCosts {get;set;}
        @AuraEnabled public String reportId {get;set;}
        @AuraEnabled public List<NCMT_Project__c> projList {get;set;}
        @AuraEnabled public String redirectProjName {get;set;}
        @AuraEnabled public String redirectMoveCostMod {get;set;}

    }
    
    @AuraEnabled
    public static NCMT_Project__c createProject(String projName)
    {
        System.debug('Create Dummy Project for Move Cost Module');
        
        String fiscalYear = String.valueOf(ncmt_customsettings.Cost_Parameter_Date__c.year()+1);
        NCMT_Project__c proj = new NCMT_Project__c(Name = projName,
            									   Estimate_Type_Proj__c = 'Parametric',
                                                   Project_Type__c = 'New Construction',
                                                   Building_Type__c = 'Office',
                                                   Building_Selection__c = 'New',
                                                   Purpose_of_Estimate__c = 'Portfolio Planning',
                                                   Start_Construction__c = System.today(),
                                                   Housing_Plan__c = true,
                                                   State__c = 'California',
                                                   City__c = 'San Diego',
                                                   Remoteness__c = 'Urban',
            									   Move_Cost_Module__c = true,
                                                   RecordTypeId = Schema.getGlobalDescribe().get('NCMT_Project__c').getDescribe().getRecordTypeInfosByName().get('New Construction').getRecordTypeId()
                                                   );
        
        
        
        NCMT_Location_Parameters__c loc = [SELECT Id FROM NCMT_Location_Parameters__c
                                          WHERE State__c =: proj.State__c 
                                          AND City__c =: proj.City__c
                                          AND Fiscal_Year__c =: '2017'];
        
        proj.Location__c = loc.Id;
        insert proj;
        
        return proj;
    }
    
    @AuraEnabled
    public static moveCostWrapper initMoveCostMod()
    {
        NCMT_RedirectCustomObjectpage__c customSettings = NCMT_RedirectCustomObjectpage__c.getOrgDefaults();
        
        moveCostWrapper mc = new moveCostWrapper();
        mc.projList = [SELECT Name, (SELECT Name, Housing_Plan_Name__c FROM NCMT_Housing_Plans__r),
                       (SELECT Total1__C FROM Other_Costs__r WHERE Cost_Type__c =: 'Moving Costs')
                       FROM NCMT_Project__C
                       WHERE Move_Cost_Module__C =: true
                       AND CreatedById =: UserInfo.getUserId()
                       ORDER BY LastModifiedDate DESC];
      
		Report rep = [Select Name, IsDeleted, Id, Description 
                      From Report 
                      Where Description = : 'NCMT Reports' 
                      and Name =: 'Project Moving Costs'
                      and IsDeleted = false 
                      Order By Name LIMIT 1];
        
        mc.reportId = rep.Id;
        
        mc.otherCosts = [SELECT Name, Cost_Type__c, Cost_based_on__c, Housing_Plan_Cost_Sub_Type__c,
                         		Housing_Plan_Option_Choice__c, Space_Type__c, Total1__c, NCMT_Project__c,
                         		NCMT_Housing_Plan_Option_Selection__r.NCMT_Housing_Plan__c
                         FROM NCMT_Other_Cost__C 
                         WHERE NCMT_Project__c IN: mc.projList
                         AND Cost_Type__c =: 'Moving Costs'];
        
        mc.redirectProjName = customSettings.Housing_Plan_Project_Name__c;
        mc.redirectMoveCostMod = customSettings.HP_Move_Cost_Module__c;
        
        return mc;
    }
    
    @AuraEnabled
    public static moveCostWrapper getOtherCostData(String recId){
        moveCostWrapper wrap = new moveCostWrapper();
        wrap.housingPlan = [SELECT Id, Name, Project__c, Move_Cost_Module__c 
                            FROM NCMT_Housing_Plan__c WHERE Id =: recId];
        String projId = wrap.housingPlan.Project__c;
        
        wrap.otherCosts = [SELECT Name, Cost_Type__c, Cost_based_on__c, Housing_Plan_Cost_Sub_Type__c,
                                                 Housing_Plan_Option_Choice__c, Space_Type__c, Total1__c, 
                           						 NCMT_Project__c, NCMT_Housing_Plan_Option_Selection__r.NCMT_Housing_Plan__c
                                          FROM NCMT_Other_Cost__C 
                                          WHERE NCMT_Project__c =: projId
                                          AND Cost_Type__c =: 'Moving Costs'
                          				  AND NCMT_Housing_Plan_Option_Selection__r.NCMT_Housing_Plan__c =: wrap.housingPlan.Id];
        return wrap;
    }
    // Added for Project Move Cost #block 1
  @AuraEnabled
    public static Boolean isLightning(){
        String theme=UserInfo.getUiThemeDisplayed();
        system.debug('urlvalue'+theme);
        
        
        If(theme=='Theme2'||theme=='Theme3'){
            return false;
                }  else {
                  return   true;
                }
    }
  // End of code added  #block 1

}