force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/PBS_Small_Projects_Historical_Database__c.object-meta.xml
<CustomObject>
    <description>Small Projects Historical Database</description>
    <label>Small Projects Historical Database</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Salesforce Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Small Projects Historical Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PBS_Small_Projects_Historical_Database__c/fields/PBS_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>PBS_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ePM Project Name</label>
    <referenceTo>PBS_Project__c</referenceTo>
    <relationshipLabel>Small Projects Historical Database</relationshipLabel>
    <relationshipName>Small_Projects_Historical_Database</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__mdt/Trigger_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to toggle triggers and set recursion control</description>
    <label>Trigger Settings</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PBS_BPA_TriggerHandler.cls
public with sharing class PBS_BPA_TriggerHandler implements ITriggerHandler {
  public void BeforeInsert(sObject[] newItems) {}

  public void BeforeUpdate(Map<Id, sObject> newItems, Map<Id, sObject> oldItems) {}

  public void BeforeDelete(Map<Id, sObject> oldItems) {}

  public void AfterInsert(Map<Id, sObject> newItems) {
    repopulateSphdBuildings(newItems.values());
  }

  public void AfterUpdate(Map<Id, sObject> newItems, Map<Id, sObject> oldItems) {
    repopulateSphdBuildings(newItems.values());
  }

  public void AfterDelete(Map<Id,sObject> oldItems) {
    repopulateSphdBuildings(oldItems.values());
  }

  public void AfterUndelete(Map<Id, sObject> oldItems) {}

  public Boolean IsDisabled() {
    try {
      return ![SELECT isActive__c
              FROM Trigger_Settings__mdt
              WHERE DeveloperName='PBS_Building_Project_Association'
              LIMIT 1].isActive__c;
    } catch (Exception e) { }

    return true;
  }


  public void repopulateSphdBuildings(sObject[] records) {
    final Set<Id> projectIds = new Set<Id>();

    for (sObject record: records) {
      projectIds.add((Id) record.get('rluProject__c'));
    }

    // Fire PBS_SPHD_Trigger to run PBS_SPHD_TriggerHandler.repopulateBuildings():
    update [SELECT Id, PBS_Project_Name__c
            FROM PBS_Small_Projects_Historical_Database__c
            WHERE PBS_Project_Name__c IN :projectIds];
  }
}